### ISSUE TITLE
Uncounted recto verso pagination

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#1001]
If somebody try to pagination with recto verso and uncounting additional "r" and "v" are added to "uncounted".

![paginierung01](https://user-images.githubusercontent.com/2129672/30733079-b13def64-9f75-11e7-9dd6-df5e62e0b961.jpg)

If you use a double side pagination the "r" and "v" are added to both sides:

![paginierung02](https://user-images.githubusercontent.com/2129672/30733108-d353362c-9f75-11e7-913a-0960ea94b7ef.jpg)

**Comment by matthias-ronge** [comment]
Looks ugly, but is what I expected. If you don’t want an `r` and `v` being added, you can use one of the other buttons.
