### ISSUE TITLE
Flexibilize the border of the business year wrap

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#1322]
Production shall be extended to support creating, maintaining and exporting repetitive structures of periodical publications with an annual border bound to a business year which wraps on a different day of the year than the 1ˢᵗ of January. It shall become possible to name the year structure accordingly to represent a business year, such as “Season 1999/2000”.

When creating the repetitive structure, is shall be possible to enter both the annual date of the business year begin, and a label, such as “Season”. When generating the METS export, the business year name shall be encoded as the METS `LABEL` attribute of the corresponding year `div`. A numeric year marker consisting of only the year numbers, separated by a dash (like “1999/2000”) shall be encoded as the METS `ORDERLABEL` attribute of the corresponding year `div`.

**Approach:** Newspaper batches will be extended to support the properties *new year’s day* and *annual name*. A possibility to input these values will be added to the calendar editor. *New year’s day* needs a validity check. On the *batches* page, these values will be made editable.

In the aggegation step of the newspaper export, in place of a year level, an annual level will be created. Multiple values are separated using slashes, and a `LABEL` will be generated if *annual name* is configured.

The development of this feature is funded by SLUB Dresden.

**Comment by henning-gerhardt** [comment]
Closing as pull request is merged.
