### ISSUE TITLE
Maintain the order of issues

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#1323]
Production shall be extended to preserve the order of several issues on the same day, also when they are maintained as individual processes.

When generating the METS export, the issue name shall be encoded as the METS `LABEL` attribute of the corresponding issue `div` to allow to distinguish them in Presentation’s calendar view.

**Approach:** When creating tasks at the granularity level “issues” and there are several issues per day, an additional value `CurrentNoSorting` will be added in the issues as metadata, which describes the sort order of the issues on this day.

When creating the XML export from the metadata editor, output will be created in the specified order. When re-importing the XML, the order of the issues will be taken into account. If necessary, one issue must be reconstructed multiple times. When exporting newspapers, the order of the issues will be evaluated and the aggregation will be carried out in this order.

The development of this feature is funded by SLUB Dresden.

**Comment by henning-gerhardt** [comment]
Closing as pull request is merged.
