### ISSUE TITLE
Userdata / Settings - ERROR

### ISSUE THREAD

**Issue by KnutLohse** [kitodo/kitodo-production#1590]
Kitodo 3.0.0-alpha.2 bug

Logged in as 'testUser', Showing 'Userdata/Settings' page throws an error:

----------------------------------------------------------------------
An Error Occured:

    javax.el.ELException: Error reading 'cssFiles' on type de.sub.goobi.forms.HelperForm
    viewId=/pages/userConfiguration.xhtml
    location=/var/lib/tomcat8/webapps/kitodo/pages/userConfiguration.xhtml
    phaseId=RENDER_RESPONSE(6)
    Caused by:
    java.util.NoSuchElementException - Error reading 'cssFiles' on type de.sub.goobi.forms.HelperForm
      at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:365)
    /WEB-INF/templates/includes/userConfiguration/userSettings.xhtml at line 44 and column 82 value="#{HelperForm.cssFiles}"
----------------------------------------------------------------------

**Comment by Beacze** [comment]
Problem is caused by missing modules directory.

**Comment by KnutLohse** [comment]
O.K. - that may be. ;-)
And how can I fix it?
What is the modules directory for?
Is there any documentation?

**Comment by Beacze** [comment]
Modules directory you can get after build application from source files:
mvn clean install

As default this modules are in Kitodo directory but adviced way is to set up variable moduleFolder (kitodo_config.properties) to local directory. After that modules during build will be copied there and application will search for them there.

**Comment by KnutLohse** [comment]
I installed the latest 3.x relase and want to use it - I DO NOT want to build anything.
Should I open an issue "release is broken"?   ;-)

**Comment by Erikmitk** [comment]
Thanks for checking out the 3.x release. The 3.x version is still in active development and the current release is still in an alpha state and intended for developers only. I can understand that you **just want to use it** but currently you still have to put in some work to do so. We will gladly give you some pointers though, like @Beacze did. :)

Future releases that are regarded as stable are a different story but at the moment that’s how it works. In the future we plan to update the documentation further so that "just using it" will hopefully be easier.

**Comment by KnutLohse** [comment]
Thanks for clarification.
But I don't understand, why a war is provided if it is not ready for use. Please consider removing the compiled application - maybe this prevents some confusion...   ;-)

**Comment by KnutLohse** [comment]
Next step: I built the application with

    mvn compile
    mvn package

I see the login screen, but cannot log in (testAdmin/test don't work).
What to do next? Can I use the environment setted up with my first try (following the installation guide for 3.x) and how? Is there a default user to log in? Any documentation?

If I try the demo mode (as given in Docs » Getting started » Build integrated demo) with

     mvn clean install -Pdemo,!development

it ends up with

    -bash: !development: event not found

Without `,!development` it works after some hacking (stopping tomcat8, mysql, elasticsearch), I see the login screen and entered the given credentials... waiting... waiting longer... and finally:
**org.hibernate.HibernateException: Unable to open JDBC Connection for DDL execution**

Any hints?

**Comment by tim-boerner** [comment]
About the demo mode:
For linux bash the command would be: mvn clean install '-Pdemo,!development'
I will correct this in the Docs.

This demo mode was introduced for the next alpha release 3 for manual testing and a quick first look with some sample data. It is still under development. Some needed local config files are still missing, so e.g. the creation of new proesses out of templates will not work yet.

**Comment by KnutLohse** [comment]
Thanks, Tim!
But which files have to be copied to point Kitodo to the environment created earlier?
May be (as two examples, repeting for all file types in that place):

    service tomcat8 stop
    cp /var/lib/tomcat8/webapps/kitodo/WEB-INF/classes/*.xml /var/lib/tomcat8/wepapps/kitodo-3.0-sbb/WEB-INF/classes/
    cp /var/lib/tomcat8/webapps/kitodo/WEB-INF/classes/*.properties /var/lib/tomcat8/wepapps/kitodo-3.0-sbb/WEB-INF/classes/
    ...
    service tomcat8 start

And how can I create an user or how to log in?

**Comment by tim-boerner** [comment]
Dear Knut,
we have updated the installation guide: [https://github.com/kitodo/kitodo-production/wiki/Installationsanleitung-f%C3%BCr-Kitodo.Production-3.x](https://github.com/kitodo/kitodo-production/wiki/Installationsanleitung-f%C3%BCr-Kitodo.Production-3.x)

We are going to provide the modules as seperate download for alpha release 2. You are informed when the download is ready.

For now you can run the following Maven command in the source code folder of alpha release 2 to build the modules:
```
mvn clean install '-P!development'
```
After that, the compiled modules should be in the source code folder at ../kitodo/modules
You need to copy the jar files to /usr/local/kitodo/modules

Please keep me informed if you still have problems.

**Comment by Erikmitk** [comment]
@KnutLohse The modules folder is now available on the release:

https://github.com/kitodo/kitodo-production/releases/tag/kitodo-production-3.0.0-alpha.2

**Comment by Erikmitk** [comment]
@KnutLohse Did this solve your issue or do you still get these issues?

**Comment by rstockm** [comment]
Hi, we decided to stop the actual testing of the 3.x branch and focus on other tasks until this gets into a beta state - but thank you very much for your effort.

**Comment by solth** [comment]
Since the old custom CSS designs only worked for Kitodo 2.x and earlier versions, we decided to remove them and the corresponding option in the user settings completely (see https://github.com/kitodo/kitodo-production/pull/1784). This should resolve the reported issue.
