### ISSUE TITLE
RFC: Support JPEG 2000 in addition to TIFF?

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-production#1664]
Pull request #1638 added support for long time preservation with the JPEG 2000 image format, but currently the workflow is based on TIFF and does not support JPEG 2000.

Is there a need to enhance Kitodo Production workflow with JPEG 2000 support? Some scanners are already able to deliver scans in lossless JPEG 2000 instead of uncompressed TIFF.

**Comment by Kathrin-Huber** [comment]
We elaborated the need for different image formats in the current Kitodo Project. As you said, several scanners already support JPEG2000, so there may be a need. We are not going to replace TIFF as it is still the common standard.

**Comment by stweil** [comment]
Sure, removing TIFF support would be a very bad idea as it will be the dominating image format in this area at least for the next years. Ideally the workflow would support both formats and detect automatically which one is available.

[OpenJPEG](https://github.com/uclouvain/openjpeg/) is a mature free software library for JPEG 2000 and could be used for that.

**Comment by Kathrin-Huber** [comment]
The DFG project intends to support JPEG2000 in the workflow, so the long time preservation with JPEG2000 is a pre-work for that.
Thanks for the tip with OpenJPEG, we are going to look into that.
