### ISSUE TITLE
3.0.0-beta.1: the inital database contents are missing on the releases page

### ISSUE THREAD

**Issue by funkyfuture** [kitodo/kitodo-production#1903]
while the provided sql dump of the previous user is missing a table (`client_x_user` or similar), there's none for the current version on the [releases page](https://github.com/kitodo/kitodo-production/releases/tag/kitodo-production-3.0.0-beta.1).

**Comment by funkyfuture** [comment]
sidenote: of course it'd be preferable that the application itself would handle the needed database structures.

**Comment by Erikmitk** [comment]
Thanks for pointing out the missing SQL-Dump. You are absolutely right and we're sorry about that. We are still deep in development mode and that step in the release process has slipped through unnoticed.

You can now find the [SQL-Dump](https://github.com/kitodo/kitodo-production/releases/download/kitodo-production-3.0.0-beta.1/kitodo-production-3.0.0-beta.1.sql) for the state of the release alongside the other files.

**Comment by funkyfuture** [comment]
thanks. yes, there are issues. i will open tickets here when i had a closer look.
