### ISSUE TITLE
Import of personal and corporate names / missing identifier

### ISSUE THREAD

**Issue by maria-federbusch** [kitodo/kitodo-production#195]
Personal and corporate metadata should be imported from catalogue together with their referred authority information - URI
In case of personal names it is possible to capture URI; now the import of these data is necessary. The functionality has to be transferred to corporate names.
There should be a relation to issue #169

**Comment by maria-federbusch** [comment]
The import of authority data (including identifier) does not works. You can add the information manually. The import of these metadata from the opac or cataloguing system is not possibly.

**Comment by sebastian-meyer** [comment]
This is 1 of only 3 remaining issues with milestone 1.11.
@matthias-ronge and @maria-federbusch could you please have a look at the issue?

**Comment by matthias-ronge** [comment]
Dear @maria-federbusch, is there still a problem with you?
