### ISSUE TITLE
Should not assign TitleDocMain meta-data for day and month

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#1963]
The meta-data `TitleDocMain` of the structure elements "day" and "month" is assigned the numerical values of the respective day and month. When creating the processes, the metadata `TitleDocMain` for the structure elements "day" and "month" should not be assigned.

**Comment by henning-gerhardt** [comment]
This issue can be closed as we unintentional allowed meta date `TitleDocMain` for "month" and "day" of a newspaper / season program. If someone is allowing this meta date for "month" and "day" then he expect the same behaviour for new processes regardless of newspaper or season programs. 
Your pull request #1964 is then even not needed and can be closed.
