### ISSUE TITLE
Should not assign LABEL attribute with value from ORDERLABEL

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#1964]
The `LABEL` attribute is always assigned, regardless of whether a value itself is in `TitleDocMain` or not. If no value is assigned, then the content is taken over from the `ORDERLABEL` attribute.
The attribute `LABEL` should only be assigned if there is a value in `TitleMainDoc`. The exception to this rule is in the year, wherever the annual or seasonal information must be included, possibly enriched by the seasonal designation.

**Comment by matthias-ronge** [comment]
I cannot reproduce that. I've also been looking for places that explicitly access `TitleDocMainShort`, both in Production and in the UGH, but there’s no hocus-pocus on it. Are you sure that `TitleDocMain` does not exist it the internal meta-data files and that it happens during normal (not-batch) export? Can it be that inadvertently a metadata copy rule works into it?

**Comment by henning-gerhardt** [comment]
@matthias-ronge : We could reproduce it as meta data `TitleDocMain` is filled on creating of newspaper processes. This was not happening in Kitodo.Production 2.0.0 and must be introduced by latest changes for seasonal appearance of newspaper. As the meta data fields are already created they are then be exported and here we have no copyData.onExport rules defined for `TitelDocMain` or `TitleDocMainShort`.

**Comment by matthias-ronge** [comment]
Then I had the misunderstood, that's not a problem from export but from the process creation. When creating "normal" newspaper processes, the field has always been created, if allowed in the ruleset. But it should be optional and if it is not allowed in the rule set it will not be filled either. At least that's how I remember it. But if I understand you correctly, you want to allow it in the ruleset and not fill it. I had already implemented that in issue #1963 for seasons. Should this also be the case with "normal" newspaper processes? If so, we should add an attribute in the `config.properties`, because then there is a change in behavior and I do not know if all the institutions want it that way.

**Comment by henning-gerhardt** [comment]
This issue can be closed as we unintentional allowed meta date `TitleDocMain` for "month" and "day" of a newspaper / season program. If someone is allowing this meta date for "month" and "day" then he expect the same behaviour for new processes regardless of newspaper or season programs.
