### ISSUE TITLE
Reconsider default password constraints?

### ISSUE THREAD

**Issue by funkyfuture** [kitodo/kitodo-production#1984]
i'm testing Kitodo 3.0 beta 1. when creating a new user, the interface tells me that a password should contain at least a digit and a special character. these constraints have commonly been rejected as they do not increase security and indeed are a horrible ux. i could elaborate more, but i don't know what your discussion on that has been and just refer to [this blog post](https://www.nist.gov/blogs/taking-measure/easy-ways-build-better-p5w0rd) that discusses the overhauled nist recommendations for now.

**Comment by funkyfuture** [comment]
thanks, i changed the issue title to reflect my follow-up impulse. ;-)

**Comment by Kathrin-Huber** [comment]
We decided on this default password constraints. It's up to any user to change them.
