### ISSUE TITLE
Wrong behaviour of "read in pagination from images" method

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#203]
Using method "read in pagination from images" to fix amount of files or reread renamed files does not work if deleting or renaming happens outside of Goobi.

effected version: Goobi CE 1.10.x
# starting scenario for both following scenarios
- create new Goobi process
- add a few images inside image directory (f.e. 8 files)
- open new process in mets editor
- use "Read in pagination from images" link to get all files (eight at example) as uncounted pages if uncounted is use as default pagination style
- store process and close it
## result in process mets.xml file
- 8 files (or how many are used) as entries in mets:fileGrp, mets:structMap and mets:structLink
# first scenario: deleting one or more image files from process
- for example last file is wrong for this process
- deleting wrong file(s) outside from Goobi
- open process in mets editor: you see 8 (or how many was there original) pages for 8 image files
- use "Read in pagination from images" link
- now you see at least 7 pages for 7 images files
- store and close process
## result in process mets.xml file
- reference to 8 image files as entries in mets:fileGrp 
- 7 entries in mets:structMap and mets:structLink
## expecting
- 7 entries in mets:fileGrp, mets:structMap and mets:structLink for 7 images files
### fix / workaround
- re-open process in mets editor
- store and close without any further change
### result now in mets.xml file
- 7 entries in mets:fileGrp, mets:structMap and mets:structLink for 7 images files
# second scenario: renaming of one or many or all image files
- one, many or all image files has wrong file name or file extension. for example your files ends with .tiff instead of .tif
- rename this file(s) according to your file name rules. for example from .tiff to tif
- open process in mets editor
- use "Read in pagination from images" link
- store and close process
## result in process mets.xml file
- all references in mets:fileGrp point to old file names and not to new file names
## expecting
- all file names are correct / changed to new name in mets.xml file
### fix / workaround
- move all files except first file outside images folder
- open process in mets editor
- use "Read in pagination from images" link
- only one page should be there as only one image exists
- store and close process
- re-open process in mets editor, store and close without any further change (step needed because of deleting scenario above)
- move back all moved files into image folder
- re-open process in mets editor, store and close without any further change
### result now in mets.xml file
- correct file names in mets.xml file

**Comment by frank-ulrich-weber** [comment]
I checked this bug for version 1.11:

First scenario: I'm able to reconstruct this behaviour. But I cannot observe a negative effect on the (more important) exported mets file. All file groups show the correct amount of images already before the fix.

Second scenaria: I'm able to reconstruct this behaviour, too. But I cannot observer a negative effect on the (more important) exported mets file, too. All the configured file groups show the correct amount of images with the right file types. The mets editor don't care if your image file types are *.jpg, *.tif or *.tif.

I think this is more a kind of (not so nice) cosmetic bug?

**Comment by henning-gerhardt** [comment]
I well recheck this for version 1.11.0. 

We got validation errors inside meta data editor with version 1.10.3 so exporting was not allowed until somebody fixed this process.

@frank-ulrich-weber : did you get any validation errors in 1.11.0?

**Comment by henning-gerhardt** [comment]
I rechecked this and it is a cosmetic bug if you don't depend on local mets:fileGrp information like on migrating your processes from one file space  to an other (bigger) one and use this stored information as one condition of checking for successful moved files.

We had with 1.10.x some (older) processes (created with 1.7.x ) where this two workarounds were the only way to get this processes finally edited and exported. Maybe one other not jet found bug was responsible for this.
