### ISSUE TITLE
Multimodule Project does not compile from scratch

### ISSUE THREAD

**Issue by M3ssman** [kitodo/kitodo-production#2158]
Hello there,

after checking out the latest commit from Master (88cf5286), I typed 
`mvn clean compile` into the Terminal, but Compilation fails on Submodule `Kitodo SRU Import` alerting:

```
[ERROR] Failed to execute goal org.codehaus.mojo:properties-maven-plugin:1.0.0:read-project-properties (default) on project kitodo-sru-import: Properties could not be loaded from File: /home/<account>/workspace/github-extern/kitodo-production/config-local/kitodo_config.properties -> [Help 1]
```

The Subfolder mentioned, `config-local`, doesn't even exist in the Repository. The Dev-Docs point out just to create the missing folder and then 

> put there your specific configuration files just before you create a distribution

but I wonder what I exactly need to place in there. Can anybody please give me a Hint? I do not want to package something, neither run the Tests.

Plattform: Ubuntu 18.04 LTS, Maven 3.5.2, OpenJDK 1.8.0_191

**Comment by Beacze** [comment]
Hello,

there are 2 possibilities to solve this problem:

1. add files flyway.properties, hibernate.cfg.xml, kitodo_config.properties and log4j2.xml - you copy them from the project and next adjust to your local environment (e.g database name / user / password, properties for elastic search index and so on)
2. run your maven build without development profile (for this you need to consider that your database, index and directories set up must be exactly the same like the default one provided in the project)

**Comment by M3ssman** [comment]
Thanks for your fast Advices!

Unfortunately, I have no local Elastic Search at hand, but I found a different approach: Just create an empty `config-local/kitodo_config.properties` File, and it compiles fine. Without proper compilation one cannot run the "fingbugs" or "checkstyle" Profiles, the Compilation stops on the Maven Submodule `Kitodo SRU Import`. 

Well, the Folder config-local is ignored by Git what makes sense of course since it's labeled local (and  some default or fallback would be nice anyway), but for my concerns it is sufficient right now.
