### ISSUE TITLE
2.x: Image directory (media) not created as expected on process creation

### ISSUE THREAD

**Issue by frank-ulrich-weber** [kitodo/kitodo-production#2159]
Under the following conditions the *_media directory is not generated when creating an process:
```
createOrigFolderIfNotExists=true
useOrigFolder=false
DIRECTORY_SUFFIX=media
MetsEditorDefaultSuffix=jpg
processDirs=images/(processtitle)_jpg
```
Adding the *_media directory to processDirs:

`processDirs=images/(processtitle)_media`

creates the required directory, but leads to a double export of images/(processtitle)_media and (processtitle)_media within the configured "DMS import images path" (Project properties).

**Comment by henning-gerhardt** [comment]
In which version and with the same configuration was this working and in which version is this failing? So far as I remember me, there is no direct change to this code for creating of directories.

**Comment by frank-ulrich-weber** [comment]
I think there is no version where it is working. The version in which I noticed this error is 2.1.0.

**Comment by henning-gerhardt** [comment]
Maybe I found some time to investigate into this issue but in our house we are creating most of all necessary sub-directories of `images` directory while creating the symbolic link into the user home directory as part of scanning task.

**Comment by solth** [comment]
Closed as no further development for Kitodo.Production 2.x is planned (see https://github.com/kitodo/kitodo-production/security/policy)
