### ISSUE TITLE
Export of attribute namespaces not possible

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#2238]
In Kitodo.Production 2.x, the export of attribute namespaces is not possible. 

Despite the definition of the namespace in the ruleset, `xlink:href` is exported as `href`. 

For example, the following XPath: 
`./mods:mods/#mods:accessCondition[@type='use and reproduction'][@xlink:href='https://creativecommons.org/publicdomain/mark/1.0/']`
will be exportet as: 
`<mods:accessCondition type="use and reproduction" href="https://creativecommons.org/publicdomain/mark/1.0/">PDM 1.0</mods:accessCondition>`

In order to avoid post-processing, Kitodo.Production should be enabled to export attribute namespaces correctly.

Further information: 
[Kitodo-Mailinglist](https://maillist.slub-dresden.de/pipermail/kitodo-community/2018-December/000250.html)
[Kitodo-Wiki](https://github.com/kitodo/kitodo-production/wiki/Korrektur-des-href-Attributs-in-Kitodo)

**Comment by henning-gerhardt** [comment]
I'm not sure if this is a bug for Kitodo.Production or Kitodo.UGH as Kitodo.UGH is writing the export METS/MODS file.

**Comment by matthias-ronge** [comment]
From the point of view of code organization, this is actually in the UGH and not in Production itself.

**Comment by andre-hohmann** [comment]
This can be implemented in Kitodo.Production 3.x.
The issue is closed, because an solution in 2.x is not necessary anymore.
