### ISSUE TITLE
Replace nexus.slub-dresden.de by a more standard location

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-production#2349]
Currently LGTM does not analyse the Java code because of timeouts from nexus.slub-dresden.de (see https://discuss.lgtm.com/t/java-language-not-detected/1403). Technically port 8081 is not always accessible from local networks because of restrictive firewall rules while such rules generally support HTTP and HTTPS.

Maybe the contents from nexus.slub-dresden.de should be provided on GitHub?

**Comment by stweil** [comment]
LGTM has indeed no access to port 8081 due to their local firewall settings. See their [build logs](https://lgtm.com/projects/g/kitodo/kitodo-production/logs/languages/lang:java) for details.

**Comment by henning-gerhardt** [comment]
If some day GitHub package registry is out of beta this could be a possible move. Read more:
* https://github.blog/2019-05-10-introducing-github-package-registry/
* https://help.github.com/en/articles/about-github-package-registry
* https://help.github.com/en/articles/configuring-apache-maven-for-use-with-github-package-registry

**Comment by stweil** [comment]
Is there a chance to get this issue solved? I think it would be highly desirable to get a usable quality report from LGTM.

**Comment by stweil** [comment]
Maybe an easy solution would be using port 80 instead of 8081. As far as I can see port 80 is currently unused on the nexus server.

**Comment by matthias-ronge** [comment]
@Kathrin-Huber, didn’t you say the SLUB Nexus no longer existed? Then the ticket can be closed here, right?

**Comment by Erikmitk** [comment]
Yes, the server does not exist anymore. It has been put int the standard location trash.

**Comment by stweil** [comment]
Thank you. Indeed, LGTM can now analyze the Java code, too: https://lgtm.com/projects/g/kitodo/kitodo-production/.

The reported code quality of C leaves room for improvements. Should I open an issue to track that?

**Comment by Erikmitk** [comment]
In my opinion, general code cleanup is a task that should be dealt with once there's a stable release with all new features. So in general, yes we should definitely take a look at analyzers and fix issues. I don't think a single issue will help us with that though, since there should be an ongoing strategy in place for future developments.
