### ISSUE TITLE
NullPointerException when adding a select type metadatum

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#242]
**Affected version:** 1.10.x

**Steps to reproduce:**
- In goobi_metadataDisplayRules.xml, in a `<context>` with `<bind>create`, define a type (multi-) `<select>` type metadatum:

``` xml
<displayRules xmlns="http://meta.goobi.org/displayRules" xmlns:tns="http://meta.goobi.org/displayRules" >
    <ruleSet>
        <context projectName="My project name">
            <bind>create</bind>
            <!-- … -->
            <select tns:ref="SomeMetadatum">
                <item tns:selected="false">
                    <label>Value one</label>
                    <value>1</value>
                </item>
                <item tns:selected="false">
                    <label>Value two</label>
                    <value>2</value>
                </item>
            </select>
```
- Try to add a metadatum of that type somewhere using the metadata editor

**Error:** NullPointerException at de.sub.goobi.metadaten.MetadatumImpl.setWert(MetadatumImpl.java:91)

**Goal:** A multi-select list should show to add values.

**Tested with browser:** Firefox 33.0.3

**Comment by solth** [comment]
Closed as no further development for Kitodo.Production 1.x is planned (see https://github.com/kitodo/kitodo-production/security/policy)
