### ISSUE TITLE
2.x Export Resources into Hotfolder

### ISSUE THREAD

**Issue by M3ssman** [kitodo/kitodo-production#2614]
Hello,

I'm struggeling with Kitodo 2.x. Is it possible to export other types of Ressources than Images from the Metadata Folder into the Hotfolder within the Step "Export to DMS"?

Our Usecase: We have a Script attached to the final DMS-Export that creates custom XML- and Textfiles that must be processed in later Export Stages. We tried to create these Files inside the (tifpath)-Folder in the Metadata-Ressort of Kitodo with a custom Script. So far, this works well, with the Files being created. 
But the Files aren't included in the Kitodo-Hotfolder when the final Export takes place, and therefore missing at later Stages.

Going further down the Kitodo 2.x-Branch, there's a a Class `de.sub.goobi.export.dms.AutomaticDmsExportWithoutHibernate` which forwards filtering to `Helper.dataFilter`. At first, this seems to be an Image-Filter, but at second, it's a bit strange. Why are Files with Extensions `.xsl` , `.ppt` or `.doc` considered legal according to this list, but plain XML or `.txt` get skipped?

Kitodo 2.x

Greetings,
M3ssman

**Comment by henning-gerhardt** [comment]
In general you can use the `processDirs` property in `goobi_config.properties` to create this kind of directories and this directories are exported too.
In general inside the `images` directory only image like files should stored in this place and maybe through historical reasons other kind of files are stored there too. If you have other files like from OCR processing you can use the `ocr`directory on the same level like the `images` directory. As we at SLUB only have XML files from OCR in a subdirectory and no other kind of files I don't know if other files would be copied too. You don't need to define the `ocr` subdirectory inside the `processDirs` property as all subdirectories from `ocr` should be copied on export.

**Comment by M3ssman** [comment]
@henning-gerhardt 
Thanks for your Advices! 

Are you referring to the `processDirs` Property or rather to the `Data copy rules` inside `goobi_config.properties` ?

**Comment by henning-gerhardt** [comment]
This is depending on what you want to do :-D

If you want to create and export directories then you should work with `processDirs` property.
If you want to manipulate the meta data on export then you should work with the `copyData.onExport` property.
You can even use both if you need both. This properties are for  independent features of Kitodo.Production.

**Comment by M3ssman** [comment]
@henning-gerhardt 

Thanks! 
I'll give a try and report back tomorrow!

**Comment by M3ssman** [comment]
Hm,
I didn't work it out.

To provide some more Context:

We need to pass additional Data to a DSpace-Repository, i.e. a `collection`-File (exactly this name, no extension). Before the DMS-Export actualles takes place, I create this File in a custom Subfolder `<processtitle>/dspace` . When DMS is triggered, File and Folder are not transferred into the Kitodo-`content`-Folder.

So I went for `goobi_config.properties` and added:

`processDirs=dspace/(processtitle)_dspace`

Hopefully, to export the  `metadata/<processid>/dspace`- Folder into something like `hotfolder/<processtitle>_dspace` , but this had no effect.

**Comment by henning-gerhardt** [comment]
Is a XML file get copied if you put an XML file into the `dspace/(processtitle)_dspace)` directory?

**Comment by frank-ulrich-weber** [comment]
Dear Mr. Hartwig,

If your folder structure looks like this:

…
…/metadata/<processid>/image/…
…/metadata/<processid>/dspace/…
…

You have to configure processDirs as in the following:

processDirs=dspace

It just copies the …/metadata/<processid>/dspace folder to the configured “DMS import path“.
There is, at the moment, no way to define a different folder-name (e.g. (processtitle)_dspace) for the export.

Best regards

Frank Ulrich Weber

**Comment by M3ssman** [comment]
@henning-gerhardt 
No, the folder is completely missing and nothing is copied.

@frank-ulrich-weber 
Yes, it is transferred this way. Unfortunately, the folder is not prefixed alike the the Image Export. 
As I found out, when no Value for proceedDirs is present, for example: 

`processedDirs=`

**all** Metadata directories (in my case: `tif` and `dspace`) are copied to the Hotfolder without restrictions (and, sadly, prefixations).

But, taken further, what happens, if there are more than one Kitodo-Exports running at the same time? I expect the worst, since the Hotfolder dirs are not distinguishable by a Prefix like the tif-Folders, so we might end up with inconsistent data.

The best approach seems to store additional data outside Kitodo into some arbitrary temp-Folder, that can be dismissed afterwards.

**Comment by frank-ulrich-weber** [comment]
Check the option "Create process folder" within the project settings and kitodo.production creates a subordinate <processname> folder for the export. No more problems with inconsistent data.

**Comment by M3ssman** [comment]
@frank-ulrich-weber 
Yes, this works as suggested. But our Problem is somehow more complex. We use an additional Module from Zeutschel called `zedExporter` and it looks this has some special requirements. It doesn't work out-of-the-box with these subordinate Process-Folders.

**Comment by frank-ulrich-weber** [comment]
OK, I can confirm this behaviour of zedExporter. I added this requirement to list of new features for the next release. Thank you!
