### ISSUE TITLE
Browsing the images in the metadata editor by shortcuts 

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#2789]
In the metadata editor, it was possible to browse the images by shortcuts Ctrl+Shift+Arrows [1]. 
This is not possible anymore, although it facilitates a quick navigation withlin the images [2]. 
Therefore it would be good, if the function is reactivated. 

[1] https://github.com/kitodo/kitodo-production/wiki/Metadateneditor---Allgemeines#einstellungen-und-funktionen-bildanzeige
[2] https://maillist.slub-dresden.de/pipermail/kitodo-community/2019-August/000288.html

**Comment by ponchofiesta** [comment]
It looks like onkeypress event is not fired by the browser. I assume this was changed in newer browser versions. Stackoverflow says: use keydown/keyup instead.

**Comment by M3ssman** [comment]
In Kitodo 2.x file `/kitodo-production/Goobi/pages/Metadaten2rechts.jsp` contains a large block of JavaScript that included this functionality turned into a comment. 

Please, can someone clarify why this has been taken away?

**Comment by henning-gerhardt** [comment]
So far as the history of this file (`Goobi/pages/Metadaten2rechts.jsp`) is available there are only format changes in this out commented JavaScript block. If this functionality was working in previous versions then was the code changed somewhere else or browser stopped supporting of executing out commented JavaScript code or something similar.

**Comment by matthias-ronge** [comment]
I remember looking at that (in Firefox). The problem here is that the Javascript function keys in combination with a control key (I think it was <kbd>Ctrl</kbd>), which is not (or no longer) passed through by the browser. You would have to change this, e.g. to use <kbd>Alt</kbd> instead (or vice versa).

**Comment by andre-hohmann** [comment]
The former shortcuts are named in the Kitodo.Production wiki: 
https://github.com/kitodo/kitodo-production/wiki/Metadateneditor---Allgemeines#einstellungen-und-funktionen-bildanzeige

**Comment by matthias-ronge** [comment]
Former shortcuts were:
- <kbd>Ctrl</kbd> + <kbd>⇧ Shift</kbd> + <kbd>→</kbd> → next image (+1)
- <kbd>Ctrl</kbd> + <kbd>⇧ Shift</kbd> + <kbd>←</kbd> → previous image (−1)
- <kbd>Ctrl</kbd> + <kbd>⇧ Shift</kbd> + <kbd>↑</kbd> → 20 images forewards (+20)
- <kbd>Ctrl</kbd> + <kbd>⇧ Shift</kbd> + <kbd>↓</kbd> → 20 images backwards (−20)

Note that the definition of ↑ and ↓ here is inverse to the images stripe showing next to the full size image, so maybe we should invert that.

**Comment by andre-hohmann** [comment]
As this issue cannot be applied exactly to Kitodo.Production 3, it is closed as not planned.
