### ISSUE TITLE
[IP] Provide reasonable default values in default.sql

### ISSUE THREAD

**Issue by sebastian-meyer** [kitodo/kitodo-production#28]
The file Goobi/setup/default.sql provides default values for database initialisation. Currently it adds some users with different roles for testing purposes. For use in production environments it should add just one admin user, which is called "admin".
- [ ] remove current users from default.sql
- [ ] add generic admin user "admin" with default password "goobi"
- [ ] rename default ldap group

See also #29.

**Comment by matthias-ronge** [comment]
This also applies to the current master.

In the current master, the standard users were preconfigured with a well-designed set of roles:

- `testAdmin`: Administration, client management
- `testScanning`: Scanning
- `testQC`: Quality control
- `testImaging`: Imaging
- `testMetaData`: Metadata
- `testProjectmanagement`: Project management, workflow management

It makes sense to me to deliver these as they make it easier to get started with the software. Delivering a standard password is a low security risk, but replacing the standard password with another openly known standard password is not an improvement in security. I therefore suggest closing this ticket.

**Comment by matthias-ronge** [comment]
Pull request #3148 was merged.
