### ISSUE TITLE
Subsequently addition of metadata to metadata group

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#2809]
# Problem description

In Kitodo.Production 2.3.0 it is not possible to add metadata subsequently to metadata groups. 
If a metadata field is added to the metadata group, the process can be opened in the metadata editor and "Pagination" and "Structure data" can be edited. If "Metadata" is selected, only a white screen appears. 

Here an example for the addition of metadata in a metadata group: 

OLD: 

---
	<Group>
		<Name>slub_serialGroup</Name>
		<language name="de">Reihe</language>
		<language name="en">serial</language>
		<metadata>slub_serialTitle</metadata>
		<metadata>slub_serialCurrentNo</metadata>
	</Group>
---

NEW: 

---
	<Group>
		<Name>slub_serialGroup</Name>
		<language name="de">Reihe</language>
		<language name="en">serial</language>
		<metadata>slub_serialTitle</metadata>
		<metadata>slub_serialCurrentNo</metadata>
		<metadata>slub_serialSortingGroup</metadata>
	</Group>
---

# Suggested solutions

1. It should be possible to add metadata to metadata groups. In old processes, the added metadata is either empty or is not displayed. It would be the same functionality like for "usual" metadata, which can be added without any impact on the metadata editor - except of mandatory metadata.

2. If solution 1 is not feasible, at least an error message should be displayed, which says, that a metadata field is missing in the metadata group.

**Comment by solth** [comment]
Closed as no further development for Kitodo.Production 2.x is planned (see https://github.com/kitodo/kitodo-production/security/policy)
