### ISSUE TITLE
Kitodo uses deprecated Hibernate API call

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#297]
Several methods still call the no-arg version of [buildSessionFactory()](https://docs.jboss.org/hibernate/core/4.0/javadocs/org/hibernate/cfg/Configuration.html#buildSessionFactory%28%29), which is deprecated and should—on the long term—be replaced as, i.e., described in [this posting](http://stackoverflow.com/a/8830848/1503237). ([The reason for the redesign can be found here.](https://hibernate.atlassian.net/browse/HHH-2578))

**Comment by henning-gerhardt** [comment]
Switching to a new hibernate release should respect this (and maybe other things like open / closing database connections, ... too) and I imagine that is a lot of work to do this. Hibernate based code is scattered all over the whole source code.

**Comment by matthias-ronge** [comment]
A newer Hibernate version is used with the current master. Session management has been significantly improved so that there have been no problems with Hibernate errors for months.
