### ISSUE TITLE
2.x ff Metadata editor: Import of metadata groups doesn‘t work

### ISSUE THREAD

**Issue by maria-federbusch** [kitodo/kitodo-production#3023]
When importing metadata into structures, only flat metadata fields are imported, but no metadata groups are imported.
We need the complete import of metadata (including personal names and corporations) especially for contained works according to the rules of the opac.xml.
![grafik](https://user-images.githubusercontent.com/8545018/70726892-10a97280-1cff-11ea-886e-11ba1c4b0c06.png)

**Comment by solth** [comment]
Closed as no further development for Kitodo.Production 2.x is planned (see https://github.com/kitodo/kitodo-production/security/policy)
