### ISSUE TITLE
3.0.0-beta.1: default password

### ISSUE THREAD

**Issue by inormann** [kitodo/kitodo-production#3049]
according to the installation guideline the default access is:
- user: testAdmin
- pass: test
However, this does not work.

**Comment by matthias-ronge** [comment]
This is still the default at the moment.

What system environment are you using? Did you install Production yourself?

Here is a small checklist that you can go through when looking for the error. All the configuration files mentioned here are in the directory `webapps/kitodo-production/WEB-INF/classes/`.
- Make sure that the MySQL database `kitodo` is set up and filled with the standard data and can be accessed with username `kitodo` and password `kitodo`, or the access data in file `hibernate.cfg.xml` needs to be changed if that differs. To fill the database, add [schema.sql](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/setup/schema.sql), [default.sql](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/setup/default.sql) and all SQL files from folder [migration](https://github.com/kitodo/kitodo-production/tree/master/Kitodo-DataManagement/src/main/resources/db/migration) in ascending order.
- Make sure that version 5.6.5 of the Elasticsearch server is installed (newer versions don’t work) and that it has started up and can be reached at the address configured in the `kitodo_config.properties` file.
- Please check whether the setting `ldap_use` in the configuration file `kitodo_config.properties` is `false`. 
- Have you adjusted the logging configuration file `log4j2.xml` and do you get any error messages in the log file? You can set `Logger name="org.kitodo" level="trace"` for a lot more of output.

**Comment by matthias-ronge** [comment]
Related: #456

**Comment by matthias-ronge** [comment]
@inormann, is this still an open question?

**Comment by Kathrin-Huber** [comment]
Shouldn't be a problem anymore. Please reopen, if otherwise
