### ISSUE TITLE
3.0.0-beta4: Path for script gets url-encoded

### ISSUE THREAD

**Issue by mnscholz** [kitodo/kitodo-production#3088]
When finishing a task, the script `script_deleteSymLink.sh` is run, but th symlink path gets url-encoded in kitodo. This is fatal as the square brackets that enclose the process ID get corrupted.

Example log:
`Command - Execution of Command 1608240105 /usr/local/kitodo/scripts/script_deleteSymLink.sh /usr/local/kitodo/users/simnscho/Workshop/Graphik01__%5B6%5D failed!: [rm: cannot remove '/usr/local/kitodo/users/simnscho/Workshop/Graphik01__%5B6%5D': No such file or directory]
`
The path `/usr/local/kitodo/users/simnscho/Workshop/Graphik01__[6]` does exist, however.

**Comment by matthias-ronge** [comment]
I tried to understand that. Unfortunately, Production on my system doesn't seem to _even try to_ execute the script when I click the button to delete the shortcut. In any case, something is broken here and needs to be repaired. Thanks for the hint!
