### ISSUE TITLE
3.0.0: wrong directory settings for workflow diagrams

### ISSUE THREAD

**Issue by mnscholz** [kitodo/kitodo-production#3136]
The 3.0.0 release is shipped with the `directory.diagrams` setting set to `/usr/local/kitodo/diagrams/`.
However, the xxx-config.zip file only contains a `diagram` directory (not trailing s!)

In Kitodo, when viewing the example workflow this causes an error:
>   /usr/local/kitodo/diagrams/Example_Workflow.bpmn20.xml (No such file or directory)

When creating a new workflow, Kitodo complains with something like
>    /usr/local/kitodo/diagrams/Bla.svg
>    /usr/local/kitodo/diagrams/Bla.bpmn20.xml

The system works correctly when I rename the dir to `diagrams`.

**Comment by mnscholz** [comment]
In general, the config.zip file seems to be incomplete and somewhat buggy for the release. Apart from this issue and #3137, I can see the following problems:

- The script `scripts/script_createDirMeta.sh` is named `scripts/script_createDirMeta_old.sh` instead.
- When following the [Kitodo install docs](https://github.com/kitodo/kitodo-production/wiki/Installationsanleitung-f%C3%BCr-Kitodo.Production-3.0), the dir `/usr/local/kitodo` contains the following: `config  diagrams  logs  metadata  modules  rulesets  scripts  xslt`.
When building the snapshot, the dir contains `config  debug  diagrams  import  logs  messages  metadata  modules  plugins  rulesets  scripts  swap  temp  users  xslt`. Some of them may not be needed, but e.g. `users` is vital afaics.

**Comment by Kathrin-Huber** [comment]
We made a bugfix release, please see latest 3.0.1 release.
Thanks for the hint!
