### ISSUE TITLE
3.0.0: Missing ruleset files

### ISSUE THREAD

**Issue by mnscholz** [kitodo/kitodo-production#3137]
In the 3.0.0 release, the database is initialized with three rulesets:
`INSERT INTO `ruleset` VALUES (1,'Simple book','simple-book.xml',0,'INDEX',1,1),(2,'SUBHH','subhh.xml',0,'INDEX',1,1),(3,'DFG-Viewer','dfg-viewer.xml',0,'INDEX',1,1);`

In the config.zip file, however, there is only a ruleset_default.xml.

This results in a blank screen when creating a process.

**Comment by matthias-ronge** [comment]
The rulesets mentioned can be found [here](https://github.com/kitodo/kitodo-production/tree/master/Kitodo/rulesets), some more examples can be found in [this folder](https://github.com/kitodo/kitodo-production/tree/master/Kitodo-DataEditor/src/test/resources). You must install them separately in the directory you specified in your local copy of [file `kitodo_config.properties` as `directory.rulesets`](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/resources/kitodo_config.properties#L27-L29).
Please note that these rulesets are just examples. You have to code your local specialist logic in your own rulesets.

**Comment by mnscholz** [comment]
Thanks for the hints to the example files!
I mainly wanted to point out that there is an inconsitency between db and fs in the release.
Before creating an own ruleset, I the examples are great for testing and playing...

**Comment by matthias-ronge** [comment]
A certain ruleset is required for the import to work. I would like to suggest that any rule sets are removed from both the database and the project, and instead only the one or maybe two rulesets (from Hamburg and Dresden libraries) that match to the import XSLT are configured and delivered.
