### ISSUE TITLE
Update ElasticSearch version

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3153]
Version 6 of the Elasticsearch index uses a new format. The so-called [mapping types have been removed](https://www.elastic.co/guide/en/elasticsearch/reference/6.7/removal-of-types.html). This requires changing the way Elasticsearch is addressed so that we can use a more recent version of Elasticsearch.

**Comment by henning-gerhardt** [comment]
Maybe the [ElasticSearch (ES) integration of Hibernate](https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#_goal_of_the_elasticsearch_integration) is a better alternative as this resolves a few issues like
* correct deleting of data in Hibernate and ES
* writing similar queries instead of two different (HQL for Hibernate and ES-dialect for ES)
* not adjusting ourself the changes for new ES versions (less maintenance for Kitodo.Production)
* ... 

I know that this is a big change but I think a good approach in long term.

**Comment by henning-gerhardt** [comment]
According to https://www.elastic.co/support/matrix#matrix_jvm a new ElasticSearch version should be used which is supported by many Java versions. At time at writing this (11/11/2020) Elastic Search version 6.8.x. or 7.7.x has most supported Java versions

**Comment by matthias-ronge** [comment]
The last version 5 of ElasticSearch ran out of support on March 11, 2019. Current version at the time of writing is 7.11.

**Comment by matthias-ronge** [comment]
After Elastic changed the license for newer versions, whi[ch is ambiguous in some formulations, so that it can be interpreted against the operators of Production instances](https://anonymoushash.vmbrasseur.com/2021/01/14/elasticsearch-and-kibana-are-now-business-risks#page-title) (even differently than it is currently intended), and since the ElasticSearch integration has to be rewritten anyway, my suggestion is to replace them entirely. Presentation uses Solr, and since Production and Presentation run on the same server in a large number of installations anyway, I would be very inclined to use Solr for Production as well. The search engine integration should be reconsidered and then implemented in a meaningful way by a search engine specialist.

**Comment by henning-gerhardt** [comment]
> After Elastic changed the license for newer versions, which is ambiguous in some formulations, so that it can be interpreted against the operators of Production instances (even differently than it is currently intended), and since the ElasticSearch integration has to be rewritten anyway,

I agree with you in terms but not overall. There are already forks of ElasticSearch and I hope on the open source community to create a stable and long supported fork of ElasticSearch. Our current implementation is not so bad but could be improved in many ways.

>  my suggestion is to replace them entirely

I did not agree. I would to move to the ElasticSearch integration of Hibernate as they already implement all your later marked / written down improvements. See my comment from 02/07/2020.

> Presentation uses Solr, and since Production and Presentation run on the same server in a large number of installations anyway, I would be very inclined to use Solr for Production as well. 

This is maybe true if you have only small amount of data (< 100.000 processes in .Production) and maybe not many full text enhanced data in solr. Even .Production and .Presentation use total different execution stacks (.Production with Java EE environment, .Presentation full PHP and TYPO3 environment) which are not necessary should run on one system. You will split it up if you have a lot of data (> 300.000 .Production processes with a few hundred GB on full text data for .Presentation). 

> The search engine integration should be reconsidered and then implemented in a meaningful way by a search engine specialist.

As long as 

* the new implementation did not implement the whole wheel as new technique rather then to use already existing implementations
* the new integration use good unit and integration tests as current implementation with a high code coverage (> 80%) 
* is performance tested against a lot of data (a few million entries at least) for (first) indexing and search usage
* there is a migration way from current ElasticSearch usage to the new integration

I would agree with the new integration.
