### ISSUE TITLE
Sort the table for creating workflows numerically

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3181]
The table for creating workflows should be sorted numerically in descending order.

![Screenshot of unsorted table](https://user-images.githubusercontent.com/3040657/74442376-b26d4d00-4e71-11ea-828a-703b14bc1d7b.jpg)

**Comment by henning-gerhardt** [comment]
Is sorting not depending on what you want migrate? Maybe both columns should be sortable or?

**Comment by matthias-ronge** [comment]
It should work but it doesn't. It is an essential aspect of the migration process that the workflow candidates with most processes are at the top.
