### ISSUE TITLE
Show progress when assigning production templates

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3183]
Assigning production templates takes a remarkably long time. The cursor turns but no feedback appears. Here would be e.g. a progress bar is desirable.

**Comment by Kathrin-Huber** [comment]
This isn't required anymore, as performance is enhanced now.

**Comment by matthias-ronge** [comment]
Is this a very recent change? I recently did a migration (with a slightly older version of Production), and assigning production templates for 17,000 process took 8 hours.
