### ISSUE TITLE
3.0: Create process button on desktop leads to wrong template form

### ISSUE THREAD

**Issue by mnscholz** [kitodo/kitodo-production#3194]
I have configured three projects that rely on different templates.

When I click the + button in the projects listing in the Kitodo desktop to create a new process of a project, the process creation form for a different project is loaded.
By browser inspection you can see that the URL for the processFromTemplate.jsf page contains parameters projectID and templateID and that both do not contain the expected values.
Rather, projectID contains the predecessor ID, ie. for project with ID 3 it is 2, for 2 it is 1, and for 1 it is 3 (!round trip!).
The templateID parameter is consistent with the projectID parameter.

**Comment by solth** [comment]
Yes, that is a bug in release 3.0.0 that has been fixed with #3151. That fix should hopefully be included in an upcoming bugfix release.

**Comment by solth** [comment]
@mnscholz can you confirm that this bug is fixed in the current version for you?

**Comment by mnscholz** [comment]
Finally I got to test it on a current version. I confirm that it is fixed.
