### ISSUE TITLE
3.0: Change permissions for /usr/local/kitodo/metadata/<processid>

### ISSUE THREAD

**Issue by mnscholz** [kitodo/kitodo-production#3196]
For each process a directory /usr/local/kitodo/metadata/<processid> is created with following permissions: 
```
drwxr-x---  4 tomcat tomcat 4096 Feb 14 14:06 16/
```
Is there a way to set other permissions?
Why is this dir created with java, but its subdirs are created with the shell script script_createDirMeta.sh? (In the shell script I can set the permissions are desired.)

This is important in cases where you want to allow a user to access the image subdirs, but the user is not in the tomcat group.

**Comment by henning-gerhardt** [comment]
If the process directory is not created through the script `script_createDirMeta.sh` (or an other defined script) then this should be bug. 
One side node: latest versions of Apache Tomcat has a more strict directory and file mask for creating directories or files through java. This can be adjusted on a global Apache Tomcat level. I can look next week how I solved / adjusted this.

**Comment by mnscholz** [comment]
The script is definitely not called. Rather, I found the method `org.kitodo.filemanagement.FileManagement.createDirectory(URI parentFolderUri, String directoryName)` that seems to create the dir and 
that uses `java.io.File.mkdir()`:
```
    private URI createDirectory(URI parentFolderUri, String directoryName) throws IOException {
        parentFolderUri = fileMapper.mapUriToKitodoDataDirectoryUri(parentFolderUri);
        File directory = new File(Paths.get(new File(parentFolderUri).getPath(), directoryName).toUri());
        if (!directory.exists() && !directory.mkdir()) {
            throw new IOException("Could not create directory.");
        }
        return fileMapper.unmapUriFromKitodoDataDirectoryUri(Paths.get(directory.getPath()).toUri());
    }
```

**Comment by mnscholz** [comment]
I must correct my previous comment:
Having done some debugging, I am now sure, the following method of the same class (`org.kitodo.filemanagement.FileManagement`) creates the dir. The problem stays basically the same...

```
    public URI createProcessLocation(String processId) throws IOException {
        File processRootDirectory = new File(KitodoConfig.getKitodoDataDirectory() + File.separator + processId);
        if (!processRootDirectory.exists() && !processRootDirectory.mkdir()) {
            throw new IOException("Could not create processRoot directory.");
        }
        return fileMapper.unmapUriFromKitodoDataDirectoryUri(Paths.get(processRootDirectory.getPath()).toUri());
    }
```

I wonder why the createDirectory() method is not used here. I also would appreciate if Kitodo would create all dirs via scripts. This would make things clearer and more configurable.

**Comment by henning-gerhardt** [comment]
I can confirm this, that at least base directory of each process is not created through a script call like in 2.x. Other directories of this process are created through the script call.

**Comment by matthias-ronge** [comment]
> I wonder why the createDirectory() method is not used here. I also would appreciate if Kitodo would create all dirs via scripts. This would make things clearer and more configurable.

At the beginning of the development project, Presentation was split into modules. The management of files is carried out by the file management module. The command module executes scripts. At the beginning of the project we adhered to the rule that the core calls functions in the modules, but that the modules should be independent of each other and not call each other. Therefore, the file management module cannot run scripts. The creation of subdirectories for media files is done in the core by a service (after it has received the URI of the process folder from the file management module), and this uses the scripts. It seems to me that this was a refactoring misfortune.

**Comment by henning-gerhardt** [comment]
@Kathrin-Huber  @matthias-ronge 

Please correct me if I'm wrong but you can use module A in module B if 
* you define the dependency in the module
* you are using the service loader 
* you only use the methods from the defined API of this imported module. 

But you can not use methods of the core inside the module.

**Comment by Kathrin-Huber** [comment]
That's right, you can include modules in other modules.
We already do this in the [DataEditor](https://github.com/kitodo/kitodo-production/blob/master/Kitodo-DataEditor/pom.xml#L38)

**Comment by matthias-ronge** [comment]
The tests do not run because the module cannot be found. How can we fix that?
