### ISSUE TITLE
Create mptr on export

### ISSUE THREAD

**Issue by Kathrin-Huber** [kitodo/kitodo-production#3215]
Wenn eine Unterordnung exportiert wird, muss ein mtpr zur Überordnung in die METS-Datei geschrieben werden.

**Comment by matthias-ronge** [comment]
This happens in [schema service, line 90](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/services/schema/SchemaService.java#L90). The question is in what context it doesn't work.

**Comment by matthias-ronge** [comment]
Writing METS Pointer works for me.

However, as we now know, METS pointers should be written "upwards" for **all** hierarchical levels (and not only for the next). I will cover this in this ticket.

**Comment by matthias-ronge** [comment]
The export of all link levels is submitted with Pull Request #3347.

@andre-hohmann please check again if the problem really still exists because I cannot reproduce it with me.

**Comment by andre-hohmann** [comment]
For multivolumes and periodicals, it works. 
For newspaper, the mtpr for the year level is missing.

**Comment by andre-hohmann** [comment]
Probably, it works. Let us first find a solution for the other problems with the exports: 
- https://github.com/kitodo/kitodo-production/issues/3614
- https://github.com/kitodo/kitodo-production/issues/3382

Otherwise, testing is very difficult and time consuming.

**Comment by andre-hohmann** [comment]
This issue is closed. The mptr to the parent processes are created: 
- https://github.com/kitodo/kitodo-production/issues/3614
