### ISSUE TITLE
Show parent in structure tree

### ISSUE THREAD

**Issue by Kathrin-Huber** [kitodo/kitodo-production#3254]
The parent nodes in newspaper processes should be shown in the structure tree in metadataeditor

**Comment by matthias-ronge** [comment]
**Example.** Currently, display is like this. Information from parent linked processes is not showing:
```
📁 [no type]
 📁 [no type]
  📁 Issue
   📁 Resort
    📁 Article
    📁 Article
    📁 Article
   📁 Resort
    📁 Article
    📁 Article
```
Should be like this. For each parent process, show the structural path until (but excluding) the downlink. The linked process is indicated by a link sybol:
```
📁 Newspaper 🔗

📁 Year 🔗
 📁 Month
  📁 Day

📁 [no type]
 📁 [no type]
  📁 Issue
   📁 Resort
    📁 Article
    📁 Article
    📁 Article
   📁 Resort
    📁 Article
    📁 Article
```
