### ISSUE TITLE
Gallery detail view does not show selected page in separate structure tree mode

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#3266]
When the metadata editor is opened with the separate structure view, a media unit selected in the physical structure tree is not displayed/updated in the gallery detail view.

<img width="1399" alt="Bildschirmfoto 2020-03-05 um 13 34 31" src="https://user-images.githubusercontent.com/19183925/75982211-5634a080-5ee6-11ea-800d-fc46f9c655be.png">

**Comment by oliver-stoehr** [comment]
The detail view does not show the selected page when it was selected in physical structure without selecting any page in the gallery beforehand.
