### ISSUE TITLE
Process link cannot be deleted

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3275]
A process link should be deletable by selecting the structural element which contains it, and then deleting it. This is not possible because the structural element of a link cannot be clicked on.

![Cannot click the linked structural element](https://user-images.githubusercontent.com/3040657/76288263-9c9f4c00-62a6-11ea-99bb-47794b1a92c0.png)

**Goal:** Allow clicking on linked structural elements again.

**Comment by matthias-ronge** [comment]
@solth, @oliver-stoehr What was the reason to disable the selectability of the linked structural elements? Can I just reactivate it? Or, what could a solution look like?

**Comment by oliver-stoehr** [comment]
This feature was disabled to prevent incompatibilities with other, existing features of the editor. Since linked structural elements don't have e.g. any metadata or media assigned these features might need some adjustments.
If you make sure that the existing features don't break in combination with selected linked structural elements you can reactivate it.

**Comment by matthias-ronge** [comment]
I think the procedure should be the other way around: This blocking deactivates working and required functionality. Simply deactivating a required and working function as a precautionary measure should never have happened and that must be withdrawn very soon. Then we have to check in detail whether operator actions are actually enabled that produce invalid (and not just uncommon, but in principle possible) results, and this must then be solved individually. If a result is valid (from a METS perspective), but is undesired, it should be possible to control this via permissions. But that should then be covered in a separate issue.
