### ISSUE TITLE
3.0: Automatic Tasks and Scripts

### ISSUE THREAD

**Issue by mnscholz** [kitodo/kitodo-production#3279]
I have a problem understanding how automatic tasks are thought to work.
My goal is to automatically run a (shell) script every time a task is finished or startet.
I thought I could do it with automatic tasks but I can't figure out how to do it.

When creating a workflow, for a certain task I can check the "automatic task" checkbox. 
I guess, by this, you can e.g. automate generation of derivatives if you also check "generate images".

Is there also the possibility to assign a script (Kitodoscript or shell script) that should be run automatically by this task?

On the process list I can manually select some processes and run a Kitodo script on them. But this is manual trigger and independent of the current task of a process.

**Comment by matthias-ronge** [comment]
The Kitodo script is a poor man's administrative menu. It has nothing to do with shell scripts. It is named a bit unfortunate.

Yes, automatic tasks are possible, they are only a little bit well hidden if you don't know where. Enter the workflow editor, click on a task. Small symbols appear to the right of it. Click on the wrench.

![Screenshot 1](https://user-images.githubusercontent.com/3040657/81158496-543f9a00-8f88-11ea-918c-aff9da2722a0.png)

"Script task" appears, click on it.

![Screenshot 2](https://user-images.githubusercontent.com/3040657/81158521-5b66a800-8f88-11ea-8569-eed424c08930.png)

Now, under "Properties" on the right, there is an additional _script name_ and _script path_ input field. Function: A link is displayed in the task with the label labeled. When clicked, the script is executed. **Script Name** is the label for the link that is displayed.  **Script Path** is for the command line. Use the absolute path to the file. You can use [placeholders](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/helper/VariableReplacer.java#L95-L152) to pass values ​​to parameters of the script.

For automation, also select "automatic task". Then the task happens automatically, that is, the system takes over the task as soon as it becomes open, executes the script and ends the task, the next one becomes open.

If the script exits with an error level, the step remains open. Assign the workflow step to an administrative role, which can see these tasks and fix them if they hang.

**Comment by mnscholz** [comment]
I have a problem passing arguments with placeholders. From description aboce and the linked code snippet I would assume that one just has to include a placeholder in parantheses in the script path, eg. "/path.to/script.sh (processid) (processtitle)".
However, this does not work for me. $@ is empty.
What is the right syntax?

**Comment by matthias-ronge** [comment]
With the syntax `/path.to/script.sh (processid) (processtitle)` I would have said now (out of my head), that's exactly right. Strange that this happens ... But that would be a separate bug if it no longer worked.

If you could take a look at the database, the string you entered has arrived correctly. You should be able to find it like this: `SELECT * FROM task WHERE scriptPath != '';`

**Comment by mnscholz** [comment]
Thanks very much for the instructions.
I get scripts executed with automatic tasks. However, I have three observations:
1. When the previous task is finished, the automatic task immediately starts the script. Although the script finishes instantly (< 1s), the process is updated/advanced in Kitodo only after a very long time (10-30min). Why is there so much idle time?
2. If the automatic script task is the first task of a process seems that the script doesn't get executed at all. The task displays as locked (strike-thru bell) forever. 
3. The exit code of the script doesn't have an effect on Kitodo. Setting `exit 1` in the script will still render the task successful.

**Comment by matthias-ronge** [comment]
These are three different issues. I have extracted these into their own issues: #3671, #3672, #3673

I would suggest not closing this issue, but marking it via the heading as "[Solved]".

**Comment by m-kotzyba** [comment]
For me, `/usr/local/kitodo/scripts/script.sh (processid)` worked well for an automatic and non-automatic task, e.g. just writing the processid into a text_file.txt in the user's home directory: `echo $1 >> /home/username/text_file.txt`

However, the remaining question for me is whether there is a list of avaliable variables such as `processid` or `processtitle`. Are this variables equal to the avaliable variables for the project folder configuration, e.g. `images/(processtitle)_tif, LOCAL`?

**Comment by matthias-ronge** [comment]
> Are this variables equal to the avaliable variables for the project folder configuration?

Yes, that’s the same functionality.

**Comment by Kathrin-Huber** [comment]
separate issues are created
