### ISSUE TITLE
Sort process list by default

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3299]
By default, the process list is not sorted by anything.

**Goal:** By default, the process list is sorted, e.g. by ID.

**Comment by solth** [comment]
The process list should already be sorted by ID:
![process_list_sorting](https://user-images.githubusercontent.com/19183925/77257585-90879700-6c75-11ea-8e31-d679d8057d08.png)

You can verify this in the available preview system.
The corresponding line in the code is here: https://github.com/kitodo/kitodo-production/blob/d379ef38d29067fcf3d103d0b6acafa22917b3e3/Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml#L31

**Comment by matthias-ronge** [comment]
I can confirm that it works the way it should. I close this ticket as done.
