### ISSUE TITLE
Show full names of parent processes

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3308]
In the display in the process list, when the child process is expanded, the names of the higher-level processes are truncated. The information is worthless like this, since the last characters in particular are decisive.

![truncated names](https://user-images.githubusercontent.com/3040657/76971561-a3286600-692d-11ea-815f-2bea0a0d6d2c.png)

**Goal:** The titles of the higher-level processes must be completely legible. If, for technical reasons, it is not possible to show the entire title, a tooltip should make it possible to see all of it.

**Comment by solth** [comment]
The tooltip has been added 5 days ago with #3287: 
https://github.com/kitodo/kitodo-production/blob/aecae3c22d7a54971349eefb5574542efae31f9b/Kitodo/src/main/webapp/WEB-INF/templates/includes/processes/processList.xhtml#L248
Maybe your code base is not up to date?
