### ISSUE TITLE
Remove switch to create unreachable production templates

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3311]
The dialog for creating production templates contains a switch named "active". If you set this "off", the production template is not displayed in the list of production templates after creation. It can no longer be reached and can no longer be viewed or edited. (Still, it is possible to create processes from this production template!)

**Goal:** Eliminate switch and functionality. Existing production templates should always be accessible somehow.

**Comment by solth** [comment]
Was this perhaps intended to filter the templates available when creating a new process for a project with multiple assigned templates, instead of the full template list?

**Comment by matthias-ronge** [comment]
Yes, I assume so. However, the implementation described above is quite the opposite and would have to be changed.
