### ISSUE TITLE
Remove symbolic link

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3314]
Symbolic links are not removed, neither when returning or completing a task, nor with the button in the process list. A quick search revealed that the configuration variable for the script is not even considered for this except in the test class. The functionality is probably completely missing in the code.

**Goal:** implement function. The symbolic link should be removed if
* task is returned (set back to open)*
* correction step*
* task ends*
* the function _remove link_ in the process list is clicked

*) condition: if task is `typeReadImages` or `typeWriteImages`

**Comment by henning-gerhardt** [comment]
Please remove the symbolic link only if you need or create the link in the task for example to read or write image files into the images process directories. If you try to remove this symbolic link on every task of a process then you are creating a lot of unnecessary calls to the underlying system.

**Comment by matthias-ronge** [comment]
You're right. So it was meant.
