### ISSUE TITLE
Reports successful export only once

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3316]
If the export was successful, this will be displayed three times. In addition, the green boxes at the top right ~~cannot be closed (and~~ do not disappear ~~) so the menu is no longer accessible~~  automatically.

![Anmerkung 2020-03-17 143015](https://user-images.githubusercontent.com/3040657/76975879-75deb680-6933-11ea-8db2-9e6c7a2b8987.png)

**Goal:** Show message only once.

**Comment by matthias-ronge** [comment]
#3367 is related to this

**Comment by andre-hohmann** [comment]
Do we need the green boxes at all? The same information is part of the "information badge" above the process list.
From my point of view, even when the boxes are closed automatically _(which currently does not work_), it is annoying to wait until they are closed. 

When newspapers are exported it becomes confusing: 
![exportmessage](https://user-images.githubusercontent.com/14835770/132632366-efea3781-0c95-4ec2-9525-8775eac56505.jpg)
