### ISSUE TITLE
Test METS file not well-formed and without license header

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3329]
The file [Kitodo/src/test/resources/metsFromKitodo.xml](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/test/resources/metsFromKitodo.xml) ist not well-formed. The error message in line 24 reads: _cvc-complex-type.2.4.b: The content of element 'mets:xmlData' is not complete. One of '`WC[##any]`' is  expected._

The file is also missing the license header.

**Comment by solth** [comment]
http://www.utilities-online.info/xsdvalidation says the file is well-formed. The error message you quoted seems to imply schema validation instead.

**Comment by matthias-ronge** [comment]
Maybe I didn't express myself clearly enough. Yes, this is always shown as incorrect.
