### ISSUE TITLE
Kitodo script for adding images to the meta file

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3333]
Carl Wagner has heavily automated his workflow in one project so that there is practically no manual work involved. For each process, however, he still needs someone who opens the process in the metadata editor and clicks Save so that the images are recognized and written to the METS file. He wants to automate this with the Kitodo script for larger amounts of processes. He also wants to be able to run Kitodo scripts from an automatic step.

**Comment by daropoi** [comment]
I want to support this issue - would be important for getting externally created alto-xml-files into the processdir in an effective way

**Comment by henning-gerhardt** [comment]
If he really wants to do a full automatic work flow then this should be done as an automatic task with defined and hard coded logic like exporting the process. So far as I understand Kitodo script calls still need a human with correct rights / permission / authority to click them so a Kitodo Script is only useful if you want to do this on the UI.

**Comment by matthias-ronge** [comment]
You are right, being able to execute KitodoScript commands from a workflow step is still missing somehow. However, in order to keep the focus of this issue, I would suggest opening a new issue for that.
