### ISSUE TITLE
Translate workflow editor

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3338]
The workflow editor is largely not translated. This affects both the tooltips for the mouse menu and the small symbols to insert further steps, as well as most of the "Properties" dialog with its content.

![Screenshot](https://user-images.githubusercontent.com/3040657/77748084-14e46c00-7020-11ea-81ca-4f429fd71d5c.PNG)

**Comment by Erikmitk** [comment]
I need is a list of the strings in both German and English for the labels and tooltips.
