### ISSUE TITLE
Advanced search’s task status filter not working

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3341]
Selecting a specific task status in the advanced search does not change the search result.

**Comment by solth** [comment]
@matthias-ronge can you check if this problem still occurs for you? I cannot reproduce it, the task status filter in the advanced search works as intended.

**Comment by matthias-ronge** [comment]
Yes, this is still the case.

![Screencast](https://user-images.githubusercontent.com/3040657/165751466-5e05cdb9-597b-4f8a-ad7c-9697dd68cf71.gif)

The most obvious variant is that, when I search for tasks of the type "completed", I also get processes that do not yet have even one task completed. It seems that this search has no effect at all. I also notice that no text appears in the filter slot. Maybe that has a connection.

My expectation here is that only those processes are displayed that have at least one task to which the condition applies.

**Comment by Kathrin-Huber** [comment]
I think you need to choose a task as well, not just the task status
