### ISSUE TITLE
Export directory hierarchy has changed

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3364]
In version 2, the exported METS file was placed in the hot folder next to a folder of the same name with files (pictures, etc.). The METS file is currently being placed _in_ this folder so that existing post-processing scripts can no longer find it.

**Goal:** As in version 2, the file should be placed _next to_ the content folder.

**Comment by frank-ulrich-weber** [comment]
Beside that the METS file is placed next to the content folder, both can be exported in a sub-folder of the hotfolder named after the process title. That behaviour can be configured within the project properties.
