### ISSUE TITLE
Metadata editor does not create backup files

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3379]
In Production version 2, when saving in the metadata editor, the current metadata file was renamed and saved as a backup. This is, when a chaotic state has been reached and then saved by the user, to return to the previous state. In version 3 such backups are no longer created.

**Goal:** Re-enable generation of backups.

**Comment by mnscholz** [comment]
I wondered if it would be possible to use a listener for an event that gets triggered when saving the metadata in the editor. Then it would be possible to have different backup strategies implemented, eg. run a script that does a git commit on the metadata file.

**Comment by matthias-ronge** [comment]
For exactly this strategy we have modules in Production: To provide for different solutions to a given problem. Your suggestion would therefore mean to solve the metadata backup by means of a module, so that alternatively another module could be put in place, which then implements, for example, Git backups. This is outside the scope of this ticket, which initially requests that a backup be called at all (which is not currently happening). But, you could record that as a separate ticket.
