### ISSUE TITLE
[Solved] How to assign a page to several divisions

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3393]
The layout of the dialog box is poor:

![Screenshot of current dialog box](https://user-images.githubusercontent.com/3040657/78376700-f9a0d000-75ce-11ea-9613-0096d101edab.png)

**Goal:** Create layout.

**Comment by solth** [comment]
I think this dialog has been removed since page allocation is done by drag'n'drop in 3.x

@matthias-ronge can you confirm this issue is resolved since the dialog is not displayed anymore?
