### ISSUE TITLE
Missing correction message

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3400]
### Problem
It is not possible to send a correction message from for example. “metadata” to “scan”. Therefore, it is not possible to set the task back to “scan”. 

![Korrekturmeldung](https://user-images.githubusercontent.com/14835770/78764676-2ebe7100-7987-11ea-9117-e4ed5dc52895.jpg)

### Solution
It must be possible to change the task of a process and to describe the correction via a correction message. 

See Kitodo.Production 2.x: [https://github.com/kitodo/kitodo-production/wiki/Korrekturmeldungen](https://github.com/kitodo/kitodo-production/wiki/Korrekturmeldungen)

**Comment by solth** [comment]
This should already be possible via the tab "Kommentare" -> button "Kommentieren" -> activate switch "Korrekturmeldung" and select the task to which the process should be resetted.

**Comment by andre-hohmann** [comment]
Ok, thank you. That was my fault. The issue is closed.
