### ISSUE TITLE
Metadata for “Select insertion position” 

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3406]
### Problem
If a new process for a periodical volume is created, it is necessary to define the position for its insertion in the list of other volumes. To support that task, curently the ID is shown as mouse over-effect. 

![zeitschriftenbandeinfügen02](https://user-images.githubusercontent.com/14835770/78779746-bfa04700-799d-11ea-9c30-bf5a1f64e2f0.jpg)

Practically, the user does not know the internal IDs of processes. If the processes for the periodical volumes are generated in the correct order, it works. Otherwise (the more likely case) not. 

### Solution
It would be helpful, if a metadata field is used for the mouse over effect. The opportunity to enable a configuration by the users would be the best solution – for example by an attribute in the ruleset use=”sortingNumber”.

**Comment by andre-hohmann** [comment]
@matthias-ronge : 
Is it possible to show the process title instead of the ID? That would be an significant improvement.

**Comment by matthias-ronge** [comment]
I think we have to make it configurable in the rule set so that you can specify which fields are shown there. I think every institution wants to see different fields.

**Comment by andre-hohmann** [comment]
Of course, this is my preferred solution!

Preparing the preview system with processes for the colleagues, it occurred to me that the ID not usable at all. 
To give the colleagues a better feeling for Kitodo during the tests, i thought the process title is an option for a "quick and dirty solution". the process title contains information about volume numbers. 
In case that analysis of metadata in the ruleset is difficult and the process title could be extracted from the properties, it would be a temporal compromise. If this is not possible, we will wait for the configuration-solution.

**Comment by matthias-ronge** [comment]
I have now solved this as follows: You can enter a `use="displaySummary"` for a metadata `<key>` in the ruleset. If this does not exist, the process title plus the internal ID in square brackets is shown (as is also used in the images link, for example).
