### ISSUE TITLE
Automatic recognition of multivolume works 

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3407]
### Problem
If a process for a volume of a multivolume work is created, the user has to set the “import depth” to 2. 

![importVolume](https://user-images.githubusercontent.com/14835770/78781164-1149d100-79a0-11ea-9dcc-cdcaea38a0d6.jpg)

If this is forgotten, the process for the volume will be created without the parent process. Then, the process for the volumes has to be deleted and a new process has to be created. 

### Solution
It would be helpful, if a volume of a multivolume work is recognised automatically, by the creation of the process. Then, the application of the “import depth” is not necessary anymore or at least optional. 
For example, the attribute use="higherlevelIdentifier" or the doctype in the ruleset could be used to identify a multivolume work.

**Comment by solth** [comment]
This seems like a duplicate of #3257 and should have been fixed by #3287 some time ago.

**Comment by andre-hohmann** [comment]
Can i like your comment in GitHub? That would be great!

**Comment by Kathrin-Huber** [comment]
So this can be closed?

**Comment by matthias-ronge** [comment]
No, it's not the same as #3257. There, it is the matter about creating a link to the parent at import depth 1 for an **existing** parent document. This ticket deals with the fact that _by default_ **not yet existing** parents are to be imported, unless the user actively wants it differently, but not that the user actively has to take action for that parents are also imported.

My proposed solution would be that in OPAC XML can be set whether an OPAC has the “import depth” option and with which default, or whether it is hidden, and then all parents are checked and imported if necessary.

**Comment by andre-hohmann** [comment]
I support that solution.

**Comment by solth** [comment]
`importDepth` is now already set to default value "2" if not actively configured differently by the user/admin. So in the default case, the system will always try to import the parent process, without the user manually activating this feature. I think that means the issue is resolved, isn't it?

**Comment by andre-hohmann** [comment]
Yes, think so, too. I will close the issue. If problems occur, we can re-open the issue.
