### ISSUE TITLE
Generation of “TSL/ATS” for volumes of multivolume works without title

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3408]
### Problem
Some volumes of multivolume works do not have an own title. Therefore, the generation of the “TSL/ATS” for the volume is not possible and the user inserts it manually. 

### Solution
In Kitodo.Production 2.x the “TSL/ATS” of the parent process was used to generate the process title. This should be possible for Kitodo.Production 3.x, too, because: 
- No manual work necessary anymore
- The probability of consistent process titles is higher

**Comment by matthias-ronge** [comment]
Would it be a wayable solution to provide something for volumes like `processTitle="+'_'+#4"`, which would resolve as “title of the parent + '_' + next index (current number of child processes + 1) with 4 digits”?

For example , for a parent "LoreIpsu_1234567X" it would create children like “LoreIpsu_1234567X_0001", "LoreIpsu_1234567X_0002", …

**Comment by andre-hohmann** [comment]
Regarding multivolume works in K10plus, each volume and the toplevel element have an own PPN. Therefore, the process title of the toplevel element should not be used. The 4 digits can be easily captured in a metadata field like "NumberProcessTitle" that can be defined in the ruleset as part of the process title: 
- <`division id="Volume" processTitle="TSL_ATS+'_'+CatalogIDDigital+'_'+NumberProcessTitle"> ` 

Here, only the "TSL/ATS” is missing. Therefore, it would be sufficient, if only the "TSL/ATS” would be copied from the parent process in the metadata field of the volume - **but only, if it is empty in the volume**. 
If it is captured in the metadata field, the process title can be generated like for all other processes.

Example 1 (with "TSL/ATS”): 
- Volume 1: `dreskuiml_351324453_0001`
- Volume 2: `dreskuiml_351326405_0002`
- Toplevel: `dreskuiml_351324453`

Example 2 (without "TSL/ATS”):
- Volume 1: `_1577422449_0001`
- Volume 2: `_1577422678_0002`
- Toplevel: `Prov_1577422147`

**Comment by andre-hohmann** [comment]
@matthias-ronge : Your suggestion would be relevant for periodical volumes, which have no own PPN. In that case, it would be reasonable to think about a concept regarding other metadata elements, that could be inherited from the parent element like: 
- collections
- language
- PPN parent element
- TSL/ATS

Or elements, that could be derived from the parent element like: 
- docType

It is possible to make the capture of metadata more efficient. I think, @subhhwendt has thought about this, too - maybe she can contribute to this discussion.

**Comment by subhhwendt** [comment]
Regarding periodical volumes my colleagues expect TSL/ATS and PPN from the parent element. The third  part will be "NumberProcessTitle" along our institutional rules. 

We agree in all aspects to André Hohmann - regarding multivolumeworks.

**Comment by andre-hohmann** [comment]
Regarding the suggestion for periodical volumes, the issue #4369 should be taken in consideration. Both issues have similar aims 
and it is probably not necessary to pursue both issues. 

Disadvantage of the suggestion above: 
- Many reoccurring values like rights information, script, footer, ... cannot be derived from the metadata of the process from the periodical and must be added manually
Advantage of the suggestion above: 
- volume-specific values (volume number, call number, identifier, ...) have not to be corrected manually and thus, mistakes can be avoided
