### ISSUE TITLE
processes of newspaper issues and volumes cannot be deleted

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3409]
### Problem
Processes of newspaper-issues cannot be deleted. 
It turned out that processes of volumes of multivolume works cannot be deleted, too. 

The following error-message is shown: 
- `Error deleting 'Link'`

![deletenewspaperprocess01](https://user-images.githubusercontent.com/14835770/78784815-507b2080-79a6-11ea-9790-5967671678e0.jpg)

### Solution
It must be possible to delete processes of newspaper-issues.

**Comment by solth** [comment]
The error message `Error deleting 'Link'` normally indicated that the process was indeed deleted successfully, but the link in the parent multivolume work or newspaper process could not be removed. Can you confirm that the process was indeed deleted, but only the link wasn't removed successfully?

**Comment by andre-hohmann** [comment]
I have trusted the error message and did not check the deletion. 

Now, i can confirm that the deleted process was deleted from the process list. 
I cannot open the direct parent process (584 BuchunKu_81803940X_1839) to check, if the link has not be removed there.

**Comment by solth** [comment]
You were correct to trust the error message, because it is indeed just the link (from the parent to the child) that could not be deleted, not the child process itself!
The incorrect link in the parent process' `meta.xml` file is also the reason why the parent process fails to load in the metadata editor - since the editor tries to resolve the links and cannot find the referenced child process in this case.

**Comment by andre-hohmann** [comment]
OK, that could be a reason for the problems with the newspaper-export.

**Comment by andre-hohmann** [comment]
Processes of newspaper issues and volumes of multivolume works are deleted without the error message. 
In the process of the multivolume work, the link to the deleted volume is deleted, too. 
In the process of the newspaper-year, it cannot be checked, if the link is deleted, because of https://github.com/kitodo/kitodo-production/issues/3436. 

@Kathrin-Huber : Do you need more information?
