### ISSUE TITLE
Update of current status of processes after “Set status”-action in process list

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3410]
### Problem
After the status of a process is set up or set down, the current status is only shown after updating the process list or the browser window. 

### Solution 
The current status should be shown directly after the status of a process is set up or set down.

**Comment by solth** [comment]
@andre-hohmann I cannot reproduce this issue. Could you check again if the error still occurs?

**Comment by andre-hohmann** [comment]
With my current examples, it works now, too. 
I will close the issue. If it happens again, we can open a new one.
