### ISSUE TITLE
Newspaper-issues: two logical structure trees

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3418]
### Problem
In processes of newspaper-issues, there are two structure trees. One consists of two elements "Unknown structure type". 

#### Example "logical and a structure tree": 
![doublestructuretree01](https://user-images.githubusercontent.com/14835770/78810822-330b7e00-79c9-11ea-97e9-ef4284583943.jpg)

The export of these processes is aborted with the following message in the task manager: 
- crashed (metadata validation failed)

#### Example "one structure tree"
![doublestructuretree02](https://user-images.githubusercontent.com/14835770/79037608-18a4f080-7bd3-11ea-9c6e-1c35b0161120.jpg)

Export progress 0%: 
![errorexport01](https://user-images.githubusercontent.com/14835770/79037799-8aca0500-7bd4-11ea-9291-b0d9eff496f6.jpg)

### Questions
- Does this have to be?
- Are there other issues regarding this phenomenon?

**Comment by matthias-ronge** [comment]
Displaying the structure trees of all superordinate processes is a feature at the moment. It has to be shown whether the practice proves it.

The “export is 0%” looks like a bug to me, but has nothing to do with the other. @andre-hohmann, could you please create a separate ticket for the second one?

**Comment by andre-hohmann** [comment]
The "export-problem" cannot be described in one ticket. There are severel problems, as for example: 
- https://github.com/kitodo/kitodo-production/issues/3436
- https://github.com/kitodo/kitodo-production/issues/3435

From my point of view, the issue can be closed. If it causes problems, we can open a new one - hopefully with more information.

**Comment by matthias-ronge** [comment]
So then, this ticket should only deal with this problem: Export says "finished" but progress is 0%. **Goal:** Either, if an error has occurred, it should not be "finished", but the error must be displayed (with text that reports what the error is). If no error occurred, 100% should be reached.

**Comment by andre-hohmann** [comment]
I opened a new issue for it, with a correct name: https://github.com/kitodo/kitodo-production/issues/3440. 

Thus, i will close this issue.
