### ISSUE TITLE
Selected processes change position in the process list after setting status of the selected processes

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3426]
### Problem
If in a process list of several pages, the status of some (for example four) selected processes is changed up or down, the position of the processes in the list changes. 
In several attempts, the processes of the first page moved on the third page of the process list. 
In some attempts, the selected processes did not change. 

### Solution
Processes in the process list should not change the position after their status has been set. Regardless of the number of processes or lenghths of the process list. 

See also: https://github.com/kitodo/kitodo-production/issues/3427

**Comment by matthias-ronge** [comment]
May be related to #3293 ?

**Comment by andre-hohmann** [comment]
Not really. 
In this case, the staus of two processes from the first page was changed and the processes were found on page three. The list was not sorted or filtered. 
It might rather be related to https://github.com/kitodo/kitodo-production/issues/3417, because another factor for the sorting was created, which causes a new sorting position.

**Comment by andre-hohmann** [comment]
A current test does not show the effect anymore. Probably, it was solved by https://github.com/kitodo/kitodo-production/issues/3417 or another issue. 

I will close the issue. If the behavior occurs again, a new issue should be opened.
