### ISSUE TITLE
Validation warning: The structure has no media assigned: PeriodicalIssue "null"

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3434]
### Problem
For processes of newspaper-issues the following warning is shown: 
`The structure has no media assigned: PeriodicalIssue "null"`

This leads to problems during the export. 

### Solution
The images of the process should be assigned automatically to the element "PeriodicalIssue". Otherwise, the images have to be assigned manually, which is quite time-consuming. 

### Example
![validationwarning01](https://user-images.githubusercontent.com/14835770/79189968-631cac00-7e23-11ea-801a-c6199e982fc8.jpg)

**Comment by matthias-ronge** [comment]
The validation criticized that no images are assigned to the “unknown structure type” root element. In this case, that's correct, it shouldn't.

**To do:**

- correct validation, for included structural element with type `null`, do not check.
- Second: warn message should not be green. Either it also turns red, or maybe a yellow hue.
- In addition: “unknown structure type” is incorrect. It is not unknown (in that case it would be yellow, with an exclamation mark), but without a type. Change text to “[Untyped]”

**Comment by andre-hohmann** [comment]
The validation is correct, because the images should be assigned to the element "PeriodicalIssue". 
After i did it manually, the validation warning was not shown anymore. 

However, the assignment of the images to the element "PeriodicalIssue" has to be done automatically!! Otherwise, it takes a long time to finish the processes.

**Comment by matthias-ronge** [comment]
Okay, then that's something else again, and what I've described above is what the error #3435 is.

Should the assignment only happen if there is only one issue in the process? What if there are multiple issues in the process?

**Comment by andre-hohmann** [comment]
That is a good question. We work in the SLUB only with one issue per process and as this is an requirement by the DFG, i think most will use it that way. So important is: 
If only one issue is in the process: _All images are assigned to the element "PeriodicalIssue"_

Otherwise:
If several issues in the process: _No images is assigned to any element_
Corrections of wrong assigned images are more time consuming then a correct initial assignment.  
If we find a better solution, we can apply it. That should depend on the amout of its application.

**Comment by Kathrin-Huber** [comment]
Is this still a problem? we had some fixes in the assignment in the meta.xml , maybe this is fixed too?

**Comment by andre-hohmann** [comment]
It is still a problem: The images have still to be assigned manually to the issue. 
Otherwise, the error message is shown.

**Comment by matthias-ronge** [comment]
**Goal:**

> the assignment of the images to the element "PeriodicalIssue" has to be done automatically!! Otherwise, it takes a long time to finish the processes.
> If only one issue is in the process: _All images are assigned to the element "PeriodicalIssue"_
> If several issues in the process: _No images is assigned to any element_

**Comment by andre-hohmann** [comment]
@matthias-ronge , it seems as if the assignment does not work. As the error messages are not shown (#4081), it is difficult to identify the other problems. 

In the preview system, the following process has been created and all images are in "Unstructed media".
-  ElbefRiS_1666403997-20201102 - ID: 3575

**Comment by Kathrin-Huber** [comment]
But isn't this a problem not just for newspapers? When structuring a Monografie, all images are also added to "unstructred" until they are assigned to the specific structural element. As I understood it, that's what the Metadataeditor is for ;-)
How am I supposed to know, where to add the media to?

**Comment by andre-hohmann** [comment]
The basic problem is **not** that the images are added to the section "Unstructred media", because then, the images are assigned automatically to the first-level structure element, for example monograph or volume. 

For newspapers, the problem is the following: 
There are two levels of "Division without type" to which no images can be assigned to, because they represent the month/day-level.  However the images of "Unstructred media" are automatically assigned to the "Division without type". 
This leads to the error message `The structure has no media assigned: PeriodicalIssue "null"`, because " PeriodicalIssue" is the first level of the structure elements to which images can be assigned to. 
This has to be done manually and is very time consuming.

**Comment by matthias-ronge** [comment]
I agree that this should be handled automatically.
