### ISSUE TITLE
Validation warning: The structure has no media assigned: null "null"

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3435]
### Problem
For newspaper processes the following warning is shown:

- `The structure has no media assigned: null "null"`

This leads to problems during the export. It is not possible to assign images to the element "newspaper". 

### Solution
Processes of newspaper and other parent-procesess must not be validated for assigned images, because the processes conatain no images. 

### Example
![validationwarning03](https://user-images.githubusercontent.com/14835770/79202053-4c814f80-7e39-11ea-8184-dd7f1c1a27a4.jpg)

**Comment by matthias-ronge** [comment]
It looks like this is the same problem as in #3434
