### ISSUE TITLE
processes of the year-level of newspaper cannot be opened

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3436]
### Problem
The processes of the year-level of newspaper cannot be opened in the metadata editor from the process list. 
This behaviour occurs also, if no child processes have been deleted. See: https://github.com/kitodo/kitodo-production/issues/3409

After a while, a error message is shown: 
```
Fehlerhaftes Gateway!
Der Proxy-Server erhielt eine fehlerhafte Antwort eines übergeordneten Servers oder Proxies.
The proxy server could not handle the request
Reason: Error reading from remote server
Sofern Sie dies für eine Fehlfunktion des Servers halten, informieren Sie bitte den Webmaster hierüber.
Error 502
```

### Solution
The reason of tha behaviour has to be found and eliminated. 

### Example
parentprocessid:951
- WochfReS_1067801324_1902
- WochfReS_1067801324_1903

**Comment by matthias-ronge** [comment]
The error message indicates a timeout in an intermediate proxy server. The solution is to increase the timeout within the used proxy server.

Background: To display the structure tree, every linked child METS file must be read. A newspaper annual process with children can be opened, it simply takes some time. The more children, the more time is needed. (A detailed performance analysis of this can be found in KIT-1112.)

I would therefore suggest closing the ticket as “no error”.

**Comment by andre-hohmann** [comment]
I know it is a local problem, but whom do i have to ask to increase the timeout of the proxy server?

**Comment by matthias-ronge** [comment]
The IT managers at `sub.uni-hamburg.de` would have to do that. @subhhwendt, do you know who the contact person is and could you pass this on?

**Comment by matthias-ronge** [comment]
Or, @solth, you also have SSH access to the preview system, right? Could you increase the timeout of the proxy server?

**Comment by solth** [comment]
I guess you need to talk to @joerg-liebenow for proxy server configuration

**Comment by andre-hohmann** [comment]
With the example processes, it works now. Therefore i close the issue.
