### ISSUE TITLE
Inconsistent information about export in the taskmanager: status/progress/error

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3440]
### Problem
In the taskmanager the infomation about the export status of a process is inconsistent, for example: 
- Progress: _0%_
- Status: _Finished_
- Error-message: _none_
However, an export cannot be finished at _0%_! 

### Solution

1. If the status is _0%_, an error message should be shown, instead of the status _Finished_. 
2. If the task has been finished correctly, the status should be set to _100%_

### Example
![inconsistentexporterror01](https://user-images.githubusercontent.com/14835770/79232346-b284cb80-7e67-11ea-96d9-c534a909a163.jpg)

**Comment by matthias-ronge** [comment]
Another occurrence of the problem:

![Screenshot](https://user-images.githubusercontent.com/3040657/80975404-5851a780-8e22-11ea-97c2-37df83599ddf.jpg)

**Comment by matthias-ronge** [comment]
Setting the task progress state is individually happening from the functions. Here, is “export process” affected, which should be fixed. But we need individual bug reports per function if this doesn’t work for some background task.
