### ISSUE TITLE
Establishing a new thumbnail view in the gallery during the tagging process is buggy

### ISSUE THREAD

**Issue by subhhwendt** [kitodo/kitodo-production#3444]
You enter a steady "F5-situation" with incomplete thumbnails when you have chosen images in the gallery and the proper structure element  - completing the action by the button "Übernehmen".

**Comment by Kathrin-Huber** [comment]
I cannot reproduce the error, what is the exact szenario?

**Comment by subhhwendt** [comment]
The error situation changed - in my testing - see the attached screen cast
![Strukturieren_06052020](https://user-images.githubusercontent.com/5708995/81184767-160aa080-8fb1-11ea-8661-f06dc5bf975e.gif)

**Comment by solth** [comment]
It appears this bug has been fixed as I cannot reproduce it with the current system.
@subhhwendt can you confirm the bug does not occur anymore?

**Comment by subhhwendt** [comment]
It's not possible to proceed in tagging with a second element in my experience. Testing with id:1237 - look at the tiny screen cast. What's the difference in your way?
![strukturieren_29052020](https://user-images.githubusercontent.com/5708995/83301979-d410fb00-a1fa-11ea-996a-859429ab10fc.gif)

**Comment by solth** [comment]
I was able to reproduce the error with the help of your screencast but couldn't find any error in the code that could cause the problem. 

Therefor I would suggest to change the `STATE_SAVING_METHOD` in Kitodo.Production from `server` to `client` - see #3769 - which effectively prevents `ViewExpiredException`s altogether (see last sentence in https://stackoverflow.com/a/8474609/5467214)

**Comment by solth** [comment]
It seems this error only occurs in Firefox. @oliver-stoehr and me have both been able to reproduce it in that browser, but not in Edge, Chrome or Safari.

The number of open tabs also seems to have some relevance here, since the `ViewExpiredException` was not triggered in a "freshly" started Firefox, but only after there were >= 50 open tabs in the browser (the error still occured after most of those tabs were closed, though)

**Comment by mnscholz** [comment]
> It seems this error only occurs in Firefox.

I also get the error in Chromium / Chrome.
