### ISSUE TITLE
Landing point in the gallery returning from detail view is not correct (by icon or by shortcut)

### ISSUE THREAD

**Issue by subhhwendt** [kitodo/kitodo-production#3445]
The focus is always the beginning of the gallery and not your place of current action - except one situation: Using "Übernehmen und Bearbeiten" and returning by icon -  in this case you arrive as expected in my experience.

**Comment by oliver-stoehr** [comment]
It seems like these changes might have had side effects on scrolling to the selected thumbnail in general.
