### ISSUE TITLE
Import multivolume work - case 3 does not work

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3456]
The issue is based on a coment on https://github.com/kitodo/kitodo-production/pull/3287. 

Case 3 of import of multivolume works: 
`3. Fall: "Volume" ist noch nicht im System, "MultiVolumeWork" aber schon, Import-Tiefe 1: "Volume" wird geladen und gespeichert und mit dem  im System vorhandenen "MultiVolumeWork" verknüpft`

The specific case when "Importtiefe=1" was chosen with a volume from a multivolumeWork, which is already imported, fails in linking to the multivolumeWork - in my experience.
The relation to the parent id is detected in metadata - but the volume shows no connection to the parentelement in the database.

![importmultivolume01](https://user-images.githubusercontent.com/14835770/79432755-8b93da00-7fcc-11ea-919d-eca82e727ad2.png)

![importmultivolume02](https://user-images.githubusercontent.com/14835770/79432766-8f276100-7fcc-11ea-911b-62f98aa8b5e6.png)

**Comment by Kathrin-Huber** [comment]
Seems to be fixed in current master.
Please confirm @andre-hohmann
