### ISSUE TITLE
metadata area in metadata editor partly hidden after validation

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3462]
### Problem
After validation in the metadata editor, the metadata area is partly hidden behind the footer and beyond. 
The scroll bar gets lost  and even with the arrows, you cannot reach the end of the metadata area.

### Solution
All parts of the metadata editor should be completly visible after validation. 

### Example
![hiddenmetadatasection01](https://user-images.githubusercontent.com/14835770/79458688-72058900-7ff2-11ea-85d1-21b60e77d30c.jpg)

**Comment by matthias-ronge** [comment]
Related to #3392

**Comment by andre-hohmann** [comment]
This behaviour cannot be reproduced anymore. 
Thus, the issue is closed.
