### ISSUE TITLE
Process title for newspapers/ephemera needs to be adjusted

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3479]
### Problem
The current process title of newspaper/ephemera follows the rule:
> TSL/ATS_PPNnewspaper_volumeInformation-Issue

Example: 
WochfReS_1067801324_1851120101-F

However, for the SLUB, if should follow the rule: 
> TSL/ATS_PPNnewspaper-volumeInformation_Issue

Example:
WochfReS_1067801324-1851120101_F

Otherwise, the record identifier for Kitodo.Presentation will not be extracted correctly.

### Solution
Adjustment on the creation of the process title for newspapers/ephemera. 
I'd be glad if i can do it independently with the ruleset, ...

**Comment by matthias-ronge** [comment]
Yes, this is configurable via the rule set. I'm not 100% sure of what the _ten_ digits of the "volumeInformation" stand for (1851-12-01-01, year, month, day, day?), but it should look something like this:
```xml
<division id="Newspaper" processTitle="TSL_ATS+'_'+CatalogIDDigital">
    <label>newspaper</label>
    <label lang="de">Zeitung</label>
    <subdivisionByDate>
        <division dates="ORDERLABEL" id="NewspaperYear" scheme="yyyy"
                  processTitle="+'_'+#YEAR"/>
        <division dates="ORDERLABEL" id="NewspaperMonth" scheme="yyyy-MM"/>
        <division dates="ORDERLABEL" id="NewspaperDay" scheme="yyyy-MM-dd"/>
    </subdivisionByDate>
</division>
<!-- ... -->
<division id="PeriodicalIssue" processTitle="+#MONTH+#DAY+#DAY+'-'+#I">
    <label>Issue</label>
    <label lang="de">Heft/Ausgabe</label>
</division>
```

**Comment by andre-hohmann** [comment]
The last two digits are the numbers of the issue, in case there are several ones a day. In 2.x, this was the configuration:  
`TSL+'_'+PPN digital b-Satz+'-'+#YEAR+#MONTH+#DAY+#is+'_'+#issu`

For the year, it works, like for example: 
`<division dates="ORDERLABEL" id="NewspaperYear" scheme="yyyy" processTitle="+'-'+#YEAR"/>` 
-> `WochfReS_1067801324-1979` 

For the issue it does not work, as for example: 
`<key id="PeriodicalIssue" processTitle="+#MONTH+#DAY+#is+'_'+#ISSU">`
-> `WochfReS_1067801324_1979070201-A`
-> `WochfReS_1067801324_1979043001-A`

**Comment by andre-hohmann** [comment]
I found the mistake in the configuration - sorry! 
Now, it is possible to generate process titles as for example: 
- Aben_774618868-1871051501_01-f
- Aben_774618868-1871051502_02-a
