### ISSUE TITLE
Export is not fully carried out when the automatic task is triggered in the process or task list

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3481]
#### Option 1
The export does not start, when the previous task is closed. 
The task “export” stays at the status “open”, although it is a automatic task. 
Information in the taskmanager : 
- Progress: 0%
- Status: Finished

#### Option 2
The export does not start, when the status of the process is set up in the process list. 
The task “export” stays at the status “open”, although it is a automatic task. 
Information in the taskmanager : 
- Progress: 0%
- Status: Finished

#### Option 3
The export triggered by the button “Export DMS” in the process list works correctly.

**Comment by Kathrin-Huber** [comment]
fixed #3526
