### ISSUE TITLE
Correction of KitodoScript names 

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3485]
The following KitodoScripts should be corrected according to the new naming (step -> task). 
It has to be ensured, that the Script still works. Contrary to https://github.com/kitodo/kitodo-production/issues/3483, **these Scripts seem to work with the current naming**. 

`setStepStatus` -> `setTaskStatus`
- `action:setStepStatus "steptitle:TITLE_STEP" status:NUMBER_0_TO_3` -> 
- `action:setTaskStatus "tasktitle:TITLE_TASK" status:NUMBER_0_TO_3`

`addShellScriptToStep` -> `addShellScriptToTask`
- `action:addShellScriptToStep "steptitle:TITLE_STEP" "label:LABEL_FOR_SCRIPT" "script:PATH_TO_SCRIPT"` -> 
- `action:addShellScriptToTask "tasktitle:TITLE_TASK" "label:LABEL_FOR_SCRIPT" "script:PATH_TO_SCRIPT"`

**Comment by matthias-ronge** [comment]
Fixed by #3560
