### ISSUE TITLE
Add new InsertionPosition for structural elements in metadata editor

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#3486]
When creating new structural elements in the metadata editor from selected consecutive pages, an additional option should be added for adding the structural element at the position of the selected pages (e.g. the index of the first selected page in the parent structural element).

**Comment by matthias-ronge** [comment]
Yes and no. Actually there is no need to insert a new option, the selection has to be deleted. Seen in this way, #3601 is more precise. All other options make no sense:

![Screenshot](https://user-images.githubusercontent.com/3040657/81380293-f091aa00-910a-11ea-9263-da93a412fc18.png)

Example: You have assigned pages 14-37 to a _chapter_ structure.

```
📁 monograph
 +-(🖼️ pages 1..99)
 +- 📁 chapter
     +- 🖼️ pages 14..37
```

Now select pages 30-32 and select the _new structure element from selected pages_ function to make a _table_ (as a child of the chapter).

_What would mean option 1: "As first sub-element of the current element"?_
```
📁 monograph
 +-(🖼️ pages 1..99)
 +- 📁 chapter
     +- 📁 table
         +- 🖼️ pages 30..32
     +- 🖼️ pages 14..29, 33..37
```
**Pages 30-32 should not appear before pages 14-29.**

_What would mean option 2: "As last sub-element of the current element"?_
```
📁 monograph
 +-(🖼️ pages 1..99)
 +- 📁 chapter
     +- 🖼️ pages 14..29, 33..37
     +- 📁 table
         +- 🖼️ pages 30-32
```
**Pages 30-32 should not appear after pages 33-37.**

_What would mean option 3: "As parent element of the current element"?_
```
📁 monograph
 +-(🖼️ pages 1..99)
 +- 📁 table
     +- 🖼️ pages 30..32
     +- 📁 chapter
         +- 🖼️ pages 14..37
```
**⚡ Child contains images not contained in parent.**

**Comment by matthias-ronge** [comment]
Closed as duplicate to #3601

**Comment by solth** [comment]
Since pages are re-numbered when reorderering them via drag'n'drop, it is very likable that the current numbering of pages at any given time is not necessarily final.

To take your first example: if pages 30-32 are added to a table that is the first child of the parent chapter, the pages will be re-labeled to 14-16 inside the table, and all following pages will be re-labeled to 33-37. 

We had many discussions about the re-labeling of pages on drag'n'drop manipulation, and it has been explicitely stated that resetting the ORDERLABEL attribute on drag'n'drop is one of the required consequences when assigning pages to structural elements.

Additionally, since selected pages in the gallery do not need to be consecutive, removing the current position-options when creating a new structural element would result in an ambigious position to insert the new element. To stay with your example: if you select pages 30 and 32 in the chapter and than create a new structural element from these selected pages, should it be inserted at the position where page 30 was or where page 32 was?

**Comment by andre-hohmann** [comment]
As Kitodo is always more complicated as it seems and many decision lead to unforeseen options, i suggest: 

1. the options "as first sub-element of the current element", "as last sub-element of the current element" are maintained. Thus, the common approach to add structure elements still exist and e. g. chapters can be created according their logical order without complications regarding ORDER, ORDERLABEL or whatever will come. See: https://github.com/kitodo/kitodo-production/issues/3601#issuecomment-626769394 
2. an additional option to insert the element at the current position (first selected page of the element) is created. Then subsequently added elements can be created between existing elements. An option to select a specific image number seems to me currently quite complicated. In the worst case, the element has to me moved manually to the correct position. 
3. the option "as parent element of the current element" can be removed. I did not find a use case for it.

**Comment by matthias-ronge** [comment]
Related to #3476
