### ISSUE TITLE
What is the function of adding permissions?

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3489]
The user interface offers the possibility to create new permissions. What is the use case of this?

![Screenshot 1](https://user-images.githubusercontent.com/3040657/79763303-2e798a80-8324-11ea-9cf4-c9826401e0a6.jpg)

![Screenshot 2](https://user-images.githubusercontent.com/3040657/79763457-68e32780-8324-11ea-81dd-c31f5017f542.JPG)

**Comment by Kathrin-Huber** [comment]
It is needed, when you add a module with frontend and own permissions.
You need to add them to the core, because otherwise, spring security cannot handle them.
