### ISSUE TITLE
What happens when I delete permissions?

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3491]
As the title says: What happens when you delete permissions?

![Screenshot](https://user-images.githubusercontent.com/3040657/79764680-fa06ce00-8325-11ea-8212-1f5514840bb1.jpg)

**Comment by Kathrin-Huber** [comment]
It's probably not a good idea.  You cannot use the stuff in the Frontend, where this Permission is required.
We should disable deletion of permissions
