### ISSUE TITLE
Drag'n'Drop in gallery panel is not possible anymore

### ISSUE THREAD

**Issue by Kathrin-Huber** [kitodo/kitodo-production#3499]
It's not possible to drag'n'drop in the gallery anymore. It's working in the structure tree.
![drag'n'drop](https://user-images.githubusercontent.com/22615787/79962650-96e17c80-8488-11ea-8918-064c7ddd7a8a.gif)

**Comment by solth** [comment]
@Kathrin-Huber can you still reproduce this issue with the current version of the master branch?

**Comment by Kathrin-Huber** [comment]
No, doesn't seem to be a problem anymore
