### ISSUE TITLE
Generation of images by actions in task detail does not work

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3504]
### Problem
The following actions in the task detail do not work: 
- Start the regeneration of all images
- Start the regeneration of all missing or damaged images
- Start the generation of all missing images

The problem is also described in https://github.com/kitodo/kitodo-production/issues/3176, but i am not sure if anyone is still aware of the problem. The referenced ticket https://github.com/kitodo/kitodo-production/issues/3172 is closed. 

Due to the importance of these action, i opened a new issue. If it is not necessary, it can be closed. 

#### Start the regeneration of all images
Beispiel LeLoM_1652459308_Einfacher_Strukturbaum (ID:948):

- Es wird bestätigt, dass die Generierung durchgeführt wird:
-- _Das Generieren der Bilder wurde gestartet, sie können diese Aufgabe jetzt abschließen. Sie können den Fortschritt der Bildgenerierung im Taskmanager verfolgen._
- Ergebnis Taskmanager: 
-- Fortschritt: 23%
-- Status: Beendet
- Im Vorgangs-Verzeichnis sind keine Images vorhanden

#### Start the regeneration of all missing or damaged images
Beispiel LeLoM_1652459308_Einfacher_Strukturbaum (ID:948):

- Es wird bestätigt, dass die Generierung durchgeführt wird:
-- _Alle fehlenden und beschädigten Bilder werden neu generiert, sie können diese Aufgabe jetzt abschließen. Sie können den Fortschritt der Bildgenerierung im Taskmanager verfolgen._
- Ergebnis Taskmanager: 
-- Fortschritt: 100%
-- Status: Beendet
- Im Vorgangs-Verzeichnis sind keine Images vorhanden

#### Start the generation of all missing images
Beispiel LeLoM_1652459308_Einfacher_Strukturbaum (ID:948):

- Es wird bestätigt, dass die Generierung durchgeführt wird:
-- _Das Generieren aller fehlenden Bilder wurde gestartet, sie können diese Aufgabe jetzt abschließen. Sie können den Fortschritt der Bildgenerierung im Taskmanager verfolgen._
- Ergebnis Taskmanager: 
-- Fortschritt: 100%
-- Status: Beendet
- Im Vorgangs-Verzeichnis sind keine Images vorhanden

**Comment by Kathrin-Huber** [comment]
Ich kann es lokal nicht nachstellen. Ich sehe außerdem Bilder in den besagten Vorgangsverzeichnissen.
Ist dieses Ticket noch ein Problem?

**Comment by andre-hohmann** [comment]
I will have a look on it. 

Maybe it was a problem with the generation in other tasks: https://github.com/kitodo/kitodo-production/issues/3577. 

The generation of images by automatic task works perfectly.

**Comment by andre-hohmann** [comment]
I have tested it again, with the following result: 

- Start the regeneration of all images -> It works correctly
- Start the generation of all missing images -> It works correctly
- Start the regeneration of all missing or damaged images -> **It does not work correctly**

The following message is shown: 
- crashed (No configuration found in kitodo_config.properties for key
LongTermPreservationValidation.mapping.TRUE.TRUE!)


![errorgeneratingimages01](https://user-images.githubusercontent.com/14835770/82215974-7e923f80-9918-11ea-9e06-723374f63e57.jpg)

**Comment by andre-hohmann** [comment]
Probably, the label "blocking" could be removed? 
@subhhwendt
@Kathrin-Huber

**Comment by subhhwendt** [comment]
I agree!

**Comment by andre-hohmann** [comment]
With the Process "id:1848" it works. 
The issue is closed.
