### ISSUE TITLE
Missing information in generated excel- and pdf-files in the process list

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3507]
#### missing values
The excel- and pdf-files generated by 
- "Possible actions" / "generate excel"
- "Possible actions" / "create pdf"
are missing the values in the columns
- CountImages
- CountMetadata

#### wrong naming
The column "CountMetadata" contains the structure elements -> naming should be adjusted, for example "CountStructureElements"

#### adding metadata
Metadata of the processes has never been generated. According to the statistic evaluation "Number of metadata" that could be added in the files, too.

**Comment by matthias-ronge** [comment]
> Metadata of the processes has never been generated.

In which area should metadata be generated when exporting Excel or PDF?

**Comment by andre-hohmann** [comment]
I would suggest: 

| Vorgangstitel  | ID | Datum | CountImages | CountStructureElements | CountMetadata | Project	Status | AltRefNo | b-number |

**Comment by matthias-ronge** [comment]
The labels should be taken from the translation file (multilingual).

About the data:

- **Vorgangstitel** `process.getTitle()`
- **ID** `process.getId()`
- **Datum** `process.getCreationDate()` − format _YYYY-MM-DD_
- **CountImages** `workpiece.getMediaUnits().size()` − If a process contains 200 TIFF files, 200 thumbnails and 200 “max” size JPEGs, this will print “200”, not 600. Correct?
- **CountStructureElements** _(as in display statistics)_
- **CountMetadata** _(as in display statistics)_
- **Project Status** `process.getProject().isActive()` − “true” if the project is still running, “false” if the project is finished. (Is that what is wanted here?)
- **AltRefNo** what is this?
- **b-number** what is this?

**Comment by andre-hohmann** [comment]
- CountImages -> Yes, 200 should be printed
- (Project) Status -> In 2.x it was shown the status of each task by three numbers
- AltRefNo ->I have no idea; it is always empty; i do not know, if anyone needs it
- b-number -> I have no idea; it is always empty; i do not know, if anyone needs it


Examples Status:

060 / 020 / 020
060 / 020 / 020
060 / 020 / 020
050 / 017 / 033
050 / 017 / 033
050 / 017 / 033
100 / 000 / 000
100 / 000 / 000
067 / 017 / 017
060 / 020 / 020
060 / 020 / 020
060 / 020 / 020
060 / 020 / 020
060 / 020 / 020
060 / 020 / 020
060 / 020 / 020
060 / 020 / 020
060 / 020 / 020
050 / 017 / 033
050 / 017 / 033
050 / 017 / 033
050 / 017 / 033
050 / 017 / 033
060 / 020 / 020
060 / 020 / 020
033 / 017 / 050
050 / 017 / 033
014 / 014 / 071

**Comment by matthias-ronge** [comment]
This is the progress, coded as a green section, yellow section, red section, each as a percentage. I generally think progress is good, but I would suggest naming the column accordingly.  It would also be a question of whether one number would suffice, where green is counted in full and yellow is counted as ½. I think that is much more intuitive! Examples:
- `014 / 014 / 071` → 21% (Scan)
- `067 / 017 / 017` → 76%
- `100 / 000 / 000` → 100% (finished process)

The algoritmh could be something like this:
```java
static final EnumMap<TaskStatus, Double> PROGRESS = new EnumMap<TaskStatus, Double>
                                                                     (TaskStatus.class){{
    PROGRESS.put(TaskStatus.LOCKED ,   0.0);
    PROGRESS.put(TaskStatus.OPEN   ,  50.0); // I have set 50% for progress both for OPEN
    PROGRESS.put(TaskStatus.INWORK ,  50.0); // and for INWORK. You could also take 40%
    PROGRESS.put(TaskStatus.DONE   , 100.0); // and 60%, or 33.33% and 66.67% ...
}};

static String progressInPercent(List<Task> taskList) {
    if(taskList.isEmpty()) return "";
    double progress = taskList.parallelStream().map(Task::getProcessingStatus)
        .mapToDouble(PROGRESS::get).sum() / taskList.size();
    return String.format("%.0f %%", progress);
}
```

We should leave away the fields that are always empty and whose meaning nobody knows, until someone says what he/she would like to have there.
