### ISSUE TITLE
Display confirm dialog on deleting structure element

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#351]
It would be nice that a confirm dialog appeared if a structure element should be deleted. 

If it is possible this confirm dialog could only be displayed on critical structure elements like on deleting `periodical volume` of a `periodical` process. Result of this deleting is a corrupted process which should be avoided.

**Comment by matthias-ronge** [comment]
Update: In 3.x it is not possible, e.g. to delete the root element. Other included structural elements can be deleted, and no warning is displayed. @henning-gerhardt, is this feature still needed?

**Comment by henning-gerhardt** [comment]
This is still correct and a missing feature or open bug in 2.x.

**Comment by matthias-ronge** [comment]
2.x is about to retire and will no longer be developed. The question is, should something similar be developed in 3.x or not?

**Comment by matthias-ronge** [comment]
^^ The latter is nonsense. I accidentally referenced the wrong issue.

**Comment by matthias-ronge** [comment]
Fixed by #3149
