### ISSUE TITLE
Extended Search: "does not contain" option for project-search does not work

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3523]
### Problem
In the extended search, it is theoretically possible to search projects for values that are not contained, as for example: "_-project:SLUB-Export-Einfach_". 
However, it does not work. The result is: all processes of the project that should not be searched. 

### Solution
Solution 1
Allow only "Contains"-search for projects. 

Solution 2
Enable the "does not contain"-search for for projects.

**Comment by solth** [comment]
@andre-hohmann this seems to be fixed in 3.6.1 and the current master (probably by #5523 or #5370) Could you check again if this still occurs for you?

**Comment by andre-hohmann** [comment]
@solth : Thanks for the hint. 

I tested some use cases and it is now possible to exclude specific values in the extended search and in the filter-box. 
I will close the issue.
