### ISSUE TITLE
"Apply" function for pagination

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3537]
### Problem
The pagination can be applied only by the "save" button which leads always to closing the "Edit pagination" pop-up window. This is inconvenient, when a diverse pagination has to be applied. 

See the example at the end of the issue. It is not possible to finish the pagination without opening and closing the pop-up window "Edit pagination" . 

### Solution
It is helpful, if an "applied"-button was available, which applies the pagination as "preview" in the "Edit pagination" pop-up window. Then, it is possible to capture the pagination more conveniently and it is possible to recognize mistakes early.  

### Example pagination

 1: uncounted
 2: uncounted
 3: 1
 4: 2
 5: 3
 6: 4
 7: 5
 8: 6
 9: 7
 10: 8
 11: 9
 12: 10
 13: 11
 14: 12
 15: 13
 16: 14
 17: 15
 18: 16
 19: 17
 20: 18
 21: 19
 22: 20
 23: 21
 24: 22
 25: 23
 26: 24
 27: 25
 28: 26
 29: 27
 30: uncounted
 31: 28
 32: 29
 33: 30
 34: 31
 35: 32
 36: uncounted
 37: 33
 38: 34
 39: 35
 40: 36
 41: 37
 42: 38
 43: 39
 44: 40
 45: 41
 46: 42
 47: 43
 48: 44
 49: 45
 50: 46
 51: 47
 52: 48
 53: 49
 54: 50
 55: 51
 56: 52
 57: uncounted
 58: 53
 59: 54
 60: 55
 61: 56
 62: 57
 63: 58
 64: uncounted
 65: 59
 66: 60
 67: 61
 68: 62
 69: 63
 70: 64
 71: 65
 72: 66
 73: 67
 74: 68
 75: 69
 76: 70
 77: 71
 78: 72
 79: 73
 80: 74
 81: uncounted
 82: uncounted
 83: uncounted
 84: uncounted

**Comment by Kathrin-Huber** [comment]
@oliver-stoehr Is it possible to reload the tree (via ajax?) from the popup without closing the popup?

**Comment by oliver-stoehr** [comment]
Sure, the suggested "apply" button could update the the tree with the attribute `update="structureTreeForm"`.
The popup would not get closed unless the button used `oncomplete="PF('paginationDialog').hide()"`.
