### ISSUE TITLE
Adding suffixes to file name of images

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3541]
### Problem 
It is possible to configure suffix parameter to image file-names in the METS parameter, as for example: 
- `export_images/original/*.tif.original.jpg`
- `export_images/thumbnail/*.tif.thumbnail.jpg`

In the internal METS file, the suffix is applied. 
The export is not possible with the suffix. The following error message is shown: 
- `crashed (Illegal character in path at index 118: https://digital.slub-dresden.de/data/kitodo/DesChWaV_1447620453_test_suffix/DesChWaV_1447620453_test_suffix_tif/jpegs/ 00000001.tif.small.jpg)`

This function is necessary, when all derivative mages are exported in the same folder and must be named differently. 

### Solution
Either the "suffix-function" should be disabled completely or the export with the suffix should be enabled.

**Comment by matthias-ronge** [comment]
I suspect the error is caused by the space between `jpegs/` and `0000`. That probably doesn't come from the configuration but is added somewhere else. That needs to be fixed.

**Comment by andre-hohmann** [comment]
It works in the preview system. Thus the issue is closed.
