### ISSUE TITLE
Folder labels are not validated

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3546]
Production allows the creation of folders in the project configuration where the internal designation “METS filegroup” is empty or the same name has been assigned to several folders. However, this designation must not be empty because the internal storage format is METS and the assignment of internal picture groups is then not possible. However, no error message is displayed.

**Goal:** When configuring the project and trying to create processes, an error message should appear if a folder has no “METS filegroup” label or several folders have the same label.

**Comment by Kathrin-Huber** [comment]
fixed by #3951
