### ISSUE TITLE
Provide XSD file for kitodo_opac.xml

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3555]
There is an XSD file for rule sets, which describes the possible elements, attributes and possible value ranges in a technical way, so that they can be offered to you by corresponding editors (e.g. code completion).

Goal: A comparable file is desired for `kitodo_opac.xml`.

**Comment by solth** [comment]
Since catalog configurations in `kitodo_opac.xml` have been replaced by the new `ImportConfiguration` class, the need for a schema definition for `kitodo_opac.xml` is not really given anymore.
