### ISSUE TITLE
metadata editor breaks down

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3556]
### Problem
The metadata editor is closed and the following message is shown. 
It happend several users after a while, when structure elements are created. The first one works, then after the second, third, .. the editor is closed. 

![fehler_metadateneditor](https://user-images.githubusercontent.com/14835770/80583832-0ddebe00-8a11-11ea-9e5d-80762e3b2437.jpg)

**Comment by matthias-ronge** [comment]
In such a case, it would be very important to state the exact time (if possible up to the second) if such an error occurs so that we (hopefully) can find an error print-out in the log file.

**Comment by andre-hohmann** [comment]
OK, the next time, i will add information. 
Now it is not reproducible anymore and i do not receive information from other users. Therefore, i will close the issue.

**Comment by andre-hohmann** [comment]
The reason was: two users worked in the metadata editor of the same process at the same time. 
See: https://github.com/kitodo/kitodo-production/issues/3363.
