### ISSUE TITLE
Default values in kitodo_opac.xml

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3561]
The catalogue search during the creation of a new process could be more comfortable, if it was possible for "Catalogue" and "Field" to define default values. 
As most users are working with one catalogue and are searching for an identifier, the manual configuration is not necessary, but after a while quite annoying. 

The target state: 
![cataloguesearch04](https://user-images.githubusercontent.com/14835770/80599533-5efbab80-8a2b-11ea-9acd-a554c30d4778.jpg)

The current state:
![cataloguesearch01](https://user-images.githubusercontent.com/14835770/80599463-4095b000-8a2b-11ea-83de-ea96963b5581.jpg)

The current way to the target state: 
![cataloguesearch02](https://user-images.githubusercontent.com/14835770/80599594-776bc600-8a2b-11ea-9ef2-9e33fdb0c6f6.jpg)

![cataloguesearch03](https://user-images.githubusercontent.com/14835770/80599581-733fa880-8a2b-11ea-928e-82d0169c8750.jpg)

**Comment by matthias-ronge** [comment]
Likewise, it is annoying to have to manually close the catalog import every time, if no catalog is used in the project. I would like to see such presets in project settings.

**Comment by solth** [comment]
@andre-hohmann, @subhhwendt Configuring these default values via the `kitodo_opac.xml` file would set them as global defaults, not on a per-project-base. If that sufficient, I would suggest to implement it in this fast and clean way to add the default value functionality in the short-term, independet of more complex and extensive reworks of the whole OPAC import in the future. It should hopefully already ease some of the pain that comes from working with the current catalog import mask.

In the long run, I would propose to rework the whole OPAC configuration and move it from the current XML configuration file to dedicated Java classes that can be configured via the Kitodo.Production GUI, if #4322 gets. Then we could configure these default values for each project individually.

**Comment by solth** [comment]
Alternatively we could use the existing configuration in `kitodo_projects.xml` to set default catalogs for projects individually, but that would prevent the intended removal of that configuration file (see #3777)

**Comment by andre-hohmann** [comment]
I absolutely agree with you. Currently, it is sufficient that one catalogue and one search field can be set as default. 

In my opinion, we should not use the `kitodo_projects.xml` to solve this issue. If #4322 gets approved, we can search for an comprehensive solution.
