### ISSUE TITLE
Confirmation fields after generating images block access to the menu

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3568]
It was reported: If you click on the link to generate images, you get a confirmation message in a box that hides the menu and doesn’t disappear any more. Apparently it’s a problem similar to #3316.

![Screenshot](https://user-images.githubusercontent.com/3040657/80975239-1e80a100-8e22-11ea-9e78-eeb6aa297b6f.jpg)

**Goal:** Only one error message is sufficient.

**Comment by matthias-ronge** [comment]
I gave the <kbd>question</kbd> badge because it has to be tested whether this has already been improved with the first fix for #3316. Here was tested with a slightly older version.

**Comment by Kathrin-Huber** [comment]
So please test and report if it is still a problem ;-)

**Comment by matthias-ronge** [comment]
You can close the box manually. But that's annoying. It should close on its own. So I leave this issue as an <kbd>improvement</kbd>.

**Comment by andre-hohmann** [comment]
I agree, it is very annoying. I have also no idea, why the messages are shown. The same information is part of the "information badge" above the process list.

**Comment by matthias-ronge** [comment]
Closed as duplicate of  #3420
