### ISSUE TITLE
Pagination popup impedes pagination

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3572]
### Problem
If the pagination of a process is conducted by the images alone, it is not possible to: 
- browse the images 
- to see the pagination information

### Solution
The pagination popup should be flexible, so that the images can be browsed and examined. 

### Example
![paginierung01](https://user-images.githubusercontent.com/14835770/80939543-48fc3b00-8ddd-11ea-91da-5f7092670780.jpg)

![paginierung02](https://user-images.githubusercontent.com/14835770/80939549-50234900-8ddd-11ea-9be5-c92499d9b925.jpg)

**Comment by matthias-ronge** [comment]
Maybe pagination could be included in a separate ribbon? For example:

![Artwork](https://user-images.githubusercontent.com/3040657/97976260-af810680-1dca-11eb-988b-699ebdb05a2a.jpg)

The box with the checkmarks would not even be necessary then, because the selected page is the one selected in the structure tree and the media view

**Comment by matthias-ronge** [comment]
Is it possible to make the modal window moveable and resizeable in PrimeFaces?

**Comment by solth** [comment]
> Is it possible to make the modal window moveable and resizeable in PrimeFaces?

Yes, it is:
- movable: `draggable=true`
- resizable: `resizable=true`

But than this single dialog would behave differently from all the other dialogs in the system. I would therefore prefer something in line with your other suggestion - to move the pagination controls from the separate dialog window to for example one of the existing columns. 

One idea could be to move it to the first column ("Structure") entirely and replace the current "Pagination" button (that opens the dialog) with an `p:accordionPanel` that allows arranging the existing structure and pagination in two panels that can be vertically collapsed (similar to how "Comments" and "Metadata" can be toggled in the second column).

**Comment by matthias-ronge** [comment]
This is what I wanted to illustrate with the image above, but I would suggest the accordion collapsing horizontally, as depicted in the picture.
