### ISSUE TITLE
Missing notification function to all users

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3586]
The super admin interface in version 2 allows a permanent message to be shown to all users. The feature was lost in version 3 (or I'm missing how to activate it).

![Screenshot 1](https://user-images.githubusercontent.com/3040657/81081156-d92ba480-8ef1-11ea-863d-bb8c6e5efb19.jpg)

→

![Screenshot 2](https://user-images.githubusercontent.com/3040657/81081175-dd57c200-8ef1-11ea-9ba8-83bdafa4e7b1.jpg)

**Goal:** restore function

**Comment by matthias-ronge** [comment]
@solth, as far as I know you're working on this. What is the status here?

**Comment by solth** [comment]
I have it mostly working, but I get an error with the websockets trying to open the communication channel directly after login, without explicetly opening it via the system page. 

Hopefully, I will get it fully working soon, so I will self-assign this issue.

You can checkout the current version here: https://github.com/effective-webwork/kitodo-production/tree/system-warning

**Comment by Kathrin-Huber** [comment]
fixed by #4413

**Comment by solth** [comment]
#4413 was not merged, but closed
