### ISSUE TITLE
Deactivate delete-button for alwaysShowing

### ISSUE THREAD

**Issue by Kathrin-Huber** [kitodo/kitodo-production#3589]
If a metadata is configured "alwaysShowing" the delete Button in the metadataEditor should be disabled

**Comment by solth** [comment]
@Kathrin-Huber @matthias-ronge Should the "delete" button also be deactivated when some metadata has been configured with `minOccurs=1` and no other metadata objects of this type are assigned to the current structure element?

**Comment by matthias-ronge** [comment]
yes, I would think so.
