### ISSUE TITLE
Selection list missing by adding metadata for newspaper issues 

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3593]
### Problem
If metadata is captured by creating the processes for newspaper issues, the configured selection lists of the ruleset are missing, which are offered by the creation of processes for monographs, manuscripts, ...
The correct capture of the metadata of the selection list is important, because otherwise further processing of it is not possible, as for example the correct assignment of the digital collection or the rights information. 
Especially, when several hundreds of processes are created, the correction of the metadata is quite extensive. 

### Solution
The configured selection lists need to be offered for the creation of processes for newspaper issues. 

For example by adding a step with the regular template (process metadata) of creating processes before the calender view is shown. There, the configured metadata can be selected. 

### Example
The expected collection name "_Abschlussarbeiten des Instituts für Literatur ‚Johannes R. Becher’ Leipzig_" has to be retrieved and copied. Furthermore, it is difficult to check it, because it is not shown completely. Errors will definitely occur.

![newspapermetadata01](https://user-images.githubusercontent.com/14835770/81290565-95a77680-9068-11ea-9a74-2ae9226d7376.jpg)

**Comment by matthias-ronge** [comment]
In the case of selection lists, the setting of the step size is superfluous because nothing can be counted here. In that case, it can be hidden.
