### ISSUE TITLE
Simple search does not work

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3612]
### Problem
After any search in the the search box the following message is shown: 
- "Error... An error has occurred."

![fehler](https://user-images.githubusercontent.com/14835770/81524930-4d7fa100-9353-11ea-8dcc-5016cf4ea387.jpg)

**Comment by Kathrin-Huber** [comment]
We have a new mapping. When the index is rebuild, the search should work again.
Currently we have problems reaching the indexing page, when this is fixed, search should work again.

**Comment by Kathrin-Huber** [comment]
Is fixed
