### ISSUE TITLE
Import breaks user interface when person has multiple roles

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3640]
Example: GBV PPN 1041657277
Here the person has 2 roles, author and artist.

Error message:
```
Type error evaluating ($role) in xsl:when/@test on line 209 column 70 
  XPTY0004: A sequence of more than one item is not allowed as the first argument of
  fn:starts-with() ("VerfasserIn", "KünstlerIn") 
  In template rule with match="element(Q{http://www.loc.gov/mods/v3}name)[xs:string(@type) eq "personal"]" on line 196 of 
     invoked by xsl:apply-templates at #28
  In template rule with match="element(Q{http://www.loc.gov/mods/v3}mods)" on line 24 of 
     invoked by built-in template rule (text-only)
```

**Goal:** XSLT has to be adjusted accordingly.

In addition: The error message must be caught and displayed correctly.

**Comment by solth** [comment]
> In addition: The error message must be caught and displayed correctly.

This part is already working (screenshot from preview system that has the current version of the software installed):
![xslt-error-message](https://user-images.githubusercontent.com/19183925/82285041-bc37ac80-999a-11ea-86ef-7bd9739f3bc6.png)

**Comment by Kathrin-Huber** [comment]
please reopen, if this is still a problem
