### ISSUE TITLE
Unknow meaning of different "Gateways" in Workflow Editor

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3645]
The difference between the two gateway types "parallel" and "exclusive" is not clear for me.
Which to use for which purpose?
Please explain.

**Comment by Erikmitk** [comment]
So far, there's no difference between the gateways internally. They carry the information about parallel/exclusive branches in the underlying workflow model but that is not considered in going through the workflow inside of Kitodo.Production's workflow engine.

Instead, conditions and properties can be set on the tasks themselves to model a truly parallel or exclusive pathway. I'd suggest the different gateways can help to visually communicate the intention behind the workflow at a glance.

In that regard, they are simply tools for the modeler to better communicate the workflow.

**Comment by stefanCCS** [comment]
Many thanks for your fast answer, understood and appreciated!
