### ISSUE TITLE
"Assign to next element" not available in the Erweiterter Strukturbaum

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3646]
### Problem
In the Erweiterter Strukturbaum, it is not possible, to assign an image to two structure elements with the function "Assign to next element". 
If the links were created, in the Einfacher Strukturbaum, they are shown in the gallery. 

### Solution 
It should be possible to add the links in the physical structure by context menu. additional to 
- Add element
- Remove element

it should be offered: 
- Assign to next element

Otherwise, the structure tree cannot be used. 

### Example

![assignelement01](https://user-images.githubusercontent.com/14835770/82318783-ba88db80-99d0-11ea-9c6c-426cff65dff9.jpg)

**Comment by matthias-ronge** [comment]
What exactly do you want to achieve? Assigning the next element would mean that you would want to assign page 8 to page 9? Or, (but that would require a structure with partial orders) a page is assigned to this and the next partial order?

**Comment by andre-hohmann** [comment]
It is the second option 

> a page is assigned to this and the next partial order

I have expected an option like this: 
![assignnextelement](https://user-images.githubusercontent.com/14835770/97993058-d7c92f00-1de3-11eb-99df-1f4a05bd1c1a.jpg)

In processes with the "Erweiterter Strukturbaum" i find no option for this. Although in my example (DesChWaV_1447620453_Hohmann_Erweiterter_Strukturbaum (ID: 1401)), there are "connected" pages. 

![assignnextelement_2](https://user-images.githubusercontent.com/14835770/97993476-6c339180-1de4-11eb-9481-9430b66c1cee.jpg)
