### ISSUE TITLE
The page "Edit role" is unusable in Edge

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3650]
The _edit role_ page is unusable in Microsoft Edge:

![Screenshot](https://user-images.githubusercontent.com/3040657/82320771-1d2fa680-99d4-11ea-9e9c-2db2b6d8cd66.jpg)

**Goal:** Fix it to work in Edge

**Comment by matthiaskissler** [comment]
Seems to work now (Edge 85.0)
![editrole](https://user-images.githubusercontent.com/66619864/94792037-bb973400-03d8-11eb-88f6-ee7a2f17d3c9.png)

**Comment by matthias-ronge** [comment]
Thank you. Then I close the ticket.
