### ISSUE TITLE
Links for generating images showing though this is not part of the task

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3655]
In the task, links will appear to generate images, although this is not part of the task. If you click on it, a green message is given that this is working, but nothing works either.

![generieren von bilder wird angeboten](https://user-images.githubusercontent.com/3040657/82322950-a1375d80-99d7-11ea-8390-f0f32cadc8f6.jpg)

**Goal:** Don't show the links if that's not the task.

**Comment by solth** [comment]
@matthias-ronge I cannot reproduce this problem. Can you confirm it still occurs in the current master?

**Comment by matthias-ronge** [comment]
The error was observed at code version b95cd3f6fb76902de6ec0299bb93b1b79be54aa1 of 4ᵗʰ May 2020. I am closing the issue meanwhile, but I have to watch that again.

**Comment by matthias-ronge** [comment]
Fixed by #3583 which was merged on 6ᵗʰ of May, 2020.
