### ISSUE TITLE
Function missing to trigger correction step

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3657]
Here, the task is the third. But there is no function to trigger a correction step if you notice that something is wrong.

![Screenshot](https://user-images.githubusercontent.com/3040657/82323893-017acf00-99d9-11ea-805d-0926eb7aabfc.jpg)

**Goal:** There must be a function so that the task can be sent backwards for correction. Compare application version 2:

![Screenshot from version 2](https://user-images.githubusercontent.com/3040657/82323932-0d669100-99d9-11ea-83be-bc5d19c67818.jpg)

**Comment by solth** [comment]
That is already possible via the `Kommentare` tab on `Details der Aufabe`:

<img width="968" alt="korrektur" src="https://user-images.githubusercontent.com/19183925/82327923-6e916300-99df-11ea-8ea4-dd74759e2c65.png">
