### ISSUE TITLE
Add search slot on the user page

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3660]
On the user page there should be a search slot to quickly find a specific entry by typing:

![Screenshot](https://user-images.githubusercontent.com/3040657/82329016-f166ed80-99e0-11ea-9574-2b3cc10630c8.jpg)

**Comment by andre-hohmann** [comment]
I appreciate such a search slot also in the list of "Authorities" and "Roles".

**Comment by solth** [comment]
This was added with #4057
