### ISSUE TITLE
Don't forget metadata when changing DocType

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3664]
If a new process is created without using the catalog, and the doctype is changed **after** metadata has already been entered manually, the metadata is forgotten. In addition, if the metadata input mask only contains digital collections, it is not updated, and it appears that the metadata has been recorded. However, an empty metadata file is saved.

**Goal:** The metadata will be retained when changing the DocType.

**Comment by solth** [comment]
@matthias-ronge it seems this has been fixed by #5355 . Can you confirm this?

**Comment by matthias-ronge** [comment]
This doesn’t happen any more
