### ISSUE TITLE
Duplicates in exported mets:structLink section

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3678]
Extracted from #3636 by @andre-hohmann:
In exported METS, the element `<mets:structLink>` contains several duplicates.

**Comment by matthias-ronge** [comment]
The question is whether the duplicates pose a problem for the presentation (e.g. in the form of repetitive pages) or are simply not pretty.

**Comment by andre-hohmann** [comment]
Even if it just not pretty, this should be corrected.
 
As there is no test presentation, it is difficult to test the effects. Furthermore, it must be assumed that different presentation software will be used, which cannot be tested. 

I would recommend the blocking label.

**Comment by matthias-ronge** [comment]
Removeal of duplicates is implemented in `MetadataEditor.assignViewsFromChildren()`, line 334:

    viewsToAdd.removeAll(assignedViews);

`equals()` and `hashCode()` in `View` and `MediaUnit` have been implemented in pull request #3765
