### ISSUE TITLE
Do not run automatic export if script exists?

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3688]
With the automatic task, if there is a script **and** DMS export is selected, the DMS export is **not** carried out, see [`TaskScriptThread`, l. 74](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/thread/TaskScriptThread.java#L74). Is it wanted like that?

**Comment by andre-hohmann** [comment]
I hope i understand it correctly. 

From my point of view, the DMS export always has to be carried out when it is in an automatic task.
