### ISSUE TITLE
Pressing enter in the advanced search wants to reset the form

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3700]
Write something in the advanced search form and hit enter. The query appears whether the form should actually be deleted.

![Screenshot](https://user-images.githubusercontent.com/3040657/82987836-875dd200-9ff8-11ea-956e-1cc7d03f322a.jpg)

**Goal:** The search is triggered.

**Comment by Kathrin-Huber** [comment]
The clearData button was removed in the PR #3535 
Can you confirm, that this is happening in the current master?

**Comment by matthias-ronge** [comment]
The problem is solved
