### ISSUE TITLE
After migration, filters cannot be deleted

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3701]
It was reported: After migration, the filters for tasks and processes cannot be deleted.

**Goal:** Filters should be able to be deleted.

**Comment by Kathrin-Huber** [comment]
What is the actual problem?
There is no delete button? The button is not working? The button is working but doesn't have any effect? the filter is deleted but is reappearing after reload?

**Comment by Kathrin-Huber** [comment]
Is it the problem described in #3597 ?

**Comment by matthias-ronge** [comment]
After clarification, this is the same issue as  #3597
