### ISSUE TITLE
Wrong header in "Permissions" tab of Workflow editor

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#3704]
The "Permissions" tab in the workflow editor has the wrong header "Conditions" (which belongs to the third tab of the same name), but should be "Permissions":

<img width="299" alt="Bildschirmfoto 2020-05-27 um 10 51 50" src="https://user-images.githubusercontent.com/19183925/82999290-14108c00-a009-11ea-9c0d-97eace071b6d.png">

**Solution**: 
- either remove the headers altogether since they don't offer any additional information that the tab texts wouldn't already provide and are therefore redundant (preferred solution) _or_ 
-  change the header in the second tab to "Permissions".

**Comment by Erikmitk** [comment]
Just an update:

I fixed this already by removing the subheadings: https://github.com/Erikmitk/kitodo-workflow-editor/commit/d4597354a7b472dc4309912b0dbd01c136c962b3

I have to adjust the localization process for https://github.com/kitodo/kitodo-production/issues/3654 further so those changes will be in a PR that deals with both localization issues.
