### ISSUE TITLE
Scipt-Interface: How to get information about current "Process"

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3712]
Question:
If I use a "Script-Task", a script is called (which works fine).
How can I get the information in the script of the "Process" this script is called from?
--> So, that I can find the meta data file, and so something with it.
(maybe as command line parameter? or as environment variable?)

**Comment by matthias-ronge** [comment]
There are a number of variables that can be used in the script path or as arguments. Syntax: Variables are parentheses, which contains the key word.

So far, this has not been documented anywhere. The source code that is responsible for this can be found in [VariableReplacer](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/helper/VariableReplacer.java#L99-L139).

**Comment by stefanCCS** [comment]
So I can use e.g.
(processpath)
and put this as "command line parameter" in my script-path.
correct?

**Comment by stefanCCS** [comment]
Well,
I have tried out the following as "Script Path":
/home/workshop/myScripts/mySimpleScript.sh (processpath)
I would have expected to find in my Script as command line parameter the "process path".
Unfortunately, I have not found anything (no command line parameter at all, checked with $# in the bash script.
So, how it is used correctly?

**Comment by matthias-ronge** [comment]
Yes, that's how it should work. I will not label this ticket now because I want to leave it open for the documentation issue, but I will create a new ticket for the bug.

**Comment by stefanCCS** [comment]
I have tried out to put all meta data variables according to [https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/helper/VariableReplacer.java#L99-L139](url) in a scripting task just to see, what values are availble in a script.
Unfortunately, this was not very promising (or I do not understand), but most of the variabels were not filled or unclear.
In detail I have put the following on the command line:
"1:(tifurl)" "2:(origurl)" "3:(imagepath)" "4:(processpath)" "5:(importpath)" "6:(sourcepath)" "7:(ocrbasispath)" "8:(ocrplaintextpath)" "9:(metaFile)" "10:(prefs)" "11:(processtitle)" "12:(processid)"
As result I have got:
"1:file://202006261359_media"                 
"2:file://master_202006261359_media"
"3:"
"4:"
"5:"
"6:"
"7:"
"8:"
"9:meta"
"10:/usr/local/kitodo/rulesets/ruleset_CCS_min.xml"
"11:202006261359"
"12:9"

==> What I do understand are 9,10, 11, 12
===> All the other als either not filled or not clear for me

--> Could you please check?

**Comment by frank-ulrich-weber** [comment]
Some time ago I made a short documentation of all the variables/placeholders of Kitodo.Production 2.x. 
Maybe that helps a little further: 
[VariableReplacer.pdf](https://github.com/kitodo/kitodo-production/files/4837042/VariableReplacer.pdf)

**Comment by stefanCCS** [comment]
Many thanks, this help a bit - at least I can see now, that my output is not that wrong.
But I am sorry to say, there are still too many riddles to solve without any further explanations,
e.g. why i get "file://202006261359_media" as tifpath, as my tifs are in "images" folder? (any many more).

**Comment by stefanCCS** [comment]
Closed, as followed up via #3718.
