### ISSUE TITLE
Kitodo-Metadata.xml - not found 

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3717]
In a Kitodo-meta-data-XML (Production, version 3.2 - build 20.05.2020), the following namespaces are defined:
<mets xmlns="http://www.loc.gov/METS/" xmlns:ns2="http://www.w3.org/1999/xlink" xmlns:ns3="http://meta.kitodo.org/v1/">
My question is: meta.kitodo.org cannot be accessed --> therefore, this namespace cannot be verified.
How should I work with this issue?

**Comment by Kathrin-Huber** [comment]
Is there a list of namespaces missing in the description?

**Comment by stefanCCS** [comment]
Was a misunderstanding from my side. This is no bug!
A kind of improvement potential still existing: It might be helpful to put something on the mentioned website: http://meta.kitodo.org/v1/
