### ISSUE TITLE
Column indexAction not updated

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#3719]
While running indexing of many objects / entries through the index page the column `indexAction` on the database tables are not updated to from `INDEX` or `NULL` to `DONE` when the object is indexed. If you must index remaining entries / objects after an index abort through some kind of error then all objects get index as new and not only the remaining not indexed objects.

This is a little bit related to #3602 for information about what this column is doing or used for.

**Comment by matthias-ronge** [comment]
![Screenshot](https://user-images.githubusercontent.com/3040657/81381257-a9a4b400-910c-11ea-9ea1-60a865f73578.jpg)
