### ISSUE TITLE
Calendar cannot be saved

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3722]
In version 2, the calendar can be downloaded and uploaded again in another session. You don't have to do all the editing at once. In addition, the (scripted) creation of the XML file offers further options for importing calendar data. The function no longer exists.

![Screenshot from version 2](https://user-images.githubusercontent.com/3040657/83736726-56157f80-a652-11ea-8059-2aa5392270a6.jpg)

**Goal:** It is cumbersome to download the file locally and upload it again. But saving should be possible.

**Comment by henning-gerhardt** [comment]
Please do not store this calendar data on server this. This would need a lot more logic behind (serving data, update data, remove data, user access, permissions to this data, permissions for users to interact with this data, ...)

**Comment by matthias-ronge** [comment]
My idea is to save a `publication-history.xml` in the newspaper's process directory. The calendar editor would then have the same buttons as the metadata editor: cancel, save, save and close. There is exactly one publication history per newspaper. Perhaps you can then later use the `publication-history.xml` to insert editions into the newspaper afterwards, which is still an unimplemented feature, but a desiration.

**Comment by henning-gerhardt** [comment]
Please keep in your mind that 
- not every "newspaper" is a newspaper
- not every newspaper has a regular publication course
- not every newspaper starts and ends in a year, like season publications from August to July next year and then from September to July the next year after (08/1900 - 07/1901 and 09/1901 - 07/1902)
- and maybe many more things which I forget now

**Comment by matthias-ronge** [comment]
That is all correct, but has nothing to do with the problem here. The issue is that you cannot interrupt the editing of the appearance history and continue later.

**Comment by matthias-ronge** [comment]
Completed.
