### ISSUE TITLE
Rulesets & projects of several clients cannot have the same name

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3726]
If you create a new ruleset or project in a client (even in a fresh and empty client), you may get an error message that it already exists. This happens, if a ruleset/project with the same name exists in another client − but the user may not have access to that other client. This is confusing and especially annoying when you have to try out several names until you find a free one.

**Goal:** The same name for the (same) ruleset/project should be possible for each client.

**Comment by matthias-ronge** [comment]
Related to #3658

**Comment by matthias-ronge** [comment]
The same problem applies to projects.

**Comment by solth** [comment]
> The same problem applies to projects.

I cannot reproduce the error for projects - I can create multiple projects with identical titles for separate clients. 
@matthias-ronge Are you sure it still occurs in the current master?

**Comment by matthias-ronge** [comment]
> > The same problem applies to projects.
> 
> I cannot reproduce the error for projects - I can create multiple projects with identical titles for separate clients.
> @matthias-ronge Are you sure it still occurs in the current master?

I didn’t notice myself, this was reported to me but it was on an older version. I suggest leaving this ticked closed unless we stumble upon the problem again.
