### ISSUE TITLE
Active workflow can be edited

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3746]
In the workflow editor, an active workflow should only be readable but not changeable. At the moment, it is changeable in the user interface and just cannot be saved.

**Goal:** The graphical user interface should not allow changes (e.g. drag drop) but only a view if the workflow is active.

**Comment by solth** [comment]
@Erikmitk do you know if it possible to configure the bpmn editor accordingly?

**Comment by Erikmitk** [comment]
I don't know if the editor itself supports this.

In any case, it should be possible to draw an overlay that prevents user-interactions on top of the diagram. Additionally, all fields could be changed to read-only/disabled for this state.

**Comment by matthias-ronge** [comment]
You would have to be able to click on the individual elements in order to be able to look up how they are parameterized. Setting all fields readonly could be a solution. Maybe you can even do this from outside the editor using Javascript editing the DOM.

**Comment by Kathrin-Huber** [comment]
obsolete due to #4897
