### ISSUE TITLE
Export: Links to files are not as expected

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3764]
Tested with version 3.2.0 - build 09.06.2020.
Remark: [https://github.com/kitodo/kitodo-production/pull/3716/files](url) should be included in this build.

In the METS exported output the links to the (image)files are not as expected.
In the meta.xml it looks good/as expected:
![grafik](https://user-images.githubusercontent.com/61045115/84491989-b9805c80-aca5-11ea-9b9a-21be1f6cc179.png)
--> subfolder images contains a file named "00003-small.jpg.tif" (yes, a strange name, but it is called this way).
in the exported METS it is
- included twice(!) - should only be once
- and the link is not correct

```
      <mets:fileGrp USE="DEFAULT">
         <mets:file ID="uuid-19047b5d-33ee-4ca2-bb3a-f991a6aa3026" MIMETYPE="image/tiff">
            <mets:FLocat xlink:href="default00003-small.jpg.tif" LOCTYPE="URL"/>
         </mets:file>
         <mets:file ID="uuid-9fa06f33-17d2-4afe-bd04-bffcbca8edad" MIMETYPE="image/tiff">
            <mets:FLocat xlink:href="default00003.tif" LOCTYPE="URL"/>
         </mets:file>
      </mets:fileGrp>

```
--> please check

**Comment by matthias-ronge** [comment]
Could you post your settings folder from the project?

**Comment by stefanCCS** [comment]
Found configuration error - no software bug.
