### ISSUE TITLE
Find a consensus on how to indent code

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-production#377]
Currently we have a mix of different indentation styles in goobi-production: tabs versus blanks, different indent width (4, 8, maybe others). We should find a consensus for new / modified code, maybe also for existing code.

As far as I know there are currently at least two different opinions:
- Use tabs (with width 4?) for indentation. If this variant is chosen, more questions follow:
  - Tab width 8 (standard for many editors, shell, printers, GitHub, ...), 4 or other value?
  - Should tabs only be used for indentation at the beginning of a line, or may they also be used later in the line?
  - Are blanks after tabs allowed to align code?
- Forbid tabs (only exception: files which require tabs technically, e. g. Makefiles - not uses in goobi-production). Indent with blanks (width 4).
  - Indent steps 2, 4 or 8?

Another question is line length, but I suggest to focus the discussion here on indentation and whitespace usage.

Readings
- Discussion for pull request #374 
- [Google Java Style](https://google.github.io/styleguide/javaguide.html#s2.3.1-whitespace-characters)
- More? Suggestions welcome.

**Comment by henning-gerhardt** [comment]
Existing indent of a file should be used and tab indent is preferred according coding guide line as specified in http://www.goobi.org/fileadmin/groups/goobi/dokumentation/20140730_Leitfaden_fuer_GoobiEntwickler.pdf

**Comment by stweil** [comment]
@henning-gerhardt, indentation is not part of the approved "Leitfaden". Citation from 2014-07-30: 

"Da die Bestimmung offensichtlich gegen unsere am 16.7. erklärte Absicht verstößt, in Version 2 „weitgehend nur Änderungen formaler Art“ vorzunehmen, würden wir zusätzlich gern auch die Frage „Leerzeichen oder Tabs“ vertagen, also die Aussage „Einrückungen erfolgen mit Tabs“ nicht aufnehmen."

**Comment by stweil** [comment]
There is a related issue for Goobi.Presentation (https://github.com/goobi/goobi-presentation/issues/80).

**Comment by henning-gerhardt** [comment]
Closing as solved / consensus found.
