### ISSUE TITLE
Export: Missing some for DFG-Viewer required entries

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3774]
I have encountered the problem, that in the export for a DFG-Viewer is missing the following entries:
- In dmdSec/mdWrap the MDTYPE="MODS"
```
  <mets:dmdSec ID="xxxx">
      <mets:mdWrap MDTYPE="MODS">

```
- In strutMap(Phyical), main"div". TYPE="physSequece"
 ```

 <mets:structMap TYPE="PHYSICAL">
      <mets:div ID="xxxx" TYPE="physSequence">

```
Both are required according to [https://dfg-viewer.de/fileadmin/groups/dfgviewer/METS-Anwendungsprofil_2.3.1.pdf](url)
- Chapter 2.5.2.1 Eingebettete Metadaten mets:mdWrap
- Chapter 2.2.2.1 Strukturelement mets:div

==> As it looks like, that these values cannot be influeced in "<my-ruleset.xsl>" which define the meta data section export, I assume, that this somehow in the Software.
Please check (or tell me, where to configure)

**Comment by matthias-ronge** [comment]
I would assume that this can be inserted using XSLT when exporting. If that doesn't work at all, we would have to do it in code, but that's actually what the XSLT is for. @andre-hohmann, what do you think?

**Comment by stefanCCS** [comment]
Well, I would guess, that this is NOT part of the XSLT (at least in my opinion the XSLT processing does NOT write out this, but lines inside these XML-Tags).

**Comment by stefanCCS** [comment]
Ok, understood and confirmed: Above mentioned attributes can be written with XSL during export.

**Comment by andre-hohmann** [comment]
See #3544
