### ISSUE TITLE
Creating a project with Folder of type "PDF" crashes with Exception

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3775]
Version 3.2 - build 09.06.2020:

I have tried to create in the project a folder like this:
![grafik](https://user-images.githubusercontent.com/61045115/85134086-38443f00-b23c-11ea-855f-2c7fb1be8b7f.png)
This has crashed with an expection like this:
![grafik](https://user-images.githubusercontent.com/61045115/85134185-6033a280-b23c-11ea-9b20-38b83e67ef9e.png)

--> please check

**Comment by solth** [comment]
I believe this does not have anything to do with PDF but is rather a duplicate of #3731 - the error message `Duplicate key ...` looks very similar. 

Could it be you added a folder and then edited again, as was the case in the other issue?

**Comment by stefanCCS** [comment]
Unfortunately not - this exception here occurs, when you create the folder for the first time.
In detail:
I could create folders "images (for the scans)", "access" (generated JPEGS with some smaller dpi), "thumbs" (generated JPEG with fixed width), "ALTO" (for the ALTO-Files).
But I could NOT create a folder marked with filetype "PDF".

**Comment by solth** [comment]
> Unfortunately not - this exception here occurs, when you create the folder for the first time.

In your screenshot it says "Edit Folder", not "Add Folder", which would appear if you added the folder for the first time. Does this screenshot not belong to the actual error?

**Comment by stefanCCS** [comment]
Well, I have checked it again ...
... Result: Today, both (Adding and editing) works fine ...
... what do you propose to do?(close this issue here)?

**Comment by solth** [comment]
If you cannot reproduce this specific PDF related issue I would suggest to close it. I find it interesting though that editing an existing folder also works for you (described in the other issue), because that error still occurs for me in the current master branch.

**Comment by stefanCCS** [comment]
Ok, I will close this now. If it encounters again, I will create a new one.

**Comment by matthias-ronge** [comment]
This is a duplicte of #3731
