### ISSUE TITLE
Question: Is there a limited runtime in external script calling?

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3778]
I would like to understande the following:
If a "script task" is performed, is there any runtime limitation?
Background: Let's assume, a complex automatic taks is performed which needs hour or even days...

**Comment by matthias-ronge** [comment]
At the moment [there](https://github.com/kitodo/kitodo-production/blob/master/Kitodo-Command/src/main/java/org/kitodo/command/Command.java#L53) is no timeout defined.

However, it is not a good implementation to keep a Java thread hanging for so long. The recommended approach is that the command only starts the external functionality and then returns. When the external function is finished, it should [use the Active MQ service to finalize steps](https://github.com/kitodo/kitodo-production/blob/master/docs/developer/api/activemq_jms_api.md#service-to-finalize-steps) to notify Production that the task has been completed. This is, for example, how the Zeutschel OCR server interacts with Production.

**Comment by stefanCCS** [comment]
ok understood - and, of course a kind o asynchronours interface is much better.
One question is still open on my side: What shall the script return in  this case.
I was under the impression, that returning "0" means "ok" = "work done", and everything not equal means "work NOT done".
So, just return something =! 0 in this case?

**Comment by matthias-ronge** [comment]
At the moment this will not work due to bug #3673

**Comment by stefanCCS** [comment]
ActiveMQ has some problems, see #3804 and #3805 
This issue here is set to "closed".
