### ISSUE TITLE
How to configure Folders for PDF

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3779]
Version 3.2_build 09.06.2020:
I have tried to configure a PDF-output (one PDF for whole process, not per page(!)).
The PDF creation itself is done "outside Kitodo".
In the meta.xml everything looks good:
![grafik](https://user-images.githubusercontent.com/61045115/85308112-1acbdb00-b4b1-11ea-8a6d-1de869095beb.png)
But in the exported output this PDF is multiplied somehow with the number of pages:
![grafik](https://user-images.githubusercontent.com/61045115/85308317-5ebee000-b4b1-11ea-9dcd-239d445a9b36.png)
The folder is configured like this:
![grafik](https://user-images.githubusercontent.com/61045115/85308402-772efa80-b4b1-11ea-9dc6-f01883ce2df8.png)

**Comment by matthias-ronge** [comment]
This is not possible with the folder configuration. Inserting a link to a PDF of the entire work must be done in a completely different way in METS. It is not yet possible with Production.

I classified the issue as a <kbd>feature</kbd> request.

**Comment by stefanCCS** [comment]
Duplicate to #4855.
Therefore closed.
