### ISSUE TITLE
Sorting in lists

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3792]
The sorting in any list kind of view (e.g. tasks) in supported only in a limited way (e.g. in Task-List it can be sorted for Task-Name only).
Is there anything to configure this sorting?
If not, in my opionion sorting of all columns should be standard in all list views --> Feature Request.

**Comment by andre-hohmann** [comment]
I absolutely agree.

**Comment by andre-hohmann** [comment]
Maybe related to: #4245.

**Comment by solth** [comment]
Since all lists are now sortable by all columns (the exceptions are the multivalued fields `roles`, `clients` and `projects` in the user list, which have been excluded from this issue), this issue can now be closed.

**Comment by stefanCCS** [comment]
@solth :
It looks like in the "All processes" view the sorting of the two columns "Processing begin/end of last task" is not possible.
Is there a special reason for it, why this is not possible?

**Comment by thomaslow** [comment]
@stefanCCS: Sorting of those two columns should work. Can you elaborate on what happens in your case? Are processes sorted incorrectly, or not at all?  There should be an icon in the column header visualizing when the table is sorted by that column:

![image](https://user-images.githubusercontent.com/6214043/203787788-fa557990-b3c6-477f-b623-0e9d7e7ad770.png)

**Comment by stefanCCS** [comment]
Thanks for your comment - indeed it works:
I just have not tried it out, because this sorting symbol 
![image](https://user-images.githubusercontent.com/61045115/203816063-1d002dc6-faa0-493c-9fd6-d1bfd10d1e80.png)
is not visible in my UI.
![image](https://user-images.githubusercontent.com/61045115/203816026-a2586016-a761-4d48-aec0-5b29d47091dc.png)
But I can use to Mouse to do the sorting as expected.

--> this means, this is more a UI related Issue.
