### ISSUE TITLE
Question to catalogue configuration - what is "<doctypes>" good for

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3794]
As far as I have understood catalogues configuration is done mainly in
- <kitodopath>/config/kitodo_opac.xml, where the catalogue interfaces are configured, and
- per catalogue in <kitodopath>/xslt/... a mapping is configured, which maps the catalogue values to the Kitodo meta data

My question is: What is <doctypes> in kitodo_opac.xml good for?

**Comment by matthias-ronge** [comment]
The `<doctypes>` are a holdover from version 2. They have no function here any more.

Objective: The `<doctypes>` section should be removed from [the template for the kitodo_opac.xml](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/resources/kitodo_opac.xml) file.

**Comment by stefanCCS** [comment]
ok, understood, many thanks.
