### ISSUE TITLE
configuration of activemq in kitodo_config.properties

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3803]
In kitodo_config.properties there is a section for activemq. This section includes the possibility to activate the following three "services":

- activeMQ.results.topic
- activeMQ.createNewProcess.queue
- activeMQ.finaliseStep.queue

I was interested in the 'finalizeStep'-service only, so I have NOT activated the other two.
Unfortunately, this leads to errors in the Kitodo-software.  In the logfile you can find something like
```
'activeMQ.createNewProcess.queue'  doesn't map to an existing object
'activeMQ.results.topic' doesn't map to an existing object

```
--> this looks like that the software expects always all services to be activated and cannot handle only just one or two of it.
In my opinion this could be changed in the software, or at least put a clear comment in kitodo_config.properties, that always all services must be activated.

**Comment by matthias-ronge** [comment]
These errors are correctly logged because they occur internally, but they are only an indication that the program tried to read the corresponding configuration entry at this point and could not find it. In addition, exactly what is expected happens: only the configured services are started.

**Comment by stefanCCS** [comment]
Ok, understood and fine for me.
