### ISSUE TITLE
activemq: No information in body of KitodoProduction.ResultMessages.Topic

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3804]
Version 3.2 from 16.09.2020
I have tried out to use the activemq interface.
The Kitodo software provides results in a topic called "KitodoProduction.ResultMessages.Topic".
Unfortunately, the body of the messages is empty (at least as answer to my "finalize step call").
I have checked reading it with two independent methods (Python/Stomp and REST). Both have the same results.
Therefore, I assume some issue in the Kitodo-SW.
Could you please check, if the body content is written?
See also #3805

**Comment by matthias-ronge** [comment]
I cannot confirm. The message is not empty. You may have tried to read them incorrectly. Here is an example of how you can view the messages:

```java
import static java.lang.System.out;
import java.lang.reflect.*;
import java.util.*;
import javax.jms.*;
import javax.jms.Message;
import org.apache.activemq.*;

public class TopicListener {
    static class MapMessagePrinter implements MessageListener {
        @Override
        public void onMessage(Message message) {
            String heading = "Received ".concat(message.getClass().getSimpleName());
            out.println(heading);
            out.println(new String(new char[heading.length()]).replace('\0', '-'));
            try {
                MapMessage mapMessage = (MapMessage) message;
                for (Enumeration names = mapMessage.getMapNames(); names.hasMoreElements();) {
                    String name = (String) names.nextElement();
                    out.print(name);
                    out.print(": ");
                    out.println(mapMessage.getString(name));
                }
                out.println();
            } catch (JMSException e) {
                throw new UndeclaredThrowableException(e);
            }
        }
    }

    public static void main(String[] args) throws Exception {
        if (args.length != 2) {
            System.err.println("Usage: TopicListener <broker URL> <topic name>");
            System.exit(64);
        }
        Connection connection = new ActiveMQConnectionFactory(args[0]).createConnection();
        connection.start();
        Session session = connection.createSession(false, Session.AUTO_ACKNOWLEDGE);
        session.createConsumer(session.createTopic(args[1])).setMessageListener(new MapMessagePrinter());
        Thread.currentThread().stop();
    }
}
```

Output (example):

```
Received ActiveMQMapMessage
---------------------------
id: 65
level: fatal
queue: KitodoProduction.FinaliseStep.Queue
timestamp: 2020-08-18T15:40:41.961+02:00
```

**ID:** ID of the job, here identical to the ID of the task to be completed  
**Level:** `success` if the task was completed, `fatal` if the task could not be completed (error). The values `error`, `warn`, `info`, `debug`, `verbose` and `ludicrous` are log messages, which indicate that processing is still ongoing.  
**Message:** Message text for log messages or errors whose error message is not `null`  
**Queue:** Queue on which the job was received  
**Timestamp:** Time at which this message was sent

**Comment by stefanCCS** [comment]
Understood, and confirmed (my test was not setup correctly).
