### ISSUE TITLE
activemq: using FinalizeStep - no reaction 

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3805]
Version 3.2 from 19.06.2020
I have tried out to use the activemq interface. I want to use the Queue "KitodoProduction.FinaliseStep.Queue" for setting a "completion" to an open task.
I can see in the ActiveMQ-Server that my message is received in the Queue and read by the Kitodo SW.
Unfortunately nothing happens: No change in task status, and also no informaiton in Kitodo-Log as well as no body information in KitodoProduction.ResultMessages.Topic.
Could you please check?
See also #3804

**Comment by matthias-ronge** [comment]
This does not work because Active MQ is not assigned to a user, but some functions expect a logged-in user. This needs to be revised.
