### ISSUE TITLE
Export: Missing DFG-Viewer required entries(attributes) for "rightsMD"

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3813]
In my export tests I have encountered the issue, that in the METS-section mets:rightsMD, sub-section mdWrap the following attributes are missing, which are required according chapter 2.6.2.4 of [METS Anwendungs profil](http://dfg-viewer.de/fileadmin/groups/dfgviewer/METS_application_profile_2.3.1.pdf):
MDTYPE="OTHER"
OTHERMDTYPE="DVRIGHTS"
See also #3774

**Comment by andre-hohmann** [comment]
That can be solved by the export-XSLT. You will find more information in: #3544

**Comment by stefanCCS** [comment]
tried out, has not worked. Please see me comment in #3544

**Comment by stefanCCS** [comment]
works now - see in #3544
