### ISSUE TITLE
Export: Missing DFG-Viewer required entries(attributes) for "digiprovMD"

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3814]
In my export tests I have encountered the issue, that in the METS-section mets:digiprovMD, sub-section mdWrap the following attributes are missing, which are required according chapter 2.6.2.6 of [METS-Anwender-Profil](http://dfg-viewer.de/fileadmin/groups/dfgviewer/METS_application_profile_2.3.1.pdf) profil:
MDTYPE="OTHER"
OTHERMDTYPE="DVLINKS"
See also #3813

**Comment by andre-hohmann** [comment]
That can be solved by the export-XSLT. You will find more information in: #3544

**Comment by stefanCCS** [comment]
tried out, has not worked. Please see me comment in #3544

**Comment by stefanCCS** [comment]
works now - see in #3544
