### ISSUE TITLE
Export: No METS data available for meta data marked as "technical" resp. marked as "mets:div"

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3815]
Hi have created a small ruleset with meta data (keys) marked with
domain="technical"
domain="mets:div"
Expection would be to find this meta data after export in amdSec area resp. div area in the METS file.
I have attached my ruleset, the meta.xml, the export xslt and the exported file (all as .txt).
[meta.txt](https://github.com/kitodo/kitodo-production/files/4885795/meta.txt)
[ruleset_CCS_min-Structure.txt](https://github.com/kitodo/kitodo-production/files/4885798/ruleset_CCS_min-Structure.txt)
[ruleset_CCS_min-Structure.txt](https://github.com/kitodo/kitodo-production/files/4885804/ruleset_CCS_min-Structure.txt)
[202007071729.txt](https://github.com/kitodo/kitodo-production/files/4885812/202007071729.txt)

Please tell me, what is wrong.

**Comment by andre-hohmann** [comment]
1 It is necessary to add the "domain"-attribute in the "key"-element (in the "correlation"-section it is not necessary):
```xml
        <key id="MainTecData" domain="technical">
            <label>MainTecDataLabel</label>
        </key>
```


2 It is necessary to "declare" the metadata in the export-XSL, as for example: 
`<xsl:variable name="MainTecData" select="kitodo:metadata[@name='MainTecData']"/>`
`<xsl:variable name="license" select="kitodo:metadata[@name='license']"/>`

Then, it is necessary to define the target, as for example: 
```xml
            <xsl:if test="$license">
                <dv:rights xmlns:dv="http://dfg-viewer.de/">
                        <dv:license>
                            <xsl:value-of select="normalize-space($license)"/>
                        </dv:license>
                </dv:rights>
            </xsl:if>
```

**Comment by stefanCCS** [comment]
I could replicate you solution for "technical" - and it works fine :-)
I am still struggeling a bit with "mets:div", but I will try out, and ask, if needed.

**Comment by stefanCCS** [comment]
Looks like to work (was a misunderstanding on my side) - I will check again, and confirm ...

**Comment by matthias-ronge** [comment]
@stefanCCS, is that resolved?

**Comment by stefanCCS** [comment]
Yes, I can confirm, both (technical as well as mets:div) works fine (if you do everything correct in ruleset and xslt for export).
