### ISSUE TITLE
Automatic Taks in strange state: (somehow finished, but process is not propagated to next state)

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3818]
In the workflow editor I have setup an automatic task, which
- on the one hand runs fine, without any errors (including no error in kitodo.log)
- on the other hand process is not propagated to next step
- and in task manager this task is finished but 0%

I did this with a meta data task (see also #3817 ).
![tm-state](https://user-images.githubusercontent.com/61045115/86919985-501b2e80-c129-11ea-80b5-b79588451c7d.png)
![process-state](https://user-images.githubusercontent.com/61045115/86920078-6f19c080-c129-11ea-9f89-9e81e94f5c90.png)

**Comment by matthias-ronge** [comment]
Related to #3440

**Comment by stefanCCS** [comment]
Any update on this issue?

**Comment by stefanCCS** [comment]
Will close this issue, as it is mainly a duplicate to #3791.
