### ISSUE TITLE
Meta data editor: At first time need to press the Save-Button twice

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3821]
Version 3.2-build 16.09.2020
After starting the meta data editor, and making some editing:
If I press the "save" button, it is NOT saved (nothing happens). I need to press the button a second time.

**Comment by solth** [comment]
I think this is due to the first click just triggering a Javascript `blur` event on the currently selected `input` element.

**Comment by matthias-ronge** [comment]
Related: #3472

**Comment by solth** [comment]
@oliver-stoehr could this be the same issue you described in #3472?

**Comment by stefanCCS** [comment]
Check this with Rel 3.5.0-beta. Looks ok now.
I will close this issue.
