### ISSUE TITLE
Sub-Structure in exported METS has "strange" ORDER-Attribute

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3826]
I have created a simple rule set with two levels of logical structure (monograph/chapter).
When this is exported the chapters have a "strange" ORDER-Attribute in structMap"LOGICAL".
"Strange" means, that the ORDER-Attribute does not follow a simple ordering number, but has instead the ORDER number of the first page, it includes.
Besides this might be very confusing, it could be even formal wrong:
Just imagine 3 chapters beginning on the same page would have the same ORDER, which is wrong from METS point of view.
Please check.

Example:
```
   <mets:structMap TYPE="LOGICAL">
        <mets:div ID="uuid-3bc8e4fd-f4ff-4373-8f45-edea308f8c98" DMDID="uuid-056dab6b-c17c-32ac-b0b7-87a384bea1b0" ADMID="uuid-7503ce07-a13e-345c-befc-3111c996eabc" TYPE="Monograph" ORDER="1" LABEL="202007091123Div">
            <mets:div ID="uuid-b48726e8-1f17-43db-9108-5ff0b43239ba" DMDID="uuid-2e789f22-462b-308d-be98-ac3139f94d2d" TYPE="Chapter" ORDER="1"/>
            <mets:div ID="uuid-33241660-8b31-4174-a593-d1abeead68b9" DMDID="uuid-2c2086c5-d938-3427-8bbe-c14b8cdb00e6" TYPE="Chapter" ORDER="2"/>
            <mets:div ID="uuid-e91798f5-c606-49ce-ac8d-885b48c10711" DMDID="uuid-14eb30c3-c891-328b-bb75-f3854dd8f8ff" TYPE="Chapter" ORDER="6"/>

```
Rule set extract:
```
   <correlation>
        <restriction division="Monograph" unspecified="forbidden">
            <permit division="Chapter"/>

```

**Comment by stefanCCS** [comment]
@sebastian-meyer: Can we have a discussion please about this topic? (e.g. via Skype)
This still looks wrong in my opinion.

**Comment by sebastian-meyer** [comment]
I agree that this is odd and can lead to invalid METS files. I'd suggest omitting the `@ORDER` attribute for the logical struct map.

But this should be discussed with @Kathrin-Huber, since she is the release manager for Kitodo.Production.

**Comment by stefanCCS** [comment]
In my opinion omitting of "ORDER" is not an option (even, if DFGViewer is ignoring this at this moment).

In [https://mets.github.io/METS_Docs/mets.html](url) you can find:
```
ORDER (integer/O): A representation of the element's order among its siblings (e.g., its absolute, numeric sequence). For an example, and clarification of the distinction between ORDER and ORDERLABEL, see the description of the ORDERLABEL attribute

ORDERLABEL (string/O): A representation of the element's order among its siblings (e.g., “xii”), or of any non-integer native numbering system. It is presumed that this value will still be machine actionable (e.g., it would support ‘go to page ___’ function), and it should not be used as a replacement/substitute for the LABEL attribute.
To understand the differences between ORDER, ORDERLABEL and LABEL, imagine a text with 10 roman numbered pages followed by 10 arabic numbered pages. Page iii would have an ORDER of “3”, an ORDERLABEL of “iii” and a LABEL of “Page iii”, while page 3 would have an ORDER of “13”, an ORDERLABEL of “3” and a LABEL of “Page 3”.
```
So, I think it is clear what to do:
**For each level** just create ORDER-numbering: Increase +1 one per item (like done already for physical items/pages).

Here one example how it should look like:
(you can see, that here of levels with just on item, no ORDER is created. But of course it would be ok, to create always ORDER to keep the implementation simple)
![ORDER-example](https://user-images.githubusercontent.com/61045115/90862153-47a34e00-e38d-11ea-9b38-03987098e8a3.png)

**Comment by andre-hohmann** [comment]
Thanks for the information @stefanCCS, 

In the example above, there are on in `"<div ID="DIVL3">` duplicates of the ORDER-values. For the `div` of TYPE="ILLUSTRATION", the numbering begins from 1 - the same for the `div` of TYPE="PARAGRAPH". 

Is that a mistake in the example or is it a demand on the ORDER-numbering?

**Comment by stefanCCS** [comment]
This is intended.
There are two different, independent types for <div> entries below "DIVL3":
- ILLUSTRATION
- PARAGRAPH
Each of this types has its own indepedent ordering.

**Comment by andre-hohmann** [comment]
As far as i understand METS (https://github.com/kitodo/kitodo-production/issues/3826#issuecomment-678289906), this is not possible. 
For each the illustrations and the paragraphs an own `div` has to be created.  

From my point of view, @Kathrin-Huber could examine, if the `@ORDER` attribute can be applied in the logical structMap. 
But according to my current knowledge, the order numbering has to be "consecutively from 1 to the last `div`" within in each `div`. Invalid METS should not be created.

**Comment by stefanCCS** [comment]
Hi @andre-hohmann ,
many thanks for being that "hard" and really try to clarify, what is needed.
I have re-checked it again internally, and I can confirm, **you are absolutey right**!
_Each numbering per `<div>`-level has to be "consecutively from 1 to the last div"._
The mistake was on my side. I have copied something from our examples, but simplified it, before I put it here (just to make it more "readable"). During this simplificataion I have omitted sub-levels. In the original example, "PARAGRAPH" and "ILLUSTRATION" were **not** on the same level - therefore the numbering, re-starting with "1", was correct there, but not correct anymore, after I have put everything togehter on the same level.

I hope, we now have a final conclusion.

**Comment by andre-hohmann** [comment]
As we have now a valid requirement, it must be now examined by the release manager @Kathrin-Huber. From my point of view, two questions must be answered: 

1. Is the `@ORDER` attribute used internally for other functions/features? 
See the question in: https://github.com/kitodo/kitodo-production/issues/3635#issuecomment-670399427. There should be no negative effects on existing functions/features! 
2. Can the `@ORDER` attribute in the `<mets:structMap TYPE="LOGICAL">` be implemented as described above? 
I cannot estimate the complexity of the  requirement.

**Comment by matthias-ronge** [comment]
At the moment, the `ORDER` attribute is used internally for the combined structure tree feature. For example, if a chapter begins at image 7, the order of the `<div>` is set to 7.

During export, it is cleared, except for newspaper issues, which are counted.

So, do I understand it correctly that all divisions in one parent division should just be counted? Like:

```
<structMap TYPE="LOGICAL">
  <div ORDER="1">
    <div ORDER="1" TYPE="chapter"/>
    <div ORDER="2" TYPE="chapter">
        <div ORDER="1" TYPE="figure"/>
        <div ORDER="2" TYPE="photo"/>
    </div>
    <div ORDER="3" TYPE="chapter"/>
    <div ORDER="4" TYPE="appendix"/>
  <div>
</structMap>
```

@sebastian-meyer, can you confirm this, too?

**Comment by stefanCCS** [comment]
From my point of view this is correct.

**Comment by sebastian-meyer** [comment]
I can confirm. From a METS point of view this would be correct.

**Comment by stefanCCS** [comment]
Please check, if/how this can be implemented.
Please clarify in detail, what dependency to "combined structure tree view" might be.
In my opion, still wrong METS is created.

**Comment by matthias-ronge** [comment]
[Here](https://github.com/kitodo/kitodo-production/blob/01a6f5735c92fce0c1020e14479f0eaefcf97381/Kitodo/src/main/java/org/kitodo/production/services/schema/SchemaService.java#L256) the internal numbering is deleted (i.e. is set to `0`) during export, except for journal issues that are counted. The count must be set here instead of `0`.
