### ISSUE TITLE
English name from rule set is not taken in meta data editor

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3831]
In the rule set I have something like this:
```
        <division id="VOLUME">              <!-- DFG-Viewer compatible -->
            <label>Volume</label>
            <label lang="de">Band</label>
        </division>
```
The "VOLUME" is a sub element of my root-element "monograph".
So, I added this via "Add Element" in the meta data editor (works fine).
What is asthonishing is, that instead of "Volume" the german word "Band" is visible. (and I use Kitodo with English UI).
--> please clarify.

See 
![band-vs-volume](https://user-images.githubusercontent.com/61045115/87168082-454dce80-c2ce-11ea-85f8-db71efe818b0.png)

I just have encounter that in the "Add element" there is the same strange behaviour ("Kapitel" instead of "Chapter")
Extract from my rule set:
```
        <division id="CHAPTER">           <!-- DFG-Viewer compatible -->
            <label>Chapter</label>
            <label lang="de">Kapitel</label>
        </division>
```
See 
![band-vs-volume-v2](https://user-images.githubusercontent.com/61045115/87168367-abd2ec80-c2ce-11ea-96c5-c2b684c0ba7c.png)

**Comment by solth** [comment]
You can change metadata language and UI language individually. The metadata language is set in your own user settings that can be accessed via the main menu -> "Benutzerdaten & Einstellungen":
<img width="487" alt="benutzereinstellungen" src="https://user-images.githubusercontent.com/19183925/87169932-f5bcd200-c2d0-11ea-99bc-551770c0631f.png">


and then:
<img width="696" alt="Bildschirmfoto 2020-07-10 um 17 08 50" src="https://user-images.githubusercontent.com/19183925/87169637-919a0e00-c2d0-11ea-8dc9-74e3c81bf649.png">

**Comment by stefanCCS** [comment]
Many thanks. I needed to log-off/log-on, which is acceptable of course.
--> works fine!
