### ISSUE TITLE
ReST interface for Kitodo 3

### ISSUE THREAD

**Issue by mnscholz** [kitodo/kitodo-production#3842]
As I infer from some issues, Kitodo 2 has a REST interface.
Does Kitodo 3 have one, too?
If so, is there any documentation?

**Comment by matthias-ronge** [comment]
The old rest interface still exists, but it can no longer work in its current form. The first goal here must be to remove the remains of the old interface, also because it hinders other clean-up work, see item #3873. If something comparable is needed, we would have to implement it from scratch.
