### ISSUE TITLE
Input fields "Change of year" are displayed inconveniently

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3846]
### Problem
The input fields in "Change year" are shown in only one row which has to be scrolled. 
Thus, the calendar cannot be used and the field "Name of the year" is barely recognizable. 

### Solution
Show all fields clearly and immediately.  

### Example
![inputfield01](https://user-images.githubusercontent.com/14835770/87767514-0e6e4000-c81b-11ea-9709-0f15a55d6780.jpg)

**Comment by matthias-ronge** [comment]
If I understand that correctly, we no longer need these inputs, because this is now set in the ruleset, isn’t it?

**Comment by matthias-ronge** [comment]
Closed as duplicate to #3741

**Comment by matthias-ronge** [comment]
Further remark: It is confusing that a year is shown in the calendar that opens. One might think that one would have to go back to the beginning of the publication.
