### ISSUE TITLE
MetadataLock not updated when user leaves metadata editor via menu

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#3860]
The class `MetadataLock` manages a list of processes that are currently opened in the metadata editor by a user. Processes are "unlocked" when the user exits the metadata editor via the `Exit` or `Save & Exit` buttons, but not when the user leaves the metadata editor via some other link, for example the Kitodo logo, the breadcrumbs or the navigation menu. 

This leads to many processes still being marked as "in work by another user" even though they are not openend in the metadata editor anymore.

**Comment by matthias-ronge** [comment]
To disable the main menu or breadcrumbs menu, should be a possibility. It may even be hidden to gain additional space for the metadata editor itself to show.
