### ISSUE TITLE
Metadata editor crashes if there are many images

### ISSUE THREAD

**Issue by mnscholz** [kitodo/kitodo-production#3896]
If a process has a certain number of images, the metadata editor consistently crashes with the message below.
The editor does not crash immediately but after doing a certain amount of actions (paginate, insert/edit structure, move images, ...).

It seems that the more images there are, the less actions you can do before crashing. So, a first guess was that Tomcat had too little memory, but setting it to 4G didn't resolve the problem.
We have problems with real-world processes with 300-500 images, but a test example showed that the number of images may be only ~>20! 

Any hints?

![Screenshot_2020-08-04 Kitodo Production](https://user-images.githubusercontent.com/1378632/89297444-21c73b00-d664-11ea-8ee1-990b7a6b2f13.png)

**Comment by mnscholz** [comment]
I don't know if it contributes to the issue:

When looking at the network traffic in the browsers developer panel, I can see that all requests for `metadataEditor.jsf` with URL parameter `uuid=...` fail with HTTP 404.

Is the Tomcat config missing something?

**Comment by mnscholz** [comment]
Yet another observation:

The GalleryPanel class logs a warning if the number of images is bigger than 200:
```
[WARN ] 2020-08-04 15:42:36.944 [http-nio-8080-exec-8] GalleryPanel - Number of images in structured view: 323
```
This seems a bit odd to me as I guess a lot of digitized objects will have more than 200 pages...

**Comment by solth** [comment]
> Yet another observation:
> 
> The GalleryPanel class logs a warning if the number of images is bigger than 200:
> 
> ```
> [WARN ] 2020-08-04 15:42:36.944 [http-nio-8080-exec-8] GalleryPanel - Number of images in structured view: 323
> ```
> 
> This seems a bit odd to me as I guess a lot of digitized objects will have more than 200 pages...

This is a warning that was added by us and is probably not connected to the error.

This issue may be a duplicate of #3444

**Comment by mnscholz** [comment]
Yes, this looks like duplicate. I will close it and comment on the other one.
