### ISSUE TITLE
Serializeable classes should have a correct ID

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#390]
Classes
- Goobi/src/org/goobi/production/model/bibliography/course/Course.java
- Goobi/src/de/sub/goobi/metadaten/copier/DataCopyrule.java
- Goobi/src/de/sub/goobi/persistence/BatchDAO.java
- Goobi/src/de/sub/goobi/helper/exceptions/GUIExceptionWrapper.java
- Goobi/src/de/sub/goobi/helper/ProjectHelper.java
- Goobi/src/org/goobi/production/chart/ProjectTask.java

and maybe some more classes should have a correct serializeable ID and not value `1L`. Found while checking pull request #385 .

**Comment by matthias-ronge** [comment]
This was discussed as part of the development project and it was decided that `serialVersionUID` should be removed because this is typically the correct behavior. I will close this ticket.
