### ISSUE TITLE
Warn message should not be green

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3925]
Extracted from issue #3434 

![validationwarning01](https://user-images.githubusercontent.com/14835770/79189968-631cac00-7e23-11ea-801a-c6199e982fc8.jpg)

Warn message should not be green.

**Goal:** Either it also turns red, or maybe a yellow hue.

**Comment by solth** [comment]
Just checked the current preview system. The same validation warning is now styled red:

<img width="1427" alt="Bildschirmfoto 2020-08-20 um 09 39 47" src="https://user-images.githubusercontent.com/19183925/90730866-211bdf00-e2c9-11ea-8792-6e1648f38c63.png">

@matthias-ronge can you confirm that this issue has been resolved in the current version of the master branch?

**Comment by matthias-ronge** [comment]
Unfortunately, I no longer have the test candidate. If it looks like the screenshot, it's okay.

**Comment by matthias-ronge** [comment]
It's okay on the test system. I close the issue.
