### ISSUE TITLE
Statistics do not work properly

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3937]
### Problem
1. The statistics from "statistical evaluation" in the process list are empty. 
2. The statistic "State of volumes" is not opened correctly and cannot be closed.

**Comment by solth** [comment]
>     2. statistic "State of volumes" is not opened correctly and cannot be closed.

@andre-hohmann Can you provide additional information about what "is not opened correctly" means? I just tested this in the current preview system after selecting all processes of the first page (client "SLUB Dresden") and got the following view which looks fine to me and can be closed without a problem:

<img width="1424" alt="Bildschirmfoto 2020-08-14 um 11 33 22" src="https://user-images.githubusercontent.com/19183925/90235809-305ee080-de22-11ea-9e19-ca00a316fe8f.png">

**Comment by andre-hohmann** [comment]
It was my fault, i forgot to select the processes for the statistical analysis. 
If you just apply the statistics, you will see what i meant.

**Comment by solth** [comment]
Sorry, I still don't see the problem... Could you perhaps just add a screenshot?

<img width="1428" alt="Bildschirmfoto 2020-08-14 um 11 55 53" src="https://user-images.githubusercontent.com/19183925/90237790-25597f80-de25-11ea-87be-0c8f8a8c92f0.png">

**Comment by andre-hohmann** [comment]
The window opens and 
- the scrollbar is kind of flickering
- it is only half visible - therefore the close-button is perhaps missing

![statistics](https://user-images.githubusercontent.com/14835770/90238155-bf212c80-de25-11ea-97e5-0b052e97a0cd.jpg)

**Comment by andre-hohmann** [comment]
I have tried to record it. And in reality, the flickering is much faster

![GIF 14 08 2020 11-50-21](https://user-images.githubusercontent.com/14835770/90238442-48d0fa00-de26-11ea-8f22-4f9bb52b6b6f.gif)

**Comment by solth** [comment]
This looks like a CSS caching issue - could you try to reload the page with F5 (to force the update of the included stylesheets) and retry?

**Comment by andre-hohmann** [comment]
Your assumption is right. In the private mode, it works correctly. 
F5 stops only the flickering. I will delete the cache, ... before i will close the browser.
