### ISSUE TITLE
Exception with "AddElement" in meta data editor

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3940]
Version 3.2 build 14.08.2020
(this is maybe related to #3820
You have a kind of substructure (lets assume chapters in a monograph).
You create in meta data editor with "AddElement" theses chapters, including direct assignment of pages in AddElement dialog --> works fine.
Move afterwards one page from a chapter to another chapter (works fine).
If you try to use "AddElement" again, then you get this exception here  (nothing visible in kitodo.log)
(looks like to be independent, on which element you perform the RightClick for AddElement)
![AddElementException](https://user-images.githubusercontent.com/61045115/90232736-6a79b380-de1d-11ea-8aea-c3cecadf58bc.png)

**Comment by solth** [comment]
I followed your instructions exactly but could reproduce the error on the current system. Maybe some kind of configuration problem?

**Comment by stefanCCS** [comment]
Maybe you can try out with my rule set:
[ruleset_CCS_min-Structure-v2.txt](https://github.com/kitodo/kitodo-production/files/5073880/ruleset_CCS_min-Structure-v2.txt)

And we could have private talk on Skype, if you like ...
