### ISSUE TITLE
Image derivatives of certain width

### ISSUE THREAD

**Issue by mnscholz** [kitodo/kitodo-production#3950]
Kitodo offers these two posibilities to create derivatives:
- Derivat erstellen: scale the original image by percent
- Web-Bild erstellen: set a width by pixels

For the latter, however, I cannot change the default 150px. If I change the value in the field, after saving the value is set to 150px again.
Thus, I cannot generate derivatives with a custom width.

**Comment by andre-hohmann** [comment]
@mnscholz : It seems that the changes in the derivate-configuration are saved and shown correctly now. Can you confirm it?
