### ISSUE TITLE
Meta data editor: Page movement changes page index (gets corrupted)

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3961]
If you move pages in meta data editor from one sub structure element to another (e.g. between chapters),
- you will loose page index "1", and get a new page index (last page number + 1, in the example below: 6+1=7)
- and after some movements you also may get the error shown below ("could not append ...")
![meta-data-editor-click-page-movement-changes-page-index](https://user-images.githubusercontent.com/61045115/90866812-b6d07080-e394-11ea-9038-850558a3e52e.png)

**Comment by matthias-ronge** [comment]
**Goal:** LABEL and ORDERLABEL should always be known in the ruleset, even if they are not explicitly defined in it.

**Comment by stefanCCS** [comment]
Confirmed - works for me in official Release 3.2
