### ISSUE TITLE
METS-Filegroup cannot be entered

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3964]
### Problem
In the project settings, it is not possible anymore to enter the METS filegroup. 

### Solution 
It should be possible to enter Text in the field. 
It should be possible to configure the menu. 

### Example
![metsfilegroup01](https://user-images.githubusercontent.com/14835770/90883028-526ddb00-e3ad-11ea-9d30-b27fcfe88a87.jpg)

**Comment by matthias-ronge** [comment]
Needs rechecking on branch #3951
