### ISSUE TITLE
Unnecessary OPAC search in creation of processes for periodical volumes 

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3966]
### Problem
When a process for a periodical volume is created by the +-Symbol in the process list, the OPAC-import is shown. This is not necessary, because the metadata cannot be imported from the union catalog. 

### Solution
It would be better, if the Tab "Title record link" is shown. 

### Examples
![periodical01](https://user-images.githubusercontent.com/14835770/90898212-9d481c80-e3c6-11ea-9001-9ed380b555a7.jpg)

![periodical02](https://user-images.githubusercontent.com/14835770/90898242-a20cd080-e3c6-11ea-8c10-7b94679e96cd.jpg)

![periodical03](https://user-images.githubusercontent.com/14835770/90898253-a5a05780-e3c6-11ea-9a27-e978a7157ee6.jpg)

**Comment by solth** [comment]
There can be constellations where metadata for child processes _can_ be imported indvidually via a search interface - we actually have such a case with an OAI-PMH interface right now. So I don't think we should generally not show the import dialog when creating subprocesses. 
Perhaps this should be configurable via `kitodo_opac.xml` or ruleset?

**Comment by andre-hohmann** [comment]
Which document types are imported via the OAI-PMH? Is it also periodical volumes? 
Will it occur often? It will be still possible to open the search with the button "Catalogue search". I know that processes for periodical volumes will be created very often. 

If it should be configured, it should in my opinion be configured in the ruleset, too. Otherwise, it gets complicated. Maybe two attributes are needed: 
1. use="createChildrenFromParentWithOPACSearch"
2. use="createChildrenFromParentWithoutOPACSearch"

**Comment by solth** [comment]
In the described case it will probably occur regularly. The problem with configuring it via the ruleset is that than it doesn't depend on the search interface for the import anymore. It _should_ depend on the interface, though, because only the interface defines what features are supported during import.

**Comment by andre-hohmann** [comment]
If it is necessary, the configuration can also be implemented in the `kitodo_opac.xml`. I have to admit that i have no idea how to realize it.

**Comment by solth** [comment]
You are probably right that the default case should be not to open the import dialog when creating a child process. Then the configuration only needs to be added for the exception when some child processes are indeed to be imported from a search interface. I guess we should propose that improvement in a separate issue.

**Comment by matthias-ronge** [comment]
I don't understand what the second ticket is for. It's all about that one question, isn't it? Did you just create a duplicate or did I not understand something correctly?

**Comment by matthias-ronge** [comment]
Related: #3561, #3407

**Comment by andre-hohmann** [comment]
You are right, i should have closed this issue. 

The issue #3970 focuses on the ability to configure the import for children processes in the `kitodo_opac.xml` : 
1. with OPAC search
2. without OPAC search ("Title record link")

In this issue, the demand of replacing of the OPAC-search for children processes was straightforward. I did not know that this feature is needed in other use cases. Enable the configuration, everyone can use it according to the demands. Otherwise , i expect suggestions for improvement like this in the future. 

As the issue #3970 is more flexible and sustainable, i close this issue.
