### ISSUE TITLE
Indexing does not work

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3999]
The indexing was started with the button "Index all" at the bottom left. The indexation remains at 25%.

![Screenshot](https://user-images.githubusercontent.com/3040657/93601119-ff457300-f9c0-11ea-8c47-d7ad1a92939d.png)

Log messages:

    [DEBUG] 2020-09-18 15:07:17.485 [IndexAllThread] IndexingService - Starting indexing of type DOCKET
    [DEBUG] 2020-09-18 15:07:18.606 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:19.607 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:20.607 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:21.608 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:22.609 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:23.609 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:24.610 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:25.610 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:26.611 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:27.611 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:28.612 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:29.612 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:30.613 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:31.613 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:32.614 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:33.614 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'
    [DEBUG] 2020-09-18 15:07:34.615 [IndexAllThread] IndexingService - Cannot start 'PROJECT' indexing while a different indexing process running: 'DOCKET'

**The workaround is** (after restarting Tomcat) to index the rows individually using the indexing button for projects, rulesets and workflows.

**Goal:** The indexing should run through completely.

**Comment by stefanCCS** [comment]
Another workaround (at least version 3.2.1-build 14.01.2021):
Press F5 in Browser to reload for each object type

**Comment by matthias-ronge** [comment]
> Another workaround (at least version 3.2.1-build 14.01.2021):
> Press F5 in Browser to reload for each object type

I can confirm: It needs revisiting of that page for the next type to be indexed. You may have been logged out meanwhile.

**Comment by matthias-ronge** [comment]
I can confirm that this is still a problem with release 3.4.1

**Comment by stefanCCS** [comment]
Well, I have to admit, that on my system (Release 3.4.0 with manually patched log4j), re-indexing works fine:
--> I have deleted the index, created the index and could start the indexing for "whole index" and this has run through all objects without any troubles.

**Comment by matthias-ronge** [comment]
Maybe related:  #4947

**Comment by matthias-ronge** [comment]
Reason why browser window needs to be reloaded: See https://github.com/kitodo/kitodo-production/issues/3713#issuecomment-1027761149

**Comment by matthias-ronge** [comment]
The problem may be a race condition: `IndexingService.getProgress()` (one thread) sets `currentIndexState` to `ObjectType.NONE`, which is the condition for `IndexingService.runIndexing()` (another thread) to start the next `indexerThread`. However, `getProgress()` later calls `indexerThread.interrupt()`. If the working order of the two threads comes to be in this order, the just started thread is interrupted, instead of the thread that has already finished.

**Comment by thomaslow** [comment]
This was fixed by #5367. I removed the thread interrupt code (including the log message above) and replaced it with a standard Java thread pool. There should be no race conditions like that any more.

**Comment by andre-hohmann** [comment]
@thomaslow : Thanks a lot for your hint. That helps us to clean up the issues. 

@matthias-ronge : Can this issue be closed?

**Comment by matthias-ronge** [comment]
When this was fixed, the issue can be closed
