### ISSUE TITLE
[Solved] The menu is empty

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4000]
I have installed [release 3.2](https://github.com/kitodo/kitodo-production/releases/tag/kitodo-production-3.2), I am logged in as `testadmin` and indexed the database. I can't do anything else here because there are no entries, neither in the main menu nor in the user menu.

![Screenshot](https://user-images.githubusercontent.com/3040657/93602906-96abc580-f9c3-11ea-9e0a-e37f64525328.png)

![Screenshot](https://user-images.githubusercontent.com/3040657/93603205-f99d5c80-f9c3-11ea-8b77-8af8257beb89.png)

There are no error messages, neither in the log files nor in the browser network panel. Restarting Tomcat does not fix it. I also tried `testProjectmanagement` user, but the problem is there, too.

**Goal:** Menu needs to be fixed. (In the delivery state, the administrator account should be allowed to do everything and not nothing. Oter users should have a sensible set of permissions. The user menu should not be limited.)

**Comment by solth** [comment]
I believe this is related to #3953 and is just a caching problem. If you instruct your browser to "hard refresh" the page (for example "CTRL" + "Shift" + "r" on Firefox Windows or "CMD" + "Shift" + "r" on MacOS), the problem should be resolved.

**Comment by matthias-ronge** [comment]
I tested it. Unfortunately, no.

**Comment by matthias-ronge** [comment]
Solved. The effect was caused by the Firefox extension “I don’t care about cookies”.
