### ISSUE TITLE
There is no possibility to choose a teaser image

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4017]
In version 2, there was the option of selecting exactly one media file per process as a teaser image which is shown in the hit list in the presentation. The file is additionally recorded as the only member in a special file group (TEASER) in the METS file.

**Goal:** to reinstall functionality.

**Comment by sebastian-meyer** [comment]
That's not how Kitodo.Presentation actually works.

In Kitodo.Presentation you can configure, which `fileGrp` the preview images should be taken from. The default ist `THUMBS`. Furthermore you can configure per document type which structure element's first page should be used as preview. The fallback would be the first page of the document. I. e. you could configure the preview for a "monograph" to be the first page associated with the structure element "title_page". If there is no "title_page" the first page of the "monograph" itself is used.

The METS application profile defines an additional fileGrp `TEASER`, which should contain a single image as a teaser for the document. However, this is optional and doesn't have to be a page of the document itself. In fact, it could be any image, i. e. with the holding institution's logo or some kind of collage.

So if you just want to support thumbnail previews in Kitodo.Presentation, implementing the `THUMBS` fileGrp would be sufficient. This fileGrp should hold a thumbnail for every page. There is no need to select a specific image in Kitodo.Production as this is handled by Kitodo.Presentation.

If you want to support the optional fileGrp `TEASER` as well, you'd need some kind of selector to choose (or provide) the image to use. This image should be the only image referenced in the `TEASER` fileGrp. But again: Kitodo.Presentation doesn't use this at all and I don't know of any presentation software which does.

**Comment by matthias-ronge** [comment]
> In Kitodo.Presentation you can configure, which `fileGrp` the preview images should be taken from. The default ist `THUMBS`.

@sebastian-meyer Is it possible to configure this `fileGrp` independently for _search-result_? If so, and given a METS file that _has_ a `TEASER` `fileGrp`, setting the `fileGrp` the preview images should be taken from to `TEASER` could bring the expected behaviour. Is this possible, or would it break the _Page preview_ gallery in _work-view_?

> this is optional and doesn't have to be a page of the document itself. In fact, it could be any image

In Production 2, the implementation only allowed selecting a page of the document itself.

![Screenshot of representative select box](https://user-images.githubusercontent.com/3040657/102459382-ce1f2200-4045-11eb-8562-41dd42d1c988.png)

You had to set this special check mark in the filegroup configuration.

![Screenshot of filegroup configuration](https://user-images.githubusercontent.com/3040657/102460195-ef344280-4046-11eb-82e3-cad4bc2f5d4c.png)

For example, this function could be used to select the jewelry title (_Germ._ “Schmucktitel”) as a preview image in the hit list.

**Comment by sebastian-meyer** [comment]
> > In Kitodo.Presentation you can configure, which `fileGrp` the preview images should be taken from. The default ist `THUMBS`.
> 
> @sebastian-meyer Is it possible to configure this `fileGrp` independently for _search-result_? If so, and given a METS file that _has_ a `TEASER` `fileGrp`, setting the `fileGrp` the preview images should be taken from to `TEASER` could bring the expected behaviour. Is this possible, or would it break the _Page preview_ gallery in _work-view_?

No, it's not possible to use different `fileGrp` for collection list and search result list. And I am not sure what you are trying to achieve. Do you want to show the same teaser image for every hit of a document?
Currently, the thumbnail depends on the hit: If the hit occured in the title data of a document, the document's thumbnail is shown (applying the same rules as for collection lists), if the hit occured in the metadata of a structure element, the thumbnail of that structure's first page is shown, and if the hit occured in the full text of a page, that page's thumbnail is shown.

> For example, this function could be used to select the jewelry title (_Germ._ “Schmucktitel”) as a preview image in the hit list.

I suggest abandoning this feature since AFAIK there is no presentation software actively using the `TEASER` file group. Furthermore, if you want to use the jewelry title as thumbnail, you can already achieve this by creating a structure element for the jewelry title in Kitodo.Production and selecting the structure type `jewelry title` as preferred thumbnail for all document types in Kitodo.Presentation.

**Comment by matthias-ronge** [comment]
Thanks for the answer. The function is thus given and nothing needs to be added. However, I'll leave the issue open so that it can go into the <kbd>documentation</kbd>.

**Comment by Kathrin-Huber** [comment]
I am closing this, because nothing has to be done anymore.
Tickets with the documentation label can also be found closed ;-)
