### ISSUE TITLE
Change password without abort / cancel button

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#4025]
A normal user can not abort password change as there is no "cancel" or "abort" button:

![Screenshot_2020-10-07_11-56-16](https://user-images.githubusercontent.com/2129672/95316553-458d4400-0894-11eb-809e-5c50d4795046.png)

used version: master branch 2020-10-05 / commit 6c5b92a674159520c1929549b80e44b5568be99f

**Comment by Kathrin-Huber** [comment]
What dou you mean with "normal user"?
The password change popup should look like this:
![Anmerkung](https://user-images.githubusercontent.com/22615787/95329528-657a3300-08a7-11eb-881f-b920c97a6b4b.png)

Where did you find this dialog?

**Comment by henning-gerhardt** [comment]
@Kathrin-Huber your dialog will be displayed if you are an administrator or have a lot of rights. The dialog which I got was from a user with limited rights.
