### ISSUE TITLE
Application should start and log an error if Active MQ server cannot be reached

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4029]
If the Active MQ server cannot be reached, the web application will not start and the Tomcat will not start up completely. There is no error message at all.

**Goal:** The application should start up. An error message should be written in the log file. It would be ideal if the application would later automatically connect to the Active MQ server when it becomes available again, but that's a bonus.

**Comment by stefanCCS** [comment]
Tried out - works fine.
