### ISSUE TITLE
Windows file endings?

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#403]
It seems the following files have windows line ending format? (After now having my Eclipse to fix line endings they show as modified.)

* Goobi/scripts/script_createDirMeta.sh
* Goobi/scripts/script_createDirUserHome.sh
* Goobi/scripts/script_createSymLink.sh
* Goobi/scripts/script_deleteSymLink.sh
* Goobi/src/edu/sysu/virgoftp/ftp/encrypt/MD4.java

**Comment by henning-gerhardt** [comment]
On linux git checkout this files looks correct. I don't know if Eclipse could handle `.gitattribute` entries  now correct. In the past Eclipse ignored this file or at least the entry

```
* text=auto
```

**Comment by matthias-ronge** [comment]
I cannot really say. If it looks okay I will close the issue and try to get my Eclipse back right. After the crash and re setup all my settings got lost, this is a bit annoying. Before, these files were never shown as changed.

**Comment by matthias-ronge** [comment]
Windows problem. Adding the following to `goobi-production/.git/config` fixes it:
```
[core]
	filemode = false
```
It explains why the scripts: They probably have execute permission which cannot be reflected by the Windows file system. But what is with MD4.java? @henning-gerhardt could you check if the permissions of that file differ on windows from the other java files and if necessary make them the same?

**Comment by henning-gerhardt** [comment]
@matthias-ronge : Thank you for hinting me too look at the file permissions. Script files are with executable rights or 0755. File `MD4.java` has executable rights too. Never notices this yet. I will correct it.

**Comment by henning-gerhardt** [comment]
Correcting file permissions for `MD4.java` in commit https://github.com/goobi/goobi-production/commit/036bc87c809a26ec2c8200263757605b86022a30

**Comment by henning-gerhardt** [comment]
Is this issue still existing or must somebody something to do?

**Comment by stweil** [comment]
All those files have correct LF line endings (checked just now). I think you can close the issue.
