### ISSUE TITLE
Newly created production template is not visible

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4036]
A new production template has been created.

![Screenshot 1](https://user-images.githubusercontent.com/3040657/95457733-9a52bc80-0971-11eb-8193-2dce8b5d53e6.png)

Now go to the project and press the <kbd>+</kbd> button, the list for selecting the production templates appears, but the newly created one is not there. (I need to reload the page.)

![Screenshot 2](https://user-images.githubusercontent.com/3040657/95457887-c2dab680-0971-11eb-943b-1e23c1eb2fc4.png)

**Goal:** The list should be up to date.

**Comment by solth** [comment]
Unable to reproduce this error. 
Are you sure you selected the project (checked the checkbox) when creating the new template?

**Comment by matthias-ronge** [comment]
The checkbox was checked. However, I can confirm that it typically does **not** happen. So I close this ticket.

It looks like this is a side effect when you first trigger bug #4035, then click cancel, then create production template.
