### ISSUE TITLE
Empty line in drop down menu

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4050]
### Problem
In the drop down menus for creation pf the process, in some cases, empty lines are contained. 
In HTML, it looks like: 
- `<option value="" selected="selected" data-escape="true">`

### Solution
The empty line should not be contained and the preset value should be "Keine Auswahl", except if: 
- another preset value is defined in the ruleset
- the value is recognized automatically by the import XSL

#### Configuration ruleset
``` xml
        <key id="slub_ownerOrig">
            <label>owner of source (corporation)</label>
            <label lang="de">Besitzer der Vorlage (Körperschaft)</label>
            <option value="Bach-Archiv Leipzig"/><!-- DE-L326 -->
            <option value="Christian-Weise-Bibliothek Zittau"/><!-- DE-124 -->
            <option value="Deutsches Stuhlbaumuseum Rabenau"/><!-- DE-MUS-859718 -->
            <option value="Ev.-Luth. Kirchgemeinde Pirna"/><!-- keine ISIL vorhanden -->
            .....
        </key>
        ....
        <key id="slub_script">
            <label>Script Type</label>
            <label lang="de">Schrifttyp</label>
            <option value="Fraktur">
                <label>Fraktur</label>
            </option>
            <option value="Antiqua">
                <label>Antiqua</label>
            </option>
            <option value="keine_OCR">
                <label>keine OCR</label>
            </option>
        </key>
        ....
        <key id="LegalNoteAndTermsOfUse">
            <label>legal note / terms of use</label>
            <label lang="de">Rechtehinweis / Nutzungshinweis</label>
            <option value="CC01.0"><label>CC0 1.0</label></option>
            <option value="CCBYSA4.0"><label>CC BY-SA 4.0</label></option>
            <option value="FZRV1.0INC1.0"><label>Freier Zugang - Rechte vorbehalten + Urheberrechtsschutz 1.0</label></option>
            <option value="FZRV1.0"><label>Freier Zugang - Rechte vorbehalten 1.0</label></option>
            <option value="INC1.0"><label>In Copyright 1.0</label></option>
            <option value="PDM1.0"><label>PDM 1.0</label></option>
            <option value="TODR1.0"><label>Totengedenkbuch Dresden 1.0</label></option>
            <option value="VW1.0"><label>Vergriffene Werke 1.0</label></option>
        </key>
```

#### Empty line in the list. 
![dropdown01](https://user-images.githubusercontent.com/14835770/95849540-e629ab00-0d4f-11eb-8734-ac97cce12f5b.jpg)

#### Missing text: "Keine Auswahl"
![dropdown02](https://user-images.githubusercontent.com/14835770/95849547-e9249b80-0d4f-11eb-86b0-fa8bc14d8ad3.jpg)

#### Text: "Keine Auswahl"
![dropdown03](https://user-images.githubusercontent.com/14835770/95849552-ec1f8c00-0d4f-11eb-889c-6d6c71e8204a.jpg)

#### Text: "Keine Auswahl"
![dropdown04](https://user-images.githubusercontent.com/14835770/95850528-40773b80-0d51-11eb-856b-e4d9e3aec31c.jpg)

**Comment by matthias-ronge** [comment]
A single-select-type metadata which is optional has two non-selection options, one added by the frontend (labelled “no selection”) and one generated by the ruleset management (empty).

![2x](https://user-images.githubusercontent.com/3040657/97441844-74458a00-1929-11eb-8ab5-bd3f9b1a9faa.png)

**Goal:** Empty entry should be removed.
