### ISSUE TITLE
Unable to save boolean metadata in metadata editor

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#4051]
In the current version of the master branch (commit faeecab9f629ae96a966d590cf93ab265fc944f3) it is impossible to save boolean metadata - e.g. "activating" the corresponding "switch" -  in the metadata editor if it isn't already "checked". 

I have a metadata key in the ruleset configured like this:
```
<key id="testBooleanMetadata">
    <label>TestBooleanMetadata</label>
    <codomain type="boolean"/>
</key>
```
and a corresponding restriction on a `division` like this:
```
<restriction division="testDivision" unspecified="forbidden">
      <permit key="testBooleanMetadata" maxOccurs="1" minOccurs="1"/>
</restriction>
```

Unchecking the resulting checkbox in the metadata table of the metadata editor works and can be saved to the `meta.xml` file. However, setting the checkbox to "checked" again afterwards cannot be saved. (tried without `minOccurs="1"` and adding the metadata via the "+" button as well).

Presumably this is caused by the current implementation not distinguishing between a boolean metadata missing from the metadata file (e.g. "Unknown state") and the metadata value being set to `false` explicitely ("unchecking" a checkbox and saving the process in the editor results in the whole `kitodo:metadata` entry being remove from the corresponding `dmdSec` in the METS file). 

@matthias-ronge do I need to configure something else to make this work? Or can you confirm that this is working as intended in the mentioned commit?

**Comment by matthias-ronge** [comment]
You `<key>` definition is missing a value, so setting the switch to true does save an empty metadata entry, which is not written and thus forgotten. It should look somewhat like this

```xml
<key id="testBooleanMetadata">
    <label>TestBooleanMetadata</label>
    <codomain type="boolean"/>
    <option value="TestValue"/>
</key>
```

Besides that, `minOccurs="1"` will be equal to always-true with `<codomain type="boolean"/>` at time of validation. I cannot imagine a constellation where this combination makes real sense, but maybe there is. Maybe what you wanted is `<setting key="testBooleanMetadata" alwaysShowing="true"/>`?

Suggested **goal:** Extend `ruleset.xsd` that a `<key>` with a `<codomain type="boolean"/>` must contain exactly one `<option value="…"/>`.

**Comment by solth** [comment]
I removed the `minOccurs="1"`, added an option with a value and `<setting key="testBooleanMetadata" alwaysShowing="true"/>`- and it still does not work - switching betwenn selected structure elements resets the value and I cannot reliably set it to a specific value.

@matthias-ronge could you please verify it works as intended in the current master?

**Comment by matthias-ronge** [comment]
I can confirm the bug. The reason seems to be that `ProcessBooleanMetadata.setActive(boolean active)` is never called.
