### ISSUE TITLE
Buttons next to metadata textareas vertically offset

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#4053]
The `delete` and `duplicate` buttons next to metadata fields rendered as html `textarea` elements are vertically offset. 

<img width="280" alt="Bildschirmfoto 2020-10-14 um 10 34 52" src="https://user-images.githubusercontent.com/19183925/95967013-10d93980-0e0c-11eb-9832-2cf0a3c49f54.png">

("Haupttitel" and "Haupttitel (Sortierung)" are rendered as `textarea` while "TSL/ATS" is rendered as `input` where the problem does not occur)

**Comment by solth** [comment]
This seems to be caused by `<p:inputTextarea>` not embedding the input element (`textarea`) inside a wrapper elment with the CSS class `ui-inputfield` - as is the case with most of the other PrimeFaces input element, apparently - but rather just as the `textarea` which receives the `ui-inputfield` class itself.

**Comment by matthias-ronge** [comment]
If these are ̀ textarea` elements, then they are too small (vertically). The whole point of being able to switch between single-line and multi-line text fields is that you have more space in the field (e.g. if you have to write an abstract in it). 4-5 lines of text should be visible at least.

**Comment by solth** [comment]
The textareas dynamically "expand" to the required height once a new line break occurs, so that part works and the whole text is visible. 
The issue I described had only to do with the positioning of the buttons next to the textarea.
