### ISSUE TITLE
Long responding time after saving of changes in project settings

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4059]
### Problem
Saving of changes in the project and redirection to the list takes a long time. The green button "You will be redirected after successful save." is shown, but only after a while, you get redirected to the project list. In that time, it is possible to work on some other elements like Folder use. 
In that time, a ring is circling besides the mouse cursor, indicating, that something is working in the background. 

### Solution
It should be analysed, if the time to save the project settings can be reduced.

**Comment by matthias-ronge** [comment]
The reason for this is that unnecessary things are happening here. Maybe among other things, the existence of all METS files of all processes belonging to the project is checked. There is a ticket for this, #3294.

I close this ticket as a duplicate.
