### ISSUE TITLE
Changes in "Sub-folders and METS file groups" cannot be saved

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4067]
### Problem
If in the project settings, the values in the "Sub-folders and METS file groups" are changed, the save-button does not turn blue and the changes cannot be saved. 
Only if values in "Folder use" or "METS parameter" are changed, the save-button turns blue and the changes can be saved. 

### Solution
It must be possible, that changes in "Sub-folders and METS file groups" can be directly changed.

**Comment by solth** [comment]
I cannot reproduce this error. Adding new folders and editing or removing existing folders all cause the "Save" button to be acitvated. 
@andre-hohmann can you try again and be more specific about which action doesn't activate the button?

**Comment by andre-hohmann** [comment]
It occurs when changes are conducted in the following fields. 
- Generate images
- Width / Scale / Resolution
- Link in METS file
- ...

If the following buttons are changed, the save-button turns blue: 
- Create empty folder on process creation
- Validate contents
- Copy on DMS export

Specifically, i wanted to change the width of the derivates and the save-button was not activated after the changes have been applied.

**Comment by solth** [comment]
Thanks for the clarification. I just tested it again with the additional information you provided and it seems the problem occurs in the preview branch, but is already fixed in the master branch.

**Comment by andre-hohmann** [comment]
Perfect - thank you. I will have a look on it after the next update of the preview system.

**Comment by matthias-ronge** [comment]
Related: #3346
