### ISSUE TITLE
Not filled DialogBox in Metadata-Editor "Validate" 

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4081]
Version used: 3.2.1-build 02.11.2020
If I press "Validate" in Metadata-Editor I get an empty dialog box like this (expected would be warning, that not all logical elements have a physical page assigned).
![error-validate](https://user-images.githubusercontent.com/61045115/97990969-04c81280-1de1-11eb-80a1-26cc4d3480b5.png)

**Comment by andre-hohmann** [comment]
The green dialog box is empty, too.

**Comment by Kathrin-Huber** [comment]
fixed by #4117
