### ISSUE TITLE
Not filled dialog box when pressing "Import to DMS"

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4082]
Version used: 3.2.1-build 02.11.2020
If I press "Import to DMS" in non-automatic export task I get an empty dialog box like this ("null"):
![error-null](https://user-images.githubusercontent.com/61045115/97991120-48228100-1de1-11eb-99c7-9841e7f99c50.png)
Maybe this is related to #4081

**Comment by matthias-ronge** [comment]
Maybe related to: #3420

**Comment by Kathrin-Huber** [comment]
fixed by #4117
