### ISSUE TITLE
Limitation of processes in the excel file (statistics) 

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4099]
### Problem
In the generated excel file, the amount of included processes seems to be limited to 1.000. 

### Solution
In the excel file, all retrieved processes should be included. 

See also: #3507.

**Comment by matthias-ronge** [comment]
I looked into the code but found no limiting. The processes are [fetched from the index](https://github.com/kitodo/kitodo-production/blob/faeecab9f629ae96a966d590cf93ab265fc944f3/Kitodo/src/main/java/org/kitodo/production/helper/SearchResultGeneration.java#L85). May this be an ElasticSerach limit?

**Comment by andre-hohmann** [comment]
As the reason for the limitation is the elastic search, i have opened a new issue: 
- #4331
