### ISSUE TITLE
Default sorting in list should be alphabetical by first column

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4101]
### Problem
The sorting of the lists of projects, users, ... is incomprehensible and useless with many entries in the list. 
Usually, the list is manually sorted by the first column. 

### Solution
The lists should be sorted by the first column: 

- Users: Username
- Projects: Titel
- ...

Related to: #3792

**Comment by andre-hohmann** [comment]
A search or filter option would be helpful, too - as described in: #3660.

**Comment by matthias-ronge** [comment]
Loosely related to #3295
