### ISSUE TITLE
Update Java (and maybe Tomcat) version 

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4106]
Java 8 has run out of support at the end of 2020. Current Java version at the time of writing is 14, or 11 LTS. Probably the Tomcat version also needs to be increased.

**Comment by henning-gerhardt** [comment]
For Tomcat update see https://github.com/kitodo/kitodo-production/pull/2929. Ignored since a long time :-(

**Comment by matthias-ronge** [comment]
I added the <kbd>security</kbd> badge because Java 8 is no longer receiving updates, so running Production on Java 8 must now be considered insecure.

**Comment by henning-gerhardt** [comment]
[Oracle stopped Java 8 public updates in January 2019 for commercial usage but indefinitely for personal usage](https://en.wikipedia.org/wiki/Java_8). Some forks like AdoptOpenJDK will provide support until May 2026. 

You can run 3.x on Java 11 but can not compile it as some build requirements are removed from OpenJDK 11 package.

**Comment by matthias-ronge** [comment]
I can confirm: Production 3 is running here on an Ubuntu 18 under OpenJDK 11. (I wasn't even aware of that.) [Redhat states](https://access.redhat.com/articles/1299013#OpenJDK_Lifecycle_Dates_and_RHEL_versions) the end of support for OpenJDK 11 for October 2024, for OpenJDK 8 even for May 2026. Those who are already using OpenJDK 11 would then have to carry out a version downgrade, with everything that means.

I'll leave the <kbd>security</kbd> label in place as a reminder that everyone here has to check which JVM version and update strategy the used distribution is using to ensure that this is secured.

**Comment by Kathrin-Huber** [comment]
is updated
