### ISSUE TITLE
Adjustments of the process list

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4121]
### Problem
The configuration of the process list is inconvenient: 
1. The column of "ID" is too narrow and long ID are not fully shown. The column "Duration" is quite wide, although it is not necessary. 
2. The lines of the columns to adjust the width are not shown. It needs to be detected with the mouse pointer. 
3. The processes are selected when a row is clicked and it is not possible to select and copy the content like for example the ID or process title. 

### Solution 
1. The columns' width should be adjusted according to its content. 
2. The columns' width should be clearly shown. 
3. The processes should only be selected, when the checkbox is activated. It should be possible to select and copy the ID, ... from the process list. 

### Examples
![configurecolums01](https://user-images.githubusercontent.com/14835770/101599114-80793880-39f9-11eb-9198-0adfdddba3a6.jpg)

**Comment by matthias-ronge** [comment]
1. See _ID column to short for big Ids_ #3738
2. See _Visual hint for resizable columns_ #3192
3. See _Process title cannot be selected to copy it_ #3578

**Comment by matthias-ronge** [comment]
Closed as duplicate
