### ISSUE TITLE
Change all table names to consist of lowercase letters only

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4130]
In MySQL, table names with uppercase letters cause problems when transferring a dump from Windows to Linux, see also issue  #3998. Production should be changed so that all table names only consist of lowercase letters to avoid this in the future.

We should include the point in the coding guidelines so that this doesn't happen again in the future.

**Comment by solth** [comment]
@matthias-ronge hasn't this been resolved by #4412 ?

**Comment by matthias-ronge** [comment]
Yes :)
