### ISSUE TITLE
User list: No distinction between enabled and disabled users

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#4140]
In 2.x there was an distinction between enabled and disabled users which is missing in 3.x if you have a large user base:

* disabled users was not displayed by default in the user list overview and you must switch them on to get displayed
* disabled users was a little bit other displayed by an other text color (light gray instead of black for enabled users)

**Comment by matthias-ronge** [comment]
Maybe it would also make sense to sort deactivated users to the end (see also #4101, #4129, #3295).

**Comment by henning-gerhardt** [comment]
No, please do not sort them to end of list. Users should be sorted by their names independent of they are enabled or not.

**Comment by andre-hohmann** [comment]
I agree with @henning-gerhardt. A different sorting of names will be irritating.

**Comment by matthias-ronge** [comment]
I had only meant the initial sort, assuming that me is still able to manually switch to alphabetical by clicking the header. If you always have 450 deactivated users from 11 former clients between the 7 active users, that's annoying, too. And as far as I know we don't have a way to hide them at the moment. If you can hide / show them with a switch, they can also appear in alphabetical order, I agree.
