### ISSUE TITLE
Improvement of the file imports layout

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4141]
### Problem
The file upload in 3.x (#4126) works, but the layout of the the new pages and buttons need some adjustments. 

#### Example 1 - Solved
<details>
  <summary>Solved: On the page to create the processes, the buttons should be in one row.</summary>

On the page to create the processes, the buttons should be in one row. 
<details>
  <summary>current state:</summary>

![fileImport01](https://user-images.githubusercontent.com/14835770/104151081-504bfd80-53dc-11eb-8e63-6bf91043bfdf.jpg)
</details>
<details>
  <summary>target state (draft):</summary>

![fileImport02](https://user-images.githubusercontent.com/14835770/104151086-5641de80-53dc-11eb-81c4-16be1b3ddcb9.jpg)
</details>
</details>

#### Example 2  - Solved
<details>
  <summary>Solved: On the page to select the catalogue for the file upload, the buttons are too close to the border and should be aligned according the page for the catalogue search.</summary>

On the page to select the catalogue for the file upload, the buttons are too close to the border and should be aligned according the page for the catalogue search. 
<details>
  <summary>current state:</summary>

![fileImport03](https://user-images.githubusercontent.com/14835770/104151244-cc464580-53dc-11eb-8db1-7e9912656588.jpg)
</details>
<details>
  <summary>target state (draft):</summary>

![fileImport04](https://user-images.githubusercontent.com/14835770/104151248-cea89f80-53dc-11eb-9878-15028bc2df5c.jpg)
</details>
</details>

#### Example 3
On the page to select the file for the file upload, the buttons are too close to the border and to each other. They should be aligned more conveniently. In addition, the button "chosseFile" needs another icon and a German name, for example: "Datei auswählen"
<details>
  <summary>current state:</summary>

![fileImport05](https://user-images.githubusercontent.com/14835770/104151659-e2083a80-53dd-11eb-9834-aeb6ed103afe.jpg)
</details>
<details>
  <summary>target state (draft):</summary>

![fileImport06](https://user-images.githubusercontent.com/14835770/104151665-e46a9480-53dd-11eb-8b06-ea3c23d6cd69.jpg)
</details>

**Comment by solth** [comment]
@andre-hohmann The first to examples should already be fixed, this most likely is just a caching problem of your browser. Try reloading the page after clearing your cache.

**Comment by andre-hohmann** [comment]
@solth : Thanks - Yes, it is fixed!
