### ISSUE TITLE
Database: Duplicate "property" n:m table?

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4151]
Hi,

if you have a look in the Kitodo-Database (version 3.2.1-build 14.01.2021) you can find, that there are two n:m "joining" tables for handling of properties.
![grafik](https://user-images.githubusercontent.com/61045115/105049990-8f79ee80-5a6d-11eb-9470-ab1e64681f22.png)
If you look in each of this n:m tables, they look the same having process_id and property_id:
![grafik](https://user-images.githubusercontent.com/61045115/105050090-b0dada80-5a6d-11eb-82a8-f211dfa377b6.png)
--> this looks like a duplicate, and maybe only one is used?
Please check.

**Comment by matthias-ronge** [comment]
There are even **three** crosstabs, `process_x_property` is the third one. This is a legacy from bygone days. The whole mess is explained in issue #3335.

Closed as duplicate.

**Comment by stefanCCS** [comment]
Many thanks for the explanation.
