### ISSUE TITLE
SafeFile need more override methods?

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#416]
As suggested by @stweil in #414 the `SafeFile` class could be extended for other methods than `toString()` only. @matthias-ronge did non found any explicit calls for `clone()`, `equals()`, `finalize()`, or `hashCode()` for this class.

This issue is primarily for discussion for best pratice / usage of such kind of classes like `SafeFile` class.

**Comment by henning-gerhardt** [comment]
I think: If it not hurts and makes no problems or better prevent any problems implement it. This methods are basic methods for any object / class. So there usage could be explicit and implicit at any time.

**Comment by matthias-ronge** [comment]
I agree that `equals()` and `hashCode()` would give incorrect results and should therefore be implemented.

I do not agree to `finalize()`. There are two reasons to do nothing: First, `finalize()` is called by the garbage collection on the object when it is destroyed. This will happen anyway, and should be left up to the garbage collection. Second, [implementing finalize is typically bad](https://howtodoinjava.com/java/basics/why-not-to-use-finalize-method-in-java/).

I also disagree with `clone()`, [implementing the clone interface](https://howtodoinjava.com/java/cloning/cloneable-interface-is-broken-in-java/) is a completely different thing and we don't need that here.
