### ISSUE TITLE
Export fails when using XSLT 2.0

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4167]
The export of a process fails if XSLT 2 is used in the XSLT file. The error message is: _Could not create XSLT transformer. Check /path/to/xslt-folder/ruleset_name.xsl for errors._

**Reason:** An attempt is being made to load the XSLT file with the built-in Xalan XSLT processor. Xalan does not support XSLT 2. (Which XSLT processor is used, depends on influences, such as in which order the library JARs are loaded. So it may happen that this error occurs, or it may not.)

**Workaround:** Add argument `-Djavax.xml.transform.TransformerFactory=net.sf.saxon.TransformerFactoryImpl` to `JAVA_OPTS` when starting Tomcat. **Note that this workout affects other webapps in the same Tomcat instance as well!** If you find a different webapp failing after this change, this is maybe because it tries to load Saxon where it used Xalan before, but cannot find the class (because it is not part of the JRE nor Tomcat). If this is the cause, you can fix it by copying Saxon-HE-9.9.1-5.jar from the WEB-INF/lib dir of Kitodo.Production to the WEB-INF/lib dir of the failing webapp.

**Goal:** Instead of the generic call to `TransformerFactory.newInstance()`, use `new TransformerFactoryImpl()` to instantiate a `net.sf.saxon.TransformerFactoryImpl` directly.

**Comment by Kathrin-Huber** [comment]
fixed by #4169
