### ISSUE TITLE
User-Configuration: Button "Write-LDAP" does not exists anymore

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4179]
Version used: 3.2.1-build 14.01.2021
In this version the Button for writing the LDAP-Entry in User-configuration does not exists anymore.
I am sure, that this button is available in official Release 3.2.

**Comment by matthias-ronge** [comment]
Missing annotations

    @Named("AuthenticationController")
    @RequestScoped

in `class DynamicAuthenticationProvider`
