### ISSUE TITLE
Check if any tasks are assigned to a user before deleting him

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#4184]
When a user is deleted who still has tasks assigned to him, the system does not unassign him from those tasks, leaving them in limbo until an admin or user with corresponding system privileges resets the tasks processing status from "IN WORK" to "OPEN".
To fix this, the system should check if any tasks are assigned to a user before deleting him and display a warning/confirmation dialog if that is the case. If the user confirms deleting the user, any tasks that are still assigned to this user should be set to "OPEN".

**Comment by matthias-ronge** [comment]
Can users be completely erased, or are they just put in tomb state?

Release of all tasks off a user should also be an independent function for admin, i.e. user-is-on-vacation function. All locks on processes of the user in the metadata editor are released. All of the user's tasks are set to pending open.

**Comment by solth** [comment]
At the moment it seems the user is not deleted from the database, but nearly all fields - apart from "id" - by which the user could be identified (`name`, `surname`, `login`, etc.) are set to `null` and therefore the user cannot be recovered. So I think its fair to say he es deleted (even if the database entry still exists in some anonymous form) and not just "deactivated" or something.

+1 one to your idea to allow admins to unassign all tasks in work and remove processes openend in the metadata editor from a user manually 👍

**Comment by henning-gerhardt** [comment]
Setting this values to ` null`  as historic reasons as it was not possible to delete the user from the database as the user was still referenced in many places in code and database. A clean user delete function was never implemented.

**Comment by solth** [comment]
Ok, thanks for the info. So it was never intended to "restore" a deleted user or something like that?

**Comment by henning-gerhardt** [comment]
According to the code: no. 

Maybe in-house usage was different as deleting users causes trouble (at least in older versions): a possible solution could be: change user password to some random value, remove all assigned projects and rights from the user and set this user to inactive. So the user with login name still exists, did not cause any trouble / issues in daily usage and the user can not log in anymore. If this user must be re-activated, then his old login can be re-activated.

**Comment by matthias-ronge** [comment]
> **Edit**: we should open another issue to implement a "clean" user delete function

This will not be easy as the user appears in many places, for example in correction comments. I think setting all table columns like name to `null` has been implemented for privacy reasons, but I have doubts that it will work everywhere. Quite possible that crashes when you want to display the comments history of a process. Has probably never been tested. It is also a question of whether that is wanted.
