### ISSUE TITLE
Metadata editor is slow to respond

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4196]
For a process with a large number of images, the metadata editor is sluggish. A yellow bar appears in the browser:

![A web page is slowing down](https://user-images.githubusercontent.com/3040657/108324685-809b6e80-71c8-11eb-8317-5d67f6b611bf.png)

Mark a series of 16 pictures with the mouse (click on the first picture, <kbd>Shift</kbd> + click on the last picture) the loading key symbol rotates for 4 minutes. It takes 3 minutes to move the images with the mouse.

![Long](https://user-images.githubusercontent.com/3040657/108324849-b7718480-71c8-11eb-956c-37179dd8ab00.png)

**Goal:** The speed of interaction must be improved.

**Comment by solth** [comment]
I just tried this with a process with over 400 pictures. 
These are the times I observed in my browser (Firefox) with > 200 open tabs and several other ressource hungry programs like IntelliJ or ElasticSearch running in the background:

- opening the process in the metadata editor: 5 seconds
- creating a new structure element: 3 seconds
- selecting > 50 thumbnails in the gallery: 2 seconds
- moving the selected thumbnails to the new strucutre element via drag'n'drop: ~ 15 seconds

(My browser did not display any warning that the current tab would slow things down.)
So moving a larger stack of images at once definitely takes some time, but is far away from the times you reported. All tested on a Kitodo.Production 3 installation on a server with fairly moderate hardware specifications.

Could it be you were testing locally and your system load was to high? Perhaps the debugger was running and many breakpoints decreased performance?

**Comment by matthias-ronge** [comment]
No, we tested on a server installation. As far as I can tell so far, two effects played a role:

1. the web browser was running on the same PC on which the video conference via MS Teams was running at the same time. Both require considerable resources. Starting the web browser in another machine via RDP makes the warning bar stay away. (Still, the fact that the browser needs so much resources is a lot.)
2. The process had well over 1000 images. Unfortunately, I have meanwhile deleted the process and no longer know how many there were. I think 1600 pictures. I was told: This is not unusual, and it has to be editable nonetheless. (I also know of processes with over 2000 images in Production 2, although I advise against it. It's also slower then, but it shouldn't be _that_ slow. )

**Comment by Kathrin-Huber** [comment]
@matthias-ronge can you confirm, that this is fixed with the newest release?

**Comment by andre-hohmann** [comment]
@matthias-ronge  : Is this still a problem, or has it been solved with the performance improvements by the following pull requests?

- https://github.com/kitodo/kitodo-production/pull/5095
- https://github.com/kitodo/kitodo-production/pull/5096
- https://github.com/kitodo/kitodo-production/pull/5113
- https://github.com/kitodo/kitodo-production/pull/5114
- https://github.com/kitodo/kitodo-production/pull/5115
- https://github.com/kitodo/kitodo-production/pull/5121

**Comment by matthias-ronge** [comment]
I didn’t see this message again with newer versions.
