### ISSUE TITLE
Confusing behavior when adding multiple divisions

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4197]
Open the dialog for adding divisions. Choose a type, then select the number of Count Docstructs.

![Screenshot 1](https://user-images.githubusercontent.com/3040657/108331369-fd314b80-71ce-11eb-9982-3fee42185b9f.png)

Enter a number, for example press <kbd>2</kbd><kbd>5</kbd>

![Screenshot 2](https://user-images.githubusercontent.com/3040657/108331939-8d6f9080-71cf-11eb-8c85-ad4b9ce6c2a0.png)

Click on “Apply”, more of the dialog appears for entering metadata:

![Screenshot 3](https://user-images.githubusercontent.com/3040657/108331992-99f3e900-71cf-11eb-8d8c-94d06ec64ee3.png)

Fill in a metadata entry to write, click “Apply” again. For a while, nothing seems to happen, then divisions are created, but metadata is not filled in.

**Workaround:** If you don’t type the number of divisions to create, but use the mouse to click the up arrow on the right side of the Count Docstructs input, the procedure works as intended.

**Goal:** Also write metadata if Apply needs to be clicked to reveal the rest of the dialog. Better: Show metadata dialog part as soon as a number is typed in. Simple solution: Show metadata input always. There is nothing wrong about having the ability to input a metadata entry on the spot even if only one division is created.

**Comment by IkramMaalej** [comment]
Retested. Issue could not be reproduced with current version of Master.
