### ISSUE TITLE
Allow updating title showing in the structure map tree

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4201]
In the structure map tree, the main title of the division is displayed after the type. However, this display is not updated after editing a division.

**Workaround:** is to create a new division and delete it again to see current state of document.

**Goal:** It should be possible to update the structure map tree, at least with a button (or better automatically). For example, when saving the document.

**Comment by solth** [comment]
Maybe a duplicate of #3501

**Comment by matthias-ronge** [comment]
Closed as duplicate
