### ISSUE TITLE
The list of types is initially empty when adding divisions

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4203]
When creating new divisions, the type menu is often empty initially. You have to put position to something else, and then back, for it to have options.

![Screenshot](https://user-images.githubusercontent.com/3040657/108337279-3ff62200-71d5-11eb-830c-a3fbacde63cb.png)

**Goal:** The allowed options should be displayed immediately.

**Comment by IkramMaalej** [comment]
The steps to reproduce this issue: 
1- add a new doc struct to any node in structure data tree except root node with one of this two positions (After current element or before current element)
2- try to add a new doc struct to the root node. here is the the type menu is initially empty.
