### ISSUE TITLE
Capture of METS-attributes LABEL and ORDERLABEL

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4205]
### Problem
In Kitodo.Production 2.x, the METS-attributes `@LABEL` and `@ORDERLABEL` for the document types and structure elements in `<mets:structMap TYPE="LOGICAL">` are created during the export with the values of the MODS-elements "title" and "title (sorting)". 
In Kitodo.Production 3.x, the METS-attributes are defined separately in the ruleset and values must be captured additionally to "title" and "title (sorting)". 

```
<key id="LABEL" domain="mets:div">
    <label>Haupttitel ‹METS›</label>
</key>
<key id="ORDERLABEL" domain="mets:div">
    <label>Haupttitel (Sortierung) ‹METS›</label>
</key>
```

For the level of the document types the METS-attributes can be captured automatically by configuration of the import-XSLT.
For the level of captured structure elements, the values must be actually captured twice manually.

Additionally, it must be regarded during the migration of the metadata, because the METS-attributes are not contained in the internal METS-file in Kitodo.Production 2.x. 

The values of the METS-attributes `@LABEL` are used in presentation systems for the display of the title in table of contents, ...

### Question
Is there any approach to optimize the capture of the values of the METS-attributes? It is difficult to explain users the capture of duplicate values.

**Comment by matthias-ronge** [comment]
A good explanation is: Because they are two different things. The labels of divisions (as they are displayed in the DFG viewer) and the metadata that describe the divisions are basically two different things. It is actually the case that these are often the same rather by chance. Basically using the title here led to a lot of semantically incorrect metadata in Production 2. A title is something very specific (in Germany, for example, it is a product label and is subject to [legal protection](https://de.wikipedia.org/wiki/Titelschutz)) and to speak of a title when describing a photo or a table is semantically incorrect.

You can make this clearer by changing the description:

```xml
<key id="LABEL" domain="mets:div">
    <label>Bezeichnung (Gliederungsanzeige)</label>
</key>
<key id="ORDERLABEL" domain="mets:div">
    <label>Ordnungswert (Gliederungsanzeige)</label>
</key>
```

Note that both values **are optional** in current [METS-Anwendungsprofil](https://dfg-viewer.de/fileadmin/groups/dfgviewer/METS-Anwendungsprofil_2.3.1.pdf#page=9).

**Comment by andre-hohmann** [comment]
I agree, that in some cases, a separation of the elements is correct. However, i have the impression, that the values of the elements are often the same or quite similar. It is difficult to explain, that the same values have to be captured twice. 

The METS-attributes are optional, but: 
> Das Attribut `LABEL` kann eine Bezeichnung enthalten, unter der das Strukturelement in der Navigation des DFG-Viewers
> erscheinen soll. Wird kein `LABEL` angegeben, erscheint dort der Strukturtyp. 
> Das Attribut `ORDERLABEL` kann einen Ordnungswert wie z.B. eine Bandzählung enthalten, die in der Navigation des DFG-Viewers erscheinen soll.

I assume that most users expect the captured title of structure elements in the navigation (table of content, structure tree, ...) and not the formal title of the structure element itself. I can also imagine, that order values are used in some presentation systems. 

The most flexible solution seems to be the configuration of the export XSLT. Every user could then decide, which elements are regarded - maybe depending on the document or structure type. 
However, it is difficult to realize this by XSLT, because of the relations of the METS-Elements `<mets:dmdSec>` and `<mets:structMap TYPE="LOGICAL">` by the attribute `@DMDID`.

**Comment by andre-hohmann** [comment]
Roughly, it can be realized by the following XSLT. 
To everyone who applies it: **please check, before using it!** The XSLT has not yet been tested extensively. 

```xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 * This file is part of the Kitodo project.
 * It is licensed under GNU General Public License version 3 or later.
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
-->
    <xsl:stylesheet version="2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:mets="http://www.loc.gov/METS/"
                xmlns:mods="http://www.loc.gov/mods/v3"
                xmlns:kitodo="http://meta.kitodo.org/v1/"
                xmlns:xlink="http://www.w3.org/1999/xlink">
    <xsl:output method="xml" indent="yes" encoding="UTF-8"/>
    <xsl:strip-space elements="*"/>

    <!-- Transorm structure element -->
     <xsl:template match="@DMDID">
        <xsl:variable name="dmSecId" select="."/>
        <xsl:variable name="TitleDocMain" select="/mets:mets/mets:dmdSec[@ID=$dmSecId]/mets:mdWrap/mets:xmlData/kitodo:kitodo/kitodo:metadata[@name='TitleDocMain']"/>
        <xsl:variable name="TitleDocMainShort" select="/mets:mets/mets:dmdSec[@ID=$dmSecId]/mets:mdWrap/mets:xmlData/kitodo:kitodo/kitodo:metadata[@name='TitleDocMainShort']"/>
        <xsl:variable name="CurrentNoSorting" select="/mets:mets/mets:dmdSec[@ID=$dmSecId]/mets:mdWrap/mets:xmlData/kitodo:kitodo/kitodo:metadata[@name='CurrentNoSorting']"/>
        <xsl:if test="$TitleDocMain !=''">
            <xsl:attribute name="LABEL">
               <xsl:value-of select="/mets:mets/mets:dmdSec[@ID=$dmSecId]/mets:mdWrap/mets:xmlData/kitodo:kitodo/kitodo:metadata[@name='TitleDocMain']"/>
            </xsl:attribute>
        </xsl:if>
        <xsl:if test="$TitleDocMainShort !=''">
            <xsl:attribute name="ORDERLABEL">
               <xsl:value-of select="/mets:mets/mets:dmdSec[@ID=$dmSecId]/mets:mdWrap/mets:xmlData/kitodo:kitodo/kitodo:metadata[@name='TitleDocMainShort']"/>
            </xsl:attribute>
        </xsl:if>
        <xsl:if test="not($TitleDocMainShort) and $TitleDocMain !=''">
            <xsl:attribute name="ORDERLABEL">
               <xsl:value-of select="/mets:mets/mets:dmdSec[@ID=$dmSecId]/mets:mdWrap/mets:xmlData/kitodo:kitodo/kitodo:metadata[@name='TitleDocMain']"/>
            </xsl:attribute>
        </xsl:if>
        <xsl:if test="$CurrentNoSorting !=''">
            <xsl:attribute name="ORDER">
               <xsl:value-of select="/mets:mets/mets:dmdSec[@ID=$dmSecId]/mets:mdWrap/mets:xmlData/kitodo:kitodo/kitodo:metadata[@name='CurrentNoSorting']"/>
            </xsl:attribute>
        </xsl:if>
    </xsl:template>

    <xsl:template match="@* | node()">
        <xsl:copy>
            <xsl:apply-templates select="@* | node()"/>
        </xsl:copy>
    </xsl:template>

</xsl:stylesheet>
```
