### ISSUE TITLE
Missing mouse menu in metadata editor

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4212]
![Screenshot](https://user-images.githubusercontent.com/3040657/109181317-149ea480-778c-11eb-98c1-176942a2d6da.PNG)

I selected a value (here, the PPN) and wanted to copy it to the clipboard, by clicking the secondary (right) mouse button and selecting „Copy“, but clicking the secondary mouse button does not open the menu. Nothing happens

**Goal:** Enable mouse menu

**Comment by solth** [comment]
The default behavior of the right click event is disabled in the metadata editor because it has its own custom context menu. You can still use keyboard shortcuts to copy and paste selected text, though (`CTRL` + `C` and `CTRL` + `V` respectively)

**Comment by matthias-ronge** [comment]
It's true that it works, but can't the menu for text fields be allowed again anyway?

**Comment by solth** [comment]
> It's true that it works, but can't the menu for text fields be allowed again anyway?

@oliver-stoehr is more qualified to answer that question, I think.

**Comment by oliver-stoehr** [comment]
Yes, it should be possible to enable it for certain elements again. I think we should enable this only for text fields and text areas to keep the browser's default context menu and the structure trees' and gallery's context menu separated as clearly as possible.
