### ISSUE TITLE
Wrong report of missing ORDERLABEL in ruleset

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4253]
The metadata editor reports the `ORDERLABEL` as missing in the ruleset even though it is properly declared:

![Screenshot 2021-03-05 143054](https://user-images.githubusercontent.com/3040657/110122120-8051c480-7dbf-11eb-8652-4d957b3044db.png)

![Screenshot 2021-03-05 143115](https://user-images.githubusercontent.com/3040657/110122137-82b41e80-7dbf-11eb-80d1-fca89678b468.png)

**Goal:** Do not show bogus error

**Comment by andre-hohmann** [comment]
@matthias-ronge : Is the wrong report of missing `ORDERLABEL` still happening?

**Comment by matthias-ronge** [comment]
I have to try that. The error occurred at a customer. Is there any reason you suspect this has changed?

**Comment by andre-hohmann** [comment]
There is no specific reason that it has changed. 
We use ORDERLABEL, too, and we have no problems. I just thought the problem might be solved and it has been forgotten that this issue exists.

**Comment by matthias-ronge** [comment]
I will test this again

**Comment by matthias-ronge** [comment]
I cannot reproduce this issue. I'm closing this one as not (anymore) reproducible. It may be reopened if the issue is observed again.
