### ISSUE TITLE
[Solved] Missing mass process creation

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4260]
There is no way to automatically create a lot of processes (random items like monographs, not newspaper issues) empty (process title just counted) or with database key and data import (fully automatic).

**Goal:** Add mass process creation / mass import

**Comment by henning-gerhardt** [comment]
Did you not found the mass import function? @Kathrin-Huber works a lot of time to implement this.

**Comment by matthias-ronge** [comment]
No, where is it and how is it started?

**Comment by henning-gerhardt** [comment]
Maybe wait for a answer from @Kathrin-Huber or look into merged pull requests
* #3290
* #3399 
* #3840

**Comment by solth** [comment]
It is this button in the project list:

<img width="208" alt="mass-import-action" src="https://user-images.githubusercontent.com/19183925/110317690-c94a8880-800c-11eb-97be-a66da37d31cd.png">

**Comment by matthias-ronge** [comment]
I've never noticed that before. Thank you!

**Comment by Kathrin-Huber** [comment]
Is fixed
