### ISSUE TITLE
Hierarchy migration: Higher-level processes with workflow

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4268]
### Problem 
After the the migration of serial publications (hierarchy migration), a workflow is assigned to the created processes for the toplevel-processes, as for example: periodical, multivolume, ... 

### Solution
During the migration of serial publications (hierarchy migration), no workflow should be assigned to the toplevel-processes. 

See also: #3307, #4267, #4269, #4270, #4271

### Example
![hierarchy_processes](https://user-images.githubusercontent.com/14835770/110930248-2ace6800-8329-11eb-97db-a4aa151871b3.jpg)

**Comment by matthias-ronge** [comment]
See also #3190
