### ISSUE TITLE
Hierarchy migration: toplevel-processes without properties

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4271]
### Problem
After the migration of serial publications (hierarchy migration), the created processes for the toplevel-processes, as for example: periodical, multivolume, ... have no properties (template properties, workpiece properties, ...). 

The processes of PeriodicalVolume and Monograph have these properties after the migration. 

### Solution
The toplevel-processes should have properties after the migration, like the other processes. 

See also: #4267, #4268, #4269, #4270

**Comment by henning-gerhardt** [comment]
Just guessing: this new top level hierarchy processes are created in an other way at hierarchy migration then normal top level hierarchy processes by import. So this information needed for properties are  not existing and can not be added on migration. Question still remain: from where should this property data come? Maybe even this properties are not needed any more and should be removed - see comments in #3482 .

**Comment by andre-hohmann** [comment]
Maybe it is then not a bug. 
However, it should be clear to everyone, that there is different content in the properties of toplevel-processes, ..., which could lead to incomplete queries. The toplevel-processes which are created in Kitodo.Production have at least workpiece properties.

**Comment by matthias-ronge** [comment]
In version 3, properties are considered eliminated. They still exist internally because they are used in the Switzerland project, so they could not be removed yet. However, they should be removed as far as possible. Instead, the corresponding metadata should be displayed or changed here. See #3156 and #3335

**Comment by andre-hohmann** [comment]
I close the issue, because it turned out that the initial declared bug is not a bug. 
I add the "documentation" label in case of similar questions.
