### ISSUE TITLE
Hierarchy migration: duplication of firstlevel document type

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4293]
### Problem
The firstlevel document type, (Volume, PeriodicalVolume) is duplicated during the migration. Both the toplevel and firstchild document type cannot be edited in the metadata editor. 

### Solution
The duplicated firstlevel document type should not be duplicated. 

#### Periodical - migrated - id:347471
Periodical
```xml
    <mets:structMap TYPE="LOGICAL">
        <mets:div ID="LOG_0000" DMDID="uuid-017a6d80-fde9-3445-a239-bc86ba0c9f14" TYPE="Periodical" ORDER="1" ORDERLABEL="Examina solemnia Gymnasii Francofurtensis jussu et auctoritate summe venerandi consistorii Aug. Conf. ... publice celebranda ea qua decet pietate et observantia indicit" LABEL="Examina solemnia Gymnasii Francofurtensis jussu et auctoritate summe venerandi consistorii Aug. Conf. ... publice celebranda ea qua decet pietate et observantia indicit">
            <mets:div ID="LOG_0001" TYPE="PeriodicalVolume" ORDER="1">
                <mets:mptr xlink:href="database://?process.id=347471" LOCTYPE="OTHER" OTHERLOCTYPE="Kitodo.Production"/>
            </mets:div>
        </mets:div>
    </mets:structMap>
```
PeriodicalVolume
```xml
    <mets:structMap TYPE="LOGICAL">
        <mets:div ID="LOG_0003" DMDID="uuid-76157dfe-172d-3087-9203-6ae6809c2cb5" TYPE="PeriodicalVolume" ORDER="18370000">
            <mets:div ID="LOG_0004" TYPE="TitlePage" ORDER="18370000"/>
            <mets:div ID="LOG_0005" DMDID="uuid-5550ea93-b326-37ec-ab29-afd2c43a7ecf" TYPE="Article" ORDER="18370000"/>
            <mets:div ID="LOG_0006" DMDID="uuid-08f3c7fb-7fd6-33f9-a282-531781923e9d" TYPE="OtherDocStrct" ORDER="18370000"/>
            <mets:div ID="LOG_0007" DMDID="uuid-c0f27d42-d114-3d6c-895a-8bfb6b5f6154" TYPE="OtherDocStrct" ORDER="18370000"/>
            <mets:div ID="LOG_0008" DMDID="uuid-04c693c1-bb12-3fab-872e-1842420d7777" TYPE="OtherDocStrct" ORDER="18370000"/>
        </mets:div>
    </mets:structMap>
```
#### Periodical - new - id:347471
Periodical
```xml
    <mets:structMap TYPE="LOGICAL">
        <mets:div ID="uuid-b884b64c-a93d-419b-9d8a-02f4acd2e7f0" DMDID="uuid-f0766b0b-c702-37d6-b92b-4e70105c2f45" TYPE="Periodical" ORDER="1" ORDERLABEL="Programm des K.K. Staats-Gymnasiums in Cilli" LABEL="Programm des K.K. Staats-Gymnasiums in Cilli">
            <mets:div ID="uuid-9e2f3698-850c-4185-84a7-d4c1874cec4d">
                <mets:mptr xlink:href="database://?process.id=435656" LOCTYPE="OTHER" OTHERLOCTYPE="Kitodo.Production"/>
            </mets:div>
        </mets:div>
    </mets:structMap>
```

PeriodicalVolume
```xml
    <mets:structMap TYPE="LOGICAL">
        <mets:div ID="uuid-1a60ef0e-9f27-44e2-ab19-607f13a0aae6" DMDID="uuid-fb9e40a6-e9aa-3c51-8c69-da72f966b4e9" TYPE="PeriodicalVolume" ORDER="1">
            <mets:div ID="uuid-97ef51eb-1cf9-4ba1-a6a9-886f287139fa" TYPE="cover_front" ORDER="1"/>
            <mets:div ID="uuid-dd6392d9-8be1-4d7f-9bf2-91cba2042971" TYPE="TitlePage" ORDER="2"/>
        </mets:div>
    </mets:structMap>
```

#### Multivolume - migrated - id:343714
![hierarchie01](https://user-images.githubusercontent.com/14835770/111948796-ff453d80-8adf-11eb-8e36-2a7344759bea.jpg)

#### Periodical - migrated - id:347471
![hierarchie02](https://user-images.githubusercontent.com/14835770/111948873-1126e080-8ae0-11eb-9d23-d65d0f1dd644.jpg)

#### Multivolume - new - id:435656
![hierarchie11](https://user-images.githubusercontent.com/14835770/111948892-171cc180-8ae0-11eb-880a-f2bd18da2531.jpg)

#### Periodical - new - id:435654
![hierarchie10](https://user-images.githubusercontent.com/14835770/111948904-18e68500-8ae0-11eb-8d34-595b0cbab389.jpg)

**Comment by matthias-ronge** [comment]
That could be a misunderstanding. What you have framed in red is the information on the parenting that the Metadata Editor is displaying. It is shown for information only. (You can't edit it there, but you can look at it so that you can see what "volume" belongs to).

**Comment by andre-hohmann** [comment]
In the first two examples, the elements "Band" and "Zeitschriften-Band" are displayed twice. One element can be edited, the other one not. These examples are migrated. 
In the last two examples, the elements "Band" and "Zeitschriften-Band" are displayed once. These examples are created directly in Kitodo.Production 3.x. 

All examples are showing a "firstchild"-element. I am irritated, that there are two variants and i think, that the last two examples are correct. Maybe it depends on the general problems during the migration of processes with hierarchies.

**Comment by matthias-ronge** [comment]
Now I understand. The difference at the METS level is that in the migrated periodical, the inner `<div>` has a `TYPE` attribute (and is then also displayed, with the type). For the newly created periodical, the inner `<div>` has no `TYPE` (which is actually correct, because it is only the container for the link, the `PeriodicalVolume` is in the child process).

The solution is, when migrating, when generating the superordinate process, not to set a `TYPE` for the elements with the links.

**Comment by matthias-ronge** [comment]
It works a little differently: The old anchor file is used (and converted) as a METS file for the parent process. The `TYPE` for the child is already included in this. So it has to be **deleted** there.
