### ISSUE TITLE
Improvement for processcreation by configurable import wizards

### ISSUE THREAD

**Issue by subhhwendt** [kitodo/kitodo-production#4322]
The idea is to analyze for these different starting points the specific requirements and support by smart and configurable wizards instead of switching between tabs 

- catalogue import of monographs, multivolume Works, periodicals and newspapers for a chosen project
- adding periodical volumes from the process list
- adding newspaper issues by the calendar functionality connected to a chosen newspaper title
- adding processes by file upload
- adding processes by mass import (with extended possibilities for ingest of individual values for metadata fields like CurrentNoSorting or NumberProcessTitle independent from catalogue import)
 
It should be configurable
-  which fields are derived form the parent process in case of hierarchical structures (e.g. docLanguage, CatalogIDDigital, Collection)
- which fields are shown for expected input or for control
 
**To Do**

- [ ] development of an import wizard for **catalogue import** -  after review of all dependencies, metadata requirements and expected choices
- [ ] development of a wizard for processcreation for **periodical volumes** - after review of all dependencies, metadata requirements and expected choices
- [ ] development of a wizard for creation of **newspaper issues** - after review of all dependencies, metadata requirements and expected choices
- [ ] development of a wizard for processcreation by **fileupload** - after review of all dependencies, metadata requirements and expected choices
- [ ] devolopment of a wizard for processcreation by **massimport**
- [ ] Documentation of all configuration issues in the perspective of processcreation

**Estimated Cost and Complexity**

This will be a complex project for about 20 PT.

**Comment by andre-hohmann** [comment]
The following issues might be related to this proposal. They could be closed, if they fit into the concept and are could be solved. 

- #3407
- #3408 (https://github.com/kitodo/kitodo-production/issues/3408#issuecomment-804003220)
- #3463
- #3561
- #3593
- #3970
- #3974

**Comment by matthias-ronge** [comment]
Another way of process creation is mass process creation with a counter, which for example is used for stocks which are not yet cataloged at all. In this mode of operation, first processes are created, that only consist of a shelf code and a sequential number. Dockets are printed and the elements of the shelf are first digitized and later cataloged. Processes that are not used at the end of the shelf are deleted later.

**Comment by matthias-ronge** [comment]
First of all, in the list of variants above, the “simple” creation of a process is missing, of course. That is: select DocType, fill in metadata fields, generate process title, done.

In addition, there was also the option in Production 2 to define a process as a template (checkbox “show in selection list”) and then to create a process as a copy of this process. I just wanted to mention it for the sake of completeness.

**Comment by stweil** [comment]
It looks like there are several open issues like the one here (others also for Kitodo.Presentation) which were marked for funding in 2021, but not 2022 und 2023. I'd expect that such issues are either no longer relevant (and should be closed), or already addressed by someone who is working on them (then some note would be good), or they are still relevant and should be part of the current funding process, too.
