### ISSUE TITLE
Process title can be assigned multiple times

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4335]
In Production 2, it was not possible to assign the same process title multiple times. Instead, an error message appeared and you had to change the process title.

**Goal:** The same should happen in Production 3. For consistency, it should only check the existence of a process title within the same client.

**Comment by henning-gerhardt** [comment]
> In Production 2, it was not possible to assign the same process title multiple times. Instead, an error message appeared and you had to change the process title.

This is only true on creating new processes. If you rename an existing process to a title which is assigned to an other process, then no error message appear.
