### ISSUE TITLE
Newspaper calendar function - blocks for different years generate wrong processes

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4363]
Using version 3.2.1-build 24.03.21
**Also, if official Release 3.3!**

If in the newspaper calendar function blocks for different years are used like this:
![grafik](https://user-images.githubusercontent.com/61045115/116376454-90f74780-a810-11eb-9506-0e06e28a9f6e.png)

--> the generated processes are created partly with wrong "years":
![grafik](https://user-images.githubusercontent.com/61045115/116376523-a3718100-a810-11eb-898d-324e718b7e13.png)

==>  Possible workaround: create only blocks/processes for same year --> this is **NOT** possible!

**Comment by stefanCCS** [comment]
This happens also, if only one block is used, which has a timeframe for more than one year.

**Comment by stefanCCS** [comment]
**It is even worse :-(**

Even, if you create independently - one after the other - a block per year, the process generation behaves wrong, and only creates processes for one year!

**Comment by stefanCCS** [comment]
A small good news:
The meta.xml of the "year" process (number 64 of above) looks ok:
![grafik](https://user-images.githubusercontent.com/61045115/116382748-8770de00-a816-11eb-8a59-54b679493320.png)

-> so, maybe "only" the process naming creation works wrong.

**Comment by Kathrin-Huber** [comment]
@stefanCCS A lot has happend in newspaper creation. Can you check if this is still a problem?

**Comment by stefanCCS** [comment]
Hi @solth @Kathrin-Huber ,

I have checked it again, and it looks like there is still something wrong.

I have created this sub processes via calendar function (2 newspaper issues for year 2021, 2 for year 2022):
![image](https://user-images.githubusercontent.com/61045115/179197528-9aaba516-b994-438c-af4b-1dec610847bb.png)

The resulting naming for the "year-processes" and "issue-processes" is:
All named "2022" (and not as expected "2021" and "2022".
![image](https://user-images.githubusercontent.com/61045115/179198109-889d70b2-3697-4ecd-b4b6-515cdced3fb2.png)

**Comment by stefanCCS** [comment]
And even more strange:
If I just create one episode in 2021 --> all named with 2022!
![image](https://user-images.githubusercontent.com/61045115/179198545-604fb88b-7819-4e59-a1bc-7751ad7b329e.png)

**Comment by stefanCCS** [comment]
Checked this with Release 3.5.0-beta. Looks ok now.
Will close this issue.
