### ISSUE TITLE
Delete option for structure elements requires a check of linked pages to more than one structure element

### ISSUE THREAD

**Issue by subhhwendt** [kitodo/kitodo-production#4367]
The user should be advised to delete at first the special link(s) for this kind of page. Otherwise a confusing state in the area of unstructured pages is caused.

**Comment by matthias-ronge** [comment]
The links are actually just pictures that are assigned to several divisions / structural elements. Actually, you shouldn't have to delete them. So if an image is deleted that is still assigned to another division / structural element, it should not appear under "unassigned pages". I rather think that's the problem.

**Comment by solth** [comment]
If I remember correctly, we found some conceptional ambiguity when deleting a structure element that contains sub structures with linked pages, but I do not remember the specific problem. @subhhwendt could you elaborate on the issue? Do you remember the details?

**Comment by subhhwendt** [comment]
We tested together today and figured out that's not necessary to involve user action as suggested in my issue. The function for deleting structure elements should check by default the state of linked pages for the first and last page of the chosen element/division  und delete this connection at first.

**Comment by solth** [comment]
So basically the function to delete structure elements is bugged when they contain links. To fix this any potential links must be removed from a structure element _before_ removing the element itself (and update any linked structural elements accordingly to display correctly)
