### ISSUE TITLE
Mark structure elements between media unit thumbnails in gallery

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#4368]
Kitodo.Production 3 allows positioning structure elements at specific indices _between_ media units within their parent structures (`ORDER` attributes in structure elements make it possible to compare their position relative to that of media untis within the same parent). 

This is not sufficiently reflected in the gallery, however. Without hovering over the individual thumbnails of media units to see their respective `ORDER` attributes and looking for gaps between those numbers, it is impossible to see whether a structure element is positioned between two pages or not (when solely using the gallery).

For example, in this screenshot the gallery does not show that the element with the name "Akte" is positioned between the pages 8 and 12 in the parent "Abschnitt" element:
![Bildschirmfoto 2021-04-29 um 15 39 34](https://user-images.githubusercontent.com/19183925/116561726-de53e180-a902-11eb-917b-20f57aac435a.png)

Therefor, a small indicator - for example a vertical line/separator - should be displayed between every two pages in the gallery that are not consecutive, indicating the presence of a structure element at that position.

**Comment by matthias-ronge** [comment]
An easy way to see this is from the horizontal difference (red arrow):

![horizontal difference](https://user-images.githubusercontent.com/3040657/117654908-ad8f6a00-b196-11eb-802a-871c9727b3ae.png)

Maybe increasing the space horizontally will easily improve visibility.

A vertical line − do you mean something like this?

![vertical line](https://user-images.githubusercontent.com/3040657/117654384-f85cb200-b195-11eb-9fda-3a121e47304c.png)

However, I like that idea, but maybe its tricky to realize.

**Comment by solth** [comment]
I should have mentioned that this problem specifically arises when the structure tree panel is collapsed (whether because the user is not allowed to view the structure tree or - more likely - because he wants to perform most actions using just one part of the editor). In that case it would be beneficial to have at least _some_ indication about the sibling and hierarchy relations between pages and structure elements in the gallery, even if it cannot (and probably should not) replace all functionality of the structure tree.
