### ISSUE TITLE
I cannot use a ruleset title, if it already exists in another client (Mandant)

### ISSUE THREAD

**Issue by daropoi** [kitodo/kitodo-production#4387]
I have tested a group of project, template, workflow, docket and ruleset in my test-client. 

I now want to take over / copy this structure to my production-client. This does not work. When adding a new ruleset, I get the error message: "The ruleset with the same title exists already."
But it does not exist in **this** client.

I should be able to have ruleset (project, template, workflow, docket) with same title in another client.

**Comment by solth** [comment]
Duplicate of #3726

**Comment by matthias-ronge** [comment]
Closed as duplicate. @daropoi please subscribe to #3726 instead
