### ISSUE TITLE
Hierarchical (newspaper, calendar) processes are not closed, even if all sub processes are closed.

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4392]
Officical Release 3.3.

I have a process hierarchy (newspaper, created via calendar), which are not closed automatically, even if all sub processes are closed:
![grafik](https://user-images.githubusercontent.com/61045115/117655562-84bba480-b197-11eb-8e56-d539dc24bae1.png)

Hint: My last task in the "leaf" processes is an automatic task.

**Comment by matthias-ronge** [comment]
Hierarchy processes don’t have a workflow, so there is nothing to be “closed”. (Closed is coded as: all tasks are in state “finished”.)

What behaviour do you want to archive?

**Comment by stefanCCS** [comment]
If a non-hierarchical process is finished, it vanishes from the process list.
I would expect, that all the processes in this hierarchy will vanish from process list, when all "leaf" processes have been finished.
This "non-vanishing" I have called "non-closing" of parent processes.
Is my expectation correct?

**Comment by Kathrin-Huber** [comment]
This should be fixed, @stefanCCS can you confirm that?

**Comment by stefanCCS** [comment]
@Kathrin-Huber : I will do this check, but I would like to do this with the expected bugfix release 3.4.4.
