### ISSUE TITLE
Release 3.3: Catalog config - uses 'hard-coded' pica2kitodo.xsl (instead of configured 'pica2kitodo_default.xsl')

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4393]
In Release 3.3 the kitodo_opac.xml contains a reference to a mapping file:
`
 <mappingFile>pica2kitodo_default.xsl</mappingFile>
`
This mapping is available in Release 3.3.
BUT, the software is searching for pica2kitodo.xsl
![grafik](https://user-images.githubusercontent.com/61045115/117658999-b171bb00-b19b-11eb-84e8-552ff9143acb.png)

You test this easily: If you create o copy of pica2kitodo_default.xsl to pica2kitodo.xsl, it will work fine!

**==> In my opinion this means, you CANNOT work with more than one catalog!**

**UPDATE**: I have configured two catalogs -> for the first one this "hard-coded" issue here is true, 
and for the second one the configured "mappingFile" is used - as wanted!
--> somehow strange ...

**Comment by solth** [comment]
The new syntax for using custom mapping files is 
```
<mappingFiles>
    <file>mapping_file.xsl</file>
</mappingFiles>
```
This is to allow multiple mapping files to be applied in sequence. (see #4105 for details)

**Comment by stefanCCS** [comment]
Confirmed, I have used old <mappingFile> instead of new <mappingFiles><file> entry.
It works fine, after I have corrected this.
BUT: I simply have used the default after fresh installation of Release 3.3. 
So, please correct this in default setup of release.

**Comment by solth** [comment]
> BUT: I simply have used the default after fresh installation of Release 3.3.
> So, please correct this in default setup of release.

I think only @Kathrin-Huber can fix this in the official release.

**Comment by stefanCCS** [comment]
For Release 3.4.3 I can confirm, that in that the` kitodo_opac.xml` in `kitodo_3-4-3_config_modules.zip` contains the correct default:
```
<mappingFiles>
    <file>pica2kitodo_default.xsl</file>
</mappingFiles>
```
