### ISSUE TITLE
Release 3.3: meta data editor- full image view - no image visible

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4394]
If I go in meta data editor to full image view in meta data editor, I cannot see the full image:
(this has worked in Release 3.2.1-build from 14.01.2021)
![grafik](https://user-images.githubusercontent.com/61045115/117673086-bee27180-b1aa-11eb-8d1e-b403f5f449f7.png)

**Comment by matthias-ronge** [comment]
Is there a scrollbar on the side and if you scroll down can you find the picture?

Or the picture cannot be loaded? Open the developer tools of your browser (typically the <kbd>F12</key> key), there select network analysis, then reload the page. If there are error messages (status ≠ 200, e.g. 404, 500 or similar)?

**Comment by matthias-ronge** [comment]
Please check if you

- have full view JPG file (derivative was created)
- project settings have full view folder selected is folder with JPG files

**Comment by stefanCCS** [comment]
I have a folder configuration like this:
![grafik](https://user-images.githubusercontent.com/61045115/124884498-9cb27780-dfd2-11eb-9e67-62d6966ff214.png)

In subfolder "access" the fimages are available:
![grafik](https://user-images.githubusercontent.com/61045115/124884695-d08d9d00-dfd2-11eb-90c1-2f891544175e.png)

==> So, this looks ok in my opinion

What I just have seen now (not recognized before) is this:
![grafik](https://user-images.githubusercontent.com/61045115/124885168-46920400-dfd3-11eb-9404-3eb553f02753.png)

--> maybe this gives a hint...


(and please let me remark again, that I have seen this behaviour, after I have updated the software only).

**Comment by stefanCCS** [comment]
Sorry, my fault (I have not pressed the image on the right correctly) --> I will close this issue here now.
