### ISSUE TITLE
"Strange" behavior when "helper" scripts (/usr/local/kitodo/scripts) are called

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4420]
I have identified a "strange" behaviour with the "helper" scripts (located in /usr/local/kitodo/scripts).
If I create a new process, the script "script_createDirMeta.sh" is called correctly (for new process-id folder and for each subfolder).
If I remove this process directly after creation I can see the following:
1) The script "script_deleteSymLink.sh" is called, which runs into an error (which is clear as no sym link for this user/process was created until then)
--> Is this a somehow intended behavior in the sense, that the according "script_createSymLink.sh" is called later in the workflow, and here we only have a special, side effect because of very early deletion of a process (which would be ok, as it does not have any other negative side effect)?
--> Or, is the call auf "script_createSymLink.sh" is somehow forgotten, and should be fixed here?
2) The call of ""script_deleteSymLink.sh" is done 9(!) times, before it stops (this is independent of, if there is a link, which could be removed, or not)
--> is this a somehow intended behavior, in case of temporary errors?
--> or an issue to be fixed?

**Comment by henning-gerhardt** [comment]
I noticed that the `script_deleteSymLink.sh` is called in some places where the script call is not useful, f.e. on "release edition of this task" ("Aufgabe abgeben") on a meta data task without the options are set to read or write images. In this scenario the script is only called once and note many times.

Is this "9 times" calling correlating to the amount of users on your system? In 2.x this script is called sometimes even in the same amount of users to ensure that all maybe existing symbolic links are get deleted.

**Comment by matthias-ronge** [comment]
See #3448

**Comment by stefanCCS** [comment]
> 
> 
> I noticed that the `script_deleteSymLink.sh` is called in some places where the script call is not useful, f.e. on "release edition of this task" ("Aufgabe abgeben") on a meta data task without the options are set to read or write images. In this scenario the script is only called once and note many times.
> 
> Is this "9 times" calling correlating to the amount of users on your system? In 2.x this script is called sometimes even in the same amount of users to ensure that all maybe existing symbolic links are get deleted.

My workflows has 9 steps(tasks), which matches to the answer, Matthias has given.

**Comment by henning-gerhardt** [comment]
@Kathrin-Huber : this should be fixed, but @stefanCCS should confirm this.

**Comment by stefanCCS** [comment]
Checked with Release 3.5.0-beta - looks ok.
Will close issue now.
