### ISSUE TITLE
When adding sub-field in Metadata-Editor, existing sub-fields are doubled

### ISSUE THREAD

**Issue by daropoi** [kitodo/kitodo-production#4457]
My ruleset has some complex keys/fields, that have sub-fields. E.g. personGroup or corporationGroup.

In Metadata-Editor, I can add such a key, e.g. corporationGroup - that is ok, group is added.

Now I want to add sub-fields: 
- First field (e.g. Displayform) is ok. 
- Next field (e.g. IdentifierPPN) can be added, but another field "DisplayForm" is also added

So, an already existing sub-field in metadata-editor gets doubled, when adding a new sub-field.

Update: this does NOT happen, when I first add the sub-fields one-by-one without entering values. 

The doubling only appears, if I am adding a sub-field, input a value, save - and then add the next sub-field.

Screenshot:
![md-editor-corporation-field-doubling](https://user-images.githubusercontent.com/64828846/120792144-5e3e1e80-c535-11eb-9af8-c2afffa0445f.png)

**Comment by matthias-ronge** [comment]
Maybe related to #4285

**Comment by Kathrin-Huber** [comment]
this also happens on root level, and also for metadata groups
![duplicateKey](https://user-images.githubusercontent.com/22615787/128496743-a3ebe8a3-830e-46f6-9397-16d4d8d0ee49.gif)
![doubleMetadata](https://user-images.githubusercontent.com/22615787/128496805-2b6f9e34-5c00-4f78-bc4b-68d5183ca64d.gif)
