### ISSUE TITLE
<key use="processTitle"> not implemented

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4459]
A `<key>` declared as `use="processTitle"` in the ruleset, should be set to the process title on process creation. However, this seems not to be implemented, except for newspaper processes. (No reference to `RulesetManagementInterface.getFunctionalKeys(FunctionalMetadata.PROCESS_TITLE)` found in code.)

**Goal:** Implement writing of process title to declared keys.

**Comment by solth** [comment]
Wouldn't this conflict with the existing "processTitle" rules in divisions? If both are configured within a ruleset (`<division id="..." processTitle="...">` and `<key id="..." use="processTitle">`), which one has higher priority for title generation and should be used?

**Comment by matthias-ronge** [comment]
No, it wouldn’t. The **division** explains _how to generate_ the process title. If a **key** has `use="processTitle"`, the process title should be written in that key during process creation.

**Comment by matthias-ronge** [comment]
The `use="processTitle"` is currently—by description—the field to which the ATS/TSL should be written. The `use` should be used for _this_ use case, and for writing the ATS/TSL, a different `use` should be introduced. Cf. #5289
