### ISSUE TITLE
Meta Data Editor - when adding a whole keygroup, mandatory subkeys of similar groups get lost!

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4465]
Release 3.3

In my Ruleset I have (extract):

```
<key id="Person">
	<label>Person (group)</label>
	<label lang="de">Person (Gruppe)</label>
	<key id="LastName">
		<label>Last name</label>
		<label lang="de">Familienname</label>
	</key>
	<key id="RoleCode">
		<label>Relationship designation (code)</label>
		<label lang="de">Beziehungskennzeichnung (Code)</label>
		<option value="rcp">
			<label>Adressat</label>
		</option>
		<option value="aut">
			<label>Verfasser</label>
		</option>
		<preset>aut</preset>
	</key>
	<key id="Authority">
		<label>Authority</label>
		<label lang="de">Quelle (Normdaten)</label>
	</key>
</key>

<restriction division="Monograph" unspecified="forbidden">
	<permit key="Person">
		<permit key="RoleCode" maxOccurs="1" minOccurs="1"/>
	</permit>

```

Same as "ContributorPerson"

If I have a "Person" in meta.xml (lets assume from catalog), and I add manually "ContributorPerson", the entry "RoleCode" in Person gets lost!
The validation shows this strange behaviour:
![grafik](https://user-images.githubusercontent.com/61045115/121490396-3e937400-c9d5-11eb-8110-89c82716a271.png)
(this example is with other keygroups with same structure)

I have made some test:
If I remove this
`
 permit key="RoleCode" maxOccurs="1" minOccurs="1" 
`
in Rule Set it looks to be ok.
==> Sorry, I was wrong, still vanishing :-(

But anyway, please check.

**Comment by andre-hohmann** [comment]
Probably related to: 
- #4588 
- [#4061 (comment)](https://github.com/kitodo/kitodo-production/issues/4061#issuecomment-717362734)

**Comment by Kathrin-Huber** [comment]
@stefanCCS a lot happend here, can you check if this is still an issue?

**Comment by stefanCCS** [comment]
I have checked this with Rel 3.5.0-beta - looks ok now.
I will close this issue.
