### ISSUE TITLE
Task list cannot be sorted by Process ID (or something else)

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4471]
Typically, lists in Production can be sorted according to the different list columns by clicking on the column heading. With the to-do list, that doesn't work, nothing happens when you click on the other columns. For "Title", it works, and sorting is also reversed, but other columns are not considered clickable by Firefox. This is bad when you want to find a certain process and you can’t get along with the search slot.

![Screenshot](https://user-images.githubusercontent.com/3040657/121650637-0ace5200-ca9a-11eb-8aeb-ceea128404fa.png)

**Goal:** Task list should be sortable by all columns.

**Comment by m-kotzyba** [comment]
In addition to that, our daily work with Kitodo has shown that also sorting of optionally columns, such as correction, would be very helpful but is not possible at the moment.

**Comment by andre-hohmann** [comment]
@matthias-ronge : I think, this solved within the current master version. 
Maybe you can check, if this issue can be closed.

**Comment by m-kotzyba** [comment]
@andre-hohmann is right. Looks good and works in 3.5.0. Hence, I close this Isssue. thx
