### ISSUE TITLE
Countless pages initially wrong with ␣-␣

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4476]
Countless pages initially contain ␣-␣, which is wrong.

Workaround: By pagining with “uncounted”, it is corrected.

![Screenshot](https://user-images.githubusercontent.com/3040657/121656488-d2317700-ca9f-11eb-946a-673082e4ae19.png)

**Goal:** Should initially be `uncounted`.

(For the display, ␣-␣ may be prettier, but it may only be replaced in the display.)

**Comment by solth** [comment]
AFAIK this is not correct. Pages should only be labeled as "uncounted" if the user explicitly set them to "uncounted". Until then it is not specified if they are uncounted or counted, thus making "-" the correct initial label.

**Comment by matthias-ronge** [comment]
Okay, did _assume_ this because this is what Production 2 did. However, there are no requirements in the [METS-Anwendungsprofil](https://dfg-viewer.de/fileadmin/groups/dfgviewer/METS-Anwendungsprofil_2.3.1.pdf#page=14):

> Das Attribut `ORDERLABEL` kann die Paginierung der Einzelseite nach Vorlage enthalten.
