### ISSUE TITLE
titleMetadata does not work for metadata groups

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#4500]
Kitodo.Production 3 allows configuring specific metadata to be displayed in the title bars of the gallery stripes in the metadata editor. To enable this feature, the names of the metadata entries must be added to the key `metsEditor.titleMetadata` in the file `kitodo_config.properties`. 

This does not work for metadata entries nested within metadata groups, though. So if the corresponding ruleset contains title information structured similar to mods (`titleInfo/title`), this information can currently not be displayed as title metadata in the editor.

**Comment by matthias-ronge** [comment]
I think it would be good if the [Key Path](https://github.com/kitodo/kitodo-production/issues/3368#issuecomment-781961426) syntax (without regex support) would work here:

`@TitleDocMain` − "TitleDocMain" on top level  
`@titleInfo@title` − "title" from "titleInfo" record

Leading @ character may be optional, so this would work, too:

`TitleDocMain` − "TitleDocMain" on top level  
`titleInfo@title` − "title" from "titleInfo" record
