### ISSUE TITLE
KitodoScript "generateImages" requires the .tif extension to be in lower case

### ISSUE THREAD

**Issue by m-kotzyba** [kitodo/kitodo-production#4534]
The KitodoScript `generateImages` fails if the image files in the source folder (e.g. `images/(processtitle)_tif, LOCAL`) have no lower-case extension, i.e. `<image>.TIF`, cf. Screenshot.

![TIF-ERROR](https://user-images.githubusercontent.com/85474095/124124030-3e3c4500-da78-11eb-98c8-995000135ee0.PNG)

Solution: Just rename the image files in the source folder.

However, if the paths to the image files in the corresponding `meta.xml` also have no lower-case, the `meta.xml` has to be adapted as well.

**Comment by matthias-ronge** [comment]
The extension is configured in the config file `kitodo_fileFormats.xml` ([here](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/resources/kitodo_fileFormats.xml#L67)). It should work that you change it to uppercase there

**Comment by m-kotzyba** [comment]
Yes, I agree, but in our case, only 20-30% of all images are *.TIF (mostly from the older Projects) and the remaining images are *.tif. 

Therefore, I tried to declare a second "TIF" entry in the kitodo_fileFormats.xml (i.e. in addition to the original "tif" entry):

The addition entry
```
    <fileFormat extension="TIF" fileType="TIFF" imageFileFormat="TIFF" mimeType="image/TIFF">
        <label>Tagged Image File Format (image/TIFF, *.TIF)</label>
    </fileFormat>
```
had the same error as above ("... hat keinen Inhalt") and an addition entry with the same mimeType as the original, i.e.:

```
    <fileFormat extension="TIF" fileType="TIFF" imageFileFormat="TIFF" mimeType="image/tiff">
        <label>Tagged Image File Format (image/TIFF, *.TIF)</label>
    </fileFormat>
```

the following error is shown:

![error_tif](https://user-images.githubusercontent.com/85474095/124232152-9410fb80-db11-11eb-855c-0346aad019bf.PNG)

Is there a way to solve this?

**Comment by matthias-ronge** [comment]
You will then have two entries in the folder settings in the project settings. Make sure you have the right one selected in the folder settings of the project. Also, you will need to edit the `meta.xml` files of processes of the project, and replace "image/tiff" with "image/TIFF"; I don’t know if the latter is valid, so you may need to overwrite it again during export to be "image/tiff" in the exported METS-XML file.

**Renaming definitely looks like the better solution here.** What about adding an automatic step to the workflow, which calls a script that does this?

![Automatic task](https://user-images.githubusercontent.com/3040657/124234301-24504000-db14-11eb-8d11-a1c0c8971e53.png)

I would start with the command like this:

    /path/to/rename_script.sh /usr/local/kitodo/metadata/(processid)/images/(processtitle)_tif/

In the script, you can do the renaming. There are [some suggestions how to code such a script on StackOverflow](https://stackoverflow.com/a/11824856).

**Comment by matthias-ronge** [comment]
I do not understand how the error you posted can happen, if you have `mimeType="image/TIFF"` and `mimeType="image/tiff"` in your file formats config. Check if you accidently have two instances of `mimeType="image/tiff"` (this is what the error complains about), that your edits to the file have been properly saved, and restart Tomcat to be sure the new file is used.

**Comment by m-kotzyba** [comment]
You are right, in the "Duplicate key image/tiff" error case I hat two instances:

```
    <fileFormat extension="tif" fileType="TIFF" imageFileFormat="TIFF" mimeType="image/tiff">
        <label>Tagged Image File Format (image/tiff, *.tif)</label>
    </fileFormat>
    <fileFormat extension="TIF" fileType="TIFF" imageFileFormat="TIFF" mimeType="image/tiff">
        <label>Tagged Image File Format (image/TIFF, *.TIF)</label>
    </fileFormat>
```
(I actually explained that but maybe the comment above was a bit ambiguous)

However, if I try:

```
    <fileFormat extension="tif" fileType="TIFF" imageFileFormat="TIFF" mimeType="image/tiff">
        <label>Tagged Image File Format (image/tiff, *.tif)</label>
    </fileFormat>
    <fileFormat extension="TIF" fileType="TIFF" imageFileFormat="TIFF" mimeType="image/TIFF">
        <label>Tagged Image File Format (image/TIFF, *.TIF)</label>
    </fileFormat>
```
the original error ("... hat keinen Inhalt") happens, i.e., no effect.

In any case, your suggestion to use an script for the renaming in the workflow is nice. Thank you!
