### ISSUE TITLE
Make workflows better visible in template details

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4559]
### Problem
In the template details, the selection field for workflows gets lost, when many projects are configured. The reason is, that the selection field is shown under the project list. 

### Solution
It would be helpful, when the selection field for workflows is shown in the row of the selection fields for Ruleset and Docket. 

### Examples
![workflowtemplate00](https://user-images.githubusercontent.com/14835770/127971784-53af62e0-0c12-45a9-a112-ca5d516969cf.jpg)

![workflowtemplate01](https://user-images.githubusercontent.com/14835770/127971790-4870af20-9326-4075-b7bc-65cee7e57d62.jpg)

**Comment by matthias-ronge** [comment]
… and: the projects could be displayed in a multiple selection list box with a scroll bar…
