### ISSUE TITLE
For Periodical and newspaper, children processes cannot be created

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4590]
### Problem
For periodical and newspaper, children processes cannot be created anymore with the "plus" or "calendar" symbol. Both symbols are grey and deactivated. 

For the shortly migrated periodical and newspaper processes, the children processes can be created, and the the symbols are blue. Thus, the configuration of the ruleset with `use="createChildrenWithCalendar"` and `use="createChildrenWithCalendar`" should be correct. In the properties and the metadata the document type seems to be correct, too. 

I am sure that the creation of the processes did work one with the parent processes, 
When the process is validated in the metadata editor, the following validation warning occurs: 
- `The structure has no media assigned: Ephemera "null"`

Usually, this warning does not occur for superordinate processes, which do not contain images. 

### Question
Does anyone had the problem too and/or knows the reason for this behaviour?

**Comment by matthias-ronge** [comment]
Yes, we had the same problem yesterday: For a newly created top-level newspaper process, the calendar wasn’t showing, though `use="createChildrenWithCalendar"` was set. We found two things. Aside from the base type, defined in the `@TYPE` attribute of the first `<div>` in the `<structMap TYPE="LOGICAL">`, we also had a `<kitodo:metadata name="docType">` with value `Periodical`. After we changed that to “Newspaper” as well and reindexing, the calendar was showing. So

* either this metadata entry plays a role (why should it? I have no clue)
* or the reindexing caused the calendar to apper. (I guess the latter, but just guessing.)

**Comment by andre-hohmann** [comment]
I think too, that "_reindexing caused the calendar to appear_". 

Interesting to know is, why the additional manual reindexing is now necessary.

Another observation confirms your assumption: 
- The linking from a multivolume work-process to the volume-processes does not work (at least not without a reindexing). The linking from the volume to the multivolume work-process works correctly. 

Examples: 
![linkvolume01](https://user-images.githubusercontent.com/14835770/129851564-90f17fe6-6580-4990-9ccd-b1a5b814cfe8.jpg)

![linkvolume02](https://user-images.githubusercontent.com/14835770/129851578-9386d5a2-992b-4bef-bcf8-5e5617d19a1b.jpg)

![linkvolume03](https://user-images.githubusercontent.com/14835770/129851587-c0983bd1-e6d8-484a-b99c-26943546994e.jpg)

**Comment by andre-hohmann** [comment]
According to https://github.com/kitodo/kitodo-production/issues/4591#issuecomment-900971301, maybe the reason here is too #4543 or #4560.
