### ISSUE TITLE
Migration of serial publications: creation of duplicates

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4608]
### Problem
For processes of volumes with the same superordinate process have been created in several projects in Kitodo.Production 2.x,  during the migration to Kitodo.Production 3.x, superordinate processes are created for each project. This leads probably to the following problems in the presentation: 
1. The superordinate processes will most probably overwrite themselves, because they have the same identifiers (PPN). 
2. When all superordinate processes can be shown in the presentation, it will be difficult to find all volumes of the superordinate processes.  

It is not clear if this behaviour is intended. For new processes it seems that it is not intended to create several superordinate processes with the same process title for each project. 

### Solution
During the migration, only one superordinate process should be created for all volume processes. The superordinate process could be assigned to the project of the oldest volume process. 

### Example
| process title superordinate  |  project superordinate | process title subordinate   | project subordinate  |
|---|---|---|---|
| GrimEc_35066434X | LDP_AAA  | GrimEc_35066434X-19010000 | LDP_AAA  | 
|   |   | GrimEc_35066434X-19020000 | LDP_AAA |
|   |   | GrimEc_35066434X-19030000 | LDP_AAA |
|   |   | GrimEc_35066434X-19040000 | LDP_AAA |
| GrimEc_35066434X | LDP_BBB | GrimEc_35066434X-19110000 | LDP_BBB |
|   |   | GrimEc_35066434X-19130000 | LDP_BBB |
|   |   | GrimEc_35066434X-19140000 | LDP_BBB |
| GrimEc_35066434X | LDP_CCC | GrimEc_35066434X-18960000 | LDP_CCC |
|   |   | GrimEc_35066434X-18970000 | LDP_CCC |

**Comment by matthias-ronge** [comment]
Did you migrate the projects together, or one by one? I would expect this to happen if you migrate the projects one by one (each in a separate `HierarchyMigrationTask`), because they don’t know about each other. I would expect it not to happen if you migrate them together (select all of the affected projects, then “migrate hierarchys”).

**Comment by andre-hohmann** [comment]
After the migration of all projects in one task, no duplicates were created. 
The issue is closed.

**Comment by matthias-ronge** [comment]
Should we leave issues that should be documented open?

**Comment by andre-hohmann** [comment]
I asked @Kathrin-Huber yesterday and we thought, we should close them. By the label "documentation", all relevant issues can be retrieved. 
Open issues indicate, that problems exist, which must be solved by development/configuration/.... Otherwise, it is difficult to evaluate, if an issue is solved or not.

**Comment by andre-hohmann** [comment]
An additional information for the documentation: 

- All projects with the **same ruleset** should be migrated in one `HierarchyMigrationTask`. 

It seems that otherwise one ruleset is assigned to all created processes of the superordinate processes, which leads to several problems.
