### ISSUE TITLE
Layout slips when zooming out with Firefox

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4661]
The controls in Production 3 are large, larger than in version 2, so there is less space on the screen. You can help yourself with zooming out in the browser. Here, with Firefox, the layout slips. In the page display, the page is under the strip instead of next to it, and the screwdriver button goes on the next line, which it shouldn't.

![problem-zoom](https://user-images.githubusercontent.com/3040657/132829790-b5d52434-f82b-4aae-9d1a-7b658e1fb577.jpg)

**Goal:** The picture stays in place with a smaller zoom, the button too.

**Comment by andre-hohmann** [comment]
The behaviour exists also in Chrome: #4711.
