### ISSUE TITLE
Login page is always German

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4676]
Foreign users report that the login page is always German, and there is no way to change it for the user who wants to log in.

**Goal:** The application should take into account the languages requested by the browser in the HTTP request headers, and if nothing is suitable, use the English language. Usually, JSF should do this automatically, so there is something going wrong in some place that it doesn't apply. 

It is a question of whether, on the login page, we should offer a language selection.

![Login page](https://user-images.githubusercontent.com/3040657/133410185-b7ef7146-9f23-4214-baf5-192a66d41c75.png)

**Comment by m-kotzyba** [comment]
If the majority of users needs english, they can change the value `language.default=de` to `language.default=en` in the `kitodo_config.properties`.

![login](https://user-images.githubusercontent.com/85474095/133441062-94d0e561-bc9f-4d5a-80d3-78f422ab81b7.PNG)

**Comment by matthias-ronge** [comment]
That's right, but for a new user who has just installed the release (not a German) shouldn't be presented with a German dialog. Perhaps, in the delivery state, is it enough to switch off the property?

**Comment by solth** [comment]
I would suggest the following adjustments:
- remove ("out comment") the `language.default` property key from `kitodo_config.properties`
- if someone actively re-adds it, it will be used, with higher priority than the browser setting
- if the property is _not_ manually re-added, the login page uses the browser setting instead, like @matthias-ronge suggested 
- if the system can neither find the property key in `kitodo_config.properties` _nor_ the corresponding browser HTTP request header, default to either the server default language or english
