### ISSUE TITLE
Individualize database names of IDs

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4680]
**Goal:** Currently, the database tables have a column that is `id` everywhere. This is less handy to make `JOIN` on the database command line, it would be better if the id column and the foreign key column have the same name, then, is less typing to join on database command line.

**Comment by henning-gerhardt** [comment]
Please don't do this. 

You have at least two possibilities without changing the whole database schema:

1) use the table name in front of the used table column
2) use an alias if the table name is to long

**Comment by matthias-ronge** [comment]
It was just told to me that it would be easier, then you would just have to write `JOIN ON foo_id`, you would have to write `JOIN ON foo.id = other.foo_id`, and that's just more to type.

Personally, I don't care because I never do that anyway.
