### ISSUE TITLE
Missing ID in crosstabs

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4681]
In database crosstabs, there are no row numbers. This makes it cumbersome to delete individual lines on the database command line. GUI tools (here namely MySQL Workbench) show these tables as read-only, because without an ID, they cannot generate suitable SQL in the background in order to delete individual rows. On the command line, it is possible to delete with appropriate `WHERE` conditions, but is more cumbersome.

**Goal:** Insert ID for the rows. It doesn't matter, but it makes life is easier for administrators.

**Comment by henning-gerhardt** [comment]
From side of a database is your suggestion a big disadvantage. If your (ui based) tools are unable to work with cross tables or tables without unique identifier for every row than is this a issue of the (ui based) tool and not of the database schema.

**Comment by matthias-ronge** [comment]
Rejected as a disadvantage to the database
