### ISSUE TITLE
Misleading meaning of task option "Finalise task after accepting"

### ISSUE THREAD

**Issue by m-kotzyba** [kitodo/kitodo-production#4693]
The thrown exception by using the option "Finalise task after accepting" was solved: #4568 
However, the meaning of the option is misleading:

Having a Workflow with tasks 'a' --> 'b' --> 'c', where only task 'b' has the option "Finalise task after accepting", the following was observed:
- Accepting and finish task 'a' opens and closes 'b' automatically and leaves 'c' open. (‘b’ was never accepted manually, only ‘a’ was finished)
- That is, 'b' is not finalized after accepting it but finalized by finishing the task 'a' before.
- This is in accordance with our use case, where the first task 'A' of a workflow has always the status "closed" and hence, the second task 'B' with option "Finalise task after accepting" is shown to the user. After accepting 'B' (click on the bell), the task 'B' is not finalized but the user has to finish it manually. That is, in out use case task 'B' is not finalized automatically, because the task 'A' before has just status "closed" but was not finished and hence cannot trigger the automatic finalization of 'B'.

If this is intended, the naming of the option in not appropriate. If this is a bug, please have a look on that.

**Comment by matthias-ronge** [comment]
The described behaiviour is a bug.

- Finishing task 'a' should leave 'b' open (unless is is an _automatic_ step; in which case the the “close after accepting” is meaningless)
- After click on the bell for task 'b', it should be finished, and 'c' should be open. The user should not need to finish the task manually
