### ISSUE TITLE
Failure in password validation

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4696]
Release 3.3.1
User passwords during "User Creations" are validated against  password-rules.properties file.
The file itself is used (closed issue #4390), but it looks like that the validation itself has an issue.
A properties file like this:
```
length.min=8
length.max=24

character.upperCase=1
character.lowerCase=1
character.digit=1
character.special=0

allowWhitespace=false

notAllowedWords=pass, password, 12345
```

--> leads to following exception:
![grafik](https://user-images.githubusercontent.com/61045115/134500558-21571071-286d-4360-bcc3-1b1a1a9f3fb5.png)

==> it looks like that this is dependend to entry character.special=0
==> If you do not use this at all (=e.g. comment out this line), the default seems to be character.special=1 (which is ok).
But as I do NOT wish to have special characters, I need to put this line with =0.
==> please check.

**Comment by matthias-ronge** [comment]
`new org.passay.CharacterRule(CharacterData, int)` wants an int ≥ 1, for not producing a „meaningless“ rule. Solution must be not to add a rule in case of 0.
