### ISSUE TITLE
Exception, when duplicating project

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4697]
Release 3.3.1
When duplicating a project
![grafik](https://user-images.githubusercontent.com/61045115/134513719-4ed81c13-973f-4fbb-9339-8f361f2ed3e4.png)

and saving this duplicated project (no other change, just given a new name)
an exception is thrown:
![grafik](https://user-images.githubusercontent.com/61045115/134513555-fee4edc7-983a-4400-88f5-c89ff90d886b.png)

**Comment by solth** [comment]
I think this issue was fixed in #4665

**Comment by matthias-ronge** [comment]
Tested: The issue no longer occurs in the current master.
