### ISSUE TITLE
Metadata groups should be created with all contained metadata fields

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4704]
### Problem
If a metadata group is added in the metadata editor, several steps have to be followed: 
1. creation of the metadata group
2. creation of each contained and needed metadata field

When there are several metadata fields, as for example for a person or a corporation (display name, first name, last name, prefix, ID, ...) this is very cumbersome. 

### Solution
If a metadata group is added in the metadata editor, all contained metadata fields should be created immediately. Unneeded metadata fields can be left empty. 
If it is inconvenient for some users to create empty metadata fields, two buttons could be offered to create the metadata groups: 
1. creation of empty metadata group
2. creation of complete metadata group

**Comment by matthias-ronge** [comment]
In the ruleset, you can activate this behaviour with the `alwaysShowing` option.

```xml
<editing>
    <setting key="Person">
        <setting key="Role" alwaysShowing="true"/>
        <setting key="IdentifierURI" alwaysShowing="true"/>
        <setting key="FirstName" alwaysShowing="true"/>
        <setting key="LastName" alwaysShowing="true"/>
        <setting key="DateOfDeath" alwaysShowing="true"/>
        <!-- ... whatever sub-keys you have/want to be showing ... ->
    </setting>
```

**Comment by andre-hohmann** [comment]
Thank you very much. It works. Therefore, i close the issue.
