### ISSUE TITLE
Pagination "Freitext" is not working proberly

### ISSUE THREAD

**Issue by apiller** [kitodo/kitodo-production#4706]
After updating Kitodo to 3.3 pagination "Freitext" is not accepting text or brackets. Probably a mistake in the release. Kitodo 3.2 was ok.

**Comment by matthias-ronge** [comment]
The input for `paginationStartValue` [is _still_ an `<p:inputText>`](/kitodo/kitodo-production/blob/master/Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/dialogs/pagination.xhtml#L69), so this is not a regression issue.
