### ISSUE TITLE
Duplicates are created during creation of newspaper-processes

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4712]
### Problem
When newspaper-processes are created with the calendar-plugin, the created processes are not examined regarding existing processes with the same processtitle. 
This may lead to duplicates, which have to be deleted or repaired. Both are unnecessary efforts. 

### Solution
When newspaper-processes are created, the processtitles should be checked for duplicates, like during the creation of processes for other document types (monograph, volume). 
In Kitodo.Production 2.x, the creation of newspaper-processes was aborted in the taskmanager, as soon as a duplicte has been identified. 

### Examples
![DubletteAusgaben](https://user-images.githubusercontent.com/14835770/135452028-593c75d1-ad61-4935-a19a-4e78bddee18c.jpg)

**Comment by matthias-ronge** [comment]
What should a good solution then look like? If, for a newspaper with 4,000 processes, the application creates the first 200 processes, then there is a duplicate and everything is canceled, you have to manually delete 200 processes to start over, which is also not convenient.

Perhaps, it would be good to first check whether all titles are free? Maybe even in the calendar editor, and not start if there is any problem.

**Comment by andre-hohmann** [comment]
> Perhaps, it would be good to first check whether all titles are free? Maybe even in the calendar editor, and not start if there is any problem.

Thanks - That is a great suggestion! Maybe it could also be shown, which processes are duplicates. 
It could be checked and warned before the message "Do you really want to create the processes" is shown, after which the processes are created.

**Comment by matthias-ronge** [comment]
I thought of something somehow like this:

![Example](https://user-images.githubusercontent.com/3040657/135845922-e8272298-6352-420e-a403-5864b54b04f7.png)

**Comment by andre-hohmann** [comment]
Yes, that would be perfect!
If possible, the button "Create processes" could be deactivated to ensure, that nobody creates the processes despite the warning message.
