### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#4715]
Since ElasticSearch was updated to version 7.10 in #4581 some tests are often failing, but sometimes succeed. I haven't been able to determine a pattern as to when the tests fail.

The tests in question are:
```
FilterServiceIT.shouldBuildQueryAndFindByProcessServiceByTaskTitle:174 Incorrect amount of processes for title containing 'Open'! expected:<1> but was:<0>
```
and
```
SearchResultFormIT.testFilterByTaskAndStatus:152 expected:<1> but was:<0>
```

**Comment by matthias-ronge** [comment]
That seems to be a timing problem. So, from the fact that the index command has returned, it cannot yet be concluded that indexing has been completed. For a large number of search engine applications it is okay to work according to the fire-and-forget principle, but we need it differently for the tests. Perhaps there is a parameter for this that you can request that the request remain open until the indexing has been completed. Or we have to incorporate a general delay after indexing?
