### ISSUE TITLE
Sorting of new volume processes is difficult with the mouse-over

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4736]
### Problem
When new processes for periodicals or multivolumes are created, they must be assigned to the correct position. The processtitle and Kitodo-ID is only visible by a mouse-over of the depicted structure element. 

This is very cumbersome, especially, because the the processes (volumes) are not sorted according to the logical structure or order, but according to the Kitodo-ID and thus by the time of creation of the process - see #4737. 

### Solution
It would be helpful, if the information in the mouse-over is shown always besides the structure element

### Example
Only for one structure element, the processtitle and Kitodo-ID is shown. 
![BändeSortierung03](https://user-images.githubusercontent.com/14835770/136802296-773defb7-f410-4eda-8e47-026fe5b53c62.jpg)

**Comment by matthias-ronge** [comment]
Yes, there would be enough space, and the information must already be loaded in order to prepare the HTML page. The mouse-over animationis just a treat.

The information about what is displayed is part of the ruleset configuration with `use="displaySummary"` in the ruleset.
