### ISSUE TITLE
Migrated processes of volumes should be ordered by logical order 

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4737]
### Problem
Processes for periodicals or multivolumes must be assigned to the correct position. The correct position follows the logical order, as for example the order number of volumes or the date of issuance. 

For the migrated processes in Kitodo.Production 3.x, the order of the processes follows the Kitodo-ID and thus the date of the creation of the processes. That can be random due to several reasons, as for example: missing volumes are added belated from other institutions, ...

This leads also to problems during the creation of new processes #4736. It is in some cases impossible to find a correct logical position. 

### Solution
**If the order in Kitodo.Production influences the order in Kitodo.Presentation**, the order in Kitodo.Production must be adjusted during the migration. I am aware of the difficulties in finding criteria that meets the demands of all institutions. 

If the order in Kitodo.Production affects only Kitodo.Production, this issue might not be regarded.

**Comment by matthias-ronge** [comment]
After looking into the ancient sources, the criterion should be the metadata `CurrentNoSorting` ([here](/kitodo/kitodo-production/blob/2.x/Goobi/plugins/import/PicaMassImport/de/intranda/goobi/plugins/PicaMassImport.java#L212-L218), [here](/kitodo/kitodo-production/blob/2.x/Goobi/src/de/sub/goobi/export/dms/ExportDms_CorrectRusdml.java#L342), [here](/kitodo/kitodo-production/blob/2.x/Goobi/src/org/goobi/production/model/bibliography/course/IndividualIssue.java#L63)).

**Comment by andre-hohmann** [comment]
Thanks for the investigation! I have analysed some of our processes and it seems that we use `CurrentNoSorting` as sorting criteria for volumes (periodical, multivolume). 
Newspaper issues are sorted maybe by "ORDERLABEL". But the newspaper migration is conducted separately and should not be affected. 

Is it possible to adjust the migration by applying `CurrentNoSorting` as sorting criteria? How complex will it be?
