### ISSUE TITLE
Creating newspaper processes - wrong color-labeling of issues

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4761]
### Problem
When more then one newspaper issue per day is created, an own color is assigned to each issue-block. 
As soon as the text-label of the issues per day and the amount of issues per each day are the same, the color-label of one issue changes - and only one issue is recognized. In the end, only one issue block is created. 

This behaviour is difficult to describe - see the example to figure it out easier. 
This approach should not be applied in order to avoid duplicates. Maybe this is a kind of duplicate check. 
In case that this behaviour influences other behaviour, it is described in this issue. 

### Solution
The color-label of the issues should not be changed automatically. To avoid duplicates, an error message should be shown - #4712. Otherwise the user cannot interpret it. 

### Example 
![ZeitungenAusgabenanzeigeHinzufügen](https://user-images.githubusercontent.com/14835770/137469765-556db331-bdcc-40ae-9b75-189a7efc24ff.gif)

**Comment by matthias-ronge** [comment]
It took me a moment: I see the problem is on the left-hand side in the _Block_ settings, where, for the second issue, the little blue box at the right of the Issue Name Input sometimes turns red.
