### ISSUE TITLE
Creating processes from process template using plus button

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4777]
Creating processes from process templates from inside the Create New Process page is implemented in a different concept than any other process creation:

![Screenshot](https://user-images.githubusercontent.com/3040657/138247410-a3e1b46f-edc0-4a0d-aa59-9935249874d3.png)

Any other process creation:

- Search for project / process template / superordinated process in the respective list → hit <kbd>+</kbd> button → Create New Process dialog shows → complete details → create process

But here

- Open Create New Process dialog → navigate to “process template” panel → select source process from list (no search available) → click apply → complete details → create process.

**Goal:** For processes, that are considered “template processes”, the <kbd>+</kbd> button will be enabled. Clicking the button opens the Create New Process dialog with the data filled in.

**Comment by solth** [comment]
This was fixed by #4834, I think.
