### ISSUE TITLE
Broken help for filters

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-production#478]
The online help uses `wiki.goobi.org`which is now down.

```
Goobi/newpages/inc/Process_Filter.jsp: <h:outputLink id="aslsid11" target="_blank" value="http://wiki.goobi.org/index.php/Filter_f%C3%BCr_Vorg%C3%A4nge">
Goobi/newpages/inc/Step_Filter.jsp:    <h:outputLink id="aslsid11" target="_blank" value="http://wiki.goobi.org/index.php/Filter_f%C3%BCr_Vorg%C3%A4nge">
```

Maybe the old help text should be made available in a local file, so it can be maintained with the source code? Ideally there would also be a version for each supported language.

**Comment by henning-gerhardt** [comment]
Do this [GitHub wiki page](https://github.com/kitodo/kitodo-production/wiki/Suche-und-Filtern) help?

**Comment by stweil** [comment]
Yes, it helps, thank you. PR #479 uses that new URL. What about language, is support for English still a development goal? I noticed that https://www.kitodo.org/ has no English text.

**Comment by henning-gerhardt** [comment]
Multi-language support is still a strategic goal of development. But I can not say anything to website content. Please use the contact mail address to get an answer to your question.

**Comment by stweil** [comment]
That's @jens-bemme, I assume.

**Comment by matthias-ronge** [comment]
Maybe distributing the user help along with the JAR file should be considered. There are Kitodo installations which run without internet connection, so having _user_ help hosted on the same server should be worth it. The same could also be linked from the kitodo.org website.

**Comment by henning-gerhardt** [comment]
Providing offline help should only be done if online help is up to date and I don't know how we could provide some kind of offline help.

**Comment by henning-gerhardt** [comment]
Can I close this issue as it is resolved?

**Comment by stweil** [comment]
The initial issue was solved by PR #479. Two questions arose:

* Wouldn't it be better to provide help with the software (available without Internet connection, matches the software version)?
* What about English?

If you prefer, those questions can be tracked in a new issue.

**Comment by henning-gerhardt** [comment]
Your two questions more a general decision and should not be discussed in this specific issue. Your first question should be discussed in a issue or on the developer mailing list. Your second question is to general to answer as multi language support for software is a goal and should be respect on every commit which affect user interface output.

**Comment by henning-gerhardt** [comment]
Removing milestone Kitodo.Production 2.0 as used URL is changed and future solution how to display help or helping information is a goal of an other milestone.

**Comment by henning-gerhardt** [comment]
Closing as solved.
