### ISSUE TITLE
JPEG-compressed TIFFs don’t work with Tomcat 7

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#482]
When using JPEG-compressed TIFF images, no image is being shown in the metadata editor.

Here are some of the stack traces occurring:

```
ERROR 2016-07-25 15:49:11,750 de.sub.goobi.metadaten.Metadaten.BildErmitteln(Metadaten.java:1746)
        javax.media.jai.util.ImagingException: All factories fail for the operation "Stream"
Error: One factory fails for the operation "tiff"
Occurs in: javax.media.jai.ThreadSafeOperationRegistry
java.lang.reflect.InvocationTargetException
    at sun.reflect.GeneratedMethodAccessor698.invoke(Unknown Source)
[…]
    at javax.media.jai.RenderedOp.createInstance(RenderedOp.java:781)
    at de.unigoettingen.sub.commons.contentlib.imagelib.ImageManipulator.scaleNextNeighbor(ImageManipulator.java:226)
    at de.unigoettingen.sub.commons.contentlib.imagelib.ImageManager.scaleImageByPixel(ImageManager.java:407)
    at de.unigoettingen.sub.commons.contentlib.imagelib.ImageManager.scaleImageByPixel(ImageManager.java:263)
    at de.unigoettingen.sub.commons.contentlib.imagelib.ImageManager.scaleImageByPixel(ImageManager.java:223)
    at de.sub.goobi.metadaten.MetadatenImagesHelper.scaleFile(MetadatenImagesHelper.java:375)
[…]
Caused by: java.lang.NoClassDefFoundError: com/sun/image/codec/jpeg/JPEGCodec
    at com.sun.media.jai.codecimpl.TIFFImage.<init>(TIFFImage.java:746)
    at com.sun.media.jai.codecimpl.TIFFImageDecoder.decodeAsRenderedImage(TIFFImageDecoder.java:112)
    at com.sun.media.jai.opimage.CodecRIFUtil.create(CodecRIFUtil.java:96)
    at com.sun.media.jai.opimage.TIFFRIF.create(TIFFRIF.java:53)
    ... 86 more
```

The class `ImageManipulator` as part of `ics-1.1.5.jar` makes use of _Java Advanced Imaging_ (`jai_core-1.1.2_01.jar`) which tries to call functionality from the `com.sun.image.codec.jpeg` package which has been removed in Java 1.7. Cf. [Java SE 7 and JDK 7 Compatibility](http://www.oracle.com/technetwork/java/javase/compatibility-417013.html#source):

> Some APIs in the sun.\* packages have changed. These APIs are not intended for use by developers. Developers importing from `sun.*` packages do so at their own risk. For more details, see [Why Developers Should Not Write Programs That Call `sun.*` Packages](http://www.oracle.com/technetwork/java/faq-sun-packages-142232.html).

**Comment by henning-gerhardt** [comment]
Does this happen even with uncompressed tif files or only with JPEG compressed tif files?

**Comment by matthias-ronge** [comment]
No, the problem occurs only for JPEG-compressed TIFFs.

**Comment by henning-gerhardt** [comment]
I will label this as bug. But as we don't have source files for ics-1.1.5.jar I see no way for a fast solution.

**Comment by matthias-ronge** [comment]
*Java Advanced Imaging API 1.1.2_01* already _is_ [the latest release](http://www.oracle.com/technetwork/java/javasebusiness/downloads/java-archive-downloads-java-client-419417.html#jai-1_1_2_01-oth-JPR). As to my above findings, I consider it **broken** in Java 7 onwards.

[Reading of images can be done using `javax.imageio.ImageIO`](https://docs.oracle.com/javase/tutorial/2d/images/loadimage.html), but it does not support TIFF out of the box. However, the [TwelveMonkeys](https://github.com/haraldk/TwelveMonkeys#user-content-tiff---aldusadobe-tagged-image-file-format) library provides a TIFF reader (and many others) to be used with `ImageIO` to read (and write) a lot of image formats. It’s licensed under the [BSD 3-clause license which is compatible with GPL](https://www.gnu.org/licenses/license-list.html#ModifiedBSD).

BTW, the way of writing temporary image files into the web application directory to expose their content via HTTP [can be considered a mistake](http://stackoverflow.com/a/36200592/1503237), too. If this gets rewritten, [`<p:graphicImage>` should be used to handle this](http://stackoverflow.com/a/12452144/1503237).

**Comment by solth** [comment]
Closed as Kitodo.Production 2.x is not supported anymore (see https://github.com/kitodo/kitodo-production/security/policy)

**Comment by stweil** [comment]
What about the other issues with 2.x (and no 3.x) label?

**Comment by solth** [comment]
> What about the other issues with 2.x (and no 3.x) label?

The `3.x` label has been removed (because 3.x became the default) so the absence of the label does not imply the issue only applies to version 2.x. Each of the remaining issues in question has to be checked individually and I do not have the resources to do all that at the same time and by my own.
