### ISSUE TITLE
Rel 3.4 - Errors in Messages-Files with '

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4854]
I think I have found a general error, which (might) occur in all messages file:
- errors_de.properties
- errors_en.properties
- messages_de.properties
- messages_en.properties

At least in error_de/en I have found several entries, which refer to a variable using
`''{0}''
`instead of just
`{0}`

I have recognized this at
`processTitleAlreadyInUse=Der Prozesstitel ''{0}'' wird bereits verwendet.`
--> in this case I see this text in th GUI: "Der Prozesstitel {0} wird bereits verwendet."

--> Please confirm, that my assumption is rigth (I will change this in my files by myself), or tell me, what else might be wrong.

--> and, if this is true, please change in next release (@Kathrin-Huber )

**Comment by matthias-ronge** [comment]
That’s a bug. As a workaround, you can remove all `''` from the messages file.
