### ISSUE TITLE
Hard-coded metadata docType is used

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4863]
When creating a process, a hard-coded metadata `docType` is searched for. If it is not found, an error message will appear:

![Screenshot 2021-12-01 103953](https://user-images.githubusercontent.com/3040657/144268817-1ba61c8f-906a-48e9-8345-6f2bd8cbaa8a.png)

Once the aim was to stop using hard-coded metadata. For metadata to which a function is linked, there is the option of assigning `use="…"`-attributes in the ruleset.

**Goal:** This should be done for `docType`. If the `use="docType"` attribute was not assigned in the ruleset, no error message should appear stating that it was not found. It should be documented how exactly the metadata with the `use="docType"` is interpreted and is to be populated.

**Comment by solth** [comment]
Perhaps the file `ruleset.xsd` should also be updated to make `use="docType"` mandatory?

**Comment by matthias-ronge** [comment]
I believe that it isn’t possible to express that in XSD language.
