### ISSUE TITLE
Display Correction Status in Process and Task List

### ISSUE THREAD

**Issue by m-kotzyba** [kitodo/kitodo-production#4877]
Similar to the process list in the Desktop

![Correction](https://user-images.githubusercontent.com/85474095/145951976-1d96fcbc-4e04-4ead-9020-74df5f952b6e.PNG)

it would be very helpful if the Correction property would be shown in the full process list and task list. Otherwise, (re-) finding these is a quite cumbersome task for the users.

Or is there any option I missed, to activate it (or search for it)?

**Comment by solth** [comment]
The "Correction" column with the grey/red "K" should already be configurable using the "List column" button in the task and process list pages
<img width="590" alt="listcolumn_button" src="https://user-images.githubusercontent.com/19183925/146027520-179850dc-fe31-4cb5-95af-3a84e1d6a619.png">

**Comment by m-kotzyba** [comment]
You're right. Found it. Thank you! :)
