### ISSUE TITLE
Inactive process templates not visible

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#4902]
If you set a process template from active to inactive and store this process template it is after this not visible in the list of process templates. Workaround to get then visible again: set them into the database to active and do a re-index of all process templates :-(

**Goal:** even inactive process templates should be visible in the list of process templates - maybe in a different color or some other styling.

**Comment by solth** [comment]
Somehow related to #3311, I guess

**Comment by henning-gerhardt** [comment]
Yes, my new issue is a duplicate of #3311. I will close this issue.
