### ISSUE TITLE
Add Metadata button in editor hides boolean fields when it is the last field

### ISSUE THREAD

**Issue by BartChris** [kitodo/kitodo-production#4922]
There is a problem with the positioning of the "Add Medadata" button in the editor, when the last visible element is of type boolean. It is not possible to click the checkbox in that case.

![grafik](https://user-images.githubusercontent.com/7516499/150572322-7c78e494-60b4-47bf-90d5-a88828ed18ba.png)

**Comment by matthias-ronge** [comment]
This problem is more general, though less critical in the other cases: If there is a text field as the last field, you can type in it, but you don’t see what you type.
