### ISSUE TITLE
Metadata Editor - Structure elements: open/close all at once and save the state

### ISSUE THREAD

**Issue by m-kotzyba** [kitodo/kitodo-production#4976]
It would be helpful to have the option (e.g. a button) in or close to the structure data window that allows to open or close all structure elements at once. Even better (as in Kitodo 2): allow a selection of the hierarchy level.

In addition: If (different) structure elements are opened or closed (individually), this state should be saved. Currently, interactions such as adding a new element results in opening all already present elements.

**Comment by andre-hohmann** [comment]
@m-kotzyba : Is this related to: https://github.com/kitodo/kitodo-production/wiki/Anpassungen-der-Anzeige-im-Strukturbaum, which was solved by #5165?

**Comment by m-kotzyba** [comment]
Dear @andre-hohmann, not really because the option to open or close all (structure) elements in the tree (of the certain hierarchy level) at once is independend of the shown type/pages.

**Comment by solth** [comment]
@m-kotzyba could you add a screenshot of the 2.x solution or describe it in more detail as I am not familiar with it?

**Comment by m-kotzyba** [comment]
@solth and @andre-hohmann after a further discussion with my colleague we concluded, that the new options "Show assigned pages" and "Show only structure elements" (solved by #5165) basically ease the work already sufficiently and a selection of the hierarchy level, as first described above, is no necessary anymore. Thanks!

However, we noticed a bug related to the new options, described here #5438 

The second point described above, namely to opened and closed (different) structure elements (individually) was possible in Kitodo 2, would be nice but not more. Imagine something like this:
![hir](https://user-images.githubusercontent.com/85474095/201036911-3f585ebf-48fe-44b7-8bb5-21ae3bf528e9.PNG)

**Comment by solth** [comment]
> The second point described above, namely to opened and closed (different) structure elements (individually) was possible in Kitodo 2, would be nice but not more. Imagine something like this:

@m-kotzyba thank you for the explanation. 

Since structure elements can already be expanded or collapsed individuall in the current implementation, I guess by "opening/closing individual structure elements" you mean "Toggle visibility assigned **pages** just for one structure element", is that correct? 

So if I understand you correctly, you would like have an option to see just _some_ pages in the combined structure tree, but not all, when "Zeige zugewiesene Seiten" is deactivated, is that correct?

**Comment by solth** [comment]
As discussed with @m-kotzyba in a separate meeting the functionality will be implemented according to the original issue description
