### ISSUE TITLE
Metadata Editor: Show the first image in detail view if structure element is clicked

### ISSUE THREAD

**Issue by m-kotzyba** [kitodo/kitodo-production#4977]
It would be helpful to show the first image if the user clicks on an structure element, that contains images and if the detail view is activated. Currently nothing is shown in the Gallery

P.s.: In Kitodo 2 the user could choose what is shown if an element was clicked.

**Comment by matthias-ronge** [comment]
The corresponding behavior would be that when you click on a structural element, the associated _stripe_ is selected. This could be done with a thick dashed line, like the one sometimes used to outline the structure tree.
