### ISSUE TITLE
Show corrections messages and comments on hovering over the ‘K’

### ISSUE THREAD

**Issue by m-kotzyba** [kitodo/kitodo-production#4994]
Currently, hovering over the correction ‘K’ only show the corrections messages. (see image)

![02](https://user-images.githubusercontent.com/85474095/154248190-3fc5e532-fd4e-4872-830d-ed44cd06cee7.PNG)

However, it would be very helpful to show also the comments, e.g. in case a correction turned out to be not necessary (cf. #4935) and hence, the tasks can be just finished instead of opening eh Metadata Editor and click on the comments.

**Comment by solth** [comment]
The "K" in the column does not stand for "Kommentar", but for "Korrektur", as the column title implies. It is only displayed if the process has a "Korrekturkommentar" ("correction comment"), so if it does not, there would be no element to hover and in which normal comments could be displayed. If we want to display normal comments as well, we need to rework this column and introduce a third state (in addition to grey "K" for solved correction comments and red "K" for unsolved correction comments) which would represent the existince only of normal comments.

**Comment by m-kotzyba** [comment]
Even though the K/C is for „Korrektur“/Correction, comments can have a relation to a correction. In other words, there is no (easy) way to make a comment within the correction process. (Or did I missed something?)

As mentioned above (in #4935) if a requested correction turned out to be no necessary, the user can not state this but he/she could use a comment what than would not be shown easily (cause it is a “comment”, not a “correction comment”). 

However, the idea of an additional state for “comments” is nice. In the column there could also be two signs, such as “C” for correction state and an additional sign representing comments. This would still be not optimal because “correction comment” and normal comments regarding the same correction would be shown in two different hover bubbles, but at least the users can avoid to open the metadata editor just to check (possible additional) comments.

Just to underline how important this issue can be: Each correction (re-)triggers every task (marked as “correction” in the workflow”) and if the correction is not necessary, all this tasks need fast to be identified as “already done because correction was not necessary”.

Not easy to find a good solution, I know.
