### ISSUE TITLE
Automatically enter process title in metadata

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#5000]
According to the ruleset description, a `<key>` with the `use="processTitle"` should be automatically filled with the process title. However, this is only implemented in newspaper processes so far.

**Goal:** This should also work when creating ordinary processes.

**Comment by matthias-ronge** [comment]
The `use="processTitle"` is currently—by description—the field to which the ATS/TSL should be written. The `use` should be used for this use case, and for writing the ATS/TSL, a different `use` should be introduced. Cf. #5289

**Comment by BartChris** [comment]
Duplicate of https://github.com/kitodo/kitodo-production/issues/4459

**Comment by matthias-ronge** [comment]
Closed as duplicate
