### ISSUE TITLE
Bug in validation logic, errors in metadata groups are not reported and validation does not work

### ISSUE THREAD

**Issue by BartChris** [kitodo/kitodo-production#5009]
If you have a metadata group like person:

![grafik](https://user-images.githubusercontent.com/7516499/155114502-3403eb8f-fe94-472a-88d2-e4b6a68ae531.png)

The ruleset validation does NOT consider non conforming metadata in metadata groups as a violation of the ruleset. What you get is a green success message which contains errors. The metadata is considered valid although it is not.

![grafik](https://user-images.githubusercontent.com/7516499/155116338-219cbff9-71a3-448e-a84d-15305e0b837e.png)

 The problem is in these lines

https://github.com/kitodo/kitodo-production/blob/4be8fa7c3905083b66fb6b6bdac6d264bac30518/Kitodo-Validation/src/main/java/org/kitodo/validation/metadata/MetadataValidation.java#L291-L293

The code is checking if there is a validation WARNING and therefor does not report back possible errors from the recursive function call.
The code has to be changed to the following:

```java
if (metadata instanceof MetadataGroup) {
    ValidationResult validationResult = checkForMandatoryQuantitiesOfTheMetadataRecursive(
        ((MetadataGroup) metadata).getGroup(),
        (ComplexMetadataViewInterface) metadataView, location + metadataView.getLabel() + " - ", translations);
    if (validationResult.getState().equals(State.ERROR)) {
        error = true;
    }
    messages.addAll(validationResult.getResultMessages());
} else {
    throw new IllegalStateException("metadataView is a " + metadataView.getClass().getSimpleName() +
        ", but metadata is a " + metadata.getClass().getSimpleName());
}
```

After this change the validation works correctly on my test system

**Comment by matthias-ronge** [comment]
Since you already describe the solution here, could you also make a pull request with the change?
