### ISSUE TITLE
Editing in Metadata editor is impossible for many structural elements and images

### ISSUE THREAD

**Issue by markusweigelt** [kitodo/kitodo-production#5012]
In general, drag and drop functionality can no longer be used with increasing number of DOM elements.

Furthermore, various events such as the initial loading of the gallery or the partial reload when dropping an image lead to long loading times during processing.

A high number of DOM elements lead to a crash depending on the client resources.

To discuss how to solve the problem, here is a discussion with possible solutions. https://github.com/kitodo/kitodo-production/discussions/5010

**Comment by andre-hohmann** [comment]
@markusweigelt : Is this still a problem, or has it been solved with the performance improvements by the following pull requests?

- https://github.com/kitodo/kitodo-production/pull/5095
- https://github.com/kitodo/kitodo-production/pull/5096
- https://github.com/kitodo/kitodo-production/pull/5113
- https://github.com/kitodo/kitodo-production/pull/5114
- https://github.com/kitodo/kitodo-production/pull/5115
- https://github.com/kitodo/kitodo-production/pull/5121

**Comment by markusweigelt** [comment]
Problems are solved for us for now. The performance optimization has shifted the problem of the media data editor with many structural elements and images to a higher number. For us this is sufficient, because we can structure our media with a high number of structural elements and images in the metadata editor.
