### ISSUE TITLE
Automatically set outline headings 

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#5016]
In version 2, the headings of the outline (which are stored in `<div LABEL="…">`) were taken from metadata `TitleDocMain`. This relationship was hardwired. In version 3, this hard-wired takeover was removed, so that outline headings can—but also must—be treated independently of other metadata. Although the editing user has more freedom in designing the outline of the digital copy, in practice it means more work, as the outline headings and the title (for example, of a chapter) are usually the same.

**Goal:** It needs an automatic takeover. To do this, the command could accept a list of simple metadata keys, and if the heading is empty, it is filled with the first metadata value found for a key in the sequence.

**Comment by andre-hohmann** [comment]
@matthias-ronge : I do not know, if i understand the problem correctly, but i think we have workarounds/solutions for at least a similar problem. I describe them to bring the similar use cases together. 

1 `ORDERLABEL/LABEL` of structure elements
For the structure elements in one process, it is possible to add the values of `ORDERLABEL/LABEL` via the export-XSLT. The advantage is, that the values need not to be added twice. 
For example by using the values of the elements `TitleDocMain` and `TitleDocMainShort`: 

<details>
  <summary>click to show the XSLT</summary>

```xml
     <xsl:template match="@DMDID">
        <xsl:variable name="dmSecId" select="."/>
        <xsl:variable name="TitleDocMain" select="/mets:mets/mets:dmdSec[@ID=$dmSecId]/mets:mdWrap/mets:xmlData/kitodo:kitodo/kitodo:metadata[@name='TitleDocMain']"/>
        <xsl:variable name="TitleDocMainShort" select="/mets:mets/mets:dmdSec[@ID=$dmSecId]/mets:mdWrap/mets:xmlData/kitodo:kitodo/kitodo:metadata[@name='TitleDocMainShort']"/>
        <xsl:variable name="CurrentNoSorting" select="/mets:mets/mets:dmdSec[@ID=$dmSecId]/mets:mdWrap/mets:xmlData/kitodo:kitodo/kitodo:metadata[@name='CurrentNoSorting']"/>
        <xsl:if test="$TitleDocMain !=''">
            <xsl:attribute name="LABEL">
               <xsl:value-of select="/mets:mets/mets:dmdSec[@ID=$dmSecId]/mets:mdWrap/mets:xmlData/kitodo:kitodo/kitodo:metadata[@name='TitleDocMain']"/>
            </xsl:attribute>
        </xsl:if>
        <xsl:if test="$TitleDocMainShort !=''">
            <xsl:attribute name="ORDERLABEL">
                <xsl:choose>
                    <xsl:when test="starts-with($TitleDocMainShort, 'Der')">
                        <xsl:value-of select="normalize-space(replace($TitleDocMainShort,'Der ', ''))"/>
                    </xsl:when>
                    <xsl:when test="starts-with($TitleDocMainShort, 'Die')">
                        <xsl:value-of select="normalize-space(replace($TitleDocMainShort,'Die ', ''))"/>
                    </xsl:when>
                    <xsl:when test="starts-with($TitleDocMainShort, 'Das')">
                        <xsl:value-of select="normalize-space(replace($TitleDocMainShort,'Das ', ''))"/>
                    </xsl:when>
                    <xsl:when test="starts-with($TitleDocMainShort, 'Eine')">
                        <xsl:value-of select="normalize-space(replace($TitleDocMainShort,'Eine ', ''))"/>
                    </xsl:when>
                    <xsl:when test="starts-with($TitleDocMainShort, 'Ein')">
                        <xsl:value-of select="normalize-space(replace($TitleDocMainShort,'Ein ', ''))"/>
                    </xsl:when>
                   <xsl:otherwise>
                        <xsl:value-of select="($TitleDocMainShort)"/>
                    </xsl:otherwise>
                </xsl:choose>
            </xsl:attribute>
        </xsl:if>
        <xsl:if test="not($TitleDocMainShort) and $TitleDocMain !=''">
            <xsl:attribute name="ORDERLABEL">
                <xsl:choose>
                    <xsl:when test="starts-with($TitleDocMain, 'Der')">
                        <xsl:value-of select="normalize-space(replace($TitleDocMain,'Der ', ''))"/>
                    </xsl:when>
                    <xsl:when test="starts-with($TitleDocMain, 'Die')">
                        <xsl:value-of select="normalize-space(replace($TitleDocMain,'Die ', ''))"/>
                    </xsl:when>
                    <xsl:when test="starts-with($TitleDocMain, 'Das')">
                        <xsl:value-of select="normalize-space(replace($TitleDocMain,'Das ', ''))"/>
                    </xsl:when>
                    <xsl:when test="starts-with($TitleDocMain, 'Eine')">
                        <xsl:value-of select="normalize-space(replace($TitleDocMain,'Eine ', ''))"/>
                    </xsl:when>
                    <xsl:when test="starts-with($TitleDocMain, 'Ein')">
                        <xsl:value-of select="normalize-space(replace($TitleDocMain,'Ein ', ''))"/>
                    </xsl:when>
                   <xsl:otherwise>
                        <xsl:value-of select="($TitleDocMain)"/>
                    </xsl:otherwise>
                </xsl:choose>
            </xsl:attribute>
        </xsl:if>
        <xsl:copy>
            <xsl:apply-templates select="@*"/>
        </xsl:copy>
    </xsl:template>
```

</details>

It would be possible to use the values of other MODS-Elements for specific document types. 

2 `ORDERLABEL/LABEL` of document elements (processes)
For document elements (processes) like volume, issue, ... the before described solution is not possible, because the `ORDERLABEL/ORDER` of superordinate and subordinate processes are written before the export-XSLT is applied. The export-XSLT cannot change the metadata of other processes. 
For these elements we create `ORDERLABEL/ORDER` with the import-XSLT. See also: 
- #4852

**Comment by matthias-ronge** [comment]
Yes, meanwhile I also know a way how this can be solved in XSLT. The disadvantage is that you only get it when you export it. @solth, do you think we still need this function? For me, the XSLT solution is fine too.

**Comment by andre-hohmann** [comment]
> The disadvantage is that you only get it when you export it.

Is it a disadvantage? If you change the metadata by script or manually, you have to export the data anyway - at least it is that way in the SLUB Dresden. 
I admit, that a solution by script could be helpful, if "special cases" needs to be modified, which cannot be realized by the export-XSLT. In my opinion, the ORDERLABEL and LABEL are applied usually globally. 

Probably, you could apply the [Metadaten Skripte](https://github.com/kitodo/kitodo-production/wiki/Metadaten-Skripte) to modify "special cases".

**Comment by matthias-ronge** [comment]
The metadata scripts cannot handle this case, because the value is not stored in the metadata section. This needed extra programming

**Comment by BartChris** [comment]
> The disadvantage is that you only get it when you export it. @solth, do you think we still need this function? For me, the XSLT solution is fine too.
If this is also about displaying the Labels in Kitodo i think what would massively help is the implementation of the ideas outlined here: https://github.com/kitodo/kitodo-production/discussions/4925 

Then the title could be assigned as a functional key used for displaying the LABEL. The way we tackle that is that we almost always assign a LABEL. And only use the "title"-element when the thing in question actually is a title in the bibliographic sense, not just a label. In those cases on could leave out the label and just generate it in XSLT.

**Comment by andre-hohmann** [comment]
Thanks for clarifying. I think i understand the aim now. 
However, as @BartChris pointed out, similar issues should be regarded - maybe a general solution can be found. 
- #4852 
- #4925

**Comment by matthias-ronge** [comment]
To clarify: I no longer need this function because the XSLT solution exists. But it's working programming that I've developed, and I think it would be a shame to just throw it away when it might be of use to someone again. The KitodoScript section is a tool kit. Many things prove useful again and again. So I would still merge this development because it's a working tool. Nobody has to use it and it doesn't bother there.
