### ISSUE TITLE
Search and filter improvement - Bundle

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#5020]
In Kitodo.Production 3.x the search for metadata or properties is not clear and in some cases unreliable. Furthermore, the filter of administrative data (users, authorities, projects ...) is not existing or unreliable. In addition, it is difficult to assess the differences of the filter, the search and the extended search. 
The search and filter functions should be improved by standardization and documentation. 

The **cost estimation** is expected to be: **high**

High costs are expected, because the analysis and the identification of possible solutions in each case will take probably a lot of time. Especially the assessment of the the search for metadata or properties needs comprehensive coordination with the community. 

_Especially the following issues regarding the properties (also in the development fund 2022 and development fund 2023) must be regarded_
- #3335
- #4317 
- #4674 

_There are some issues which are related to the search and filter_:

- #3301
- #3341
- #3511
- #3512
- #3519
- #3606
- #3341
- #4792
- #4960
- #4980
- #4981
- #5019
- #5212
- #5473 
- #5492

**Comment by matthias-ronge** [comment]
Search in issues for: [is:open is:issue label:search](../issues?q=is%3Aopen+is%3Aissue+label%3Asearch+sort%3Acreated-asc)

**Comment by andre-hohmann** [comment]
For the following reasons, i am closing this bundle-issue, which was created for `development fund 2022`. Two years after the creation of this bundle-issue, the requirements regarding the search should be thoroughly re-examined and a new issue should be created.

1. Some of the issues, which are listed in this bundle-issue have been already solved and the original cost estimation might have been changed. 
2. The project [Hibernate Search and search index](https://github.com/orgs/kitodo/projects/7) will probably have influence on several issues, which are listed in this bundle-issue. In the worst case, the projects will block each other and/or cause a high coordination effort instead of the development of functionality.

**Comment by andre-hohmann** [comment]
It seems that I have no authorization to close this issue. Maybe someone with the permissions can do this.
