### ISSUE TITLE
Automatically assign subsequently created child process to parent

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#5072]
When I create a process as a child via the plus button

![Screenshot creating a child process](https://user-images.githubusercontent.com/3040657/164715789-38b38871-cc39-43e9-b6d9-1f7022618de7.png)

and complete the process creation with save-and-new

![Screenshot using save-and-new button](https://user-images.githubusercontent.com/3040657/164715848-3d951c00-2fe0-4535-b92a-e299e85198be.png)

then the second process created will not be created as a child of the same parent, but as a standalone process—unless I manually re-attach it on the "Title record link" tab.

**Goal:** If I create a child process via the plus button, after save-and-new, the next process should be another child of the same parent, that means, the parent connection on the "Title record link" page shall already be pre-filled.

**Comment by andre-hohmann** [comment]
@solth : 
No, it is not the opposite. It would be absolutely fine, if children processes are created for the parent document via "Save + New". 

In #4920 it is described that it should not be possible to link a new imported process with another process, which has no relation to it. In #4920 for example, a monograph has been linked to a multivolume work, wich must not be possible. 

Thus, the following aspects must be regarded: 
- Is the button "Save + New" or "Data transfer" used?
- Are volumes of the same parent process or new processes created?
