### ISSUE TITLE
NPE on GalleryPanel on non defined media directory

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#5099]
A null pointer exception is thrown if no media or preview folder is defined in a project and a process of this project is opened in the meta data editor:

```
java.lang.NullPointerException
        at org.kitodo.production.forms.dataeditor.GalleryPanel.getMediaViewMimeType(GalleryPanel.java:163)
        at org.kitodo.production.forms.dataeditor.GalleryMediaContent.getMediaViewData(GalleryMediaContent.java:98)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

The null pointer exception is created on accessing the folder information and is set explicit to `null` if there is no media folder defined [GalleryPanel.java#L403](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/GalleryPanel.java#L403) and [GalleryPanel.java#L405](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/GalleryPanel.java#L405) but there is no check if this the case later on working with the value ([GalleryPanel.java#L187](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/GalleryPanel.java#L187) and [GalleryPanel.java#L163](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/GalleryPanel.java#L163)).

This could maybe be solved if there is not an other issue #5097 which is preventing adding new folder information to existing and new projects. 

But the application should even work if there are no media folder(s) defined inside the project settings and not show a null pointer exception to the user. The application may should show in this case a nice warning message that there are no media folders in the project are defined and no pictures will be shown.

**Comment by matthias-ronge** [comment]
The problem here is that the `<p:graphicImage>` for the media view is not `rendered` conditionally, but shall be shown even if there is no data.

**Comment by matthias-ronge** [comment]
Adding the `rendered` attribute should fix it: https://github.com/matthias-ronge/kitodo-production/pull/new/issue-5099

**Comment by henning-gerhardt** [comment]
@matthias-ronge : please open one or two pull requests which solve this issue. My approach to solve it is created with my knowledge about how to fix it.

**Comment by matthias-ronge** [comment]
This is just my conclusion from looking at the problem. I must test the change first …

**Comment by solth** [comment]
@henning-gerhardt I am unable to reproduce this error with the current master. Could you check if it solved for you as well?

**Comment by henning-gerhardt** [comment]
Looks like the issue is solved. On disabled media / preview projects settings the pictures are not shown in a direct way (only some placeholder images in amount of the original media files are shown). How this is maybe missing information later used or not, is not part of this issue.
