### ISSUE TITLE
Build process occasionally hangs under Windows

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#5130]
Running `mvn clean install` sometimes hangs under Windows in step _copying webapp resources…_

![Screencast](https://user-images.githubusercontent.com/3040657/167443679-b1f576af-84ea-407b-ae82-0bed09e470e0.gif)

Workaround is to press <kbd>Ctrl</kbd>+<kbd>C</kbd> and restart the build process.

**Goal:** Build should complete (or give an exception, if it can’t).

**Comment by Kathrin-Huber** [comment]
I literally NEVER had this problem...
I see, that your resources are under D: maybe there is an issue with network reachability?

**Comment by matthias-ronge** [comment]
This isn’t happening anymore and I still don’t know what caused the problem.
