### ISSUE TITLE
Error creating links to child processes in metadata editor

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#5142]
When adding new child processes to a process in the metadata editor via the context menu option `Add Element` and then `Link`, the link to the child process is added to the mets structure of the current process, but the current process is not set as parent process to the added child process.

**Comment by matthias-ronge** [comment]
Updating the links in the database was implemented to happen when you click save. [Here](https://github.com/kitodo/kitodo-production/pull/2602/files#diff-6543641a24476d529daa735f5a340b415b7d011f2d0573875e632ffd88595513R279) is where this initially came in, and [here](https://github.com/matthias-ronge/kitodo-production/commit/65044594a4185ced4f5373587d59d3e99a1c1283#diff-6543641a24476d529daa735f5a340b415b7d011f2d0573875e632ffd88595513L282) it went lost.

**Comment by solth** [comment]
Any idea _why_ you removed the call to `updateChildrenFromRootElement`?

**Comment by matthias-ronge** [comment]
This just looks like an accident. The function is still there in `ProcessService` but was renamed meanwhile:

    processService.updateChildrenFromLogicalStructure(process, logicalDivison);
