### ISSUE TITLE
Initial indexing of processes and tasks failed

### ISSUE THREAD

**Issue by joerg-liebenow** [kitodo/kitodo-production#5196]
Since release 3.4.3 an initial indexing of processes and tasks failed with errorlog messages like
#
[ERROR] 2022-06-07 09:37:58.069 [http-nio-10480-exec-7] DesktopForm - errorLoadingMany
org.kitodo.data.exceptions.DataException: Not possible to retrieve boolean value for key hasProcesses. Exception: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.Map.get(Object)" is null
#
for processes and
#
[ERROR] 2022-06-07 09:47:34.491 [Indexing 0 of type PROCESS] ErrorTracker - <AST>:1:101: unexpected AST node: OR
antlr.NoViableAltException: unexpected AST node: OR
#
for tasks

**Comment by thomaslow** [comment]
Hello Joerg, the ElasticSearch mapping has changed in this release. Have you tried deleting the index and re-creating the mapping?
![image832](https://user-images.githubusercontent.com/6214043/172608941-de144cc6-35e8-4efb-b898-7d43a8351576.png)

**Comment by joerg-liebenow** [comment]
Hello Thomas,
yes i delete the index and then i re-create it. If i start the indexing one after one, all parts will do the indexing but processes and tasks start but then nothing happen and the sytem hang !

I found the problems in the sourcecode too:
Kitodo-DataManagement/src/main/java/org/kitodo/data/database/persistence/TaskDAO.java
line 48 take the brackets away will results
     + " AND indexAction = 'INDEX' OR indexAction IS NULL ORDER BY id ASC",

and Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java
line 256 the same
     + " AND indexAction = 'INDEX' OR indexAction IS NULL");

This will help for that problem and processes and tasks will indexing !  

I will do a pull request for that, but to clone the repo in my private account in github to do that, seems to take ages !

**Comment by henning-gerhardt** [comment]
@joerg-liebenow : did you update ElasticSearch to 7.17.3 or 7.17.4 from a 7.10.x version?

**Comment by henning-gerhardt** [comment]
The mentioned issues in this two files with the brackets are introduced by 28befd3b78ca79bb5a2ef3eff299cc1542585031 and was not covered before :-(

**Comment by henning-gerhardt** [comment]
I did found a few more wrong and / or missing brackets introduced by https://github.com/kitodo/kitodo-production/commit/28befd3b78ca79bb5a2ef3eff299cc1542585031 and will open a pull request to fix this.

**Comment by joerg-liebenow** [comment]
> 
We use Version elasticsearch 7.10.2 !
