### ISSUE TITLE
Problems with the new import configuration

### ISSUE THREAD

**Issue by BartChris** [kitodo/kitodo-production#5219]
I have some problems transferring the current xml based configuration to the new import configuration (https://github.com/kitodo/kitodo-production/pull/5038). Right now i cannot make some catalogs work which worked before. It seems that some of the features got lost which originally ( https://github.com/kitodo/kitodo-production/pull/3374) allowed for the usage of arbitrary search interfaces. It would be good if those features could be ported to the new interface as well to make use of catalogs which worked before

I have some questions in this context:

-  The xml based configuration had a way to specfiy custom url parameters. This allowed to add parameters to the URL in additon to those which are given by the user query. How can something like that be done in the new interface?
```
<urlParameters>
    <param name="format" value="oai_mods" />
</urlParameters>
```
- What does Query delimiter actually stand for and what has to go there?

![grafik](https://user-images.githubusercontent.com/7516499/177597311-b2213e73-9358-4ecc-8783-3dbfad249700.png)

- Is it ensured that the mapping files are actually applied in the right order if i want to chain multiple transformations?

![grafik](https://user-images.githubusercontent.com/7516499/177595143-f89f2f33-c39d-4404-9187-b3fe9f476f00.png)

- How can a prefix for the identifier be specfied:

`<identifierParameter prefix="prefix:" value="id" />`

**Comment by solth** [comment]
> * What does Query delimiter actually stand for and what has to go there?
> 
> 
> ![grafik](https://user-images.githubusercontent.com/7516499/177597311-b2213e73-9358-4ecc-8783-3dbfad249700.png)

The query delimiter is an optional character in which the query part of the URL can be enclosed. This was necessary for some SRU interfaces like the "LfULG - DiGAS" where the query would need to be enclosed in `"` characters in order for the interface to process the query successfully.

**Comment by solth** [comment]
> * Is it ensured that the mapping files are actually applied in the right order if i want to chain multiple transformations?
> 
> 
> ![grafik](https://user-images.githubusercontent.com/7516499/177595143-f89f2f33-c39d-4404-9187-b3fe9f476f00.png)

Yes, the mapping files are saved in a list internally, preserving the order in which they have been assigned to the import configuration and ensuring they are applied in the correct order to the imported metadata file. In fact, an exception will be thrown if you try to save a an ImportConfiguration where 
- the input metadata format of the _first_ of a sequence of mapping files does not correspond to the metadata format of the ImportConfiguration, or
- the output metadata format of the _last_ file in the sequence of assigned mapping files is not "Kitodo", or
- the output format of one mapping file in the sequence of mapping files does not correspond to the input format of the next mapping file

**Comment by solth** [comment]
> * How can a prefix for the identifier be specfied:
> 
> 
> `<identifierParameter prefix="prefix:" value="id" />`

You are right, I missed this feature when implementing the new `ImportConfuguration` class. I will try to re-add it before the next release.

**Comment by BartChris** [comment]
I checked again and the problem seems to have to do with the missing ordering of the entries in the database table. I changed the following by hand:

![grafik](https://user-images.githubusercontent.com/7516499/177784438-060c435f-9083-4bb7-a132-35bda16f5937.png)

to:

![grafik](https://user-images.githubusercontent.com/7516499/177784496-24b56811-129a-4bd2-a467-79d16927e374.png)

so that the MARC converter comes first. Now everything works. We pobably need an "order"-column in the database to ensure that the mappings are applied in the correct order at runtime.

**Comment by solth** [comment]
> What is the specific purpose of giving an XPath to the parent element here? Is this used in a different context than the `higherlevelIdentifier`?

The `Parent element - XPath` setting is used to extract the catalog ID of the parent record of the imported record from the imported XML document.

The metadata configured as `higherLevelIdentifier` in the ruleset defines the internal metadata field in which the parent ID is saved.
