### ISSUE TITLE
Database migration fails on newer MySQL versions

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#5230]
**Describe the bug**
When migrating from 2.x, I get the following error:

> SQL-Befehl:
> 
> ```
> ALTER TABLE user_x_userGroup
>   CHANGE BenutzerID user_id INT(11) NOT NULL AUTO_INCREMENT,
>   CHANGE BenutzerGruppenID userGroup_id INT(11)
> ```
> 
> MySQL meldet:
> #1846 - ALGORITHM=COPY is not supported. Reason: Columns participating in a foreign key are renamed. Try ALGORITHM=INPLACE.

The command in question is in file `V2_1__Translate_columns_names_to_English.sql`.

**To Reproduce**
1. run database migration

**Expected behavior**
Database migration should migrate the database without crashing.

**Additional context**
As found [here](https://stackoverflow.com/a/46494304), this problem is caused due to a bug in older versions of MySQL, which did—in error—allow this command. This bug has now been fixed. Migration SQL must be rewritten, as explained in the link.

**Comment by henning-gerhardt** [comment]
Can you provide which MySQL or MariaDB version you are used and got this error? I migrate very often and did not get this error.

**Comment by matthias-ronge** [comment]
There were additional foreign key definitions in the database that shouldn’t have been there.
