### ISSUE TITLE
Import configuration: wrong usage of search identifier

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#5259]
**Describe the bug**

We have an OPAC catalogue where the search for an identifier did not work and results into an exception. The search is defined to use the search field `SATZNR` which get an unique identifer of this opac. The first query to this catalogue (for getting at maximum 10 entries) is working but the second query to the catalogue (to retrieve the data of the choosen or in this case to only one result) use a total different identifier which did not work with the given search field. Log entries show this

```
[DEBUG] 2022-07-18 06:54:11,601 [http-nio-127.0.0.1-8080-exec-6] org.kitodo.queryurlimport.QueryURLImport - Requesting: https://xxx/sru/au.sru?recordSchema=mods&operation=searchRetrieve&version=1.2&maximumRecords=10&query=SATZNR%3D%2200327678%22
[DEBUG] 2022-07-18 06:54:11,815 [http-nio-127.0.0.1-8080-exec-6] org.kitodo.queryurlimport.QueryURLImport - Requesting: https://xxx/sru/au.sru?recordSchema=mods&operation=searchRetrieve&version=1.2&maximumRecords=1&query=SATZNR%3DGA02615-00327678
[ERROR] 2022-07-18 06:54:12,014 [http-nio-127.0.0.1-8080-exec-6] org.kitodo.production.forms.createprocess.CatalogImportDialog - Premature end of file.
org.xml.sax.SAXParseException: Premature end of file.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261) ~[?:?]
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:?]
```

The second search use content of the `mods:mods/mods:recordInfo/mods:recordIdentifier` which is may in some use scenarios correct but not in this one and should be configurable.

**To Reproduce**
1. configure this opac
2. start a search with an unique identifier
3. got every time the exception message "Premature end of file."

**Expected behavior**
No exception and retrieving the data from this opac.

**Release**
3.4.4-SNAPSHOT since the new import configuration

**Additional context**
The import with this opac did work perfect before integration of the new import configuration and must work even with the new import configuration.

**Comment by andre-hohmann** [comment]
@solth : i talked about this issue with @henning-gerhardt and we wondered, if you may need more information about the behavior and if a solution is possible. 
Without the opportunity to import the metadata from this source, we will not be able to apply Kitodo.Production 3.x.

**Comment by solth** [comment]
I think this problem is caused by #5049

**Comment by henning-gerhardt** [comment]
No, this issue is not caused by #5049.

This catalogue is returning a `mods:recordIdentifier` as the second search request is using the content of `mods:recordIdentifier` but this catalogue needs a search term from `mods:identifier type='...'` entry or the given search term from the first query.

A second issue which I found: the second search did not respect or use the defined search delimiter for this catalogue.

I tested this with a modified version which change the used mods identifier field as even use the defined search delimiter of the catalogue which is working fine for my local system but I did not test this in a bigger and real world environment.

**Comment by solth** [comment]
I am pretty sure it's the same underlaying problem: the MODSResponseHandler expects the catalog ID to be stored in a specific MODS field, which is not always the case. If the XML response of your search interface does contain this field, the error triggered during import might differ, but the underlying cause is the same nonetheless.
