### ISSUE TITLE
Remove catalog configurations from "kitodo_opac.xml"

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#5262]
Since catalog configurations are now maintained using the new class `ImportConfiguration` introduced in #5038, the corresponding `<catalog>` entries in the main OPAC config file [kitodo_opac.xml](https://github.com/kitodo/kitodo-production/blob/156006e7cedcf145e20171546800468b19ad20e1/Kitodo/src/main/resources/kitodo_opac.xml) should be removed to reflect this change and to avoid confusion. 

**Note:** the catalog configurations from the corresponding _test_ configuration file [kitodo_opac.xml](https://github.com/kitodo/kitodo-production/blob/156006e7cedcf145e20171546800468b19ad20e1/Kitodo/src/test/resources/kitodo_opac.xml) should **not** be removed because it will be used for testing the upcoming `CatalogConfigurationImporter` (see #5224)

**Comment by BartChris** [comment]
By the way: The kitodo_opac.xml file seems to be necessary for creating a template. Will this be the case in the future as well or is the goal to completely remove the xml file for end users as it is intended for the kitodo_projects.xml  (see https://github.com/kitodo/kitodo-production/issues/3777) 

![grafik](https://user-images.githubusercontent.com/7516499/188101207-5d79d88f-b67d-48ca-8716-e6a17da56251.png)
