### ISSUE TITLE
Different validation for process creation with template

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#5269]
**Describe the bug**
The creation of processes for periodical volumes does not work, when metadata fields with selection lists are used. The following error messages are shown: 

- editForm:processFromTemplateTabView:metadataTable:19:selectOneMenu: Validation Error: Value is not valid
- editForm:processFromTemplateTabView:metadataTable:20:selectOneMenu: Validation Error: Value is not valid
- editForm:processFromTemplateTabView:metadataTable:23:selectOneMenu: Validation Error: Value is not valid
- editForm:processFromTemplateTabView:metadataTable:24:selectOneMenu: Validation Error: Value is not valid
- editForm:processFromTemplateTabView:metadataTable:25:selectOneMenu: Validation Error: Value is not valid

If the value of the selection field in the metadata fields is changed to "no selection". the error message disappears. 

**To Reproduce**
1. Create a process with a selection lists for several metadata fields for a periodical volume with [process template](https://github.com/kitodo/kitodo-production/wiki/Zeitschriften#band---mit-vorlage)
2. Try to save the process

**Expected behavior**

- It should be possible to create processes for periodical volumes with selection lists in the metadata fields.
- The behavior should be the same as for creation of the processes [without template](https://github.com/kitodo/kitodo-production/wiki/Zeitschriften#band---ohne-vorlage). 
- The error message should contain the label of the incorrect metadata field, not the table number. 

**Screenshots**
![ErrorProcessTemplates](https://user-images.githubusercontent.com/14835770/182096018-4b383f29-d1a4-4c0c-93f0-bfaaeacaefa3.jpg)

**Release**

- Kitodo.Production version 3.4.4

**Desktop (please complete the following information):**

- OS: Windows 10
- Chrome 103.0.5060.134 (Offizieller Build) (64-Bit)

**Comment by matthias-ronge** [comment]
Maybe related to #5270

**Comment by IkramMaalej** [comment]
@andre-hohmann: As discussed, this issue is resolved and can be closed.

**Comment by andre-hohmann** [comment]
The error cannot be reproduced anymore after using a newer master-version. The issue is closed. 

@matthias-ronge : As you thought that this issue might be related to issue #5270, you probably want to check if the #5270 is solved, too?
