### ISSUE TITLE
File names with dots are not working

### ISSUE THREAD

**Issue by BartChris** [kitodo/kitodo-production#5278]
**Describe the bug**
If a file name contains a dot Kitodo cannot differentiate the names, does not display all the images in the metadata editor and throws an error on saving. 

"Ambiguous canonical file name part in the same physical division"

**To Reproduce**
1. Name your files test.a-1.tif and test.a-2.tif
2. Try to open a process with the images in the medatada editor.

**Expected behavior**
Kitodo should support dots in a file name or unallowed charcters should be documented as other characters have problems as well:
https://github.com/kitodo/kitodo-production/issues/5044 

**Release**
3.4.4 SNAPSHOT

**Comment by henning-gerhardt** [comment]
This is only the case if you have more then one dot in the file name as your examples has two dots in the file name as the file extension is a part of the file name ;) But you are right that the application should handle this or it should be documented that certain characters are not allowed or should not used many times like the dot character.

**Comment by matthias-ronge** [comment]
Can you try to change you folder setting to add the extension, like this:

`images/(processtitle)_media` → `images/(processtitle)_media/*.tif`

Just guessing, but it might work

**Comment by IkramMaalej** [comment]
> Can you try to change you folder setting to add the extension, like this:
> 
> `images/(processtitle)_media` → `images/(processtitle)_media/*.tif`
> 
> Just guessing, but it might work

This suggestion doesn't work for me.
