### ISSUE TITLE
TSL/ATS is not created for children processes without an own title when superordinate process exists

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#5321]
**Describe the bug**
The `TSL/ATS` for volumes of multivolume works without title is not created, when the superordinate process exists. 

**To Reproduce**
1. Import process with K10plus-PPN 1371414327 -> TSL/ATS is created correctly
2. Import process with K10plus-PPN 1371421307 -> TSL/ATS is not created correctly and not written in the Field "Vorgangstitel"

See [SLUB Dresden Katalogimport](https://github.com/kitodo/kitodo-production/wiki/SLUB-Dresden---Katalogimport) for catalogue configuration. 

**Expected behavior**
The value of TSL/ATS should be written in the field "TSL/ATS". 
The value of TSL/ATS should be written in the field "Vorgangstitel". 

**Screenshots**
![tsl03](https://user-images.githubusercontent.com/14835770/186091169-79b1d171-1ba2-467b-a96a-6b241bab14a8.jpg)
![tsl04](https://user-images.githubusercontent.com/14835770/186091190-afa5657c-d969-4bb7-861b-de127329b05a.jpg)

**Release**
- 3.4.4-SNAPSHOT

**Desktop (please complete the following information):**
- OS: Windows 10
- Chrome 103.0.5060.134 (Offizieller Build) (64-Bit)

**Additional context**
See also: 
- #5208

**Comment by markusweigelt** [comment]
@andre-hohmann Tried to reproduce the error. In my case it works when importing from the PPN "1371421307" with K10Plus.  

![image](https://user-images.githubusercontent.com/3832618/187481691-ca7fc913-1225-4f6d-9853-11e823f8d180.png)

I configured the basic K10Plus according to the template. Possibly you can look at it again with?

**Comment by andre-hohmann** [comment]
@markusweigelt : i can confirm that the described behavior still exists. Is it possible that you have another master version?

![tsl01](https://user-images.githubusercontent.com/14835770/187596422-fe404109-954b-47a6-bf9b-c96ccf11f160.jpg)

![tsl02](https://user-images.githubusercontent.com/14835770/187596059-a50b4e0c-5193-40df-84c7-2811ffe1638e.jpg)

**Comment by markusweigelt** [comment]
@andre-hohmann Can now reproduce the error. Problem was that I have not saved the reproduction step 1.
