### ISSUE TITLE
SQL error V2_114__Add_metadata_record_id_and_namespace_to_importconfiguration.sql

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#5332]
**Describe the bug**
SQL file `Kitodo-DataManagement/src/main/resources/db/migration/V2_114__Add_metadata_record_id_and_namespace_to_importconfiguration.sql` gives a error:

    Error Code: 1175. You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column.  To disable safe mode, toggle the option in Preferences -> SQL Editor and reconnect.

**To Reproduce**
1. Migrate database until and including V2_113.
2. Run `V2_114__Add_metadata_record_id_and_namespace_to_importconfiguration.sql`

**Expected behavior**
SQL file should execute without errors.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/3040657/187223661-fc8322a5-f79a-411b-9e67-4ea90d551756.png)

**Release**
Current `master` branch

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 103.0.2

**Comment by henning-gerhardt** [comment]
I have already used this migration file but I did not get this kind of error. The mentioned fix in #5333 is maybe not bad but even not necessary.
