### ISSUE TITLE
Tomcat Folder with spaces

### ISSUE THREAD

**Issue by KHeindl** [kitodo/kitodo-production#540]
Due to the fact, that goobi uses two different data source connections, it is possible that hibernate works, but jdbc doesn't. Unfortunately it isn't that obvious, because login for example is working.
A special szenario (which i ran into) occures on windows. If goobi wants to use jdbc, but the tomcat is located in the programms folder "Program Files", there are spaces in the folder name. due to the wrong coding of the space, the tomcat folder is not found.
In my special case, the hibernate.config wasn't found, so the default values from src/de/sub/goobi/persistence/apache/SqlConfiguration were used which leads to an "access denied for user ..." error, which wasn't exactly the problem.

**Comment by henning-gerhardt** [comment]
I added a possible fix in PR #545. Does this changes help you?
