### ISSUE TITLE
Release 3.5.0-beta - Release Notes - Converter for kitodo_opax.xml

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#5442]
In the Release Notes there is given a hint, that a "converter" should exists, which converts existing `kitodo_opac.xml` to new `ImportConfiguration`, with reference to [Projektauswahl-und-Katalogsuche](https://github.com/kitodo/kitodo-production/wiki/Projektauswahl-und-Katalogsuche).
Unfortunately, I cannot find a hint to a converter tool behind this link.
Please clarify.

**Comment by solth** [comment]
The converter can be reached via "ImportConfiguration" tab on the "Projects" page:

<img width="797" alt="Bildschirmfoto 2022-11-17 um 13 55 37" src="https://user-images.githubusercontent.com/19183925/202452134-ea45470a-1003-4fa9-ad6b-ccf46b06e57b.png">

Please keep in mind that the new permissions to see the "ImportConfiguration" and "MappingFile" tabs on the "Projects" page are not assigned to any role by default, so you should add them to any role you find appropriate (e.g. "Administrator" or similar) or create a new role for these permissions.

**Comment by solth** [comment]
> Unfortunately, I cannot find a hint to a converter tool behind this link.

I added a section decribing the catalog configuration converter to https://github.com/kitodo/kitodo-production/wiki/Projektauswahl-und-Katalogsuche

Since this issue only describes the missing documentation of that tool, I will close it. If you encounter a functional problem with the converter, please open a new issue for that or reopen this issue if you think the documentation is not yet sufficient.

**Comment by stefanCCS** [comment]
@solth:
I have tried to use the 'convertion' feature using the button "Import catalogue configurations".
Unfortunately, I get an empty dialog like this:
![image](https://user-images.githubusercontent.com/61045115/203325180-dfabf1a0-4e69-4a81-abbe-3a659878ab7a.png)

My /usr/local/kitodo/config folder contains
![image](https://user-images.githubusercontent.com/61045115/203325124-6e329926-68eb-4ee6-abc0-2a5b315cd16f.png)
With `kitodo_opac.xml` being the default one, provided with this new Release 3.5.0-beta,
and `kitodo_opac_old.xml` being my old `kitodo_opac.xml`.

Somehow, I have expected to see a choice of XML-Files (where I could have chosen for `kitodo_opac_old.xml`

--> please explain, what I should do?

P.S I do not have the rights to re-open this issue, maybe you would like to do this.

**Comment by solth** [comment]
The `kitodo_opac.xml` file in this release is empty because it is not used for configurations anymore. The converter is meant as a convenient way to transform **existing** legacy files. That's what I tried to document under https://github.com/kitodo/kitodo-production/wiki/Projektauswahl-und-Katalogsuche with the following:

"Zur Umwandlung **bestehender** Katalogkonfigurationen aus der `kitodo_opac.xml` bietet Kitodo einen Konverter an. "

So you should use your `kitodo_opac_old.xml` file with your custom configurations and rename it back to `kitodo_opac.xml`. Than the converter will find it.

**Comment by solth** [comment]
Correct

**Comment by stefanCCS** [comment]
Well, next issue concerning this new feature:
I will not be asked for a catalogue import during process generation.

Then, I have found a new configuration possibility for a project:
![image](https://user-images.githubusercontent.com/61045115/203341996-fa4df1f8-0efc-4c5b-8e96-df11c365cdc9.png)
Which could be set e.g. to "K10Plus" in my case.
If I do this, "K10Plus" is chosen as default catalogue and I have the possibility to chose also the other catalogues.

So far, so good, but maybe another hint in the documentation would be fine, like:
"You need to set in Project setting the Default Import Configuration" (Maybe incl. Screenshot)

**Comment by stefanCCS** [comment]
Doing this I get this error here:
![image](https://user-images.githubusercontent.com/61045115/203342815-7dc49583-b671-4b50-ad7b-32457310afa9.png)
Which is a bit strange, as I have chosen "K10Plus" and behind "K10Plus" my mapping file is "pica2kitodo_k10plus_CCS.xsl".
Whereas "pica2kitodo.xsl" is the default one, provided with the Release.

**Comment by stefanCCS** [comment]
Checking the setting in the UI for "K10Plus" I have found this:
![image](https://user-images.githubusercontent.com/61045115/203343696-c2eb28f5-2b32-41df-8186-c8f882ecd862.png)
--> it looks like that the "converter" does not set the correct mapping file.
--> in my opinion this is a bug
--> please clarify

**Comment by solth** [comment]
> So far, so good, but maybe another hint in the documentation would be fine

There is already a note in the documentation describing the option to set a default import configuration for a project:

<img width="921" alt="Bildschirmfoto 2022-11-22 um 15 45 09" src="https://user-images.githubusercontent.com/19183925/203343858-2e45898e-53b0-469c-986b-e38a728d2acf.png">

**Comment by solth** [comment]
> --> it looks like that the "converter" does not set the correct mapping file.

Yes, this is something I noticed as well. If there is another mapping file in the system providing the same mapping as the one configured in the catalog configuration in `kitodo_opac.xml`. This warrants a separate bug ticket.

**Comment by stefanCCS** [comment]
Found this on the other other Tab ("Details"):
![image](https://user-images.githubusercontent.com/61045115/203344667-6c147719-27c5-4ae5-b99f-e3e4878d47fd.png)

--> looks like a non-mandatory field (without "*") might be mandatory ...

**Comment by stefanCCS** [comment]
> > --> it looks like that the "converter" does not set the correct mapping file.
> 
> Yes, this is something I noticed as well. If there is another mapping file in the system providing the same mapping as the one configured in the catalog configuration in `kitodo_opac.xml`, the wrong mapping file might get assigned. This warrants a separate bug ticket.

Should I create a new Bug Issue, or will you do it by yourself?

**Comment by solth** [comment]
> Should I create a new Bug Issue, or will you do it by yourself?

I will do that.

**Comment by solth** [comment]
> --> looks like a non-mandatory field (without "*") might be mandatory ...

This issue is more or less already documented at #5238 (although its the other way round in that case): the error message is lost when the error during saving occurs on another tab of the import configuration edit form, so we cannot update the active tab automatically.

**Comment by stefanCCS** [comment]
> > --> looks like a non-mandatory field (without "*") might be mandatory ...
> 
> This issue is more or less already documented at #5238 (although its the other way round in that case): the error message is lost when the error during saving occurs on another tab of the import configuration edit form, so we cannot update the active tab automatically.

In my opinion this is just one part of the error ("not seeing the error cause").
The other part is in my case here: Why do I get an error at all? (I only have changed the mapping file, and a non-mandatory field is marked "red" when pressing "save).
