### ISSUE TITLE
Multiview state warning

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#5444]
**Describe the bug**
In certain usage scenarios the message

```
[warning] Multiview state for viewId: "/pages/searchResult.xhtml" and clientId "searchResultTabView:searchResultForm:searchResultTable" not found
```

appears in the catalina.out of the running Tomcat instance. This message is maybe introduced by #5358.

**Expected behavior**
If this warning message is important then they reason should be found and fixed so this message did not appear anymore.

**Release**
3.4.4-snapshot and 3.5.0-beta-1

**Comment by thomaslow** [comment]
Hi Henning. This message is not important. I will add a fix that will hide the message.
