### ISSUE TITLE
Github builds failing because requests to LoC resources are blocked

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#5449]
**Describe the bug**
The files `mets.xsd`, `xlink.xsd` and `marc21slim2mods.xsl` are downloaded from the website of the Library of Congress (loc.gov) during builds of Kitodo.Production and are used for test cases and to automatically create Java classes for METS concepts like `StructLink`, `MdSec`etc. Since about two weeks, these downloads fail when initiated by automatic Github builds that are triggered by each new commit, with http status code **403** ("forbidden") and the following error message in the build log:

```
Could not get content
org.apache.maven.wagon.authorization.AuthorizationException: authorization failed for https://www.loc.gov/standards/mets/version111/mets.xsd, status: 403 Forbidden
```

This also means builds triggered by pull requests will fail and automatic tests and other checks are not performed. This hinders further development and must be fixed before any new pull requests can be merged.

A potential fix could be to add all auto generated Java files to the repository and thus make builds independent of the availability of resources from loc.gov. A draft version for this fix has been implmented in 441169ff7da92d0c10cafda50d95f303ac5f28c5 and indeed seems to resolve the issue (the corresponding build was successful, marked by the green check mark) but before this fix can be merged to the master branch it has to be verified that adding those auto generated files without the Kitodo license header is unproblematic or not.

**To Reproduce**
1. Commit changes and push to repository or fork of repository

**Expected behavior**
Builds should not fail

**Additional context**
The requests for the loc.gov resources succeed and the files are downloaded when triggered by builds on my local development environment. This presumably means only requests from Github to loc.gov resources are blocked specifically.

**Comment by thomaslow** [comment]
We could temporarily switch over to Archive.org:

https://web.archive.org/web/20220930194744if_/https://www.loc.gov/standards/mets/version111/mets.xsd

It definitely shouldn't be used as a permanent solution, though. Just to not bring the current development efforts to a halt.

**Comment by henning-gerhardt** [comment]
This did not work (we tried it with an mets.xsd mirror on GitHub itself) as the xsd file contain links to other xsd on loc.gov :-(

**Comment by solth** [comment]
Yes, initially I thought we could just switch to another source for the download, too. There is even an official METS repository here on Github from where we could obtain the `mets.xsd` schema definition: https://raw.githubusercontent.com/mets/METS-schema/Version-1.11/mets.xsd

I tried this approach, but unfortunately it didn't work, because the `mets.xsd` contains a link to another schema definition file (`xlink.xsd`) on the loc.gov server (http://www.loc.gov/standards/xlink/xlink.xsd) and and here at the latest the build will run into the same problem again. 

So in my opinion the best solution would be to become independent of those online resources whose availability is sketchy at best.

**Comment by solth** [comment]
Ninja'd by @henning-gerhardt !  :ninja:

**Comment by henning-gerhardt** [comment]
> So in my opinion the best solution would be to become independent of those online resources whose availability is sketchy at best.

Or by separating the modules into separate source code repositories and linking them with the GitHub maven repository together. So the modules must only be build if there are changes inside. But doing this takes a lot of work :-( And this should to go into a separate discussion

>  Ninja'd by @henning-gerhardt !  ![image](https://user-images.githubusercontent.com/2129672/203516345-d1584d02-1a36-4984-a458-b343f4871139.png)

Better two answers then none.

**Comment by thomaslow** [comment]
Just guessing here (for the purpose of finding a relatively easy solution). Do you think it would be possible to create a mirror of all relevant xsd files, and modify them such that the `xmlns="some-url"` definitions point to the mirror and will not cause a request to the `loc.gov` website?

**Comment by solth** [comment]
Maybe it's is possible, but I am unsure about any license related incompatibilities if we want to change the content of xsd files that fall under a different open source license then Kitodo.

I am not convinced that automatically generating the corresponding Java classes from downloaded schema definitions brings any real advantage anyway. It's a technically interesting solution, but IMO does not really justify the unclear licence situation and the dependence on the availability of certain online resources.

If the solution outlined in the issue description (add auto generated Java files to repository, remove part where XSD files are downloaded and used for dynamic Java class generation, see commit https://github.com/kitodo/kitodo-production/commit/441169ff7da92d0c10cafda50d95f303ac5f28c5 as mentionend above) solves the problem, too, and does not impose licensing issues, I would propably prefer it.

**Comment by thomaslow** [comment]
From a technical perspective, the proposed solution would be fine, of course. 

Any potential licensing concerns probably can not be resolved on GitHub. Still, just for context, there seem to be a lot of library-related OpenSource projects that simply include the XSD files in their repositories. Just search for the files on GitHub:

- [mets.xsd](https://github.com/search?q=%22The+Digital+Library+Federation%2C+as+creator+of+this+document%2C+has+waived+all+rights+to+it+worldwide+under+copyright+law%22&type=code)
- [xlink.xsd](https://github.com/search?q=%22METS+XLink+Schema%2C+v.%22&type=code)
- [marc21slim2mods.xsl](https://github.com/search?q=%22Expanded+script+template+to+include+code+conversions+for+extended+scripts+-+2010%2F09%2F22+tmee%22&type=code)

Most notably, OCR-D (Apache 2.0) includes both [mets.xsd](https://github.com/OCR-D/core/blob/master/ocrd_validators/ocrd_validators/mets.xsd) and [xlink.xsd](https://github.com/OCR-D/core/blob/master/ocrd_validators/ocrd_validators/xlink.xsd) in their repository.

**Comment by solth** [comment]
> Most notably, OCR-D (Apache 2.0) includes both [mets.xsd](https://github.com/OCR-D/core/blob/master/ocrd_validators/ocrd_validators/mets.xsd) and [xlink.xsd](https://github.com/OCR-D/core/blob/master/ocrd_validators/ocrd_validators/xlink.xsd) in their repository.

Thanks a lot for pointing this out. Based on that I created another pull request (#5461) adding the schema definitions instead of the auto generated Java files which also resolves the issue.

@henning-gerhardt, @thomaslow, @matthias-ronge (everyone elses opinion is welcome, too, of course!): before deciding on which pull request to merge, I would like to hear your opinions on both solutions and which route you think we should take. Anyway, this issue needs to be addressed as soon as possible, so I plan to merge one of both PRs in the next few days.

**Comment by henning-gerhardt** [comment]
In my opinion the second pull request (5461) is the better one as updating the used / needed xsd files is easier then to re-generate the class files if an update is necessary or should performed.
