### ISSUE TITLE
Rel 3.5.0-beta - Import of additional metadata - field was added, even if it was there before

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#5454]
I have tried out the feature of "Import of additional metadata" with the following data
1) Create process with meta data of K10plus, ppn=1022427806
2) Add metadata from HEBIS, ppn=058289550

==> this has created a 2nd entry of "Haupttitle (METS)" like this
![image](https://user-images.githubusercontent.com/61045115/203745166-f8019a15-6608-44ab-86e0-a5c9c2092ed3.png)

Which IMO should not be the case (only new fields are filed, but no "overloading" is done).

Please be aware, that this is a METS-Field in the RuleSet-Definition (maybe this is the cause for this behavior):
```
		<key id="LABEL" domain="mets:div">
			<label>Main title ‹METS›</label>
			<label lang="de">Haupttitel ‹METS›</label>
		</key>

```

**Comment by solth** [comment]
@markusweigelt can you comment on this issue?

**Comment by markusweigelt** [comment]
@solth Fixed in PR #5500

**Comment by IkramMaalej** [comment]
Based on my understanding, I would say, this is not an issue. More than one Metadata with the same key is possible to have. This is configurable through the ruleset with `maxOccurs` attribute.
 In this exemple: `<permit key="LABEL" maxOccurs="1"/>` the metadata 'LABEL' is only allowed one time.

**Comment by markusweigelt** [comment]
As i decribed here https://github.com/kitodo/kitodo-production/wiki/Projektauswahl-und-Katalogsuche for additional import ruleset is not considered at the moment. So may be `LABEL` is configured with `maxOccurs` 2 in ruleset (what is not useful for an attribute) of stefan. The problem in this case was, that LABEL is treated somewhat differently than other metadata, so to consider that I did some changes to match the behaviour of documentation.
