### ISSUE TITLE
Rel 3.5.0-beta - Feature "Import of additional metadata" - Unclear behavior for "Persons"

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#5456]
I submit this here as "non-categorized" issue, but I assume, that this is more a discussion.
Please feel free to convert it accordingly.

I have tried out the "Import of additional metadata" feature, which works fine in general for the main meta data of a document (see also my comments on #5453, and #5454).

What I refer here to is the - at least for me  - not clear behavior, what to do with "Person" meta data (or in general, meta data, which are in a kind of substructure).
In my RuleSet I have the following definition for a "Person" (and I hope, this matches my intention):
```
<key id="Person">
	<label>Person (group)</label>
	<label lang="de">Person (Gruppe)</label>
	<key id="LastName">
		<label>Last name</label>
		<label lang="de">Familienname</label>
	</key>
...
        <key id="RoleCode">
        <label>Relationship designation (code)</label>
        <label lang="de">Beziehungskennzeichnung (Code)</label>
        <option value="rcp">
	        <label>Adressat</label>
        </option>
...

<restriction division="Monograph" unspecified="forbidden">
...
	<permit key="Person">
		<permit key="RoleCode" maxOccurs="1" minOccurs="1"/>
	</permit>
...

```
Which means IMO, that I can have many "Persons", as long as they have different RoleCodes.

The current implementation of the  "Import of additional metadata" -Feature looks like to work this way:
If a "Person" already exists, then any new "Person" retrieved from the additional data is not considered at all (independent of "RoleCode").

If this is intended, then I would like to have an according hint in the documentation.

Or maybe this needs an additional discussion round at least with the original owner of this change (SUBHH?).
@subhhwendt : Was this build on your request?

**Comment by solth** [comment]
I think @markusweigelt could help answer this question because he developed this feature, IIRC.

**Comment by stefanCCS** [comment]
@markusweigelt : Can you please answer my question from above?

**Comment by stefanCCS** [comment]
@markusweigelt:  Many thanks for your good explanations.
As you have proposed for the future it might be good, if a new "discussion" item is created, in case there is a really need (which I am not sure about).
I will think about it and maybe will create this, or of course you (or somebody else) can do this.

For now, in my opinion it will be very helpful, if you "just" create a documentation, which describes the possibilities and constraints of the current "additional import"-Feature.

@solth : Please feel free to close this issue or to keep it open until the documentation is done

**Comment by solth** [comment]
I agree, once this feature is documented (for example by adding a small section to https://github.com/kitodo/kitodo-production/wiki/Projektauswahl-und-Katalogsuche) the issue can be closed.

@markusweigelt do you mind adding a small description of the feature to the documentation page linked above?

**Comment by markusweigelt** [comment]
Yes. Just added a short description of the behavior of the "additional import" to documentation page.
