### ISSUE TITLE
Second default import configuration for creating child processes

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#5460]
**Is your feature request related to a problem? Please describe.**
Currently, Kitodo.Production allows defining a single default `ImportConfiguration` for a project that is used whenever a new process is created in a that project. This is sufficient in many cases, but when a project contains monographs _and_ newspapers, where new newspaper volumes are to be created from a template newspaper volume process, it is cumbersome to first close the configured default catalog search import configuration for creating monographs and then manually open the template process dialog every time a newspaper volume is created.

**Describe the solution you'd like**
It would be helpful to have an optional second default `ImportConfiguration` that is specifically used for creating new child processes for an existing parent process:
- first default configuration is used when user clicks on "+" symbol in **project** list
- second default configuration is used when user clicks on "+" symbol in of a parent process in **process** list

To prevent confusion and better distinguish between these two they could use different icons:
- "+" in **project** list keeps using https://fontawesome.com/v4/icon/plus-square
- "+" in **process** list is changed to https://fontawesome.com/v4/icon/plus-circle 

@subhhwendt please feel free to add any further points I may have forgotten!

**Comment by subhhwendt** [comment]
Only a tiny detail - may be it's confusing to refer to "newspaper". Here we have the calendar icon for the specific way of creating processes for newspaper. The need for a second default ImportConfiguration belongs to the world of "journals", where we add processes for volumes by process template.

**Comment by solth** [comment]
You are right, sorry, I got those two confused. But if I understand you correctly, this is just a terminological issue, isn't it? As discussed earlier, I would propably rather take a generic route and call the second configuration something like "Default import configuration for creating child processes" instead of refering to "Newspaper" or "Journal". Would that work for you, too?

**Comment by subhhwendt** [comment]
The perspective of the ruleset defining a top level structure element is:

- use="createChildrenWithCalendar" => newspaper/"ephemera" (e.g. Theaterzettel)
- use="createChildrenFromParent" => creating processes by template 
- without a "use-Statement" => catalog import

Should we add "by template" in your suggested configuration name "Default import configuration for creating child processes" - for the perfect generic approach?

**Comment by solth** [comment]
> Should we add "by template" in your suggested configuration name "Default import configuration for creating child processes" - for the perfect generic approach?

So the labels for the two default import configuration on the "Edit project" page should read
- "Default import configuration" and
- "Default import configuration for creating child processes by template (process)"?

I guess we need the additional "process" (so "template process" instead of just "template") to avoid confussion because there are already entities called "templates" (e.g. "Produktionsvorlagen") in the Kitodo.Production, and _all_ new processes are created using such a "template", not just child processes. We should clearly distinguish between "production templates" and "template processes", in my opinion.

**Comment by solth** [comment]
> * "Default import configuration for creating child processes by template (process)"?

On a second thought if we should really restrict this second default import configuration to those with type "Template process". This will probably the case most of the time, but do we loose anything to potentially allow users to select other import configuations here as well? I would therefor opt for staying with "Default import configuration for creating child processes", if that is ok with you, @subhhwendt
