### ISSUE TITLE
How to fix “the number of nested documents has exceeded the allowed limit”?

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#5477]
Error “ElasticsearchStatusException: Elasticsearch exception [type=mapper_parsing_exception, reason=The number of nested documents has exceeded the allowed limit of [10000]. This limit can be set by changing the [index.mapping.nested_objects.limit] index level setting.]” occurs when saving large documents (here about 800 divisions, 2000 images).

The shell command

    curl -XPUT -H "Content-Type: application/json" 'localhost:9200/kitodo/_settings' \
        -d '{"index.mapping.total_fields.limit": 100000 }'

leads to the error “index not found”, the command

    curl -XPUT -H "Content-Type: application/json" 'localhost:9200/kitodo_process/_settings' \
        -d '{"index.mapping.total_fields.limit": 100000 }'

executes successfully, but does not eliminate the error. Even if you delete the index, recreate the index profile, then call the command and then reindex, this does not solve the problem. The error still occurs, still reporting the numerical value of a maximum of 10'000 allowed sub-documents, not 100'000, although 100'000 should have been set with the command.

**How can Elasticsearch be properly configured to overcome this limit?**

**Comment by henning-gerhardt** [comment]
There is already in an issue the solution flying around as we have this issue too. I will search for our used solution.

**Comment by henning-gerhardt** [comment]
As I see now, you are changing the wrong field. You must adjust the `index.mapping.nested_objects.limit` field and not the `index.mapping.total_fields.limit`:

`curl -XPUT -H "Content-Type: application/json" 'localhost:9200/kitodo_process/_settings' \
    -d '{"index.mapping.nested_objects.limit": 100000 }'`

**Comment by solth** [comment]
@matthias-ronge I think your question is answered, isn't it?

**Comment by matthias-ronge** [comment]
Yes
