### ISSUE TITLE
Deactivate filter option

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#549]
It is possible to filter processes in Kitodo.Production by users "Schritt abgeschlossen von Benutzer:"

![image01](https://cloud.githubusercontent.com/assets/14835770/19483136/9800b93c-9553-11e6-9410-fddcf9e5b824.jpg)

A request on the community mailing list [1] revealed that due to data privacy protection, this function is not needed or even rejected. To prevent manual disabling of the function after installing a new version it is hereby suggested to remove the function completely in Kitodo.Production. 

[1] https://maillist.slub-dresden.de/pipermail/kitodo-community/2016-July/000000.html

**Comment by henning-gerhardt** [comment]
Reactivation was done in pull request #443. But there some more files to change to remove this feature.
