### ISSUE TITLE
Searching for a process by title in linking dialogue search breaks for strings.

### ISSUE THREAD

**Issue by BartChris** [kitodo/kitodo-production#5509]
**Describe the bug**
If one searches for a string in the AddDocStructDialog

![grafik](https://user-images.githubusercontent.com/7516499/212746290-73aa881a-d02a-4d9c-a963-e9e1ab267ff5.png)

Elasticsearch throws an "search_phase_executuion_exception":

![grafik](https://user-images.githubusercontent.com/7516499/212746445-1ace07cd-4d42-452d-81bf-dbc70e328607.png)

**To Reproduce**
1. Go to the Dialog for adding a new structural element. Use the "linking" functionality.
2. Search for a string like "retro" 
3. You get an Elasticsearch exception

**Expected behavior**
The search should work. 

**Release**
Current Master

**Additional context**
It seems like both fields `id` and `title` are queries with a string. This might lead to an exception because `id` is defined of type `long` in the Elasticsearch mapping

![grafik](https://user-images.githubusercontent.com/7516499/212747554-985018ed-0541-4fd4-985e-02332334a95d.png)

I was able to fix that by defining setting the lenient attribute on the `id` field
https://javadoc.io/doc/org.elasticsearch/elasticsearch/7.5.0/org/elasticsearch/index/query/MatchQueryBuilder.html#lenient()

https://github.com/kitodo/kitodo-production/blob/964a09f5a4b6f5dd1bb19b0f480816487183befc/Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java#L765-L768

```java
 BoolQueryBuilder query = new BoolQueryBuilder()
                .should(new MatchQueryBuilder(ProcessTypeField.ID.getKey(), searchInput).lenient(true))
                .should(new MatchQueryBuilder(ProcessTypeField.TITLE.getKey(), "*" + searchInput + "*"))
                .must(new MatchQueryBuilder(ProcessTypeField.RULESET.getKey(), rulesetId));
```

I am still investigating wether the returned results are actually correct.

**Comment by solth** [comment]
@BartChris thanks a lot for reporting and analyzing this bug. I remember encountering it some time ago, too, but I didn't know it can be fixed this easily. Would you mind opening a pull request with your fix?

**Comment by BartChris** [comment]
@solth If i understand the current query correctly, a match is returned, if the process has the right ruleset and it's base type matches the allowed types. In my understanding even processes are returned which do not match by `id` or `title` since a  `should` query is used for them which just changes the relevance scoring but not the returned results. So the query should enforce that one of `title` or `id` have to match.
In addition to that i think when using wildcards we have to use the WildcardQueryBuilder. Therefor i would suggest rewriting the query like that:

```java
BoolQueryBuilder query = new BoolQueryBuilder()
                .must(new BoolQueryBuilder()
                        .should(new MatchQueryBuilder(ProcessTypeField.ID.getKey(), searchInput).lenient(true))
                        .should(new WildcardQueryBuilder(ProcessTypeField.TITLE.getKey(), "*" + searchInput + "*"))
                )
                .must(new MatchQueryBuilder(ProcessTypeField.RULESET.getKey(), rulesetId));
```
to actually enfoce that there is a match either on the the `id` or `title` field. I would probably also remove the wildcard in the beginning of the query since that can be very slow:

https://www.javadoc.io/doc/org.elasticsearch/elasticsearch/6.0.1/org/elasticsearch/index/query/WildcardQueryBuilder.html

so i would suggest this query:

```java
  BoolQueryBuilder query = new BoolQueryBuilder()
                .must(new BoolQueryBuilder()
                        .should(new MatchQueryBuilder(ProcessTypeField.ID.getKey(), searchInput).lenient(true))
                        .should(new WildcardQueryBuilder(ProcessTypeField.TITLE.getKey(), searchInput + "*"))
                )
                .must(new MatchQueryBuilder(ProcessTypeField.RULESET.getKey(), rulesetId));
        List<ProcessDTO> linkableProcesses = new LinkedList<>();
```

**Comment by henning-gerhardt** [comment]
Is the above possible changed code code which is used in the search form? Then it should still be possible to use partials of a search context to get hits back (left and right side truncating search) like a newspaper search with an used newspaper identifier like PPN and you get all processes of this PPN back independent how the f.e. process title is generated.

**Comment by henning-gerhardt** [comment]
No, you understand my question wrong: I would only know if your suggested change change the search from the search form. Your answer answered me the question itself: no this are different queries which should - in my opinion - stay independent.
