### ISSUE TITLE
NPE in metadata editor when MediaView is not configured in project

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#5532]
**Describe the bug**
#5405 introduced an improvement where the first medium of a selected structure element would be automatically shown in the gallery of the metadata editor. However, this revealed a bug in the system where a Null Pointer Exception would be thrown when the obligatory `MediaView` folder is not configured in a project settings and the user opened a process of that project in the metadata editor with at least one medium assigned to the root element (e.g. not assigned to any other structure element). 

This exception is caused by the hidden `p:graphicImage` element in the file `gallery.xhtml` with ID `mediaViewData` - that is meant for storing the image to be displayed in the OpenLayers component of the gallerys detail view - not checking for a complete project configuration but instead always trying to load the mime type of said `MediaView` project folder configuration.

**To Reproduce**
1. Create a project where a folder is correctly configured as `MediaView`
2. Create a process in that project
3. Add at least one image to the process and save the process so that the image is assigned to the logical root node
4. Change the project configuration and remove the configuration for the `MediaView` folder
5. Open the process in the metadata editor again
6. Observe the NPE

**Expected behavior**
Either setting a `MediaView` folder in the project settings should be mandatory or (better) the function loading the image for the OpenLayers detail view of the metadata editor gallery should check whether the `MediaView` is properly configured or at least not null before trying to retrieve it's mime type. In any way, a NullPointerException should not be displayed in the circumstances described above.

**Screenshots**
![Bildschirm­foto 2023-02-06 um 17 38 38](https://user-images.githubusercontent.com/19183925/217238753-5569a57c-26e2-4aae-807b-42316e7afb60.png)

**Release**
3.6.0-SNAPSHOT

**Comment by henning-gerhardt** [comment]
Is this maybe related to https://github.com/kitodo/kitodo-production/issues/5099 ?

**Comment by solth** [comment]
Yes, you are correct. Closing this as duplicate of #5099
