### ISSUE TITLE
Rename jpegs after changing sequence in Kitodo 3

### ISSUE THREAD

**Issue by apiller** [kitodo/kitodo-production#5601]
In Kitodo 2 was a subpoint of pagination to regenerate filenames after changing the sequence of the scans. 
It was useful after adding or deleting pictures. Especially when URN granular is generated afterwards based on the filenames. 
As far as I see there was no implementation of this feature in Kitodo 3. 
There is no possibility to delete or add pictures afterwards either. 

Is there by any chance a possibilty that I just overlook the features or is there no implementation yet?

**Comment by apiller** [comment]
Yes this would help partly. Actually I am not able to reproduce this picture. The point adding a medium is missing. Is this because of our old version (3.3.1) or do I have to add permissions to the task/role? 
The point deleting the element is just for deleting the structure element or medium/structure in general?

**Comment by subhhwendt** [comment]
@apiller "Medien hochladen" and "Medien löschen" are configurable elements in rolemanagement since Version 3.5

@solth We want to discuss with you pretty soon if it's feasible and(!) reasonable to build a function for renaming filenames according to the value of "ORDER". Analyzing different examples/situations in Metadataeditor we are feeling hope to do so.

**Comment by apiller** [comment]
@subhhwendt Do you have any idea how much time this would take? Because we need this pretty soon otherwise we have to change our workflow completely. Maybe we can share the effort somehow.

**Comment by solth** [comment]
As discussed this will be implemented as a button in the metadata editor that allows renaming image files corresponding to their current order while adding a configurable number of leading zeros.
