### ISSUE TITLE
Disable pagination on metadata editor start

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#563]
When opening the metadata editor, an automated pagination is conducted. Depending on the value of `MetsEditorDefaultPagination`, pages are added either `uncounted`, or with `arabic` or `roman` counting. Unlike clicking the link to manually read in the pagination from the images, the automatic pagination does not output validation errors. It is not possible to disable the automatic pagination completely, which may result in errors which should be reported in this place slipping through the whole workflow without being noticed. It is not possible to track whether the link to manually read in the pagination from the images was ever clicked or not in a later quality control step.

So a feature shall be added to completely disable the automatic pagination. This will force the person in charge to input the pagination to manually click the link, for that he or she may return the process to a previous step if there are image errors.

The development of this feature is funded by Staatsbibliothek zu Berlin − Preußischer Kulturbesitz.

**Comment by matthias-ronge** [comment]
@henning-gerhardt What do you think is better? Commenting out the `MetsEditorDefaultPagination` to disable it, setting it to `off`, or to `false`?

**Comment by henning-gerhardt** [comment]
Why not add a parameter to enable / disable automatic pagination (`withAutomaticPagination` with values `true` / `false`)? Overloading parameters is not a good decision in my opinion.

Was automatic pagination not added as a requirement for massive newspaper processing?

**Comment by matthias-ronge** [comment]
No. I never examined this parameter in detail before. I like `withAutomaticPagination`.

**Comment by matthias-ronge** [comment]
Solution was merged. Close issue.

**Comment by matthias-ronge** [comment]
With automatic pagination disabled, images are not shown after clicking manual pagination link. You have to switch the image folder twice to see any. This needs to be fixed.

**Comment by henning-gerhardt** [comment]
Could this behaviour related to #644?

**Comment by matthias-ronge** [comment]
I don’t think so, but I keep an eye on that.
