### ISSUE TITLE
Cannot create exclusive branch in workflow modeler

### ISSUE THREAD

**Issue by aetherfaerber** [kitodo/kitodo-production#5630]
**Describe the bug**
According to https://github.com/kitodo/kitodo-production/issues/3645 the gateway symbols in the workflow editor do nothing on a functional level towards the workflow engine but are only there to signal an intention to the modeler.

The comment by @Erikmitk to the linked issue goes on to explain that
> Instead, conditions and properties can be set on the tasks themselves to model a truly parallel or exclusive pathway. 

But tasks only have a checkbox to mark parallel tasks which appears to be doing nothing.

**To Reproduce**
1. Create a new workflow.
2. Create four tasks “always“, ”either“, ”or“ and ”also“.
3. Create gateways to put ”either“ and ”or“ on two branches between ”always“ and ”also“.
4. Leave all ”parallel task“ checkboxes unchecked.
5. Assign the workflow to a project and create a new process for the workflow.
6. Observe how after you close either the ”either“ or the ”or“ task, the other one remains open and the ”also“ task is not available or open until the other one is closed.
7. Tik the ”parallel task“ checkboxes on both (and in another try only one) of ”either“ and ”or“.
8. Again create a new workflow and observe the same results as in 6.

**Expected behavior**
Parallel task branches should both need to be finished for the workflow can continue. But exclusive task branches should exclude the other branch. The workflow should continue to the next step as soon as one of the branches (or in Kitodo's case tasks, see https://github.com/kitodo/kitodo-production/discussions/5629) has been finished.

**Screenshots**
![exclusive](https://user-images.githubusercontent.com/779261/232745343-c50daaea-afca-43f2-b2fa-f29f9441e70c.png)

**Release**
3.5.0

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - 111.0

**Additional context**
This is frustrating. After going through quite some struggles with importing the metadata and management of images, accepting more complicated workflows in order to make room for Kitodos quirkyness or ignoring the software altogether by replacing its functions through scripts of our own, we expected the workflow engine, as the heart of the software, to make our lives easier. But again, we are left with only a few and hardly documented options that seem to have been strung together for a use case most alien to the ones we see every day.

**Comment by Erikmitk** [comment]
Can you elaborate what your desired workflow is supposed to be? What happens at the individual exclusive branches?

**Comment by solth** [comment]
I think there is a misunderstanding. The flag "Parallele Aufgabe" in the workflow editor does indeed have a function attached to it and  is meant to allow parallel tasks to be performed simultanously. This means that in your example, once task "immer" has been closed, both tasks "entweder" and "oder" will be opened. 

If both tasks have the "Parallele Aufgabe" flag set to "true" (e.g. checked), task "oder" will still be available for assignement in the task list even if someone already self-assigned task "entweder". 

If both task have "Parallele Aufgabe" set to "false" (e.g. unchecked), these two tasks still both need to be completed in order to advance to "auch", but once one of those tasks (for example "entweder") has been assigned to a user (and therefore changes processing status from "open" to "in work"), the other task ("oder") will disappear from the list of available tasks until the first task has been completed, effectively forcing the user to perform both tasks sequentially (but in arbitrary order) instead of simultanously/in parallel.

**Comment by aetherfaerber** [comment]
> Can you elaborate what your desired workflow is supposed to be? What happens at the individual exclusive branches?

We have several occurrences of this in our established workflows. Most often these are used for correction loops which are not necessary in Kitodo due to the Korrekturmeldung function. 
The two main remaining use cases are:
* images of objects for which no metadata exists need special treatment that involves reaching out to the description department and, depending on the reply received, will follow a different workflow than images of fully described objects (I see now that this could maybe be accomplished by using tasks that will only activate based on the the condition that a variable is set or file exists which in turn has to be triggered by the task responsible for finding missing metadata.)
* images that may not be publicized need to be stored in a different place and derivate images of these need to be deleted or should not be created at all. (I see now that this also could be accomplished by sequential tasks that activate based on a check created through another previous task.)

I must stress that this way of doing things is undocumented, cumbersome and seems highly unintuitive to someone sitting in front of a workflow modeler which allows to model exclusive (and parallel) gateways. Of course we discovered the option to set script-based conditions for tasks but immediately said ”that can't be it. What is the use of a workflow engine if we have to write our own scripts for checking previous tasks' status and outputs?“

The use case I had in mind when filing the above bug report is one to circumvent the workflow engines limitation of having only one task per branch as modeled in https://user-images.githubusercontent.com/779261/232723523-115942e1-3985-41ea-9cfc-cb659856eafc.png from #5629. The tasks regarding hard disks on the right depend on the completion of the tasks on top between the gateways. If exclusive branches worked the same way (which is not the case) as I expected parallel branches to work (which is not accurate as @solth points out in https://github.com/kitodo/kitodo-production/issues/5630#issuecomment-1512913149) only one branch could be the parallel branch (the ones at the bottom) and the workflow could continue as soon as the upper tasks have finished with the bottom ones staying open.

**Comment by aetherfaerber** [comment]
> I think there is a misunderstanding. The flag "Parallele Aufgabe" in the workflow editor does indeed have a function attached to it and is meant to allow parallel tasks to be performed simultanously. This means that in your example, once task "immer" has been closed, both tasks "entweder" and "oder" will be opened.
> 
> If both tasks have the "Parallele Aufgabe" flag set to "true" (e.g. checked), task "oder" will still be available for assignement in the task list even if someone already self-assigned task "entweder". Once _both_ tasks have been finished (or skipped, if a workflow condition is configured), the process will proceed to "auch".
> 
> If both tasks have "Parallele Aufgabe" set to "false" (e.g. unchecked), these two tasks still both need to be completed in order to advance to "auch", but once one of those tasks (for example "entweder") has been assigned to a user (and therefore changes processing status from "open" to "in work"), the other task ("oder") will disappear from the list of available tasks until the first task has been completed, effectively forcing the user to perform both tasks sequentially (but in arbitrary order) instead of simultanously/in parallel.

Thank you for this explanation. It is not the first time I read a comment (of yours) to an issue here and wish that this information would have been part of the documentation.

Bad luck for us then to expect a completely different behavior than the one that has been implemented from these buttons and features. Maybe we saw the BPMN rather as a logic/state machine than as a flow diagram of people running around and doing actual things and possibly getting in each others way.
