### ISSUE TITLE
Inconsistent image number

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#5677]
**Describe the bug**
After moving file objects in the structure tree, there are inconsistencies in the page labels of the window "New docstruct from selected pages". 
It seems, as if the label of the internal order is applied - which happens often before: 
- #5031

**To Reproduce**
1. Open a process with structure elements
2. Move one structure element to another position
3. Add a new structure element on a position behind the element, which has been moved
4. Compare the labels of the image number in the structure tree and the window "New docstruct from selected pages"

**Expected behavior**
The labels of the file objects should be the same in all frames and windows.

**Screenshots**
![InconsistantLabels](https://github.com/kitodo/kitodo-production/assets/14835770/9b003e91-aead-4004-9bfa-92ad2d503104)

**Release**
KITODO.PRODUCTION Version 3.6.0 - 01.03.2023 + some selected pull requests

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by thomaslow** [comment]
I'm sorry for the late reply. I added a fix for this problem that uses the same label in the dialog as everywhere else in the meta data editor.
