### ISSUE TITLE
It should not be possible to create processes in an inactive project

### ISSUE THREAD

**Issue by BartChris** [kitodo/kitodo-production#5686]
**Describe the bug**
It is possible to create processes for an inactive project, using normal process creation and mass import. After process creation in those projects the processes are not visible in the process list.
Apart from that, inactive projects should not be displayed by default to have a coherent behaviour between projects and process templates. 

![grafik](https://github.com/kitodo/kitodo-production/assets/7516499/5529858b-98a9-4972-a904-223ef1488cc5)

**To Reproduce**
1. Mark an project as inactive.
2. Create a process for that project either using manual process creation or mass import.

**Expected behavior**
It should be impossible to create processes for an inactive project. The display behavior should be the same as it is implemented for process templates.

**Release**
Master

**Comment by solth** [comment]
> It is possible to create processes for an inactive project, using normal process creation and mass import. After process creation in those projects the processes are not visible in the process list.

I think you mean "...the processes **should** not be visible in the process list", don't you? We do have a filter in the process list to show processes of deactivated projects which is deactivated by default but this seems to be bugged as described in #5295 

![Bildschirmfoto 2023-06-05 um 13 11 20](https://github.com/kitodo/kitodo-production/assets/19183925/4eac72d2-3102-420b-8218-701a4126b79a)
