### ISSUE TITLE
Incorrect sorting by column "process" in the list of tasks  

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#5751]
**Describe the bug**
When a list of tasks is sorted by column "Process", not all tasks are displayed in the correct order. This occurs more often in extensive list of tasks (for example 10.000), but also in shorter lists. 

The processes in the process list are sorted correctly. 

**To Reproduce**
1. Show task list
2. Click on column "Process"
3. Click on column "Process" (to check sorting a-z and z-a)
4. Check the order of the processes by process title
5. See wrong sorting of the processes

**Expected behavior**
The column "process" in the task list should be ordered correctly by characters and numbers of the process titles - according to the sorting of the process in the process list.

**Screenshots**
Example with ~12.000 hits
![exampleSortingTasklist01](https://github.com/kitodo/kitodo-production/assets/14835770/df930477-47b5-41b7-af98-fdaf40f30fca)

Example with ~90 hits
![exampleSortingTasklist02](https://github.com/kitodo/kitodo-production/assets/14835770/d35da3a0-d1ca-4241-8142-ab56d99164de)

**Release**
3.6.0-SNAPSHOT from 03/01/2023

**Desktop (please complete the following information):**
 - Windows
 - Chrome

**Comment by solth** [comment]
I think this has to do what @thomaslow described here: https://github.com/kitodo/kitodo-production/issues/5730#issuecomment-1663499106

**Comment by andre-hohmann** [comment]
Thanks a lot for the quick reply. I think it does not depend on the issue of 10.000 hits in Elastic Search. My second example has only around 90 hits and the sorting is not correct. 
Besides, it should also the process list, which could have even more hits, if also the closed processes are shown. 

Maybe in lists with many hits, the probability for incorrect sorting on the first page is higher. I did not check all pages of the task list. 

I have to admit that my description is not precisely enough and i will correct it.

**Comment by andre-hohmann** [comment]
Thanks for the additional information. 
It may be the reason, but I cannot assess it, as i have currently no access to the database... 

I just can state: 
* Modifying of the metadata of the process does have any consequences. 
* Modifying the current state of the task does have any consequences. 
* Modifying the process title does have any consequences. 
* On the page `indexing` in Kitodo.Production, there are no warnings/errors, which usually occur, if there are differences between database and index. 
* I can hardly imagine, that someone changed the amount of affected process title, as it is the test-system.

**Comment by thomaslow** [comment]
I found the problem. It was my mistake. I didn't consider that ElasticSearch would actually sort a list based on an analyzed field instead of the raw text. I submitted a pull request that will fix the problem.

I also checked the other ElasticSearch-based data tables in Kitodo-Production and could not find any other instances of this issue.

**Comment by andre-hohmann** [comment]
Thanks a lot for the investigation and the solution!
