### ISSUE TITLE
Page box does not navigate on enter

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#5763]
When writing a page number in the page box and then clicking somewhere in the page (not a link), the table goes to the desired page.

![Bild eingefügt am 2023-8-30 11-05](https://github.com/kitodo/kitodo-production/assets/3040657/b2f746fd-da60-4650-89d8-c29a62d96655)

But when you type the number and press <kbd>Enter</kbd>, it does not.

**Goal: Should also work on <kbd>Enter</kbd> key press**

**Comment by solth** [comment]
Maybe related to #4355 . Does this only happen on the "Tasks" page?

**Comment by matthias-ronge** [comment]
I am not really sure, but could have been. I will temporarily close this as duplicate, maybe reopen if, I find it happen on a different page again.
