### ISSUE TITLE
Task Manager fails with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#5771]
**Describe the bug**
In a productive environment with many scripts, sooner or later, Task Manager cannot be opened anymore, showing an error like this:

![image_2023_09_06T12_52_33_324Z](https://github.com/kitodo/kitodo-production/assets/3040657/2b2c6d01-a9d9-4ba0-b572-45b5cd71599e)

Tasks do still run, but cannot be observed anymore. Reloading the page or logging of and logging back on doesn’t fix it, the error is visible to all users. Needs Tomcat restart.

**Comment by henning-gerhardt** [comment]
As the code of the task manager was not changed a lot in the past, I think the issue https://github.com/kitodo/kitodo-production/issues/4135 is still correct and is existing in 3.x

**Comment by matthias-ronge** [comment]
Your suggestion is incomplete, as also class `TaskSitter` accesses the tasks list. This is turn makes it impossible to simply use the `synchronized` keyword, because both classes would synchronize on their own rkes. See my PR

**Comment by henning-gerhardt** [comment]
My change was introduced in earlier versions of Kitodo.Production 2.x and is working until now. Even without the changes in `TaskSitter` class I did not get an error in 3.x until now. Your change is setting the lock inside the methods and my lock is set by calling the methods. So it would work in both cases.

I can review your pull request after beginning of October 2023.
