### ISSUE TITLE
Misleading message while password change

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#5787]
**Describe the bug**
If a normal user (not an administrative user) is changing his own password two messages appear:
- one is saying that the old and the new password did not match
- second is saying that the password was successful changed

Using the old password afterwards is not possible any more and only the new password is accepted.

I don't know if this is happening only if the user is connected to LDAP service or even on database only password usage.

**To Reproduce**
1. Login as a regular user
2. Switch to the user properties
3. Change the password (entering old and twice new password) 
4. See the misleading error message

**Expected behavior**
Comparing that the old used password is correct and differ from the new password is right but the error message should not appear in this case. If the old password is incorrect than this message should appear and the password should not be changed.

**Screenshots**
![Screenshot_2023-09-26_10-04-46](https://github.com/kitodo/kitodo-production/assets/2129672/de201236-9e68-49a3-ba20-cfce497ec61a)

**Release**
3.6.0-SNAPSHOT from 03/01/2023

**Comment by solth** [comment]
@henning-gerhardt I just reproduced the error. It only seems to occur when the _old_ password is indeed wrong. When the correct old password is entered and the two fields for the new password contain the same value, the red error message does not appear. So the error seems to be that the password is changed even when the old password is not correct!

**Comment by henning-gerhardt** [comment]
I could reproduce this error message many times. My workflow was every time:
1. logged in as an administrative user
2. changed the user password to an intermediate password
3. logged in as the user with the intermediate password
4. set the user password to an other password which was send later to the user so he can log in again

I know that this was is not necessary but I got the information from the user that the password change did not work and the user can not log in anymore nor use the new password for example the WebDAV access (password is stored in LDAP and LDAP is connected to the application and the WebDAV service).
