### ISSUE TITLE
User cant login if login and ldapLogin is set

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#5792]
**Describe the bug**
If a user has a `login` and `ldapLogin` entry the user can't login and the message appear

[ERROR] org.kitodo.production.services.data.UserService - Login 'xxx' was found more than once! Affected IDs: 303, 303

The reason behind this error message is the code in

https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/services/data/UserService.java#L166-L170

There are 2 queries which get merged but identical users are not merged and delivered as separate entries.

**Possible solution(s)**
1) Still use the two queries but filter identical but duplicated users from the list before the result list is returned
2) Merge the two queries to one query

**Workaround**
Remove the entry in `ldapLogin` if not really needed.

**Release**
3.6.0-SNAPSHOT from 03/01/2023

**Comment by matthias-ronge** [comment]
Older versions of Production didn’t remove the _ldapLogin_ when “deleting” accounts (which actually is only setting its fields to `NULL`). If you then recreate the account with a same _ldapLogin_, you will get this message. You can repair the database with:

```sql
UPDATE user SET ldapLogin = NULL WHERE login IS NULL;
```

**Comment by henning-gerhardt** [comment]
That is here not the case: all logins are still in use but can't login as both fields `login`  and `ldapLogin` contain data but the current code is reporting the same user twice and this is a bug in the software.
