### ISSUE TITLE
Metadata editor: Keep size of image in detail view

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#5796]
**Is your feature request related to a problem? Please describe.**
If in the detailed view of metadata editor the size of the image is changed, the change is not applied to the other images. If the next image is selected, the default value is applied. 
This becomes annoying, if the size of the image has to be adjusted each time after another image is selected. 

**Describe the solution you'd like**
The customized size of the image should be kept for the current process for all images until it is changed by the user. 
If the next process is opened, the default value can be applied. 
_Addition on 2024-02-21_: There should be an opportunity, to reset the size to the standard value. 

**Describe alternatives you've considered**
~~It could be considered, if the feature could be made configurable. In case that the current behavior should be kept. 
However, if there is consensus that the image size should be maintained, the effort is probably not justified.~~
In [2024‐02‐20 Community Board (Kitodo.Production)](https://github.com/kitodo/kitodo-production/wiki/2024%E2%80%9002%E2%80%9020-Community-Board-(Kitodo.Production)) it was decided not to realize a configuration. Instead, a reset-button should be realized to set the size to the standard value.

**Comment by solth** [comment]
The current behaviour was probably caused by #2904

**Comment by thomaslow** [comment]
@andre-hohmann Could you check the demo video in #6236 and verify that this is the correct intended behavior? Thank you!

**Comment by andre-hohmann** [comment]
@thomaslow : Thanks a lot!
For me and my colleagues, the demo video shows the intended behavior and corresponds to our expectations.
