### ISSUE TITLE
Kitodo 3.6: No Pages shown in Meta Data Editor - Main Title View

### ISSUE THREAD

**Issue by m-kotzyba** [kitodo/kitodo-production#5815]
In the Meta Data Editor, switching the view from Type (Image 1) to Main Title (Image 2) causes that no pages are shown in the structure tree. This was not the case in Version 3.5.

![01](https://github.com/kitodo/kitodo-production/assets/85474095/415b6329-2d39-49ce-9481-da7bf7ad74e5)

![02](https://github.com/kitodo/kitodo-production/assets/85474095/2f86dcf6-fee3-40f6-aa6c-24d632ba57c8)

**Comment by solth** [comment]
@m-kotzyba thanks for reporting this issue. Ideally this should be fixed when implementing https://github.com/kitodo/kitodo-production/discussions/4925

**Comment by solth** [comment]
This turned out to be a rather small change so I fixed this bug individually after all.
