### ISSUE TITLE
On “System” page, the main menu closes itself

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#5841]
**Describe the bug**
On the “System” page, the main menu always closes very quickly.

**To Reproduce**
1. Go to “System” page
2. Click on main menu (𓃑).
3. Try to click something in the menu.

**Expected behavior**
Menu should stay open.

**Screenshots**
![Screencast](https://github.com/kitodo/kitodo-production/assets/3040657/f5ebe30d-16ef-4dc6-a33d-af61a7f82c3e)

**Release**
3.6 release

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 120.0

**Comment by solth** [comment]
I am unable to reproduce this error. Maybe you just need to clear your browser cache and reload the page including it's resource files like Javascript and CSS to resolve this issue. At least the breadcrumb for "System" implies something like outdated stylesheets.

**Comment by matthias-ronge** [comment]
Refreshing the cache didn’t fix it. Also, the „smaller“ breadcrumbs continue to appear if the window is smaller than 1200 px.

![Screencast](https://github.com/kitodo/kitodo-production/assets/3040657/01f6059e-c743-479a-8b06-5d7bbf7c747e)

The page refresh is actually triggered by clicking on the menu icon, not by the timer page refresh of the task manager, as I did think before. You see it by highlighting some text, or in the network console. It also happens on the „Legal texts“ tab

![Screencast2](https://github.com/kitodo/kitodo-production/assets/3040657/1c84bd56-8c58-4e03-a926-93260e6bc8fd)

**Comment by matthias-ronge** [comment]
When I open the “System” page, everything is normal. Normal mouse pointer, no network activity.

When I click on the main menu, the whole page gets reloaded.

Clearing the browser cache didn’t help.

System: Ubuntu 20.04
Java: OpenJDK 11.0.21
Servlet container: Apache Tomcat 9.0.31
Release: Kitodo.Production 3.6.0
Browser: Firefox 120.0 (all extensions disabled)
User: testadmin

Browser console warning:

```
jQuery.Deferred exception: PF(...) is undefined @http://localhost:8002/kitodo/javax.faces.resource/lists.js.jsf?ln=js:54:20 (jquery.js.jsf:2:31008)
e@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:29453
Deferred/then/l/</t<@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:29755
setTimeout handler*Deferred/then/l/<@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:29964
c@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:27742
add@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:28020
Deferred/then/<@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:30060
Deferred@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:30473
then@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:29989
@http://localhost:8002/kitodo/javax.faces.resource/lists.js.jsf?ln=js:53:13
dispatch@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:42571
add/v.handle@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:40572
EventListener.handleEvent*add@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:41039
Ae/<@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:39656
each@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:2777
each@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:1419
Ae@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:39632
on@http://localhost:8002/kitodo/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&v=8.0&v=8.0:2:46222
@http://localhost:8002/kitodo/javax.faces.resource/lists.js.jsf?ln=js:52:11
 undefined
```

**Comment by matthias-ronge** [comment]
The code in question is here:

![Screenshot 2023-11-30 091146](https://github.com/kitodo/kitodo-production/assets/3040657/1c9493f3-844b-4f51-8174-f5ba755f3061)

**Comment by matthias-ronge** [comment]
I temporarily fixed this problem …
```js
$(window).on("load", function () {
    $.ready.then(function () {
      if (typeof PF === 'function') {
        if (typeof PF('processesTable').selection !== "undefined" && (PF('processesTable').selection[0] === '@all' || PF('processesTable').selection.length === PF('processesTable').cfg.paginator.rowCount )) {
            PF('processesTable').selectAllRows();
            PF('processesTable').selection=new Array("@all");
            $(PF('processesTable').selectionHolder).val('@all');
            let excludedIds = $('#excludedProcessIds').children();
            for(let i = 0; i < excludedIds.length; i++) {
                let processId = excludedIds.get(i).textContent;
                PF('processesTable').unselectRow($('tr[data-rk="' + processId + '"]'), true);
            }
        }
      }
    });
});
```

The warning is gone, but the behaviour is still the same. So this seems not to be the problem

**Comment by matthias-ronge** [comment]
JSF decides for some reason, that the whole page needs to be updated:

    <?xml version="1.0" encoding="UTF-8"?><partial-response id="j_id__v_0"><changes><update id="javax.faces.ViewRoot"><![CDATA[<!DOCTYPE html> …

**Comment by solth** [comment]
I was able to reproduce the error now. My observation is that it only occurs if the indexing on the system page has been started, because this triggers a continuous polling of the page (for progress updates) that is not stopped even when the indexing is finished. Could that explain the behavior you reported? 

You could easily check this by renewing your session (logout + login) and opening the system page again. If you do _not_ start the indexing the error should not occur anymore.

**Comment by solth** [comment]
> The code in question is [here](/kitodo/kitodo-production/blob/master/Kitodo/src/main/webapp/WEB-INF/resources/js/lists.js#L54):
> 
> ![Screenshot 2023-11-30 091146](https://private-user-images.githubusercontent.com/3040657/286860703-1c9493f3-844b-4f51-8174-f5ba755f3061.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDM0NzQsIm5iZiI6MTcwNDcwMzE3NCwicGF0aCI6Ii8zMDQwNjU3LzI4Njg2MDcwMy0xYzk0OTNmMy04NDRiLTRmNTEtODE3NC1mNWJhNzU1ZjMwNjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMDgzOTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjMzNTA4YTY4Zjc0ODRkZTMwMjBiOTE2YjYwMTBjZGQ3MGE1YjUzMWU2NDVkZmJmMTk0ZTZhYzAyODI4YmU0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nA3daSl7tTg9mYCWdme6A98Lc2SyBHfLidR5vdHUHl8)

@matthias-ronge could you check if #5868 fixes the problem?

**Comment by matthias-ronge** [comment]
I can no longer reproduce the problem with the current master. I am closing this issue.
