### ISSUE TITLE
I miss the "Projekt" Tab

### ISSUE THREAD

**Issue by mSIESTE** [kitodo/kitodo-production#5870]
I miss the Projekt Button:
![image](https://github.com/kitodo/kitodo-production/assets/16195237/975ea25e-289c-4bbd-9766-882549c8dd12)

My installation looks like this:
![image](https://github.com/kitodo/kitodo-production/assets/16195237/04c9451a-f428-4992-ac1c-66a93ca7dd44)

Any idea whats wrong ?
I use: KITODO.PRODUCTION Version 3.1.0

**Comment by BartChris** [comment]
I think you need to configure the permissions. The user you log in with needs to have a role which is able to view all projects. To be more precise: The role needs to have one of the following permissions:

"viewAllProjects, viewAllTemplates, viewAllWorkflows, viewAllDockets, viewAllRulesets"

https://github.com/kitodo/kitodo-production/blob/d3bba5c8d15986f94132e86be15a581912896f3e/Kitodo/src/main/java/org/kitodo/production/controller/SecurityAccessController.java#L713
