### ISSUE TITLE
Release 3.6.1. - missing messages for ES

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#5885]
In Release 3.6.1 I miss messages for ES, which are defined for DE and EN (it is about message files defined in war-file in webinf/classes/messages):

For error-messages there are new defined labels:
- errorsOccurredCheckLog
- tooManyProcessesSelectedForMediaRenaming
which are not defined in error_es.properties

For the messages there are new defined labels:
- renamingMediaFilesOfSelectedProcessesStarted
- renameMediaForProcessesConfirmMessage
which are not defined in messages_es.properties.

--> I would expect to find these messages also in ES-variant.

**Comment by solth** [comment]
@danilopenagos could you provide Spanish translations for the message keys mentioned above?

**Comment by danilopenagos** [comment]
Hi, @solth yes, I do. Let me check!

**Comment by danilopenagos** [comment]
@solth the update of Kitodo message ES is #5891

**Comment by solth** [comment]
> @solth the update of Kitodo message ES is #5891

@danilopenagos thank you very much for the quick response and update!

**Comment by solth** [comment]
Fixed by #5960
