### ISSUE TITLE
Add option to open select pages in the metadata editor gallery in a separate browser window

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#5887]
**Is your feature request related to a problem? Please describe.**
It can be difficult to apply pagination to a set of pages in the metadata editor if the information for the pagination has to be obtained from a table of contents in the same process. Since selecting the scans for pagination moves the page with the table of contents out of view, it becomes cumbersome and difficult for the user to move back and forth between those pages.

**Describe the solution you'd like**
A new option should be added to the context menu of individual pages in the metadata editor (gallery and structure tree) to open a selected page in a separate window. Some users have reported that they actually print out a table of contents and use it next to the computer to help with pagination, so this approach with a separate browser window should fulfil the requirement in a similar way (albeit without the need for a printer and paper).

**Describe alternatives you've considered**
Instead of opening a selected page in a separate browser window, it was initially proposed to add the option to "pin" the page to keep it in view even when the user subsequently selects different pages for the purpose of pagination. This would also resolve the issue described above, but would presumably be much more expensive in the implementation (since the whole layout and structure of the metadata would have to be refactored to take into account the pinned page) without adding much more value as a solution for the described problem.

**Additional context**
This topic has been discussed at the Kitodo community meeting 2023 and has been documented at #5881 and https://github.com/kitodo/kitodo-production/wiki/Barcamp-2023:-Usability-Metadateneditor

**Comment by thomaslow** [comment]
I implemented the option to open a new browser window. My proposed solution can be found in #5887, including a demo video.
