### ISSUE TITLE
Add option to save default data editor layout

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#5888]
**Is your feature request related to a problem? Please describe.**
Layout settings in the metadata editor can be saved for individual tasks using this button:
<img width="399" alt="Bildschirmfoto 2024-01-18 um 17 02 08" src="https://github.com/kitodo/kitodo-production/assets/19183925/e0d4123f-c916-41fa-8e02-37c3452a5a60">

This allows users to adjust the editor for different purposes - e.g. the gallery could be hidden for tasks configured to enter metadata while the structure tree is not displayed in QC tasks where the user only wants to inspect the quality of the images - and save those customized layouts for individual tasks. The saved layouts will then be applied whenever the user opens the metadata editor with a process created by the same workflow via the same task in the future.

It is _not_ possible to save the current layout of the editor when opening a process via the process list, though. In that case the button mentioned above is deactivated:
<img width="80" alt="Bildschirmfoto 2024-01-18 um 17 14 27" src="https://github.com/kitodo/kitodo-production/assets/19183925/84580a22-bf49-479b-a9b5-9ca16974f3b1">

**Describe the solution you'd like**
The option to save the current column width distribution and metadata editor layout should also be available when opening a process via the corresponding action in the process list, thus not in relation to any particular task. The layout should then be considered to be saved as a "general default layout" of the editor for the user, that will always be applied when either opening the metadata editor via the process list or when opening it via the details page of a specific task for which no task-specific layout has been saved.

**Additional context**
This topic has been discussed at the Kitodo community meeting 2023 and has been documented at #5881 and https://github.com/kitodo/kitodo-production/wiki/Barcamp-2023:-Usability-Metadateneditor

**Comment by thomaslow** [comment]
@solth @andre-hohmann  Do we want to keep the green `metadata editor layout loaded successfully` message (see demo video in #6245). As soon as a layout was saved once, this message is shown every single time the metadata editor is opened. 

Personally, this message seems unnecessary to me. Why is the column layout so important that there needs to be a special message to the user (in contrast to other features of the metadata editor that also load successfully without an extra message to the user)?

**Comment by solth** [comment]
> Why is the column layout so important that there needs to be a special message to the user (in contrast to other features of the metadata editor that also load successfully without an extra message to the user)?

This notification was added because there were concerns that users might not understand why their metadata editor looks different from that of other users or how it used to look in the past (before they - perhaps accidentally - clicked the "wrench" symbol). I still see the value of this notification, but I can also understand your opinion, especially when watchting the video you attached to your pull request. 

Maybe the wording in the dialog needs to be improved to more effectively convey the information about the settings being loaded - I feel the current message may be too generic and users might not understand what kind of layout is meant? Alternatively, we could perhaps somehow signal "custom" settings in a more sublte way, like - for example - changing the style of the "wrench" symbol (for example by adding a small "bubble" and corresponding tooltip to it), than we could omit the notification altogether?

**Comment by thomaslow** [comment]
@solth Thank you for your clarification. 

Maybe we could add a little bit more detail to the "save confirmation dialog" message. For example:

Instead of:
> Ihre aktuellen Metadaten-Editor-Einstellungen wurden erfolgreich gespeichert! Sie werden für alle zukünftigen Aufgaben dieses Typs wiederverwendet.

We could write (default):
> Ihre Einstellungen wurden erfolgreich als Standard-Einstellungen gespeichert! Beim nächsten Öffnen des Matadaten-Editors wird die Breite der drei Spalten (Strukturdaten, Metadaten und Galerie) entsprechend ihrer aktuellen Einstellung geladen.

And (task-type-specific):
> Ihre Einstellungen wurden erfolgreich für alle zukünftigen Aufgaben dieses Typs gespeichert! Beim nächsten Öffnen des Matadaten-Editors wird die Breite der drei Spalten (Strukturdaten, Metadaten und Galerie) entsprechend ihrer aktuellen Aufgaben-spezifischen Einstellung geladen.

Maybe, this helps users to better understand what is happening (and reduce the need for the green loading message)?

**Comment by andre-hohmann** [comment]
In my opinion, we should avoid the green message. 

- @thomaslow proposals are good, but I do not understand the task-specific one. What type of tasks (_... für alle zukünftigen Aufgaben dieses Typs gespeichert!_) are meant?
The "default"-proposal is from my point of view short and understandable. 
A detailed description of the function should be written in the documentation. 
- I like @solth idea very much to change the "wrench" symbol, if customizing the setting is active. 

If a message should shown, i would prefer the message in the area in which validation results are shown - as ribbon between the button-panel and the three columns. 
Messages which are covering buttons, ... are very annoying and there are discussions regarding other use cases. We should not create new ones, but harmonize the types of messages. 
- #3316
- #5215

**Comment by thomaslow** [comment]
I understand the idea to change the "wrench" symbol. However, as soon as the user clicks the "wrench" button once, the icon will change and stay like that forever. There is no way to turn this setting off. Eventually, people will forget what the "wrench with a bubble" icon means, too.

In my opinion, the only way to improve the "intuitiveness" of this button is to add more detail to it, e.g., by showing a menu with options such as:
- "save default column layout" (with an icon if active)
- "save task-specific column layout" (with an icon if active or disabled if not possible)

Anyway, the pull request #6245 now shows more detailed text in the confirmation dialog (after clicking the "wrench" icon). The demo video was updated accordingly.

**Comment by andre-hohmann** [comment]
Hello @thomaslow , thanks you very much for your suggestions!

We talked about this issue in the @kitodo/kitodo-community-board  and now I understand the difference of saving the metadata editor layout via task. As we have in the SLUB Dresden only one task, which is conducted in the metadata editor. Now I know that there can be other tasks such as quality control, which are conducted in the metadata editor, too. 

We came to the following conclusions and i hope it supports finalizing the issue to everyone's satisfaction . 
1. We would be glad, if the green message would be removed. After a while, this becomes very annoying, as it needs to be closed manually. 
We expect the users will become used to layout, even if it differs in the tasks – it only should be documented well and be explained clearly when the functionality is introduced. 
2. We would support implementing a menu, which shows the two options you mentioned. Then it is much clearer, what the user should expect, even if he/she might not remember.
Would this be possible within the scope of the issue?

@solth : What do you think about?

Thank you very much for the videos – this makes it much easier to assess your proposals/solutions and to involve other colleagues!

**Comment by thomaslow** [comment]
@andre-hohmann Yes, I could add a simple menu within the scope of this issue.

@solth Let me know if you see any problems with @andre-hohmann 's proposed changes.

**Comment by solth** [comment]
> @solth : What do you think about?

The menu is a good idea, so I am all for it! 

We should also consider adding a button that _removes_ the saved settings and restores the default. That would resolve the issue @thomaslow mentioned where any marker on the wrench symbol signaling custom settings would stay permanently once activated because currently we do not have a way to deactivate such custom settings again:

> However, as soon as the user clicks the "wrench" button once, the icon will change and stay like that forever. There is no way to turn this setting off. Eventually, people will forget what the "wrench with a bubble" icon means, too.

I don't know if that's feasible for this pull request but if not we should perhaps document this as a feature idea for the future.

Also thumbs up for improving the message!

> Messages which are covering buttons, ... are very annoying and there are discussions regarding other use cases. We should not create new ones, but harmonize the types of messages.

Yes, I agree that our current implementation of the "growl" message (that's what they are called in PrimeFaces) is not optimal because of their position, obstructing the main menus in the upper right. I still prefer them over the static message line that we sometimes display, and had some discussions with @oliver-stoehr regarding this topic. One idea that maybe worth considerung would be to re-position them from the upper right corner to the lower right corner where they wouldn't cover any buttons or menus (I think there are examples in the wild where such popups appear in the lower right corner, so it wouldn't be too unconventional):

<img width="1491" alt="Bildschirmfoto 2024-10-15 um 14 37 12" src="https://github.com/user-attachments/assets/0a60f665-02ad-449d-8aeb-ad349fe7027e">

Since these messages disappear automatically after a few seconds it shouldn't be necessary for the user at all to close them manually. But if they are perceived as too obtrusive, perhaps we could just reduce the number of seconds they are visible?

**Comment by andre-hohmann** [comment]
@thomaslow : Thanks a lot for implementing the menu. In my opinion this avoids possible misinterpretations. Especially, because it is possible to derive the current status. 

@solth : We discussed about the growl-message in the community board. In some institutions, the message does not disappear after a few seconds and it needs to be closed manually - probably this is caused by an old Kitodo.Production version. 
Still we would rather do without the growl-message. 
If it is necessary, the message would be better positioned right at the bottom of the metadata editor - although it might irritate in the gallery view.

**Comment by solth** [comment]
@andre-hohmann sorry, I saw your comment too late. I already merged the pull request from @thomaslow. If you think the growl message should be removed that's absolutely fine with me. I thought it was a good idea initially, but totally understand that seeing it all the time might not be as helpful as intended and perhaps perceived as more of a hassle. 

Nevertheless, since the original PR is already merged, this has to be done in a follow-up pull request. Perhaps now that custom settings can also be deleted, coming back to the idea of a small visual marker like a bubble next to the wrench symbol when custom settings are currently applied makes sense again?

**Comment by andre-hohmann** [comment]
@solth : In my opinion (not the community board), marking the wrench symbol when custom settings are currently applied, would be a very good solution - much better then the growl message. 
Would you create a pull request for this?

**Comment by oliver-stoehr** [comment]
I created a mockup, for a possible marking on the wrench button:
![dataeditorsettings_1](https://github.com/user-attachments/assets/fc7722c1-1799-4899-9036-d2a4ee06445a)
![dataeditorsettings_2](https://github.com/user-attachments/assets/ee495a29-fc28-4c0e-bf16-e9d365f6a621)
These two icons could also give a hint on the type of setting that is applied.

**Comment by solth** [comment]
> I created a mockup, for a possible marking on the wrench button:
> ![dataeditorsettings_1](https://private-user-images.githubusercontent.com/32509444/385024410-fc7722c1-1799-4899-9036-d2a4ee06445a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDk5OTYsIm5iZiI6MTczMTM0OTY5NiwicGF0aCI6Ii8zMjUwOTQ0NC8zODUwMjQ0MTAtZmM3NzIyYzEtMTc5OS00ODk5LTkwMzYtZDJhNGVlMDY0NDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDE4MjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYWNlOTM0NWFiODNkOTUzMmJlYTlhM2VlY2UyNzgxMWMxNWJmNTgyZjViMWQ5MWM0MGJlMDdlZTgxYzUxMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1Z5Aqc9jl5c6d3gvFqMIWOo5SD7khzUr4ojN8rgXlvI)
> ![dataeditorsettings_2](https://private-user-images.githubusercontent.com/32509444/385024449-ee495a29-fc28-4c0e-bf16-e9d365f6a621.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDk5OTYsIm5iZiI6MTczMTM0OTY5NiwicGF0aCI6Ii8zMjUwOTQ0NC8zODUwMjQ0NDktZWU0OTVhMjktZmMyOC00YzBlLWJmMTYtZTlkMzY1ZjZhNjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDE4MjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYTFiNmNjMTM2MDI0ODViMDg1MzhjYWUwODUzNWI3ZGEwZDk4NTFjZTlhNTBmYmU0ZTQzYjI3YjYxOGZhZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zazsiknTSHQ6lmC8BVjHn5AYRXXxLPrDQvP8bACy7AA)
> These two icons could also give a hint on the type of setting that is applied.

@andre-hohmann what do you think about this idea?
