### ISSUE TITLE
Long numbers are not written into the Elasticsearch Index

### ISSUE THREAD

**Issue by BartChris** [kitodo/kitodo-production#5906]
**Describe the bug**
If you have a long number, e.g. a catalog identifier like `991022551489706476` those number does not get indexed into the Elasticsearch index. I encountered that problem, when i tried to import a child process and Kitodo did not find a parent process although the parent process exists. The problem is that for those long  numbers no value gets indexed.The metadata section of the indexed document looks like this. (The relevant field here is CatalogIDDigital)

```json 
                    {
                        "name": "Author",
                        "content": "Martin Chemnitz"
                      },
                      {
                        "name": "CatalogIDDigital"
                      },
                      {
                        "name": "DocLanguage",
                        "content": "lat"
                      }

```

The problem is that those numbers have the Java type `Long` and when constructing the Index we currently only look for strings and integers:

https://github.com/kitodo/kitodo-production/blob/39a881e8e0eb9381d8c2fbd52ecfcabfb26bdc72/Kitodo/src/main/java/org/kitodo/production/services/data/ProcessService.java#L2121-L2123

We probably should also keep Longs here by explicitely allowing that. 

```java
 Object value = xmlJSONObject.get(key);
            if (value instanceof String || value instanceof Integer || value instanceof Long) {
                json.put(prepareKey(key), value);
            }
```
When applying this change the CatalogIDDigital has a value in Elasticsearch.
```json
  {
                        "name": "CatalogIDDigital",
                        "content": 9910211111112122
                      },
                      {
                        "name": "TitleDocMain",
                        "content": "... Pars Examinis decretorum Concilii Tridentini"
                      },

```
This fix enables me to find my parent process again, but i am not sure wether we better convert the value to a string or how to differentiate this from other cases where we need a Long. (we probably do not need Longs for identifiers, since we are not doing any calculations on them).

**To Reproduce**
1. Put a long number into a metadatafield
2. Save the record
3. Check the Elasticsearch Index. The long number is missing from the metadata

**Expected behavior**
Long numbers shoutd not be lost when indexing the document.

**Release**
3.6.1, Master

@solth I put this into the 3.6.2 milestone because i consider it as a quite serious bug. Feel free to take it out, if you are not planning to include this in the next bugfix release.

**Comment by solth** [comment]
Fixed by #5936
