### ISSUE TITLE
Incorrect display of filter option list in process view (only in 3.6.1 with Firefox)

### ISSUE THREAD

**Issue by m-kotzyba** [kitodo/kitodo-production#5916]
We updated Kitodo to version 3.6.1
Now in the view "All Processes" several filter options are incorrectly shown, namely between the filter field (at the top) and the actual process list below (see Image, yellow marked area).
Clicking in this area, makes it disappear.
However, this issue only occurs in Firefox, not Chrome.

![Screenshot 2024-02-12 142034](https://github.com/kitodo/kitodo-production/assets/85474095/4197cb17-9b41-4f9e-bec1-4278c355a5e5)

**Comment by solth** [comment]
@m-kotzyba that very much seems like a caching problem and your browser may just contain outdated JavaScript and CSS resources for the page - the fact that the problem only occurs in Firefox, but not in Chrome, further corroborates that suspicion. 

Could you try reloading the page _including_ _the_ _cache_ in your browser? On Firefox/MacOs this is down with the keyboard shortcut "CMD + Shift + r", but this will differ between browser/operating system combinations.

**Comment by m-kotzyba** [comment]
@solth Yes, this solved the problem ... to easy ... Thanks!

**Comment by m-kotzyba** [comment]
Problem solved.
