### ISSUE TITLE
#issu placeholder for issues of periodical only outputs truncated issue labels

### ISSUE THREAD

**Issue by mnscholz** [kitodo/kitodo-production#5924]
We use the `#issu` placeholder for generating process titles of issues.
Example from our ruleset:
```
<division id="issue" processTitle="+'--'+#YEAR+'-'+#MONTH+'-'+#DAY+'_'+#issu">
```

However, `#issu` will only insert the first 4 chars of the label. 
Is there a way to insert more than 4 chars? `#iss` prints 3 chars, however, `#issue` doesn't seem to be recognized.

**Comment by henning-gerhardt** [comment]
Did you tried `#Issue` (with an  i in upper case)?

**Comment by mnscholz** [comment]
That works, thanks!
Also thanks for the link!
Has this been documented somewhere?
