### ISSUE TITLE
Physical page number always visible for thumbnails instead of only when hovering

### ISSUE THREAD

**Issue by Westedt** [kitodo/kitodo-production#5928]
In the metadata editor, the physical page number should always be visible in the thumbnails (gallery view) instead of only when hovering. The image number could be displayed above each image.

<img width="373" alt="image" src="https://github.com/kitodo/kitodo-production/assets/137274174/ce0c0b0a-5ee6-4bf3-a95e-0dee6e67aa03">

**Comment by solth** [comment]
This could be made configurable on a per-user base in the personal metadata editor settings.

**Comment by thomaslow** [comment]
@Westedt Hello, could you check the demo video in #6239 and verify that my proposed change matches your expectations? Let me know in case you prefer a different styling (font, background, position top/bottom). Thank you!

**Comment by Westedt** [comment]
Thanks @thomaslow! That's exactly what we wished for.
