### ISSUE TITLE
Show and focus always new metadata fields in the metadataeditor

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#5929]
**Is your feature request related to a problem? Please describe.**
If a new metadata field is added in the metadata editor, it is necessary to scroll down to its position, which is determined in the ruleset. In processes with much metadata, especially metadata groups, this is cumbersome. 

**Describe the solution you'd like**
If a new metadata field is added in the metadata editor, its position should be shown directly. Regarding metadata groups, the first sub-metadata field should be shown. Thus, it is possible to enter the values quickly.

The metadata field should be "on top" in the metadata frame. It should be possible to see as much sub-metadata fields of a metadata group as possible without additional scrolling. See screenshot in section _Addition context_.

**Additional context**
This can be seen as alternative for:
- #5886 

~~Here, it is necessary, to click the button "Übernehmen", which is not necessary it the new metadata field is directly shown.~~
Edit: This is not correct - there is no difference in the number of clicks. See comments below. 

Position of a metadata group
![positionNewMetadata](https://github.com/kitodo/kitodo-production/assets/14835770/9b962bd8-18e0-496a-a83b-195cfd0ba3f8)

**Comment by solth** [comment]
I had already included this aspect in the issue you linked - #5886 - in the last paragraph:

> In addition the metadata table should scroll to the new field and put the browser focus on it so that the user can immediately change or adjust the value if required.

**Comment by andre-hohmann** [comment]
@solth : Thanks for the reply!
We recognized that and in our opinion, the additional dialog is not necessary. If the added metadata field is in focus, the value can be captured directly, too. 
We are afraid that this solution can be quite difficult for metadata groups, multi-value fields, and other specific cases. A possible distinctive approach for metadata fields and metadata groups seems to us inconvenient. 

In the end, we decided for the simplest solution in order to consider as many other issues as well in: 
- #5935 

If our decision turns out to be wrong, your approach can still be realized.

**Comment by solth** [comment]
@andre-hohmann which "additional dialog" do you mean? I did not propose to add another dialog in addition to the one which already exists, but instead just add another _input_ field to the already existing dialog. Or did I misunderstand you and you meant to remove the one dialog that we already have, that appears when clicking the "+"-button? If that is the idea, how are you going to select the type of the new metadata?

**Comment by andre-hohmann** [comment]
@solth : Sorry, i was confused and formulated it badly. I meant the additional input field for metadata or metadata groups. 
You are right, there is no additional dialog.

**Comment by solth** [comment]
@andre-hohmann So I guess there is no real difference in number of clicks then, right?

> Here, it is necessary, to click the button "Übernehmen", which is not necessary it the new metadata field is directly shown.

**Comment by andre-hohmann** [comment]
@solth : Yes, you are right - thanks for the hint and sorry for the wrong description!
I changed it in the issue.

**Comment by thomaslow** [comment]
@andre-hohmann I added another demo video in #6285. Please let me know whether this fits your expectations. I added a yellow background such that the metadata field can be found more easily, especially when it is not possible to scroll all the way to it (if it is one of the last ones).
