### ISSUE TITLE
Reduce the time to open superordinate processes with many subordinate processes

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#5934]
**Is your feature request related to a problem? Please describe.**
Processes of superordinate processes as for example processes of newspaper years with more than 350 and up to 600 subordinate processes can take up to 20 minutes and more. 
Furthermore, corrections in ordering, ... is not possible as for example: 
- #5821 

**Describe the solution you'd like**
The time to open the superordinate process and the time to modify the structure tree, ... should be reduced. 

**Additional context**
There has been an issue before, but during the work in the productive system, the need open the processes faster rises again. 
- #3436

**Comment by BartChris** [comment]
I suppose that one of the reasons is that, there are a lot of look ups needed to construct the list although the provided information is often not really useful. (See: https://github.com/kitodo/kitodo-production/discussions/4925#discussioncomment-7653084) 
If you have a lot of volumes you would e.g. be interested in the information which is configured as "displaySummary" in the ruleset. (https://github.com/kitodo/kitodo-production/wiki/Regelsatz-3.x#schl%C3%BCssel-mit-besonderer-verwendung), but this is not used here.
Regarding performance: Would it maybe be possible to use some of the mechanisms wich Hibernate Search offers to display this information way faster. It seems like we do lookups in hundreds of XML files to get minimal information.
