### ISSUE TITLE
Import von Archiv-Metadaten aus EAD-DDB-XML um hierarchische Vorgänge automatisch zu erstellen

### ISSUE THREAD

**Issue by van-chess** [kitodo/kitodo-production#5984]
### Discussed in https://github.com/kitodo/kitodo-production/discussions/5829

<div type='discussions-op-text'>

<sup>Originally posted by **solth** November  2, 2023</sup>
Kitodo.Production 3.x unterstützt verschiedene Formen des Metadaten-Imports. Diese werden über sogenannte "Importkonfigurationen" konfiguriert (siehe https://github.com/kitodo/kitodo-production/wiki/Projektauswahl-und-Katalogsuche#import-konfigurationen), die die alte Datei `kitodo_opac.xml` ersetzen:

1. **Katalogabfrage** - Metadaten einzelner Datensätze können via ID (oder andere Suchparameter) von konfigurierten Suchschnittstellen abgefragt und daraus Digitalisierungsvorgänge erstellt werden. Wenn die Suchschnittstelle dies unterstützt, sind verschiedene Arten des **hierarchischem Imports** möglich, d.h. die Katalogschnittstelle wird für den Import von potentiellen Über- oder Unterordnungen erneut abgefragt, wenn deren IDs in den Metadaten des ursprünglich importierten Datensatzes enthalten sind, und die zurückgegebenen Datensätze als hierarchisch verknüpfte Vorgänge importiert. (siehe auch https://github.com/kitodo/kitodo-production/wiki/Kalliope-SRU-deutsch). Wenn der Datensatz die ID einer Überordnung enthält, ein Vorgang mit dieser ID aber bereits in Kitodo existiert, wird die Überordnung nicht erneut importiert, sondern der importierte Datensatz mit der bereits in Kitodo bestehenden Überordnung hierarchisch verknüpft.

2. **Datei-Upload** - XML-Dateien mit Metadaten können direkt vom lokalen Rechner hochgeladen werden. Es ist möglich, aus der gleichen XML-Datei zusätzlich die Überordnung des Datensatzes zu importieren, wenn eine separate Abbildungsdatei für die Extraktion der Metadaten der Überordnung in der verwendeten Importkonfiguration hinterlegt ist. Es ist also auch hier ein (auf die Überordnung) eingeschränkter, hierarchischer Import möglich. 

3. **Vorgangsvorlagen** - Metadaten können von entsprechend ausgezeichnten Vorgängen übernommen werden, z.B. für das Anlegen multipler Zeitschriftenbände mit größtenteils gleichen Metadaten.

4. **Massenimport** - Über eine zusätzliche Maske können Listen von IDs an eine konfigurierte Katalogschnittstelle (siehe 1.) übergeben werden, die dann den Import sequentiell für jede einzelne ID automatisch durchführt und multiple Vorgänge erstellt. Wie beim regulären Katalogimport werden importierte Datensätze (z.B. Bände eines mehrbändigen Werkes) als Unterordnungen an existierende Überordnungen (das mehrbändige Werk) gehängt, wenn ein entsprechender Vorgang der Überordnung in Kitodo bereits existiert oder die ID der Überordnung in der Liste der zu importierenden IDs _vor_ den IDs der Unterordnungen steht und damit zuerst importiert wird.

---

Konzept Weiterentwicklung: 

**Hierarchischer Massenimport (e.g. "Archivdatenimport")**:
Aus mehreren Gesprächen mit Archiven ist hervorgegangen, dass die bestehenden und oben beschriebenen Möglichkeiten des Metadatenimports für den Einsatz von Kitodo.Production in Archiven unzureichend sind. Es besteht der Wunsch, mehrere Vorgänge inkl. einer Überordnung (Bestand) und potentiell vieler Unterordnungen (Verzeichniseinheiten) aus _EINER_ manuell hochgeladenen oder von einer Schnittstelle zurückgegebenen XML-Datei (z.B. EAD) automatisch als einzelne, hierarchisch miteinander verknüpfte Vorgänge zu importieren.

Dies könnte über eine Erweiterung der Massenimport-Seite funktionieren. Wenn hierbei von einer festen Struktur einer solchen, hochgeladenen Archivmetadaten-Datei ausgegangen werden kann, würde der Massenimport aus **einer** Datei automatisch einen Vorgang für den Bestand ("collection") und n Vorgänge für die Verzeichniseinheiten ("item") erstellen und diese hierarchisch miteinander verknüpfen. 

@vernst @aetherfaerber @rchr @PeterJunger @Aigeus erfüllt dieses Konzept aus Sicht der Archive die prinzipielle Anforderung an eine Erweiterung des Imports? Was müsste noch ergänzt werden bzw. was habe ich nicht bedacht oder vielleicht falsch verstanden? 

@kitodo/kitodo-community-board könnte dieses Thema in Eure Liste aufgenommen werden?</div>

## Description

Bei uns wären genau die oben beschriebenen Funktionalität nützlich. Unser Archivinformationssystem hat keine Schnittstelle. Wir würden uns aber wünschen, dass wir hierarchische Exportdateien (EAD-DDB-XML) in Kitodo importieren können und, dass so ganze Vorgänge mit den jeweiligen Metadaten der Bestände, Unterbestände und einzelner Archivalieneinheiten als verknüpfte hierarchische Vorgänge importiert werden können. Momentan müssen sämtliche Metadaten manuell eingegeben werden, was einen erheblichen Zeitaufwand bei der Erstellung vieler hierarchischer Vorgänge bedeutet. 

## Expected Benefits of this Development

Zeitersparnis bei der Erfassung von Metadaten hierarchischer Vorgänge, die sich aus der Tektonik eines Archivinformationssystems ergeben. 

## Estimated Costs and Complexity

low to medium

e.g.

* **low** ~ less than 5 working days
* **medium** ~ less than 10 working days
* **high** ~ more than 10 working days

**Comment by solth** [comment]
Votes: 18
