### ISSUE TITLE
Run static code analysis with Coverity Scan more often

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-production#5991]
The last static code analysis with Coverity Scan was run nearly 5 years ago. That tool is still one of the standard tools for finding security and other issues in the code. Therefore I suggest to run it more often, for example once per month or at least before tagging a new release. Ideally that could be done in a GitHub action.

**Comment by stweil** [comment]
See also discussion for related issue #320.

**Comment by henning-gerhardt** [comment]
Did you look into CodeQL? It is already available in the repo and is doing the same job already. You can see the results of the CodeQL report in your fork.

**Comment by stweil** [comment]
Of course one could argue that as long as CodeQL reports more than 1500 issues (errors, warnings and notes) there is no use in additional code analyzers which even increase that number. But I don't think so. We need a complete overview of issues in order to decide about steps to fix them.

**Comment by henning-gerhardt** [comment]
As long as Coverity was integrated there was not a big usage of this results as you must setup an account there and the scan results was not visible on GitHub. Spotbugs was / is intregrated into every build but as this results even not visible on GitHub no one cares about this results. No you suggest to integrate an former tool again which was not really used?

**Comment by henning-gerhardt** [comment]
I have no access to Coverity anymore and I transferred the admin rights to Kathrin as she was doing the release management.

But this is not the point: If this tools are not really integrated into GitHub (former Coverity results was running on my development system and was transferred afterwards to Coverity), scanning results not visible in the pull requests  and you must view the results on a different website then is the usage really low.

I'm out now.
