### ISSUE TITLE
Wrong file path after image reorganize

### ISSUE THREAD

**Issue by fe-kre** [kitodo/kitodo-production#617]
We are working with Goobi 1.11.0. In our Workflow we have the task 'Edit metadata' and using therefor the Goobi front end. The Goobi interface offers the column 'Pagination'.  At this category you can select one or more pages with a click and adapt to 'Move selected pages up' or 'Move selected pages down'. The image preview shows the reorganized sequence.

If we then take a look at the 'meta.xml', the following happend:

      <mets:file ID="FILE_0050" MIMETYPE="image/tiff">
        <mets:FLocat xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="file:/storage/metadata/304/images/master_BiblMideA_433161639_media/00000050.tif"/>
      </mets:file>
      <mets:file ID="FILE_0051" MIMETYPE="image/tiff">
        <mets:FLocat xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="00000052.tif"/>
      </mets:file>
      <mets:file ID="FILE_0052" MIMETYPE="image/tiff">
        <mets:FLocat xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="00000051.tif"/>
      </mets:file>
      <mets:file ID="FILE_0053" MIMETYPE="image/tiff">
        <mets:FLocat xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="file:/storage/metadata/304/images/master_BiblMideA_433161639_media/00000053.tif"/>
      </mets:file>
      
This results in the following DMS Export:

      <mets:file ID="FILE_0050_ORIGINAL" MIMETYPE="image/tiff">
        <mets:FLocat xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="BiblMideA_433161639_tif/00000050.tif"/>
      </mets:file>
      <mets:file ID="FILE_0051_ORIGINAL" MIMETYPE="image/tiff">
        <mets:FLocat xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="BiblMideA_433161639_tif/tif"/>
      </mets:file>
      <mets:file ID="FILE_0052_ORIGINAL" MIMETYPE="image/tiff">
        <mets:FLocat xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="BiblMideA_433161639_tif/tif"/>
      </mets:file>
      <mets:file ID="FILE_0053_ORIGINAL" MIMETYPE="image/tiff">
        <mets:FLocat xmlns:xlink="http://www.w3.org/1999/xlink" LOCTYPE="URL" xlink:href="BiblMideA_433161639_tif/00000053.tif"/>
      </mets:file>
      
Our following steps after the Export also failed because of this wrong file path.

**Comment by henning-gerhardt** [comment]
@fe-kre : It is possible for you to test my pull request #684?

**Comment by henning-gerhardt** [comment]
Merged pull request and closing this issue.
