### ISSUE TITLE
Free pagination

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#620]
Archives need a far more flexible approach for pagination. They use both parentheses (`()`) and brackets (`[]`) and have both fixed and incrementing numbers in the pagination value. An additional “free” pagination mode shall be added to account for this.

**Approach:** A new “free” pagination mode will be added which allows to specify all of the required parts by a special syntax. Numbers in back-ticks (` `` `) will be treated as literals, where bare numbers will be incremented. Superscript numbers (`¹²³`) can be used to modify the increment value. `½` will cause a half-increment, as required for verso/recto pagination. Supports latin numbers and roman numerals in both uppercase and lowercase. A wiki page with usage examples will be provided. The free pagination mode can be hidden in the configuration.

The development of this feature is funded by Landratsamt Esslingen.

**Comment by henning-gerhardt** [comment]
Is this feature for Kitodo.Production 2.x or 3.x (DFG based development)?

**Comment by matthias-ronge** [comment]
2.x − developed on behalf of Landratsamt Esslingen

**Comment by henning-gerhardt** [comment]
Thank you. I added general Kitodo.Production 2.x milestone and change this milestone after merged pull request or before next 2.x release.
