### ISSUE TITLE
Can not edit search phrase

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#6221]
**Describe the bug**
After entering a search phrase in the task or process list it is not possible anymore to edit this search phrase without deleting them before which is resulting in a search over all tasks / processes. 

F.e. you are limiting the processes list to a newspaper year like 453042023-1903 and doing something. After this you need the processes of year 1904 and would not modify it to "453042023-1904" which was possible before only by removing the last number and entering the new number. Now you must delete the whole search phrase which is resulting in a search over all processes (which is in some kind bad) and then entering the whole modified search phrase. 

This is not limited to only process titles even more complex search phrases can not modified easily any more.

**To Reproduce**
1. Go to to the task or process list
2. Enter a search term and start the search
3. After search is done and try to modify the search phrase
4. You can modify the search phrase only by complete deleting it and entering the modified search phrase

**Expected behavior**
It should be possible to modify the existing search phrase without deleting and entering them modified again.

**Release**
- 3.7.0 but maybe even before. Was working in 3.6.0-SNAPSHOT from 2023-03-01 (so may with a 3.5 release if search modifications was done after 2023-03-01).

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser:  Firefox 
 - Version: 130

**Comment by solth** [comment]
If you are referring to the "filter menu" on the task and process lists, you can adjust the current filter by clicking on it, then it will change into a string that can be adjusted:


https://github.com/user-attachments/assets/c9b35449-c53f-46ee-92ca-bdab7fa5a2b6

**Comment by henning-gerhardt** [comment]
I will try it. Your video (*.mov) is not supported on system so I can not see it.

**Comment by henning-gerhardt** [comment]
Video is now available. Maybe GitHub is converting it in background.

Your suggested way is working but a little bit confusing as you had the original search phrase on the left side and the edit version on the right side and in the background a new search over all is performing. After editing the search phrase a new search is immediately started and on closing this dialog a search is performed again.

So the original issue is done but all the performed search requests (in background or on "closing the dialog") is for me at least not expecting while editing.

**Comment by henning-gerhardt** [comment]
I'm closing this issue as how to edit a filter got described and for the remaining problem I opened a new issue: #6348
