### ISSUE TITLE
Put date format string in central place

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#6223]
The date fromat string `"yyyy-MM-dd HH:mm:ss"` is used in several places. It should be put in one global constant and be used from there. Maybe even, put in `kitodo_config.properties`?

**Comment by henning-gerhardt** [comment]
I don't think that this value should be changed by the user. It should be placed into a central constant variable holder class.

**Comment by stweil** [comment]
Would it be possible to use class DateTimeFormatter which already provides constants like [ISO_LOCAL_DATE](https://docs.oracle.com/en%2Fjava%2Fjavase%2F22%2Fdocs%2Fapi%2F%2F/java.base/java/time/format/DateTimeFormatter.html#ISO_LOCAL_DATE) and [ISO_LOCAL_TIME](https://docs.oracle.com/en%2Fjava%2Fjavase%2F22%2Fdocs%2Fapi%2F%2F/java.base/java/time/format/DateTimeFormatter.html#ISO_LOCAL_TIME)?

Maybe some places which currently use the mentioned format string would better use [ISO_OFFSET_DATE_TIME](https://docs.oracle.com/en%2Fjava%2Fjavase%2F22%2Fdocs%2Fapi%2F%2F/java.base/java/time/format/DateTimeFormatter.html#ISO_OFFSET_DATE_TIME).

**Comment by matthias-ronge** [comment]
That's how time information (task accepted, task completed, ...) is displayed to the user. `ISO_OFFSET_DATE_TIME` would be the closest, but try explaining to a professional user why there has to be a “T” there.
