### ISSUE TITLE
Wrong spelling in German message after applying pagination

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#6258]
**Describe the bug**

The spelling of the message after applying the pagination is wrong: 
- `Paginierung wurde erfolgreich übernehmen.`

**To Reproduce**
1. Go to 'Paginierung' and do some stuff
2. Click on 'Übernehmen'
3. See message: `Paginierung wurde erfolgreich übernehmen.`

**Expected behavior**
The message should be spelled: 
- `Paginierung wurde erfolgreich übernommen.`

**Screenshots**
![FehlermeldungPaginierung01](https://github.com/user-attachments/assets/16311353-70fd-4e26-80b0-153fc3ac4530)

**Release**
KITODO.PRODUCTION Version 3.7.0

**Desktop (please complete the following information):**
 - Windows
 - Chrome

**Additional context**
Probably, the following line should be changed: 
- https://github.com/kitodo/kitodo-production/blob/5efafdb7cb78848ba86ca9fc877c5f3f60ec48e2/Kitodo/src/main/resources/messages/messages_de.properties#L891

**Comment by stweil** [comment]
There are many more spelling issues in the German translation. I hope that the pull requests #6259 and #6260 fix them (or at least most of them).

**Comment by solth** [comment]
I think my favorites are these:
<img width="526" alt="Bildschirmfoto 2024-10-09 um 10 53 36" src="https://github.com/user-attachments/assets/ba0e0e17-3431-4237-9fc5-62a1f28bfd3e">

**Comment by stweil** [comment]
Should I add a commit with "Neugenerierung aller Bilder starten" and "Start der Neuerstellung aller fehlenden und beschädigten Bilder"?

**Comment by solth** [comment]
> Should I add a commit with "Neugenerierung aller Bilder starten" and "Start der Neuerstellung aller fehlenden und beschädigten Bilder"?

I think that is a good idea!

**Comment by stweil** [comment]
Done. I updated and hopefully improved all related texts.
