### ISSUE TITLE
Add a wiki link button on every page

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#634]
On each page of the user interface, a button with a link to a corresponding page in the Kitodo wiki could be added (like it is already in place for filters). This would lead to better presence of the fact that there is a wiki, and might also encourage more users to improve existing wiki articles.

**Comment by stweil** [comment]
This would require Wiki pages for the different versions of Kitodo.Production as the user interface can change.

**Comment by henning-gerhardt** [comment]
Your suggestion is similar to discussion in #478.

I think a helping system should be integrated into Kitodo.Production software and only additional informations should be put into a wiki

**Comment by matthias-ronge** [comment]
Differences in the user interface can be documented on the wiki page as well. I would vote against different pages for different versions. What would be sensible is pages in English and German.

The drawback of an integrated help system is that users cannot contribute to it in a way other users from other institutions can see those contributions. Knowledge, where available, would not be shared.

**Comment by henning-gerhardt** [comment]
A small note: DFG project containing one development milestone to create / update current user manual for at least to different languages (English, German).

Personal note: I don't think that GitHub based wiki is a good place for multi language user manual as maintaining GitHub wiki pages is not easy and it does not contain possibilities and functionalities of other wiki software stacks.

**Comment by matthias-ronge** [comment]
I will close this issue, looking forward to the solution arising in the DFG project.
