### ISSUE TITLE
Access configuration through an instance passed in as parameter

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#635]
There is a general issue with static access to the configuration: Methods that access `ConfigMain` cannot be unit-tested. Testable code requires to pass in an instance of a configuration object which also must be creatable from code within tests in order to make things testable.

Bad solution:

    boolean allImagesOnPath() {
        String path = ConfigMain.getParameter("pathToFolder");
        for(String image : images) {
            if(!image.startsWith(path) {
                return false;
            }
        }
        return true;
    }

Better solution:

    boolean allImagesOnPath() {
        allImagesOnPath(ConfigMain.getAsMap());
    }

    boolean allImagesOnPath(Map<String, String> conf) {
        String path = new Parameters(conf).getPathToFolder();
        for(String image : images) {
            if(!image.startsWith(path) {
                return false;
            }
        }
        return true;
    }

Now the second method is testable:

    @Test
    void testAllImagesOnPath() {
        MyClass underTest = // .. set up class
        Map<String, String> testConfig = new HashMap<>();
        testConfig.put("pathToFolder", "/tmp/unit-tests/srv/www/content");
        assertTrue(underTest.allImagesOnPath(testConfig));
    }

**Comment by henning-gerhardt** [comment]
Did you try to mock this `ConfigMain` class inside test scenarios? As this would not require to rewrote / refactor all usage places of `ConfigMain`.

For DFG based development there is already a internal discussion of configuration management and it's usage.

**Comment by matthias-ronge** [comment]
My intention was to care about this topic in DFG based development. If this is already the case I can close it.
