### ISSUE TITLE
Use the same sort of white space everywhere

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#650]
Leaving tab indent in existing files and using four spaces indent in newly created files (in 2.x branch) is a mess when editing the project with Eclipse. The spacing is configured in the “Code formatter” settings and cannot be defined on a per-file basis. This means that, whatever file you are currently editing, you always have to go to the project settings and change the code formatter used, because the setting also influences code automatically generated (such as Javadoc comment templates). You cannot safely cut/paste code accross files any more, nor use “save all” button any more.

Most files use tab in 2.x branch. This should also be applied to new files.

**Comment by matthias-ronge** [comment]
… or the other way ‘round. It really exists both, but editing files is hell the way it is. I don’t have a best solution for it.

**Comment by henning-gerhardt** [comment]
Stefan Weil made a statistic about indent usage and with his numbers there are more files with space indent as tab indent. New coding guidelines (not official released yet) prefer space indent. So solution should be that all files of 2.x branch should be converted to space indent. 

Issue is related to #377

**Comment by matthias-ronge** [comment]
GitHub unified diff is capable to ignore white space differences, which will be necessary if we proceed here. You have to add **?w=1** to the URL in the browser to do so. Found [in the blog](https://github.com/blog/967-github-secrets).
