### ISSUE TITLE
Artefact opensymphony:quartz-all:1.6.5 aus dem Jiha-reposetory ist nicht verfügbar

### ISSUE THREAD

**Issue by Basti890** [kitodo/kitodo-production#651]
das Artefact opensymphony:quartz-all:1.6.5 aus dem Jiha-reposetory ist nicht verfügbar.

Scheinbar ist das reposetory von Jiha auf ein neues System (offensichtlich ein Nexus) umgezogen. Die neue Adresse wäre: https://devtools.jahia.com/nexus/content/groups/public/ dort ist allerding nicht die korrekte von uns benötigte Version 1.6.5 von opensymphony:quartz-all zu finden (siehe https://devtools.jahia.com/nexus/content/groups/public/opensymphony/quartz-all/).

Ob diese noch nicht verfügbar ist, oder gar nicht mehr dort angeboten wird, ist noch ungewiss.

Derzeit einzigste Möglichkeit das daraus resultierende Problem beim Bauen von Kitodo zu umgehen, ist sein lokales Maven-Repo nicht zu löschen.

**Comment by Basti890** [comment]
Gerade entdeckt: es gibt noch ein anderes Maven-Repo, welches die von uns benötigte Version bereitstellt: https://maven-eu.nuxeo.org/nexus/content/repositories/public/opensymphony/quartz-all/1.6.5/

**Comment by henning-gerhardt** [comment]
An alternative is so search for a compatible quartz library or made necessary changes for newer versions. To stay all time with a old and maybe not existing library is no good way.
