### ISSUE TITLE
Duplicated classes with same package structure

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#654]
While debugging for #653 I got some debugging trouble for class `SimplePDFMetadataExtractor`. 

This and other classes are provided by `kitodo-contentserver-2.0.0.jar`and `simplemets-0.0.1-SNAPSHOT.jar`.

A similar duplication exists between  `kitodo-contentserver-2.0.0.jar` and `util-0.0.1-SNAPSHOT.jar`.

For jar files `simplemets-0.0.1-SNAPSHOT.jar` and `util-0.0.1-SNAPSHOT.jar` does not exists any source code. For me it looks like that 
- parts of content server should be separated but this was never finished
- parts of smaller libraries are merged into content server library as they used only inside content server

Having duplicated classes with same package structure causes a big problem if they are outdated or different changed you never know which version is used. 

So I would prefer to remove `simplemets-0.0.1-SNAPSHOT.jar` and `util-0.0.1-SNAPSHOT.jar` files in favour for source code available versions.

**Comment by stweil** [comment]
Great, that sounds as if two more jar files with unknown origin and without sources could be removed.

**Comment by henning-gerhardt** [comment]
Fixed by PR #656
