### ISSUE TITLE
Create multiple structural elements at once

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#659]
Adding the same type of structural elements over and over again manually is tedious work. This shall be automatized in future.

**Approach:** The number of structual elements to create can be chosen arbitrarily. A meta-datum can be chosen to be automatically added, and support for a counter should be provided.

The development of this feature is funded by Landratsamt Esslingen.

**Comment by matthias-ronge** [comment]
Development is for 2.x branch

**Comment by henning-gerhardt** [comment]
Can this issue be closed as PR #676 is merged?
