### ISSUE TITLE
Is tiny_mce still used?

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#669]
I think that the content of `Goobi/js/tiny_mce` is of no functional use any more. I believe to remember that this is the editor which was offered for the wiki-field (when it once was what is name suggests) but it was removed since it interfered with the javascript generated by faces in Internet Explorer. If I am right, it could be removed. We shoud check this.

**Comment by henning-gerhardt** [comment]
tiny_mce Javascript is still referenced in at least
- `Goobi/newpages/inc_AktuelleSchritte/schritt_box_Details.jsp`
- `Goobi/newpages/inc_Batches/batch_box_Details.jsp`
- `Goobi/newpages/inc_Prozessverwaltung/prozess_box_Prozessdetails.jsp`

but if tiny_mce is not used any more then it should be removed

**Comment by stweil** [comment]
> but if tiny_mce is not used any more then it should be removed.

... and if it will be used for the next years, too, then an update of that code might be a good idea.

**Comment by henning-gerhardt** [comment]
I opened PR #682 for removing tinymce:

-  I could test my changes only for 2 of 3 usage scenarios (process and step details) - but I did not find a way to let me show batch details. Maybe @matthias-ronge  can look into this?
- I adjusted HTML output only in a simple way. This change could be improved maybe.

**Comment by henning-gerhardt** [comment]
TinyMCE is now removed by PR #682.

Can issue now closed or is something more to discuss?
