### ISSUE TITLE
Meta-data editor not fetching serach fields from catalogue plug-in

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#674]
Search fields are still hard-coded [in `Strukturdaten.jsp`](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/webapp/pages/incMeta/Strukturdaten.jsp#L175-L179). Affected function is _Add docstructs from Opac_ on the _Structure data_ page of the meta-data editor.

_BTW, does someone know how this function is used and what it does?_

![unbenannt](https://cloud.githubusercontent.com/assets/3040657/23461800/a8bffdc2-fe8b-11e6-98c9-24c677fad991.PNG)

**Comment by henning-gerhardt** [comment]
There is some documentation inside wiki entry: https://github.com/kitodo/kitodo-production/wiki/Staatsbibliothek-zu-Berlin---Preu%C3%9Fischer-Kulturbesitz#anh%C3%A4ngende-werke-pdf

**Comment by henning-gerhardt** [comment]
Changes by PR #683.

@matthias-ronge: can you look into this changes?

**Comment by henning-gerhardt** [comment]
PR #683 is merged. Closing issue.
