### ISSUE TITLE
Should the generator interface be renamed?

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#806]
I’ve got the impression that the generator interface is a misnomer. I wondered what else is being generated. There is a lot: image derivatives, PDFs, OCR, … If the generator interface was what its name suggests, it would have to be the super-interface of all of these interfaces. For me, this shows that it isn’t what it pretends to be.

I rather see the generator interface as an interface to catalogue into an external system from Production. Therefore, meta-data is passed to the external catalogue (in this case, Production’s internal ID). The answer is the catalogue key of the foreign system (in this case, the URN).

This is why I would plead for renaming the interface into something like _cataloging interface_.

From this perspective, passing the URN namespace seems wrong to me. It should be something the external catalogue should know. It should be possible to configure several external catalogues. Maybe the design should also be extended to be more flexible _which_ meta-data shall be exported.

Further more, we should consider wheter the interface should support updating the remote catalogue. Updating may cause the catalogue identifier to change, which requires that the local identifier is replaced.

**Comment by Kathrin-Huber** [comment]
In Pull Request #810 I adjusted the APIs and transferred the workshop results to the code, maybe it is now, how you thought it should be?

**Comment by matthias-ronge** [comment]
Persistent identifier interfice is fine for the moment. Cataloging to an external catalog isn’t a feature requirement at the moment.
